// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: quiz/v1/quiz.proto

package quizv1

import (
	v1 "github.com/elearning/shared/pkg/proto/gamification/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Quiz messages
type Quiz struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LessonId               string                 `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Title                  string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TimeLimitMinutes       *int32                 `protobuf:"varint,5,opt,name=time_limit_minutes,json=timeLimitMinutes,proto3,oneof" json:"time_limit_minutes,omitempty"`
	MaxAttempts            int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	PassingScorePercentage float64                `protobuf:"fixed64,7,opt,name=passing_score_percentage,json=passingScorePercentage,proto3" json:"passing_score_percentage,omitempty"`
	ShuffleQuestions       bool                   `protobuf:"varint,8,opt,name=shuffle_questions,json=shuffleQuestions,proto3" json:"shuffle_questions,omitempty"`
	ShowCorrectAnswers     bool                   `protobuf:"varint,9,opt,name=show_correct_answers,json=showCorrectAnswers,proto3" json:"show_correct_answers,omitempty"`
	IsRequired             bool                   `protobuf:"varint,10,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *Quiz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quiz) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *Quiz) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Quiz) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Quiz) GetTimeLimitMinutes() int32 {
	if x != nil && x.TimeLimitMinutes != nil {
		return *x.TimeLimitMinutes
	}
	return 0
}

func (x *Quiz) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Quiz) GetPassingScorePercentage() float64 {
	if x != nil {
		return x.PassingScorePercentage
	}
	return 0
}

func (x *Quiz) GetShuffleQuestions() bool {
	if x != nil {
		return x.ShuffleQuestions
	}
	return false
}

func (x *Quiz) GetShowCorrectAnswers() bool {
	if x != nil {
		return x.ShowCorrectAnswers
	}
	return false
}

func (x *Quiz) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *Quiz) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Quiz) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type QuizQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	QuestionType  string                 `protobuf:"bytes,3,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"` // multiple_choice, multiple_select, true_false, text_input
	QuestionText  string                 `protobuf:"bytes,4,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	Explanation   string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"` // URL изображения для вопроса
	Points        int32                  `protobuf:"varint,7,opt,name=points,proto3" json:"points,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,8,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizQuestion) Reset() {
	*x = QuizQuestion{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizQuestion) ProtoMessage() {}

func (x *QuizQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizQuestion.ProtoReflect.Descriptor instead.
func (*QuizQuestion) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *QuizQuestion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizQuestion) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *QuizQuestion) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *QuizQuestion) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *QuizQuestion) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *QuizQuestion) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *QuizQuestion) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *QuizQuestion) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *QuizQuestion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QuizQuestion) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type QuizAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerText    string                 `protobuf:"bytes,3,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,4,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,5,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizAnswer) Reset() {
	*x = QuizAnswer{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAnswer) ProtoMessage() {}

func (x *QuizAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAnswer.ProtoReflect.Descriptor instead.
func (*QuizAnswer) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *QuizAnswer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizAnswer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QuizAnswer) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *QuizAnswer) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *QuizAnswer) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *QuizAnswer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type QuestionWithAnswers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *QuizQuestion          `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answers       []*QuizAnswer          `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionWithAnswers) Reset() {
	*x = QuestionWithAnswers{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionWithAnswers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionWithAnswers) ProtoMessage() {}

func (x *QuestionWithAnswers) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionWithAnswers.ProtoReflect.Descriptor instead.
func (*QuestionWithAnswers) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *QuestionWithAnswers) GetQuestion() *QuizQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *QuestionWithAnswers) GetAnswers() []*QuizAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type QuizWithQuestions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	Questions     []*QuestionWithAnswers `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizWithQuestions) Reset() {
	*x = QuizWithQuestions{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizWithQuestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizWithQuestions) ProtoMessage() {}

func (x *QuizWithQuestions) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizWithQuestions.ProtoReflect.Descriptor instead.
func (*QuizWithQuestions) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *QuizWithQuestions) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

func (x *QuizWithQuestions) GetQuestions() []*QuestionWithAnswers {
	if x != nil {
		return x.Questions
	}
	return nil
}

type QuizAttempt struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId           string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AttemptNumber    int32                  `protobuf:"varint,4,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	ScorePercentage  *float64               `protobuf:"fixed64,7,opt,name=score_percentage,json=scorePercentage,proto3,oneof" json:"score_percentage,omitempty"`
	TotalPoints      *int32                 `protobuf:"varint,8,opt,name=total_points,json=totalPoints,proto3,oneof" json:"total_points,omitempty"`
	EarnedPoints     *int32                 `protobuf:"varint,9,opt,name=earned_points,json=earnedPoints,proto3,oneof" json:"earned_points,omitempty"`
	IsPassed         bool                   `protobuf:"varint,10,opt,name=is_passed,json=isPassed,proto3" json:"is_passed,omitempty"`
	TimeSpentSeconds *int32                 `protobuf:"varint,11,opt,name=time_spent_seconds,json=timeSpentSeconds,proto3,oneof" json:"time_spent_seconds,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuizAttempt) Reset() {
	*x = QuizAttempt{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAttempt) ProtoMessage() {}

func (x *QuizAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAttempt.ProtoReflect.Descriptor instead.
func (*QuizAttempt) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *QuizAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizAttempt) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *QuizAttempt) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizAttempt) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *QuizAttempt) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *QuizAttempt) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *QuizAttempt) GetScorePercentage() float64 {
	if x != nil && x.ScorePercentage != nil {
		return *x.ScorePercentage
	}
	return 0
}

func (x *QuizAttempt) GetTotalPoints() int32 {
	if x != nil && x.TotalPoints != nil {
		return *x.TotalPoints
	}
	return 0
}

func (x *QuizAttempt) GetEarnedPoints() int32 {
	if x != nil && x.EarnedPoints != nil {
		return *x.EarnedPoints
	}
	return 0
}

func (x *QuizAttempt) GetIsPassed() bool {
	if x != nil {
		return x.IsPassed
	}
	return false
}

func (x *QuizAttempt) GetTimeSpentSeconds() int32 {
	if x != nil && x.TimeSpentSeconds != nil {
		return *x.TimeSpentSeconds
	}
	return 0
}

func (x *QuizAttempt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QuizAttempt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type QuizAttemptAnswer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttemptId         string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	QuestionId        string                 `protobuf:"bytes,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SelectedAnswerIds []string               `protobuf:"bytes,4,rep,name=selected_answer_ids,json=selectedAnswerIds,proto3" json:"selected_answer_ids,omitempty"`
	TextAnswer        *string                `protobuf:"bytes,5,opt,name=text_answer,json=textAnswer,proto3,oneof" json:"text_answer,omitempty"`
	IsCorrect         *bool                  `protobuf:"varint,6,opt,name=is_correct,json=isCorrect,proto3,oneof" json:"is_correct,omitempty"`
	PointsEarned      int32                  `protobuf:"varint,7,opt,name=points_earned,json=pointsEarned,proto3" json:"points_earned,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuizAttemptAnswer) Reset() {
	*x = QuizAttemptAnswer{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAttemptAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAttemptAnswer) ProtoMessage() {}

func (x *QuizAttemptAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAttemptAnswer.ProtoReflect.Descriptor instead.
func (*QuizAttemptAnswer) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *QuizAttemptAnswer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizAttemptAnswer) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *QuizAttemptAnswer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QuizAttemptAnswer) GetSelectedAnswerIds() []string {
	if x != nil {
		return x.SelectedAnswerIds
	}
	return nil
}

func (x *QuizAttemptAnswer) GetTextAnswer() string {
	if x != nil && x.TextAnswer != nil {
		return *x.TextAnswer
	}
	return ""
}

func (x *QuizAttemptAnswer) GetIsCorrect() bool {
	if x != nil && x.IsCorrect != nil {
		return *x.IsCorrect
	}
	return false
}

func (x *QuizAttemptAnswer) GetPointsEarned() int32 {
	if x != nil {
		return x.PointsEarned
	}
	return 0
}

func (x *QuizAttemptAnswer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AttemptWithAnswers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *QuizAttempt           `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Answers       []*QuizAttemptAnswer   `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptWithAnswers) Reset() {
	*x = AttemptWithAnswers{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptWithAnswers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptWithAnswers) ProtoMessage() {}

func (x *AttemptWithAnswers) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptWithAnswers.ProtoReflect.Descriptor instead.
func (*AttemptWithAnswers) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *AttemptWithAnswers) GetAttempt() *QuizAttempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

func (x *AttemptWithAnswers) GetAnswers() []*QuizAttemptAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

// CreateQuiz
type CreateQuizRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LessonId               string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Title                  string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TimeLimitMinutes       *int32                 `protobuf:"varint,4,opt,name=time_limit_minutes,json=timeLimitMinutes,proto3,oneof" json:"time_limit_minutes,omitempty"`
	MaxAttempts            int32                  `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	PassingScorePercentage float64                `protobuf:"fixed64,6,opt,name=passing_score_percentage,json=passingScorePercentage,proto3" json:"passing_score_percentage,omitempty"`
	ShuffleQuestions       bool                   `protobuf:"varint,7,opt,name=shuffle_questions,json=shuffleQuestions,proto3" json:"shuffle_questions,omitempty"`
	ShowCorrectAnswers     bool                   `protobuf:"varint,8,opt,name=show_correct_answers,json=showCorrectAnswers,proto3" json:"show_correct_answers,omitempty"`
	IsRequired             bool                   `protobuf:"varint,9,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateQuizRequest) Reset() {
	*x = CreateQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizRequest) ProtoMessage() {}

func (x *CreateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *CreateQuizRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *CreateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateQuizRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateQuizRequest) GetTimeLimitMinutes() int32 {
	if x != nil && x.TimeLimitMinutes != nil {
		return *x.TimeLimitMinutes
	}
	return 0
}

func (x *CreateQuizRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *CreateQuizRequest) GetPassingScorePercentage() float64 {
	if x != nil {
		return x.PassingScorePercentage
	}
	return 0
}

func (x *CreateQuizRequest) GetShuffleQuestions() bool {
	if x != nil {
		return x.ShuffleQuestions
	}
	return false
}

func (x *CreateQuizRequest) GetShowCorrectAnswers() bool {
	if x != nil {
		return x.ShowCorrectAnswers
	}
	return false
}

func (x *CreateQuizRequest) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

type CreateQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuizResponse) Reset() {
	*x = CreateQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizResponse) ProtoMessage() {}

func (x *CreateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizResponse.ProtoReflect.Descriptor instead.
func (*CreateQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{9}
}

func (x *CreateQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

// GetQuiz
type GetQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizRequest) Reset() {
	*x = GetQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizRequest) ProtoMessage() {}

func (x *GetQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizRequest.ProtoReflect.Descriptor instead.
func (*GetQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{10}
}

func (x *GetQuizRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type GetQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *QuizWithQuestions     `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizResponse) Reset() {
	*x = GetQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizResponse) ProtoMessage() {}

func (x *GetQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizResponse.ProtoReflect.Descriptor instead.
func (*GetQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{11}
}

func (x *GetQuizResponse) GetQuiz() *QuizWithQuestions {
	if x != nil {
		return x.Quiz
	}
	return nil
}

// UpdateQuiz
type UpdateQuizRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                  string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TimeLimitMinutes       *int32                 `protobuf:"varint,4,opt,name=time_limit_minutes,json=timeLimitMinutes,proto3,oneof" json:"time_limit_minutes,omitempty"`
	MaxAttempts            int32                  `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	PassingScorePercentage float64                `protobuf:"fixed64,6,opt,name=passing_score_percentage,json=passingScorePercentage,proto3" json:"passing_score_percentage,omitempty"`
	ShuffleQuestions       bool                   `protobuf:"varint,7,opt,name=shuffle_questions,json=shuffleQuestions,proto3" json:"shuffle_questions,omitempty"`
	ShowCorrectAnswers     bool                   `protobuf:"varint,8,opt,name=show_correct_answers,json=showCorrectAnswers,proto3" json:"show_correct_answers,omitempty"`
	IsRequired             bool                   `protobuf:"varint,9,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateQuizRequest) Reset() {
	*x = UpdateQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizRequest) ProtoMessage() {}

func (x *UpdateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateQuizRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateQuizRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateQuizRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateQuizRequest) GetTimeLimitMinutes() int32 {
	if x != nil && x.TimeLimitMinutes != nil {
		return *x.TimeLimitMinutes
	}
	return 0
}

func (x *UpdateQuizRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *UpdateQuizRequest) GetPassingScorePercentage() float64 {
	if x != nil {
		return x.PassingScorePercentage
	}
	return 0
}

func (x *UpdateQuizRequest) GetShuffleQuestions() bool {
	if x != nil {
		return x.ShuffleQuestions
	}
	return false
}

func (x *UpdateQuizRequest) GetShowCorrectAnswers() bool {
	if x != nil {
		return x.ShowCorrectAnswers
	}
	return false
}

func (x *UpdateQuizRequest) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

type UpdateQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quiz          *Quiz                  `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuizResponse) Reset() {
	*x = UpdateQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizResponse) ProtoMessage() {}

func (x *UpdateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

// DeleteQuiz
type DeleteQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizRequest) Reset() {
	*x = DeleteQuizRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizRequest) ProtoMessage() {}

func (x *DeleteQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteQuizRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type DeleteQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuizResponse) Reset() {
	*x = DeleteQuizResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizResponse) ProtoMessage() {}

func (x *DeleteQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteQuizResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListQuizzes
type ListQuizzesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuizzesRequest) Reset() {
	*x = ListQuizzesRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuizzesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuizzesRequest) ProtoMessage() {}

func (x *ListQuizzesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuizzesRequest.ProtoReflect.Descriptor instead.
func (*ListQuizzesRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{16}
}

func (x *ListQuizzesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListQuizzesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListQuizzesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*Quiz                `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuizzesResponse) Reset() {
	*x = ListQuizzesResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuizzesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuizzesResponse) ProtoMessage() {}

func (x *ListQuizzesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuizzesResponse.ProtoReflect.Descriptor instead.
func (*ListQuizzesResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{17}
}

func (x *ListQuizzesResponse) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

// GetQuizzesByLesson
type GetQuizzesByLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizzesByLessonRequest) Reset() {
	*x = GetQuizzesByLessonRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizzesByLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizzesByLessonRequest) ProtoMessage() {}

func (x *GetQuizzesByLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizzesByLessonRequest.ProtoReflect.Descriptor instead.
func (*GetQuizzesByLessonRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{18}
}

func (x *GetQuizzesByLessonRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type GetQuizzesByLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quizzes       []*Quiz                `protobuf:"bytes,1,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizzesByLessonResponse) Reset() {
	*x = GetQuizzesByLessonResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizzesByLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizzesByLessonResponse) ProtoMessage() {}

func (x *GetQuizzesByLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizzesByLessonResponse.ProtoReflect.Descriptor instead.
func (*GetQuizzesByLessonResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{19}
}

func (x *GetQuizzesByLessonResponse) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

// AddQuestion
type AddQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	QuestionType  string                 `protobuf:"bytes,2,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	QuestionText  string                 `protobuf:"bytes,3,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	Points        int32                  `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,7,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	Answers       []*AddAnswerRequest    `protobuf:"bytes,8,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddQuestionRequest) Reset() {
	*x = AddQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionRequest) ProtoMessage() {}

func (x *AddQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionRequest.ProtoReflect.Descriptor instead.
func (*AddQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{20}
}

func (x *AddQuestionRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *AddQuestionRequest) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *AddQuestionRequest) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *AddQuestionRequest) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *AddQuestionRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *AddQuestionRequest) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *AddQuestionRequest) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *AddQuestionRequest) GetAnswers() []*AddAnswerRequest {
	if x != nil {
		return x.Answers
	}
	return nil
}

type AddAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerText    string                 `protobuf:"bytes,1,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,3,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAnswerRequest) Reset() {
	*x = AddAnswerRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAnswerRequest) ProtoMessage() {}

func (x *AddAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAnswerRequest.ProtoReflect.Descriptor instead.
func (*AddAnswerRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{21}
}

func (x *AddAnswerRequest) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *AddAnswerRequest) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *AddAnswerRequest) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

type AddQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *QuizQuestion          `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddQuestionResponse) Reset() {
	*x = AddQuestionResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionResponse) ProtoMessage() {}

func (x *AddQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionResponse.ProtoReflect.Descriptor instead.
func (*AddQuestionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{22}
}

func (x *AddQuestionResponse) GetQuestion() *QuizQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

// UpdateQuestion
type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionType  string                 `protobuf:"bytes,2,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	QuestionText  string                 `protobuf:"bytes,3,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	Points        int32                  `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,7,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateQuestionRequest) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *UpdateQuestionRequest) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *UpdateQuestionRequest) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *UpdateQuestionRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *UpdateQuestionRequest) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *UpdateQuestionRequest) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *QuizQuestion          `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateQuestionResponse) GetQuestion() *QuizQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

// DeleteQuestion
type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type DeleteQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionResponse) Reset() {
	*x = DeleteQuestionResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionResponse) ProtoMessage() {}

func (x *DeleteQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuestionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteQuestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// StartQuizAttempt
type StartQuizAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartQuizAttemptRequest) Reset() {
	*x = StartQuizAttemptRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartQuizAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQuizAttemptRequest) ProtoMessage() {}

func (x *StartQuizAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQuizAttemptRequest.ProtoReflect.Descriptor instead.
func (*StartQuizAttemptRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{27}
}

func (x *StartQuizAttemptRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *StartQuizAttemptRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StartQuizAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *QuizAttempt           `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartQuizAttemptResponse) Reset() {
	*x = StartQuizAttemptResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartQuizAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQuizAttemptResponse) ProtoMessage() {}

func (x *StartQuizAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQuizAttemptResponse.ProtoReflect.Descriptor instead.
func (*StartQuizAttemptResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{28}
}

func (x *StartQuizAttemptResponse) GetAttempt() *QuizAttempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

// SubmitAnswer
type SubmitAnswerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttemptId         string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	QuestionId        string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SelectedAnswerIds []string               `protobuf:"bytes,3,rep,name=selected_answer_ids,json=selectedAnswerIds,proto3" json:"selected_answer_ids,omitempty"`
	TextAnswer        *string                `protobuf:"bytes,4,opt,name=text_answer,json=textAnswer,proto3,oneof" json:"text_answer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{29}
}

func (x *SubmitAnswerRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetSelectedAnswerIds() []string {
	if x != nil {
		return x.SelectedAnswerIds
	}
	return nil
}

func (x *SubmitAnswerRequest) GetTextAnswer() string {
	if x != nil && x.TextAnswer != nil {
		return *x.TextAnswer
	}
	return ""
}

type SubmitAnswerResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Answer *QuizAttemptAnswer     `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	// Заполняется, когда ответ оказался неверным и quiz-service настроен на
	// gamification-service: содержит обновленное состояние hearts после
	// gamification.LoseHeart. Если nil — фронт не обновляет heart-cache.
	Hearts        *v1.Hearts `protobuf:"bytes,2,opt,name=hearts,proto3,oneof" json:"hearts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{30}
}

func (x *SubmitAnswerResponse) GetAnswer() *QuizAttemptAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *SubmitAnswerResponse) GetHearts() *v1.Hearts {
	if x != nil {
		return x.Hearts
	}
	return nil
}

// CompleteQuizAttempt
type CompleteQuizAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteQuizAttemptRequest) Reset() {
	*x = CompleteQuizAttemptRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteQuizAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteQuizAttemptRequest) ProtoMessage() {}

func (x *CompleteQuizAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteQuizAttemptRequest.ProtoReflect.Descriptor instead.
func (*CompleteQuizAttemptRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{31}
}

func (x *CompleteQuizAttemptRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type CompleteQuizAttemptResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Attempt *QuizAttempt           `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// XP-payload (transaction, stats, leveled_up, unlocked_achievements,
	// daily_goal_progress). Заполняется только при первом переходе попытки
	// в completed-состояние и если gamification-service сконфигурирован.
	Xp            *v1.AddXPResponse `protobuf:"bytes,2,opt,name=xp,proto3,oneof" json:"xp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteQuizAttemptResponse) Reset() {
	*x = CompleteQuizAttemptResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteQuizAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteQuizAttemptResponse) ProtoMessage() {}

func (x *CompleteQuizAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteQuizAttemptResponse.ProtoReflect.Descriptor instead.
func (*CompleteQuizAttemptResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{32}
}

func (x *CompleteQuizAttemptResponse) GetAttempt() *QuizAttempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

func (x *CompleteQuizAttemptResponse) GetXp() *v1.AddXPResponse {
	if x != nil {
		return x.Xp
	}
	return nil
}

// GetAttempt
type GetAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttemptRequest) Reset() {
	*x = GetAttemptRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttemptRequest) ProtoMessage() {}

func (x *GetAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttemptRequest.ProtoReflect.Descriptor instead.
func (*GetAttemptRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{33}
}

func (x *GetAttemptRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type GetAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *AttemptWithAnswers    `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttemptResponse) Reset() {
	*x = GetAttemptResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttemptResponse) ProtoMessage() {}

func (x *GetAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttemptResponse.ProtoReflect.Descriptor instead.
func (*GetAttemptResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{34}
}

func (x *GetAttemptResponse) GetAttempt() *AttemptWithAnswers {
	if x != nil {
		return x.Attempt
	}
	return nil
}

// GetUserAttempts
type GetUserAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAttemptsRequest) Reset() {
	*x = GetUserAttemptsRequest{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAttemptsRequest) ProtoMessage() {}

func (x *GetUserAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAttemptsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{35}
}

func (x *GetUserAttemptsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserAttemptsRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type GetUserAttemptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      []*QuizAttempt         `protobuf:"bytes,1,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAttemptsResponse) Reset() {
	*x = GetUserAttemptsResponse{}
	mi := &file_quiz_v1_quiz_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAttemptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAttemptsResponse) ProtoMessage() {}

func (x *GetUserAttemptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_v1_quiz_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAttemptsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAttemptsResponse) Descriptor() ([]byte, []int) {
	return file_quiz_v1_quiz_proto_rawDescGZIP(), []int{36}
}

func (x *GetUserAttemptsResponse) GetAttempts() []*QuizAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

var File_quiz_v1_quiz_proto protoreflect.FileDescriptor

const file_quiz_v1_quiz_proto_rawDesc = "" +
	"\n" +
	"\x12quiz/v1/quiz.proto\x12\aquiz.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"gamification/v1/gamification.proto\"\x88\x04\n" +
	"\x04Quiz\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\tR\blessonId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x121\n" +
	"\x12time_limit_minutes\x18\x05 \x01(\x05H\x00R\x10timeLimitMinutes\x88\x01\x01\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x128\n" +
	"\x18passing_score_percentage\x18\a \x01(\x01R\x16passingScorePercentage\x12+\n" +
	"\x11shuffle_questions\x18\b \x01(\bR\x10shuffleQuestions\x120\n" +
	"\x14show_correct_answers\x18\t \x01(\bR\x12showCorrectAnswers\x12\x1f\n" +
	"\vis_required\x18\n" +
	" \x01(\bR\n" +
	"isRequired\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x15\n" +
	"\x13_time_limit_minutes\"\x82\x03\n" +
	"\fQuizQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12#\n" +
	"\rquestion_type\x18\x03 \x01(\tR\fquestionType\x12#\n" +
	"\rquestion_text\x18\x04 \x01(\tR\fquestionText\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12 \n" +
	"\timage_url\x18\x06 \x01(\tH\x00R\bimageUrl\x88\x01\x01\x12\x16\n" +
	"\x06points\x18\a \x01(\x05R\x06points\x12\x1f\n" +
	"\vorder_index\x18\b \x01(\x05R\n" +
	"orderIndex\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\f\n" +
	"\n" +
	"_image_url\"\xd9\x01\n" +
	"\n" +
	"QuizAnswer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12\x1f\n" +
	"\vanswer_text\x18\x03 \x01(\tR\n" +
	"answerText\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x04 \x01(\bR\tisCorrect\x12\x1f\n" +
	"\vorder_index\x18\x05 \x01(\x05R\n" +
	"orderIndex\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"w\n" +
	"\x13QuestionWithAnswers\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.quiz.v1.QuizQuestionR\bquestion\x12-\n" +
	"\aanswers\x18\x02 \x03(\v2\x13.quiz.v1.QuizAnswerR\aanswers\"r\n" +
	"\x11QuizWithQuestions\x12!\n" +
	"\x04quiz\x18\x01 \x01(\v2\r.quiz.v1.QuizR\x04quiz\x12:\n" +
	"\tquestions\x18\x02 \x03(\v2\x1c.quiz.v1.QuestionWithAnswersR\tquestions\"\x9d\x05\n" +
	"\vQuizAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x0eattempt_number\x18\x04 \x01(\x05R\rattemptNumber\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01\x12.\n" +
	"\x10score_percentage\x18\a \x01(\x01H\x01R\x0fscorePercentage\x88\x01\x01\x12&\n" +
	"\ftotal_points\x18\b \x01(\x05H\x02R\vtotalPoints\x88\x01\x01\x12(\n" +
	"\rearned_points\x18\t \x01(\x05H\x03R\fearnedPoints\x88\x01\x01\x12\x1b\n" +
	"\tis_passed\x18\n" +
	" \x01(\bR\bisPassed\x121\n" +
	"\x12time_spent_seconds\x18\v \x01(\x05H\x04R\x10timeSpentSeconds\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0f\n" +
	"\r_completed_atB\x13\n" +
	"\x11_score_percentageB\x0f\n" +
	"\r_total_pointsB\x10\n" +
	"\x0e_earned_pointsB\x15\n" +
	"\x13_time_spent_seconds\"\xdc\x02\n" +
	"\x11QuizAttemptAnswer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vquestion_id\x18\x03 \x01(\tR\n" +
	"questionId\x12.\n" +
	"\x13selected_answer_ids\x18\x04 \x03(\tR\x11selectedAnswerIds\x12$\n" +
	"\vtext_answer\x18\x05 \x01(\tH\x00R\n" +
	"textAnswer\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_correct\x18\x06 \x01(\bH\x01R\tisCorrect\x88\x01\x01\x12#\n" +
	"\rpoints_earned\x18\a \x01(\x05R\fpointsEarned\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_text_answerB\r\n" +
	"\v_is_correct\"z\n" +
	"\x12AttemptWithAnswers\x12.\n" +
	"\aattempt\x18\x01 \x01(\v2\x14.quiz.v1.QuizAttemptR\aattempt\x124\n" +
	"\aanswers\x18\x02 \x03(\v2\x1a.quiz.v1.QuizAttemptAnswerR\aanswers\"\x8f\x03\n" +
	"\x11CreateQuizRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x12time_limit_minutes\x18\x04 \x01(\x05H\x00R\x10timeLimitMinutes\x88\x01\x01\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\x05R\vmaxAttempts\x128\n" +
	"\x18passing_score_percentage\x18\x06 \x01(\x01R\x16passingScorePercentage\x12+\n" +
	"\x11shuffle_questions\x18\a \x01(\bR\x10shuffleQuestions\x120\n" +
	"\x14show_correct_answers\x18\b \x01(\bR\x12showCorrectAnswers\x12\x1f\n" +
	"\vis_required\x18\t \x01(\bR\n" +
	"isRequiredB\x15\n" +
	"\x13_time_limit_minutes\"7\n" +
	"\x12CreateQuizResponse\x12!\n" +
	"\x04quiz\x18\x01 \x01(\v2\r.quiz.v1.QuizR\x04quiz\")\n" +
	"\x0eGetQuizRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\"A\n" +
	"\x0fGetQuizResponse\x12.\n" +
	"\x04quiz\x18\x01 \x01(\v2\x1a.quiz.v1.QuizWithQuestionsR\x04quiz\"\x82\x03\n" +
	"\x11UpdateQuizRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x12time_limit_minutes\x18\x04 \x01(\x05H\x00R\x10timeLimitMinutes\x88\x01\x01\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\x05R\vmaxAttempts\x128\n" +
	"\x18passing_score_percentage\x18\x06 \x01(\x01R\x16passingScorePercentage\x12+\n" +
	"\x11shuffle_questions\x18\a \x01(\bR\x10shuffleQuestions\x120\n" +
	"\x14show_correct_answers\x18\b \x01(\bR\x12showCorrectAnswers\x12\x1f\n" +
	"\vis_required\x18\t \x01(\bR\n" +
	"isRequiredB\x15\n" +
	"\x13_time_limit_minutes\"7\n" +
	"\x12UpdateQuizResponse\x12!\n" +
	"\x04quiz\x18\x01 \x01(\v2\r.quiz.v1.QuizR\x04quiz\",\n" +
	"\x11DeleteQuizRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\".\n" +
	"\x12DeleteQuizResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x12ListQuizzesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\">\n" +
	"\x13ListQuizzesResponse\x12'\n" +
	"\aquizzes\x18\x01 \x03(\v2\r.quiz.v1.QuizR\aquizzes\"8\n" +
	"\x19GetQuizzesByLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\"E\n" +
	"\x1aGetQuizzesByLessonResponse\x12'\n" +
	"\aquizzes\x18\x01 \x03(\v2\r.quiz.v1.QuizR\aquizzes\"\xb7\x02\n" +
	"\x12AddQuestionRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12#\n" +
	"\rquestion_type\x18\x02 \x01(\tR\fquestionType\x12#\n" +
	"\rquestion_text\x18\x03 \x01(\tR\fquestionText\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12 \n" +
	"\timage_url\x18\x05 \x01(\tH\x00R\bimageUrl\x88\x01\x01\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x05R\x06points\x12\x1f\n" +
	"\vorder_index\x18\a \x01(\x05R\n" +
	"orderIndex\x123\n" +
	"\aanswers\x18\b \x03(\v2\x19.quiz.v1.AddAnswerRequestR\aanswersB\f\n" +
	"\n" +
	"_image_url\"s\n" +
	"\x10AddAnswerRequest\x12\x1f\n" +
	"\vanswer_text\x18\x01 \x01(\tR\n" +
	"answerText\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\x12\x1f\n" +
	"\vorder_index\x18\x03 \x01(\x05R\n" +
	"orderIndex\"H\n" +
	"\x13AddQuestionResponse\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.quiz.v1.QuizQuestionR\bquestion\"\xfc\x01\n" +
	"\x15UpdateQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rquestion_type\x18\x02 \x01(\tR\fquestionType\x12#\n" +
	"\rquestion_text\x18\x03 \x01(\tR\fquestionText\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12 \n" +
	"\timage_url\x18\x05 \x01(\tH\x00R\bimageUrl\x88\x01\x01\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x05R\x06points\x12\x1f\n" +
	"\vorder_index\x18\a \x01(\x05R\n" +
	"orderIndexB\f\n" +
	"\n" +
	"_image_url\"K\n" +
	"\x16UpdateQuestionResponse\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.quiz.v1.QuizQuestionR\bquestion\"8\n" +
	"\x15DeleteQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"2\n" +
	"\x16DeleteQuestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x17StartQuizAttemptRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"J\n" +
	"\x18StartQuizAttemptResponse\x12.\n" +
	"\aattempt\x18\x01 \x01(\v2\x14.quiz.v1.QuizAttemptR\aattempt\"\xbb\x01\n" +
	"\x13SubmitAnswerRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12.\n" +
	"\x13selected_answer_ids\x18\x03 \x03(\tR\x11selectedAnswerIds\x12$\n" +
	"\vtext_answer\x18\x04 \x01(\tH\x00R\n" +
	"textAnswer\x88\x01\x01B\x0e\n" +
	"\f_text_answer\"\x8b\x01\n" +
	"\x14SubmitAnswerResponse\x122\n" +
	"\x06answer\x18\x01 \x01(\v2\x1a.quiz.v1.QuizAttemptAnswerR\x06answer\x124\n" +
	"\x06hearts\x18\x02 \x01(\v2\x17.gamification.v1.HeartsH\x00R\x06hearts\x88\x01\x01B\t\n" +
	"\a_hearts\";\n" +
	"\x1aCompleteQuizAttemptRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\"\x89\x01\n" +
	"\x1bCompleteQuizAttemptResponse\x12.\n" +
	"\aattempt\x18\x01 \x01(\v2\x14.quiz.v1.QuizAttemptR\aattempt\x123\n" +
	"\x02xp\x18\x02 \x01(\v2\x1e.gamification.v1.AddXPResponseH\x00R\x02xp\x88\x01\x01B\x05\n" +
	"\x03_xp\"2\n" +
	"\x11GetAttemptRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\"K\n" +
	"\x12GetAttemptResponse\x125\n" +
	"\aattempt\x18\x01 \x01(\v2\x1b.quiz.v1.AttemptWithAnswersR\aattempt\"J\n" +
	"\x16GetUserAttemptsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\"K\n" +
	"\x17GetUserAttemptsResponse\x120\n" +
	"\battempts\x18\x01 \x03(\v2\x14.quiz.v1.QuizAttemptR\battempts2\xde\b\n" +
	"\vQuizService\x12E\n" +
	"\n" +
	"CreateQuiz\x12\x1a.quiz.v1.CreateQuizRequest\x1a\x1b.quiz.v1.CreateQuizResponse\x12<\n" +
	"\aGetQuiz\x12\x17.quiz.v1.GetQuizRequest\x1a\x18.quiz.v1.GetQuizResponse\x12E\n" +
	"\n" +
	"UpdateQuiz\x12\x1a.quiz.v1.UpdateQuizRequest\x1a\x1b.quiz.v1.UpdateQuizResponse\x12E\n" +
	"\n" +
	"DeleteQuiz\x12\x1a.quiz.v1.DeleteQuizRequest\x1a\x1b.quiz.v1.DeleteQuizResponse\x12H\n" +
	"\vListQuizzes\x12\x1b.quiz.v1.ListQuizzesRequest\x1a\x1c.quiz.v1.ListQuizzesResponse\x12]\n" +
	"\x12GetQuizzesByLesson\x12\".quiz.v1.GetQuizzesByLessonRequest\x1a#.quiz.v1.GetQuizzesByLessonResponse\x12H\n" +
	"\vAddQuestion\x12\x1b.quiz.v1.AddQuestionRequest\x1a\x1c.quiz.v1.AddQuestionResponse\x12Q\n" +
	"\x0eUpdateQuestion\x12\x1e.quiz.v1.UpdateQuestionRequest\x1a\x1f.quiz.v1.UpdateQuestionResponse\x12Q\n" +
	"\x0eDeleteQuestion\x12\x1e.quiz.v1.DeleteQuestionRequest\x1a\x1f.quiz.v1.DeleteQuestionResponse\x12W\n" +
	"\x10StartQuizAttempt\x12 .quiz.v1.StartQuizAttemptRequest\x1a!.quiz.v1.StartQuizAttemptResponse\x12K\n" +
	"\fSubmitAnswer\x12\x1c.quiz.v1.SubmitAnswerRequest\x1a\x1d.quiz.v1.SubmitAnswerResponse\x12`\n" +
	"\x13CompleteQuizAttempt\x12#.quiz.v1.CompleteQuizAttemptRequest\x1a$.quiz.v1.CompleteQuizAttemptResponse\x12E\n" +
	"\n" +
	"GetAttempt\x12\x1a.quiz.v1.GetAttemptRequest\x1a\x1b.quiz.v1.GetAttemptResponse\x12T\n" +
	"\x0fGetUserAttempts\x12\x1f.quiz.v1.GetUserAttemptsRequest\x1a .quiz.v1.GetUserAttemptsResponseB\x8b\x01\n" +
	"\vcom.quiz.v1B\tQuizProtoP\x01Z4github.com/elearning/shared/pkg/proto/quiz/v1;quizv1\xa2\x02\x03QXX\xaa\x02\aQuiz.V1\xca\x02\aQuiz\\V1\xe2\x02\x13Quiz\\V1\\GPBMetadata\xea\x02\bQuiz::V1b\x06proto3"

var (
	file_quiz_v1_quiz_proto_rawDescOnce sync.Once
	file_quiz_v1_quiz_proto_rawDescData []byte
)

func file_quiz_v1_quiz_proto_rawDescGZIP() []byte {
	file_quiz_v1_quiz_proto_rawDescOnce.Do(func() {
		file_quiz_v1_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quiz_v1_quiz_proto_rawDesc), len(file_quiz_v1_quiz_proto_rawDesc)))
	})
	return file_quiz_v1_quiz_proto_rawDescData
}

var file_quiz_v1_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_quiz_v1_quiz_proto_goTypes = []any{
	(*Quiz)(nil),                        // 0: quiz.v1.Quiz
	(*QuizQuestion)(nil),                // 1: quiz.v1.QuizQuestion
	(*QuizAnswer)(nil),                  // 2: quiz.v1.QuizAnswer
	(*QuestionWithAnswers)(nil),         // 3: quiz.v1.QuestionWithAnswers
	(*QuizWithQuestions)(nil),           // 4: quiz.v1.QuizWithQuestions
	(*QuizAttempt)(nil),                 // 5: quiz.v1.QuizAttempt
	(*QuizAttemptAnswer)(nil),           // 6: quiz.v1.QuizAttemptAnswer
	(*AttemptWithAnswers)(nil),          // 7: quiz.v1.AttemptWithAnswers
	(*CreateQuizRequest)(nil),           // 8: quiz.v1.CreateQuizRequest
	(*CreateQuizResponse)(nil),          // 9: quiz.v1.CreateQuizResponse
	(*GetQuizRequest)(nil),              // 10: quiz.v1.GetQuizRequest
	(*GetQuizResponse)(nil),             // 11: quiz.v1.GetQuizResponse
	(*UpdateQuizRequest)(nil),           // 12: quiz.v1.UpdateQuizRequest
	(*UpdateQuizResponse)(nil),          // 13: quiz.v1.UpdateQuizResponse
	(*DeleteQuizRequest)(nil),           // 14: quiz.v1.DeleteQuizRequest
	(*DeleteQuizResponse)(nil),          // 15: quiz.v1.DeleteQuizResponse
	(*ListQuizzesRequest)(nil),          // 16: quiz.v1.ListQuizzesRequest
	(*ListQuizzesResponse)(nil),         // 17: quiz.v1.ListQuizzesResponse
	(*GetQuizzesByLessonRequest)(nil),   // 18: quiz.v1.GetQuizzesByLessonRequest
	(*GetQuizzesByLessonResponse)(nil),  // 19: quiz.v1.GetQuizzesByLessonResponse
	(*AddQuestionRequest)(nil),          // 20: quiz.v1.AddQuestionRequest
	(*AddAnswerRequest)(nil),            // 21: quiz.v1.AddAnswerRequest
	(*AddQuestionResponse)(nil),         // 22: quiz.v1.AddQuestionResponse
	(*UpdateQuestionRequest)(nil),       // 23: quiz.v1.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil),      // 24: quiz.v1.UpdateQuestionResponse
	(*DeleteQuestionRequest)(nil),       // 25: quiz.v1.DeleteQuestionRequest
	(*DeleteQuestionResponse)(nil),      // 26: quiz.v1.DeleteQuestionResponse
	(*StartQuizAttemptRequest)(nil),     // 27: quiz.v1.StartQuizAttemptRequest
	(*StartQuizAttemptResponse)(nil),    // 28: quiz.v1.StartQuizAttemptResponse
	(*SubmitAnswerRequest)(nil),         // 29: quiz.v1.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil),        // 30: quiz.v1.SubmitAnswerResponse
	(*CompleteQuizAttemptRequest)(nil),  // 31: quiz.v1.CompleteQuizAttemptRequest
	(*CompleteQuizAttemptResponse)(nil), // 32: quiz.v1.CompleteQuizAttemptResponse
	(*GetAttemptRequest)(nil),           // 33: quiz.v1.GetAttemptRequest
	(*GetAttemptResponse)(nil),          // 34: quiz.v1.GetAttemptResponse
	(*GetUserAttemptsRequest)(nil),      // 35: quiz.v1.GetUserAttemptsRequest
	(*GetUserAttemptsResponse)(nil),     // 36: quiz.v1.GetUserAttemptsResponse
	(*timestamppb.Timestamp)(nil),       // 37: google.protobuf.Timestamp
	(*v1.Hearts)(nil),                   // 38: gamification.v1.Hearts
	(*v1.AddXPResponse)(nil),            // 39: gamification.v1.AddXPResponse
}
var file_quiz_v1_quiz_proto_depIdxs = []int32{
	37, // 0: quiz.v1.Quiz.created_at:type_name -> google.protobuf.Timestamp
	37, // 1: quiz.v1.Quiz.updated_at:type_name -> google.protobuf.Timestamp
	37, // 2: quiz.v1.QuizQuestion.created_at:type_name -> google.protobuf.Timestamp
	37, // 3: quiz.v1.QuizQuestion.updated_at:type_name -> google.protobuf.Timestamp
	37, // 4: quiz.v1.QuizAnswer.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: quiz.v1.QuestionWithAnswers.question:type_name -> quiz.v1.QuizQuestion
	2,  // 6: quiz.v1.QuestionWithAnswers.answers:type_name -> quiz.v1.QuizAnswer
	0,  // 7: quiz.v1.QuizWithQuestions.quiz:type_name -> quiz.v1.Quiz
	3,  // 8: quiz.v1.QuizWithQuestions.questions:type_name -> quiz.v1.QuestionWithAnswers
	37, // 9: quiz.v1.QuizAttempt.started_at:type_name -> google.protobuf.Timestamp
	37, // 10: quiz.v1.QuizAttempt.completed_at:type_name -> google.protobuf.Timestamp
	37, // 11: quiz.v1.QuizAttempt.created_at:type_name -> google.protobuf.Timestamp
	37, // 12: quiz.v1.QuizAttempt.updated_at:type_name -> google.protobuf.Timestamp
	37, // 13: quiz.v1.QuizAttemptAnswer.created_at:type_name -> google.protobuf.Timestamp
	5,  // 14: quiz.v1.AttemptWithAnswers.attempt:type_name -> quiz.v1.QuizAttempt
	6,  // 15: quiz.v1.AttemptWithAnswers.answers:type_name -> quiz.v1.QuizAttemptAnswer
	0,  // 16: quiz.v1.CreateQuizResponse.quiz:type_name -> quiz.v1.Quiz
	4,  // 17: quiz.v1.GetQuizResponse.quiz:type_name -> quiz.v1.QuizWithQuestions
	0,  // 18: quiz.v1.UpdateQuizResponse.quiz:type_name -> quiz.v1.Quiz
	0,  // 19: quiz.v1.ListQuizzesResponse.quizzes:type_name -> quiz.v1.Quiz
	0,  // 20: quiz.v1.GetQuizzesByLessonResponse.quizzes:type_name -> quiz.v1.Quiz
	21, // 21: quiz.v1.AddQuestionRequest.answers:type_name -> quiz.v1.AddAnswerRequest
	1,  // 22: quiz.v1.AddQuestionResponse.question:type_name -> quiz.v1.QuizQuestion
	1,  // 23: quiz.v1.UpdateQuestionResponse.question:type_name -> quiz.v1.QuizQuestion
	5,  // 24: quiz.v1.StartQuizAttemptResponse.attempt:type_name -> quiz.v1.QuizAttempt
	6,  // 25: quiz.v1.SubmitAnswerResponse.answer:type_name -> quiz.v1.QuizAttemptAnswer
	38, // 26: quiz.v1.SubmitAnswerResponse.hearts:type_name -> gamification.v1.Hearts
	5,  // 27: quiz.v1.CompleteQuizAttemptResponse.attempt:type_name -> quiz.v1.QuizAttempt
	39, // 28: quiz.v1.CompleteQuizAttemptResponse.xp:type_name -> gamification.v1.AddXPResponse
	7,  // 29: quiz.v1.GetAttemptResponse.attempt:type_name -> quiz.v1.AttemptWithAnswers
	5,  // 30: quiz.v1.GetUserAttemptsResponse.attempts:type_name -> quiz.v1.QuizAttempt
	8,  // 31: quiz.v1.QuizService.CreateQuiz:input_type -> quiz.v1.CreateQuizRequest
	10, // 32: quiz.v1.QuizService.GetQuiz:input_type -> quiz.v1.GetQuizRequest
	12, // 33: quiz.v1.QuizService.UpdateQuiz:input_type -> quiz.v1.UpdateQuizRequest
	14, // 34: quiz.v1.QuizService.DeleteQuiz:input_type -> quiz.v1.DeleteQuizRequest
	16, // 35: quiz.v1.QuizService.ListQuizzes:input_type -> quiz.v1.ListQuizzesRequest
	18, // 36: quiz.v1.QuizService.GetQuizzesByLesson:input_type -> quiz.v1.GetQuizzesByLessonRequest
	20, // 37: quiz.v1.QuizService.AddQuestion:input_type -> quiz.v1.AddQuestionRequest
	23, // 38: quiz.v1.QuizService.UpdateQuestion:input_type -> quiz.v1.UpdateQuestionRequest
	25, // 39: quiz.v1.QuizService.DeleteQuestion:input_type -> quiz.v1.DeleteQuestionRequest
	27, // 40: quiz.v1.QuizService.StartQuizAttempt:input_type -> quiz.v1.StartQuizAttemptRequest
	29, // 41: quiz.v1.QuizService.SubmitAnswer:input_type -> quiz.v1.SubmitAnswerRequest
	31, // 42: quiz.v1.QuizService.CompleteQuizAttempt:input_type -> quiz.v1.CompleteQuizAttemptRequest
	33, // 43: quiz.v1.QuizService.GetAttempt:input_type -> quiz.v1.GetAttemptRequest
	35, // 44: quiz.v1.QuizService.GetUserAttempts:input_type -> quiz.v1.GetUserAttemptsRequest
	9,  // 45: quiz.v1.QuizService.CreateQuiz:output_type -> quiz.v1.CreateQuizResponse
	11, // 46: quiz.v1.QuizService.GetQuiz:output_type -> quiz.v1.GetQuizResponse
	13, // 47: quiz.v1.QuizService.UpdateQuiz:output_type -> quiz.v1.UpdateQuizResponse
	15, // 48: quiz.v1.QuizService.DeleteQuiz:output_type -> quiz.v1.DeleteQuizResponse
	17, // 49: quiz.v1.QuizService.ListQuizzes:output_type -> quiz.v1.ListQuizzesResponse
	19, // 50: quiz.v1.QuizService.GetQuizzesByLesson:output_type -> quiz.v1.GetQuizzesByLessonResponse
	22, // 51: quiz.v1.QuizService.AddQuestion:output_type -> quiz.v1.AddQuestionResponse
	24, // 52: quiz.v1.QuizService.UpdateQuestion:output_type -> quiz.v1.UpdateQuestionResponse
	26, // 53: quiz.v1.QuizService.DeleteQuestion:output_type -> quiz.v1.DeleteQuestionResponse
	28, // 54: quiz.v1.QuizService.StartQuizAttempt:output_type -> quiz.v1.StartQuizAttemptResponse
	30, // 55: quiz.v1.QuizService.SubmitAnswer:output_type -> quiz.v1.SubmitAnswerResponse
	32, // 56: quiz.v1.QuizService.CompleteQuizAttempt:output_type -> quiz.v1.CompleteQuizAttemptResponse
	34, // 57: quiz.v1.QuizService.GetAttempt:output_type -> quiz.v1.GetAttemptResponse
	36, // 58: quiz.v1.QuizService.GetUserAttempts:output_type -> quiz.v1.GetUserAttemptsResponse
	45, // [45:59] is the sub-list for method output_type
	31, // [31:45] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_quiz_v1_quiz_proto_init() }
func file_quiz_v1_quiz_proto_init() {
	if File_quiz_v1_quiz_proto != nil {
		return
	}
	file_quiz_v1_quiz_proto_msgTypes[0].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[1].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[5].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[6].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[8].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[12].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[20].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[23].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[29].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[30].OneofWrappers = []any{}
	file_quiz_v1_quiz_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quiz_v1_quiz_proto_rawDesc), len(file_quiz_v1_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quiz_v1_quiz_proto_goTypes,
		DependencyIndexes: file_quiz_v1_quiz_proto_depIdxs,
		MessageInfos:      file_quiz_v1_quiz_proto_msgTypes,
	}.Build()
	File_quiz_v1_quiz_proto = out.File
	file_quiz_v1_quiz_proto_goTypes = nil
	file_quiz_v1_quiz_proto_depIdxs = nil
}
