// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: social/v1/social.proto

package socialv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialService_ListLeagues_FullMethodName           = "/social.v1.SocialService/ListLeagues"
	SocialService_EnsureUserInLeague_FullMethodName    = "/social.v1.SocialService/EnsureUserInLeague"
	SocialService_GetMyLeague_FullMethodName           = "/social.v1.SocialService/GetMyLeague"
	SocialService_GetMyLeaderboard_FullMethodName      = "/social.v1.SocialService/GetMyLeaderboard"
	SocialService_GetHistory_FullMethodName            = "/social.v1.SocialService/GetHistory"
	SocialService_RunWeeklyRotation_FullMethodName     = "/social.v1.SocialService/RunWeeklyRotation"
	SocialService_SendFriendRequest_FullMethodName     = "/social.v1.SocialService/SendFriendRequest"
	SocialService_AcceptFriendRequest_FullMethodName   = "/social.v1.SocialService/AcceptFriendRequest"
	SocialService_RejectFriendRequest_FullMethodName   = "/social.v1.SocialService/RejectFriendRequest"
	SocialService_RemoveFriend_FullMethodName          = "/social.v1.SocialService/RemoveFriend"
	SocialService_ListFriends_FullMethodName           = "/social.v1.SocialService/ListFriends"
	SocialService_ListPendingRequests_FullMethodName   = "/social.v1.SocialService/ListPendingRequests"
	SocialService_SearchUsersByUsername_FullMethodName = "/social.v1.SocialService/SearchUsersByUsername"
	SocialService_GetFriendsLeaderboard_FullMethodName = "/social.v1.SocialService/GetFriendsLeaderboard"
)

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SocialService — Phase 4 (Leagues / Cohorts / Leaderboards).
//
// Хранит состояние юзера в Duolingo-like лигах: 10 уровней (Bronze → Diamond),
// когорты по 30 человек, weekly cycle понедельник 00:00 → воскресенье 23:59 UTC.
//
// Источник XP — Kafka topic `xp.gained`, который публикует gamification-service
// после каждого AddXP. Consumer обновляет weekly_xp в Postgres + Redis ZIncrBy
// в leaderboard:cohort:{cohort_id}.
//
// Каждое воскресенье 23:59 cron WeeklyRotation:
//   - Считывает финальный rank из Redis,
//   - Записывает в league_history,
//   - Top 7 → promotion в следующую лигу,
//   - Bottom 5 (не Bronze) → demotion,
//   - Reassign в новую когорту,
//   - Reset Redis + weekly_xp.
type SocialServiceClient interface {
	// ListLeagues — каталог 10 лиг (Bronze → Diamond), отсортированы по tier.
	// Public, кэшируемый. Для UI badges, иконок и т.п.
	ListLeagues(ctx context.Context, in *ListLeaguesRequest, opts ...grpc.CallOption) (*ListLeaguesResponse, error)
	// EnsureUserInLeague — гарантирует что юзер привязан к когорте.
	// Idempotent: при повторном вызове возвращает существующую запись.
	// Используется при первом активном действии (login / первый XP).
	// На MVP: новый юзер автоматически попадает в Bronze League.
	EnsureUserInLeague(ctx context.Context, in *EnsureUserInLeagueRequest, opts ...grpc.CallOption) (*EnsureUserInLeagueResponse, error)
	// GetMyLeague — текущая лига юзера + cohort_id + weekly_xp + rank.
	// Если юзер ещё не в лиге — возвращает NotFound.
	GetMyLeague(ctx context.Context, in *GetMyLeagueRequest, opts ...grpc.CallOption) (*GetMyLeagueResponse, error)
	// GetMyLeaderboard — топ 30 моей когорты, отсортированы по weekly_xp.
	// Включает promotion/demotion zone hints. Profiles обогащаются
	// через user-service.BatchGetProfiles.
	GetMyLeaderboard(ctx context.Context, in *GetMyLeaderboardRequest, opts ...grpc.CallOption) (*GetMyLeaderboardResponse, error)
	// GetHistory — история выступлений в лигах с пагинацией.
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// RunWeeklyRotation — запускает rotation немедленно. Обычно вызывается
	// cron'ом по расписанию (вс 23:59 UTC), но также доступен админу для
	// manual trigger / тестирования. Параметр force=true игнорирует
	// проверку "когорта ещё не закрыта".
	RunWeeklyRotation(ctx context.Context, in *RunWeeklyRotationRequest, opts ...grpc.CallOption) (*RunWeeklyRotationResponse, error)
	// SendFriendRequest — отправить запрос дружбы (caller → target).
	// Idempotent: повторный запрос на pending = no-op.
	// Если target уже отправил pending caller'у — записи объединяются
	// в accepted (mutual auto-accept).
	SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error)
	// AcceptFriendRequest — принять входящий pending. Только если
	// caller — target запроса (не requester).
	AcceptFriendRequest(ctx context.Context, in *AcceptFriendRequestRequest, opts ...grpc.CallOption) (*AcceptFriendRequestResponse, error)
	// RejectFriendRequest — отклонить входящий pending. Удаляет запись
	// (юзер сможет отправить запрос снова).
	RejectFriendRequest(ctx context.Context, in *RejectFriendRequestRequest, opts ...grpc.CallOption) (*RejectFriendRequestResponse, error)
	// RemoveFriend — расторгнуть дружбу (любая сторона). Удаляет
	// accepted-запись.
	RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error)
	// ListFriends — список accepted-друзей с обогащением профилями.
	ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
	// ListPendingRequests — pending-входящие (which target == caller)
	// и/или исходящие (requester == caller).
	ListPendingRequests(ctx context.Context, in *ListPendingRequestsRequest, opts ...grpc.CallOption) (*ListPendingRequestsResponse, error)
	// SearchUsersByUsername — поиск пользователей для добавления в друзья.
	// Делегирует в auth-service.SearchByUsername + обогащает профилями.
	// Возвращает также текущий статус дружбы с caller'ом (если есть).
	SearchUsersByUsername(ctx context.Context, in *SearchUsersByUsernameRequest, opts ...grpc.CallOption) (*SearchUsersByUsernameResponse, error)
	// GetFriendsLeaderboard — leaderboard среди друзей + self,
	// отсортирован по weekly_xp (DESC) из user_leagues.
	GetFriendsLeaderboard(ctx context.Context, in *GetFriendsLeaderboardRequest, opts ...grpc.CallOption) (*GetFriendsLeaderboardResponse, error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) ListLeagues(ctx context.Context, in *ListLeaguesRequest, opts ...grpc.CallOption) (*ListLeaguesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeaguesResponse)
	err := c.cc.Invoke(ctx, SocialService_ListLeagues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) EnsureUserInLeague(ctx context.Context, in *EnsureUserInLeagueRequest, opts ...grpc.CallOption) (*EnsureUserInLeagueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureUserInLeagueResponse)
	err := c.cc.Invoke(ctx, SocialService_EnsureUserInLeague_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetMyLeague(ctx context.Context, in *GetMyLeagueRequest, opts ...grpc.CallOption) (*GetMyLeagueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyLeagueResponse)
	err := c.cc.Invoke(ctx, SocialService_GetMyLeague_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetMyLeaderboard(ctx context.Context, in *GetMyLeaderboardRequest, opts ...grpc.CallOption) (*GetMyLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyLeaderboardResponse)
	err := c.cc.Invoke(ctx, SocialService_GetMyLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, SocialService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) RunWeeklyRotation(ctx context.Context, in *RunWeeklyRotationRequest, opts ...grpc.CallOption) (*RunWeeklyRotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunWeeklyRotationResponse)
	err := c.cc.Invoke(ctx, SocialService_RunWeeklyRotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFriendRequestResponse)
	err := c.cc.Invoke(ctx, SocialService_SendFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) AcceptFriendRequest(ctx context.Context, in *AcceptFriendRequestRequest, opts ...grpc.CallOption) (*AcceptFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptFriendRequestResponse)
	err := c.cc.Invoke(ctx, SocialService_AcceptFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) RejectFriendRequest(ctx context.Context, in *RejectFriendRequestRequest, opts ...grpc.CallOption) (*RejectFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectFriendRequestResponse)
	err := c.cc.Invoke(ctx, SocialService_RejectFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFriendResponse)
	err := c.cc.Invoke(ctx, SocialService_RemoveFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendsResponse)
	err := c.cc.Invoke(ctx, SocialService_ListFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ListPendingRequests(ctx context.Context, in *ListPendingRequestsRequest, opts ...grpc.CallOption) (*ListPendingRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingRequestsResponse)
	err := c.cc.Invoke(ctx, SocialService_ListPendingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) SearchUsersByUsername(ctx context.Context, in *SearchUsersByUsernameRequest, opts ...grpc.CallOption) (*SearchUsersByUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsersByUsernameResponse)
	err := c.cc.Invoke(ctx, SocialService_SearchUsersByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetFriendsLeaderboard(ctx context.Context, in *GetFriendsLeaderboardRequest, opts ...grpc.CallOption) (*GetFriendsLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsLeaderboardResponse)
	err := c.cc.Invoke(ctx, SocialService_GetFriendsLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServiceServer is the server API for SocialService service.
// All implementations must embed UnimplementedSocialServiceServer
// for forward compatibility.
//
// SocialService — Phase 4 (Leagues / Cohorts / Leaderboards).
//
// Хранит состояние юзера в Duolingo-like лигах: 10 уровней (Bronze → Diamond),
// когорты по 30 человек, weekly cycle понедельник 00:00 → воскресенье 23:59 UTC.
//
// Источник XP — Kafka topic `xp.gained`, который публикует gamification-service
// после каждого AddXP. Consumer обновляет weekly_xp в Postgres + Redis ZIncrBy
// в leaderboard:cohort:{cohort_id}.
//
// Каждое воскресенье 23:59 cron WeeklyRotation:
//   - Считывает финальный rank из Redis,
//   - Записывает в league_history,
//   - Top 7 → promotion в следующую лигу,
//   - Bottom 5 (не Bronze) → demotion,
//   - Reassign в новую когорту,
//   - Reset Redis + weekly_xp.
type SocialServiceServer interface {
	// ListLeagues — каталог 10 лиг (Bronze → Diamond), отсортированы по tier.
	// Public, кэшируемый. Для UI badges, иконок и т.п.
	ListLeagues(context.Context, *ListLeaguesRequest) (*ListLeaguesResponse, error)
	// EnsureUserInLeague — гарантирует что юзер привязан к когорте.
	// Idempotent: при повторном вызове возвращает существующую запись.
	// Используется при первом активном действии (login / первый XP).
	// На MVP: новый юзер автоматически попадает в Bronze League.
	EnsureUserInLeague(context.Context, *EnsureUserInLeagueRequest) (*EnsureUserInLeagueResponse, error)
	// GetMyLeague — текущая лига юзера + cohort_id + weekly_xp + rank.
	// Если юзер ещё не в лиге — возвращает NotFound.
	GetMyLeague(context.Context, *GetMyLeagueRequest) (*GetMyLeagueResponse, error)
	// GetMyLeaderboard — топ 30 моей когорты, отсортированы по weekly_xp.
	// Включает promotion/demotion zone hints. Profiles обогащаются
	// через user-service.BatchGetProfiles.
	GetMyLeaderboard(context.Context, *GetMyLeaderboardRequest) (*GetMyLeaderboardResponse, error)
	// GetHistory — история выступлений в лигах с пагинацией.
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// RunWeeklyRotation — запускает rotation немедленно. Обычно вызывается
	// cron'ом по расписанию (вс 23:59 UTC), но также доступен админу для
	// manual trigger / тестирования. Параметр force=true игнорирует
	// проверку "когорта ещё не закрыта".
	RunWeeklyRotation(context.Context, *RunWeeklyRotationRequest) (*RunWeeklyRotationResponse, error)
	// SendFriendRequest — отправить запрос дружбы (caller → target).
	// Idempotent: повторный запрос на pending = no-op.
	// Если target уже отправил pending caller'у — записи объединяются
	// в accepted (mutual auto-accept).
	SendFriendRequest(context.Context, *SendFriendRequestRequest) (*SendFriendRequestResponse, error)
	// AcceptFriendRequest — принять входящий pending. Только если
	// caller — target запроса (не requester).
	AcceptFriendRequest(context.Context, *AcceptFriendRequestRequest) (*AcceptFriendRequestResponse, error)
	// RejectFriendRequest — отклонить входящий pending. Удаляет запись
	// (юзер сможет отправить запрос снова).
	RejectFriendRequest(context.Context, *RejectFriendRequestRequest) (*RejectFriendRequestResponse, error)
	// RemoveFriend — расторгнуть дружбу (любая сторона). Удаляет
	// accepted-запись.
	RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error)
	// ListFriends — список accepted-друзей с обогащением профилями.
	ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error)
	// ListPendingRequests — pending-входящие (which target == caller)
	// и/или исходящие (requester == caller).
	ListPendingRequests(context.Context, *ListPendingRequestsRequest) (*ListPendingRequestsResponse, error)
	// SearchUsersByUsername — поиск пользователей для добавления в друзья.
	// Делегирует в auth-service.SearchByUsername + обогащает профилями.
	// Возвращает также текущий статус дружбы с caller'ом (если есть).
	SearchUsersByUsername(context.Context, *SearchUsersByUsernameRequest) (*SearchUsersByUsernameResponse, error)
	// GetFriendsLeaderboard — leaderboard среди друзей + self,
	// отсортирован по weekly_xp (DESC) из user_leagues.
	GetFriendsLeaderboard(context.Context, *GetFriendsLeaderboardRequest) (*GetFriendsLeaderboardResponse, error)
	mustEmbedUnimplementedSocialServiceServer()
}

// UnimplementedSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServiceServer struct{}

func (UnimplementedSocialServiceServer) ListLeagues(context.Context, *ListLeaguesRequest) (*ListLeaguesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeagues not implemented")
}
func (UnimplementedSocialServiceServer) EnsureUserInLeague(context.Context, *EnsureUserInLeagueRequest) (*EnsureUserInLeagueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureUserInLeague not implemented")
}
func (UnimplementedSocialServiceServer) GetMyLeague(context.Context, *GetMyLeagueRequest) (*GetMyLeagueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyLeague not implemented")
}
func (UnimplementedSocialServiceServer) GetMyLeaderboard(context.Context, *GetMyLeaderboardRequest) (*GetMyLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyLeaderboard not implemented")
}
func (UnimplementedSocialServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedSocialServiceServer) RunWeeklyRotation(context.Context, *RunWeeklyRotationRequest) (*RunWeeklyRotationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWeeklyRotation not implemented")
}
func (UnimplementedSocialServiceServer) SendFriendRequest(context.Context, *SendFriendRequestRequest) (*SendFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedSocialServiceServer) AcceptFriendRequest(context.Context, *AcceptFriendRequestRequest) (*AcceptFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptFriendRequest not implemented")
}
func (UnimplementedSocialServiceServer) RejectFriendRequest(context.Context, *RejectFriendRequestRequest) (*RejectFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectFriendRequest not implemented")
}
func (UnimplementedSocialServiceServer) RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (UnimplementedSocialServiceServer) ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFriends not implemented")
}
func (UnimplementedSocialServiceServer) ListPendingRequests(context.Context, *ListPendingRequestsRequest) (*ListPendingRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingRequests not implemented")
}
func (UnimplementedSocialServiceServer) SearchUsersByUsername(context.Context, *SearchUsersByUsernameRequest) (*SearchUsersByUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUsersByUsername not implemented")
}
func (UnimplementedSocialServiceServer) GetFriendsLeaderboard(context.Context, *GetFriendsLeaderboardRequest) (*GetFriendsLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendsLeaderboard not implemented")
}
func (UnimplementedSocialServiceServer) mustEmbedUnimplementedSocialServiceServer() {}
func (UnimplementedSocialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServiceServer will
// result in compilation errors.
type UnsafeSocialServiceServer interface {
	mustEmbedUnimplementedSocialServiceServer()
}

func RegisterSocialServiceServer(s grpc.ServiceRegistrar, srv SocialServiceServer) {
	// If the following call panics, it indicates UnimplementedSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialService_ServiceDesc, srv)
}

func _SocialService_ListLeagues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeaguesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ListLeagues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ListLeagues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ListLeagues(ctx, req.(*ListLeaguesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_EnsureUserInLeague_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureUserInLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).EnsureUserInLeague(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_EnsureUserInLeague_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).EnsureUserInLeague(ctx, req.(*EnsureUserInLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetMyLeague_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyLeagueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetMyLeague(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetMyLeague_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetMyLeague(ctx, req.(*GetMyLeagueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetMyLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetMyLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetMyLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetMyLeaderboard(ctx, req.(*GetMyLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_RunWeeklyRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunWeeklyRotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).RunWeeklyRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_RunWeeklyRotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).RunWeeklyRotation(ctx, req.(*RunWeeklyRotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).SendFriendRequest(ctx, req.(*SendFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_AcceptFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).AcceptFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_AcceptFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).AcceptFriendRequest(ctx, req.(*AcceptFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_RejectFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).RejectFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_RejectFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).RejectFriendRequest(ctx, req.(*RejectFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_RemoveFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).RemoveFriend(ctx, req.(*RemoveFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ListFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ListFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ListFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ListFriends(ctx, req.(*ListFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ListPendingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ListPendingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ListPendingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ListPendingRequests(ctx, req.(*ListPendingRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_SearchUsersByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).SearchUsersByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_SearchUsersByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).SearchUsersByUsername(ctx, req.(*SearchUsersByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetFriendsLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetFriendsLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetFriendsLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetFriendsLeaderboard(ctx, req.(*GetFriendsLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialService_ServiceDesc is the grpc.ServiceDesc for SocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.v1.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLeagues",
			Handler:    _SocialService_ListLeagues_Handler,
		},
		{
			MethodName: "EnsureUserInLeague",
			Handler:    _SocialService_EnsureUserInLeague_Handler,
		},
		{
			MethodName: "GetMyLeague",
			Handler:    _SocialService_GetMyLeague_Handler,
		},
		{
			MethodName: "GetMyLeaderboard",
			Handler:    _SocialService_GetMyLeaderboard_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _SocialService_GetHistory_Handler,
		},
		{
			MethodName: "RunWeeklyRotation",
			Handler:    _SocialService_RunWeeklyRotation_Handler,
		},
		{
			MethodName: "SendFriendRequest",
			Handler:    _SocialService_SendFriendRequest_Handler,
		},
		{
			MethodName: "AcceptFriendRequest",
			Handler:    _SocialService_AcceptFriendRequest_Handler,
		},
		{
			MethodName: "RejectFriendRequest",
			Handler:    _SocialService_RejectFriendRequest_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _SocialService_RemoveFriend_Handler,
		},
		{
			MethodName: "ListFriends",
			Handler:    _SocialService_ListFriends_Handler,
		},
		{
			MethodName: "ListPendingRequests",
			Handler:    _SocialService_ListPendingRequests_Handler,
		},
		{
			MethodName: "SearchUsersByUsername",
			Handler:    _SocialService_SearchUsersByUsername_Handler,
		},
		{
			MethodName: "GetFriendsLeaderboard",
			Handler:    _SocialService_GetFriendsLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social/v1/social.proto",
}
