// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ai/v1/ai.proto

package aiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_StartConversation_FullMethodName     = "/ai.v1.AIService/StartConversation"
	AIService_SendMessage_FullMethodName           = "/ai.v1.AIService/SendMessage"
	AIService_SendMessageStream_FullMethodName     = "/ai.v1.AIService/SendMessageStream"
	AIService_ListConversations_FullMethodName     = "/ai.v1.AIService/ListConversations"
	AIService_GetConversation_FullMethodName       = "/ai.v1.AIService/GetConversation"
	AIService_DeleteConversation_FullMethodName    = "/ai.v1.AIService/DeleteConversation"
	AIService_ListScenarios_FullMethodName         = "/ai.v1.AIService/ListScenarios"
	AIService_ExplainMistake_FullMethodName        = "/ai.v1.AIService/ExplainMistake"
	AIService_ExplainMistakeStream_FullMethodName  = "/ai.v1.AIService/ExplainMistakeStream"
	AIService_AssessWriting_FullMethodName         = "/ai.v1.AIService/AssessWriting"
	AIService_AssessWritingStream_FullMethodName   = "/ai.v1.AIService/AssessWritingStream"
	AIService_CheckPronunciation_FullMethodName    = "/ai.v1.AIService/CheckPronunciation"
	AIService_AskTutor_FullMethodName              = "/ai.v1.AIService/AskTutor"
	AIService_AskTutorStream_FullMethodName        = "/ai.v1.AIService/AskTutorStream"
	AIService_GenerateExercise_FullMethodName      = "/ai.v1.AIService/GenerateExercise"
	AIService_GetQuotaStatus_FullMethodName        = "/ai.v1.AIService/GetQuotaStatus"
	AIService_SubmitMessageFeedback_FullMethodName = "/ai.v1.AIService/SubmitMessageFeedback"
	AIService_DeleteMessageFeedback_FullMethodName = "/ai.v1.AIService/DeleteMessageFeedback"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIService — Phase 5 (AI Integration).
//
// Управляет AI-фичами платформы:
//   - Conversation — свободный диалог / roleplay / tutor с AI.
//   - Explain — объяснение ошибок ученика на родном языке.
//   - Writing assessment — оценка письменной работы.
//   - Pronunciation check — оценка произношения по аудио.
//   - Content generation — генерация упражнений для админа.
//   - Quota — суточные лимиты для free-плана.
//
// Все вызовы — pull (gateway → ai-service). Хуков из других сервисов
// нет (push-стиля как gamification.OnStepCompleted). При недоступности
// ai-service обучение не страдает: gateway вернёт 5xx только на
// /api/v1/ai/* эндпоинтах.
type AIServiceClient interface {
	// StartConversation — создаёт новую AI-сессию. scenario определяет
	// тип: free_chat / roleplay_<id> / tutor_qa. user_level берётся из
	// user-service (если не указан явно — fallback B1).
	StartConversation(ctx context.Context, in *StartConversationRequest, opts ...grpc.CallOption) (*StartConversationResponse, error)
	// SendMessage — отправляет user-сообщение в существующую беседу,
	// получает AI-reply (с опциональным TTS audio_url, переводом и
	// grammar-correction'ами). Учитывает last 10 сообщений из истории.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// SendMessageStream — server-streaming версия SendMessage для UX
	// typewriter-эффекта (Phase 5.27). Гарантированно эмитит:
	//  1. первым chunk — UserMessage (после sanitize/PII/moderation/persist);
	//  2. затем N delta-chunk'ов — incremental текст assistant-reply;
	//  3. финальным chunk — Done с полным AssistantMessage (включая
	//     tokens / cost / id / timestamp).
	//
	// При ошибке середины потока — Error chunk и закрытие stream'а.
	// Для streaming-режима translation/corrections не возвращаются (plain
	// text reply); за полным форматом — обычный SendMessage.
	SendMessageStream(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SendMessageStreamChunk], error)
	// ListConversations — конверсации текущего юзера, отсортированы
	// по started_at DESC. Без сообщений (lightweight).
	ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
	// GetConversation — конверсация + все её сообщения (для рендера
	// полной истории чата).
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error)
	// DeleteConversation — soft-delete (ставит ended_at), оставляя
	// данные для cost-аналитики.
	DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error)
	// ListScenarios — каталог roleplay-сценариев (статика из кода).
	ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error)
	// ExplainMistake — объясняет, почему ответ неверен, на нативном
	// языке юзера. Кэшируется по (step_id, md5(incorrect_answer)) —
	// повторные запросы возвращают cached=true мгновенно.
	ExplainMistake(ctx context.Context, in *ExplainMistakeRequest, opts ...grpc.CallOption) (*ExplainMistakeResponse, error)
	// ExplainMistakeStream — server-streaming версия ExplainMistake (Phase 5.X).
	//
	// При cache-hit'е поток сразу эмитит один Done chunk с cached=true
	// (без delta'ы, так как объяснение уже есть). При miss'е — стандартные
	// delta-chunks → final Done с cached=false.
	// Reply при cache miss — plain text (не JSON), чтобы streaming был
	// токен-по-токену.
	ExplainMistakeStream(ctx context.Context, in *ExplainMistakeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExplainMistakeStreamChunk], error)
	// AssessWriting — оценивает письменную работу: 4 score'а,
	// corrected_text, structured feedback по категориям.
	AssessWriting(ctx context.Context, in *AssessWritingRequest, opts ...grpc.CallOption) (*AssessWritingResponse, error)
	// AssessWritingStream — server-streaming версия AssessWriting (Phase 5.X).
	//
	// Provider возвращает структурированный JSON, который сложно парсить
	// пo-чанково. Поэтому stream эмитит сырые delta-чанки (raw JSON-токены)
	// как «typing indicator» для UI, а финальный Done chunk содержит уже
	// распарсенный AssessWritingResponse со всеми scores / feedback.
	AssessWritingStream(ctx context.Context, in *AssessWritingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AssessWritingStreamChunk], error)
	// CheckPronunciation — принимает аудио (raw bytes), транскрибирует,
	// считает phonetic similarity, word-level alignment. На MVP audio_*
	// обрабатываются через mock-provider; реальный Whisper — позже.
	CheckPronunciation(ctx context.Context, in *CheckPronunciationRequest, opts ...grpc.CallOption) (*CheckPronunciationResponse, error)
	// AskTutor — однократный вопрос «учителю»: prompt + answer без
	// persistence. Если нужен контекст — открывайте Conversation
	// со scenario=tutor_qa.
	AskTutor(ctx context.Context, in *AskTutorRequest, opts ...grpc.CallOption) (*AskTutorResponse, error)
	// AskTutorStream — server-streaming версия AskTutor (Phase 5.X).
	// Тот же контракт что и SendMessageStream, но без UserMessage echo
	// (нет persistence): первый chunk — delta или сразу done. Поток
	// гарантированно завершается одним из: done | error_message.
	// Reply — plain text (не JSON), потому что streaming JSON неудобно
	// парсить пo-чанково.
	AskTutorStream(ctx context.Context, in *AskTutorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AskTutorStreamChunk], error)
	// GenerateExercise — генерирует упражнение указанного типа из
	// словаря. Без сохранения в БД — caller сам решает дальше.
	GenerateExercise(ctx context.Context, in *GenerateExerciseRequest, opts ...grpc.CallOption) (*GenerateExerciseResponse, error)
	// GetQuotaStatus — текущие счётчики free-плана. Premium юзеры
	// получают unlimited: -1 в полях лимитов.
	GetQuotaStatus(ctx context.Context, in *GetQuotaStatusRequest, opts ...grpc.CallOption) (*GetQuotaStatusResponse, error)
	// SubmitMessageFeedback — UPSERT thumbs up/down оценки assistant-message.
	// Повторный вызов с другим rating'ом — переключает оценку.
	SubmitMessageFeedback(ctx context.Context, in *SubmitMessageFeedbackRequest, opts ...grpc.CallOption) (*SubmitMessageFeedbackResponse, error)
	// DeleteMessageFeedback — снимает оценку (idempotent).
	DeleteMessageFeedback(ctx context.Context, in *DeleteMessageFeedbackRequest, opts ...grpc.CallOption) (*DeleteMessageFeedbackResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) StartConversation(ctx context.Context, in *StartConversationRequest, opts ...grpc.CallOption) (*StartConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartConversationResponse)
	err := c.cc.Invoke(ctx, AIService_StartConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, AIService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) SendMessageStream(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SendMessageStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], AIService_SendMessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, SendMessageStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_SendMessageStreamClient = grpc.ServerStreamingClient[SendMessageStreamChunk]

func (c *aIServiceClient) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResponse)
	err := c.cc.Invoke(ctx, AIService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationResponse)
	err := c.cc.Invoke(ctx, AIService_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationResponse)
	err := c.cc.Invoke(ctx, AIService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScenariosResponse)
	err := c.cc.Invoke(ctx, AIService_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ExplainMistake(ctx context.Context, in *ExplainMistakeRequest, opts ...grpc.CallOption) (*ExplainMistakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainMistakeResponse)
	err := c.cc.Invoke(ctx, AIService_ExplainMistake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ExplainMistakeStream(ctx context.Context, in *ExplainMistakeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExplainMistakeStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[1], AIService_ExplainMistakeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExplainMistakeRequest, ExplainMistakeStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ExplainMistakeStreamClient = grpc.ServerStreamingClient[ExplainMistakeStreamChunk]

func (c *aIServiceClient) AssessWriting(ctx context.Context, in *AssessWritingRequest, opts ...grpc.CallOption) (*AssessWritingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessWritingResponse)
	err := c.cc.Invoke(ctx, AIService_AssessWriting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) AssessWritingStream(ctx context.Context, in *AssessWritingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AssessWritingStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[2], AIService_AssessWritingStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssessWritingRequest, AssessWritingStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_AssessWritingStreamClient = grpc.ServerStreamingClient[AssessWritingStreamChunk]

func (c *aIServiceClient) CheckPronunciation(ctx context.Context, in *CheckPronunciationRequest, opts ...grpc.CallOption) (*CheckPronunciationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPronunciationResponse)
	err := c.cc.Invoke(ctx, AIService_CheckPronunciation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) AskTutor(ctx context.Context, in *AskTutorRequest, opts ...grpc.CallOption) (*AskTutorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskTutorResponse)
	err := c.cc.Invoke(ctx, AIService_AskTutor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) AskTutorStream(ctx context.Context, in *AskTutorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AskTutorStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[3], AIService_AskTutorStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AskTutorRequest, AskTutorStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_AskTutorStreamClient = grpc.ServerStreamingClient[AskTutorStreamChunk]

func (c *aIServiceClient) GenerateExercise(ctx context.Context, in *GenerateExerciseRequest, opts ...grpc.CallOption) (*GenerateExerciseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateExerciseResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateExercise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetQuotaStatus(ctx context.Context, in *GetQuotaStatusRequest, opts ...grpc.CallOption) (*GetQuotaStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuotaStatusResponse)
	err := c.cc.Invoke(ctx, AIService_GetQuotaStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) SubmitMessageFeedback(ctx context.Context, in *SubmitMessageFeedbackRequest, opts ...grpc.CallOption) (*SubmitMessageFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitMessageFeedbackResponse)
	err := c.cc.Invoke(ctx, AIService_SubmitMessageFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) DeleteMessageFeedback(ctx context.Context, in *DeleteMessageFeedbackRequest, opts ...grpc.CallOption) (*DeleteMessageFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageFeedbackResponse)
	err := c.cc.Invoke(ctx, AIService_DeleteMessageFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
//
// AIService — Phase 5 (AI Integration).
//
// Управляет AI-фичами платформы:
//   - Conversation — свободный диалог / roleplay / tutor с AI.
//   - Explain — объяснение ошибок ученика на родном языке.
//   - Writing assessment — оценка письменной работы.
//   - Pronunciation check — оценка произношения по аудио.
//   - Content generation — генерация упражнений для админа.
//   - Quota — суточные лимиты для free-плана.
//
// Все вызовы — pull (gateway → ai-service). Хуков из других сервисов
// нет (push-стиля как gamification.OnStepCompleted). При недоступности
// ai-service обучение не страдает: gateway вернёт 5xx только на
// /api/v1/ai/* эндпоинтах.
type AIServiceServer interface {
	// StartConversation — создаёт новую AI-сессию. scenario определяет
	// тип: free_chat / roleplay_<id> / tutor_qa. user_level берётся из
	// user-service (если не указан явно — fallback B1).
	StartConversation(context.Context, *StartConversationRequest) (*StartConversationResponse, error)
	// SendMessage — отправляет user-сообщение в существующую беседу,
	// получает AI-reply (с опциональным TTS audio_url, переводом и
	// grammar-correction'ами). Учитывает last 10 сообщений из истории.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// SendMessageStream — server-streaming версия SendMessage для UX
	// typewriter-эффекта (Phase 5.27). Гарантированно эмитит:
	//  1. первым chunk — UserMessage (после sanitize/PII/moderation/persist);
	//  2. затем N delta-chunk'ов — incremental текст assistant-reply;
	//  3. финальным chunk — Done с полным AssistantMessage (включая
	//     tokens / cost / id / timestamp).
	//
	// При ошибке середины потока — Error chunk и закрытие stream'а.
	// Для streaming-режима translation/corrections не возвращаются (plain
	// text reply); за полным форматом — обычный SendMessage.
	SendMessageStream(*SendMessageRequest, grpc.ServerStreamingServer[SendMessageStreamChunk]) error
	// ListConversations — конверсации текущего юзера, отсортированы
	// по started_at DESC. Без сообщений (lightweight).
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	// GetConversation — конверсация + все её сообщения (для рендера
	// полной истории чата).
	GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error)
	// DeleteConversation — soft-delete (ставит ended_at), оставляя
	// данные для cost-аналитики.
	DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error)
	// ListScenarios — каталог roleplay-сценариев (статика из кода).
	ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error)
	// ExplainMistake — объясняет, почему ответ неверен, на нативном
	// языке юзера. Кэшируется по (step_id, md5(incorrect_answer)) —
	// повторные запросы возвращают cached=true мгновенно.
	ExplainMistake(context.Context, *ExplainMistakeRequest) (*ExplainMistakeResponse, error)
	// ExplainMistakeStream — server-streaming версия ExplainMistake (Phase 5.X).
	//
	// При cache-hit'е поток сразу эмитит один Done chunk с cached=true
	// (без delta'ы, так как объяснение уже есть). При miss'е — стандартные
	// delta-chunks → final Done с cached=false.
	// Reply при cache miss — plain text (не JSON), чтобы streaming был
	// токен-по-токену.
	ExplainMistakeStream(*ExplainMistakeRequest, grpc.ServerStreamingServer[ExplainMistakeStreamChunk]) error
	// AssessWriting — оценивает письменную работу: 4 score'а,
	// corrected_text, structured feedback по категориям.
	AssessWriting(context.Context, *AssessWritingRequest) (*AssessWritingResponse, error)
	// AssessWritingStream — server-streaming версия AssessWriting (Phase 5.X).
	//
	// Provider возвращает структурированный JSON, который сложно парсить
	// пo-чанково. Поэтому stream эмитит сырые delta-чанки (raw JSON-токены)
	// как «typing indicator» для UI, а финальный Done chunk содержит уже
	// распарсенный AssessWritingResponse со всеми scores / feedback.
	AssessWritingStream(*AssessWritingRequest, grpc.ServerStreamingServer[AssessWritingStreamChunk]) error
	// CheckPronunciation — принимает аудио (raw bytes), транскрибирует,
	// считает phonetic similarity, word-level alignment. На MVP audio_*
	// обрабатываются через mock-provider; реальный Whisper — позже.
	CheckPronunciation(context.Context, *CheckPronunciationRequest) (*CheckPronunciationResponse, error)
	// AskTutor — однократный вопрос «учителю»: prompt + answer без
	// persistence. Если нужен контекст — открывайте Conversation
	// со scenario=tutor_qa.
	AskTutor(context.Context, *AskTutorRequest) (*AskTutorResponse, error)
	// AskTutorStream — server-streaming версия AskTutor (Phase 5.X).
	// Тот же контракт что и SendMessageStream, но без UserMessage echo
	// (нет persistence): первый chunk — delta или сразу done. Поток
	// гарантированно завершается одним из: done | error_message.
	// Reply — plain text (не JSON), потому что streaming JSON неудобно
	// парсить пo-чанково.
	AskTutorStream(*AskTutorRequest, grpc.ServerStreamingServer[AskTutorStreamChunk]) error
	// GenerateExercise — генерирует упражнение указанного типа из
	// словаря. Без сохранения в БД — caller сам решает дальше.
	GenerateExercise(context.Context, *GenerateExerciseRequest) (*GenerateExerciseResponse, error)
	// GetQuotaStatus — текущие счётчики free-плана. Premium юзеры
	// получают unlimited: -1 в полях лимитов.
	GetQuotaStatus(context.Context, *GetQuotaStatusRequest) (*GetQuotaStatusResponse, error)
	// SubmitMessageFeedback — UPSERT thumbs up/down оценки assistant-message.
	// Повторный вызов с другим rating'ом — переключает оценку.
	SubmitMessageFeedback(context.Context, *SubmitMessageFeedbackRequest) (*SubmitMessageFeedbackResponse, error)
	// DeleteMessageFeedback — снимает оценку (idempotent).
	DeleteMessageFeedback(context.Context, *DeleteMessageFeedbackRequest) (*DeleteMessageFeedbackResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) StartConversation(context.Context, *StartConversationRequest) (*StartConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartConversation not implemented")
}
func (UnimplementedAIServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedAIServiceServer) SendMessageStream(*SendMessageRequest, grpc.ServerStreamingServer[SendMessageStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method SendMessageStream not implemented")
}
func (UnimplementedAIServiceServer) ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedAIServiceServer) GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedAIServiceServer) DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedAIServiceServer) ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedAIServiceServer) ExplainMistake(context.Context, *ExplainMistakeRequest) (*ExplainMistakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainMistake not implemented")
}
func (UnimplementedAIServiceServer) ExplainMistakeStream(*ExplainMistakeRequest, grpc.ServerStreamingServer[ExplainMistakeStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method ExplainMistakeStream not implemented")
}
func (UnimplementedAIServiceServer) AssessWriting(context.Context, *AssessWritingRequest) (*AssessWritingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssessWriting not implemented")
}
func (UnimplementedAIServiceServer) AssessWritingStream(*AssessWritingRequest, grpc.ServerStreamingServer[AssessWritingStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method AssessWritingStream not implemented")
}
func (UnimplementedAIServiceServer) CheckPronunciation(context.Context, *CheckPronunciationRequest) (*CheckPronunciationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPronunciation not implemented")
}
func (UnimplementedAIServiceServer) AskTutor(context.Context, *AskTutorRequest) (*AskTutorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AskTutor not implemented")
}
func (UnimplementedAIServiceServer) AskTutorStream(*AskTutorRequest, grpc.ServerStreamingServer[AskTutorStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method AskTutorStream not implemented")
}
func (UnimplementedAIServiceServer) GenerateExercise(context.Context, *GenerateExerciseRequest) (*GenerateExerciseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateExercise not implemented")
}
func (UnimplementedAIServiceServer) GetQuotaStatus(context.Context, *GetQuotaStatusRequest) (*GetQuotaStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuotaStatus not implemented")
}
func (UnimplementedAIServiceServer) SubmitMessageFeedback(context.Context, *SubmitMessageFeedbackRequest) (*SubmitMessageFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMessageFeedback not implemented")
}
func (UnimplementedAIServiceServer) DeleteMessageFeedback(context.Context, *DeleteMessageFeedbackRequest) (*DeleteMessageFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessageFeedback not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_StartConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).StartConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_StartConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).StartConversation(ctx, req.(*StartConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_SendMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).SendMessageStream(m, &grpc.GenericServerStream[SendMessageRequest, SendMessageStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_SendMessageStreamServer = grpc.ServerStreamingServer[SendMessageStreamChunk]

func _AIService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ListConversations(ctx, req.(*ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DeleteConversation(ctx, req.(*DeleteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ListScenarios(ctx, req.(*ListScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ExplainMistake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainMistakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ExplainMistake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ExplainMistake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ExplainMistake(ctx, req.(*ExplainMistakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ExplainMistakeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExplainMistakeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).ExplainMistakeStream(m, &grpc.GenericServerStream[ExplainMistakeRequest, ExplainMistakeStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ExplainMistakeStreamServer = grpc.ServerStreamingServer[ExplainMistakeStreamChunk]

func _AIService_AssessWriting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessWritingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AssessWriting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AssessWriting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AssessWriting(ctx, req.(*AssessWritingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_AssessWritingStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AssessWritingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).AssessWritingStream(m, &grpc.GenericServerStream[AssessWritingRequest, AssessWritingStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_AssessWritingStreamServer = grpc.ServerStreamingServer[AssessWritingStreamChunk]

func _AIService_CheckPronunciation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPronunciationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).CheckPronunciation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_CheckPronunciation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).CheckPronunciation(ctx, req.(*CheckPronunciationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_AskTutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskTutorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AskTutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AskTutor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AskTutor(ctx, req.(*AskTutorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_AskTutorStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AskTutorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).AskTutorStream(m, &grpc.GenericServerStream[AskTutorRequest, AskTutorStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_AskTutorStreamServer = grpc.ServerStreamingServer[AskTutorStreamChunk]

func _AIService_GenerateExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateExercise(ctx, req.(*GenerateExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetQuotaStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuotaStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetQuotaStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetQuotaStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetQuotaStatus(ctx, req.(*GetQuotaStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_SubmitMessageFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMessageFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).SubmitMessageFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_SubmitMessageFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).SubmitMessageFeedback(ctx, req.(*SubmitMessageFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_DeleteMessageFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DeleteMessageFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DeleteMessageFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DeleteMessageFeedback(ctx, req.(*DeleteMessageFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartConversation",
			Handler:    _AIService_StartConversation_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _AIService_SendMessage_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _AIService_ListConversations_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _AIService_GetConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _AIService_DeleteConversation_Handler,
		},
		{
			MethodName: "ListScenarios",
			Handler:    _AIService_ListScenarios_Handler,
		},
		{
			MethodName: "ExplainMistake",
			Handler:    _AIService_ExplainMistake_Handler,
		},
		{
			MethodName: "AssessWriting",
			Handler:    _AIService_AssessWriting_Handler,
		},
		{
			MethodName: "CheckPronunciation",
			Handler:    _AIService_CheckPronunciation_Handler,
		},
		{
			MethodName: "AskTutor",
			Handler:    _AIService_AskTutor_Handler,
		},
		{
			MethodName: "GenerateExercise",
			Handler:    _AIService_GenerateExercise_Handler,
		},
		{
			MethodName: "GetQuotaStatus",
			Handler:    _AIService_GetQuotaStatus_Handler,
		},
		{
			MethodName: "SubmitMessageFeedback",
			Handler:    _AIService_SubmitMessageFeedback_Handler,
		},
		{
			MethodName: "DeleteMessageFeedback",
			Handler:    _AIService_DeleteMessageFeedback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessageStream",
			Handler:       _AIService_SendMessageStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExplainMistakeStream",
			Handler:       _AIService_ExplainMistakeStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AssessWritingStream",
			Handler:       _AIService_AssessWritingStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AskTutorStream",
			Handler:       _AIService_AskTutorStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai/v1/ai.proto",
}
