// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: video/v1/video.proto

package videov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetVideoURL - получение signed URL
type GetVideoURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoURLRequest) Reset() {
	*x = GetVideoURLRequest{}
	mi := &file_video_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoURLRequest) ProtoMessage() {}

func (x *GetVideoURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoURLRequest.ProtoReflect.Descriptor instead.
func (*GetVideoURLRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoURLRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetVideoURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetVideoURLResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SignedUrl        string                 `protobuf:"bytes,1,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	ExpiresInSeconds int32                  `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetVideoURLResponse) Reset() {
	*x = GetVideoURLResponse{}
	mi := &file_video_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoURLResponse) ProtoMessage() {}

func (x *GetVideoURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoURLResponse.ProtoReflect.Descriptor instead.
func (*GetVideoURLResponse) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *GetVideoURLResponse) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

func (x *GetVideoURLResponse) GetExpiresInSeconds() int32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// UploadVideo - загрузка видео
type UploadVideoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadVideoRequest_Metadata
	//	*UploadVideoRequest_Chunk
	Data          isUploadVideoRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_video_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *UploadVideoRequest) GetData() isUploadVideoRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadVideoRequest) GetMetadata() *VideoMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadVideoRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadVideoRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadVideoRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadVideoRequest_Data interface {
	isUploadVideoRequest_Data()
}

type UploadVideoRequest_Metadata struct {
	Metadata *VideoMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadVideoRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadVideoRequest_Metadata) isUploadVideoRequest_Data() {}

func (*UploadVideoRequest_Chunk) isUploadVideoRequest_Data() {}

type VideoMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ContentType     string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Resolution      string                 `protobuf:"bytes,6,opt,name=resolution,proto3" json:"resolution,omitempty"`
	UploadedBy      string                 `protobuf:"bytes,7,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoMetadata) Reset() {
	*x = VideoMetadata{}
	mi := &file_video_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadata) ProtoMessage() {}

func (x *VideoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadata.ProtoReflect.Descriptor instead.
func (*VideoMetadata) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *VideoMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *VideoMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *VideoMetadata) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *VideoMetadata) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *VideoMetadata) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_video_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *UploadVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UploadVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetVideoMetadata - получение метаданных
type GetVideoMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoMetadataRequest) Reset() {
	*x = GetVideoMetadataRequest{}
	mi := &file_video_v1_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoMetadataRequest) ProtoMessage() {}

func (x *GetVideoMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetVideoMetadataRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoMetadataRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetVideoMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *Video                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoMetadataResponse) Reset() {
	*x = GetVideoMetadataResponse{}
	mi := &file_video_v1_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoMetadataResponse) ProtoMessage() {}

func (x *GetVideoMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetVideoMetadataResponse) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoMetadataResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

// ListVideos - список видео
type ListVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // active, processing, deleted
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"` // Search by title or description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	mi := &file_video_v1_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{7}
}

func (x *ListVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVideosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVideosRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListVideosRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosResponse) Reset() {
	*x = ListVideosResponse{}
	mi := &file_video_v1_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosResponse) ProtoMessage() {}

func (x *ListVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosResponse.ProtoReflect.Descriptor instead.
func (*ListVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{8}
}

func (x *ListVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListVideosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// DeleteVideo - удаление видео
type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_video_v1_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type DeleteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResponse) Reset() {
	*x = DeleteVideoResponse{}
	mi := &file_video_v1_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResponse) ProtoMessage() {}

func (x *DeleteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Video - полная информация о видео
type Video struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StorageKey      string                 `protobuf:"bytes,4,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	BucketName      string                 `protobuf:"bytes,5,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	ContentType     string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,8,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Resolution      string                 `protobuf:"bytes,9,opt,name=resolution,proto3" json:"resolution,omitempty"`
	ThumbnailUrl    string                 `protobuf:"bytes,10,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Status          string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	UploadedBy      string                 `protobuf:"bytes,12,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_video_v1_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{11}
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *Video) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *Video) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Video) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Video) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Video) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *Video) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Video) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Video) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *Video) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Video) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_video_v1_video_proto protoreflect.FileDescriptor

const file_video_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x14video/v1/video.proto\x12\bvideo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x12GetVideoURLRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"b\n" +
	"\x13GetVideoURLResponse\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x01 \x01(\tR\tsignedUrl\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\x05R\x10expiresInSeconds\"k\n" +
	"\x12UploadVideoRequest\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x17.video.v1.VideoMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\xf5\x01\n" +
	"\rVideoMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x1e\n" +
	"\n" +
	"resolution\x18\x06 \x01(\tR\n" +
	"resolution\x12\x1f\n" +
	"\vuploaded_by\x18\a \x01(\tR\n" +
	"uploadedBy\"J\n" +
	"\x13UploadVideoResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x17GetVideoMetadataRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"A\n" +
	"\x18GetVideoMetadataResponse\x12%\n" +
	"\x05video\x18\x01 \x01(\v2\x0f.video.v1.VideoR\x05video\"t\n" +
	"\x11ListVideosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"S\n" +
	"\x12ListVideosResponse\x12'\n" +
	"\x06videos\x18\x01 \x03(\v2\x0f.video.v1.VideoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"/\n" +
	"\x12DeleteVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"I\n" +
	"\x13DeleteVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf2\x03\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vstorage_key\x18\x04 \x01(\tR\n" +
	"storageKey\x12\x1f\n" +
	"\vbucket_name\x18\x05 \x01(\tR\n" +
	"bucketName\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12)\n" +
	"\x10duration_seconds\x18\b \x01(\x05R\x0fdurationSeconds\x12\x1e\n" +
	"\n" +
	"resolution\x18\t \x01(\tR\n" +
	"resolution\x12#\n" +
	"\rthumbnail_url\x18\n" +
	" \x01(\tR\fthumbnailUrl\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1f\n" +
	"\vuploaded_by\x18\f \x01(\tR\n" +
	"uploadedBy\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x98\x03\n" +
	"\fVideoService\x12J\n" +
	"\vGetVideoURL\x12\x1c.video.v1.GetVideoURLRequest\x1a\x1d.video.v1.GetVideoURLResponse\x12L\n" +
	"\vUploadVideo\x12\x1c.video.v1.UploadVideoRequest\x1a\x1d.video.v1.UploadVideoResponse(\x01\x12Y\n" +
	"\x10GetVideoMetadata\x12!.video.v1.GetVideoMetadataRequest\x1a\".video.v1.GetVideoMetadataResponse\x12G\n" +
	"\n" +
	"ListVideos\x12\x1b.video.v1.ListVideosRequest\x1a\x1c.video.v1.ListVideosResponse\x12J\n" +
	"\vDeleteVideo\x12\x1c.video.v1.DeleteVideoRequest\x1a\x1d.video.v1.DeleteVideoResponseB\x93\x01\n" +
	"\fcom.video.v1B\n" +
	"VideoProtoP\x01Z6github.com/elearning/shared/pkg/proto/video/v1;videov1\xa2\x02\x03VXX\xaa\x02\bVideo.V1\xca\x02\bVideo\\V1\xe2\x02\x14Video\\V1\\GPBMetadata\xea\x02\tVideo::V1b\x06proto3"

var (
	file_video_v1_video_proto_rawDescOnce sync.Once
	file_video_v1_video_proto_rawDescData []byte
)

func file_video_v1_video_proto_rawDescGZIP() []byte {
	file_video_v1_video_proto_rawDescOnce.Do(func() {
		file_video_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_v1_video_proto_rawDesc), len(file_video_v1_video_proto_rawDesc)))
	})
	return file_video_v1_video_proto_rawDescData
}

var file_video_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_video_v1_video_proto_goTypes = []any{
	(*GetVideoURLRequest)(nil),       // 0: video.v1.GetVideoURLRequest
	(*GetVideoURLResponse)(nil),      // 1: video.v1.GetVideoURLResponse
	(*UploadVideoRequest)(nil),       // 2: video.v1.UploadVideoRequest
	(*VideoMetadata)(nil),            // 3: video.v1.VideoMetadata
	(*UploadVideoResponse)(nil),      // 4: video.v1.UploadVideoResponse
	(*GetVideoMetadataRequest)(nil),  // 5: video.v1.GetVideoMetadataRequest
	(*GetVideoMetadataResponse)(nil), // 6: video.v1.GetVideoMetadataResponse
	(*ListVideosRequest)(nil),        // 7: video.v1.ListVideosRequest
	(*ListVideosResponse)(nil),       // 8: video.v1.ListVideosResponse
	(*DeleteVideoRequest)(nil),       // 9: video.v1.DeleteVideoRequest
	(*DeleteVideoResponse)(nil),      // 10: video.v1.DeleteVideoResponse
	(*Video)(nil),                    // 11: video.v1.Video
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_video_v1_video_proto_depIdxs = []int32{
	3,  // 0: video.v1.UploadVideoRequest.metadata:type_name -> video.v1.VideoMetadata
	11, // 1: video.v1.GetVideoMetadataResponse.video:type_name -> video.v1.Video
	11, // 2: video.v1.ListVideosResponse.videos:type_name -> video.v1.Video
	12, // 3: video.v1.Video.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: video.v1.Video.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: video.v1.VideoService.GetVideoURL:input_type -> video.v1.GetVideoURLRequest
	2,  // 6: video.v1.VideoService.UploadVideo:input_type -> video.v1.UploadVideoRequest
	5,  // 7: video.v1.VideoService.GetVideoMetadata:input_type -> video.v1.GetVideoMetadataRequest
	7,  // 8: video.v1.VideoService.ListVideos:input_type -> video.v1.ListVideosRequest
	9,  // 9: video.v1.VideoService.DeleteVideo:input_type -> video.v1.DeleteVideoRequest
	1,  // 10: video.v1.VideoService.GetVideoURL:output_type -> video.v1.GetVideoURLResponse
	4,  // 11: video.v1.VideoService.UploadVideo:output_type -> video.v1.UploadVideoResponse
	6,  // 12: video.v1.VideoService.GetVideoMetadata:output_type -> video.v1.GetVideoMetadataResponse
	8,  // 13: video.v1.VideoService.ListVideos:output_type -> video.v1.ListVideosResponse
	10, // 14: video.v1.VideoService.DeleteVideo:output_type -> video.v1.DeleteVideoResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_video_v1_video_proto_init() }
func file_video_v1_video_proto_init() {
	if File_video_v1_video_proto != nil {
		return
	}
	file_video_v1_video_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadVideoRequest_Metadata)(nil),
		(*UploadVideoRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_v1_video_proto_rawDesc), len(file_video_v1_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_v1_video_proto_goTypes,
		DependencyIndexes: file_video_v1_video_proto_depIdxs,
		MessageInfos:      file_video_v1_video_proto_msgTypes,
	}.Build()
	File_video_v1_video_proto = out.File
	file_video_v1_video_proto_goTypes = nil
	file_video_v1_video_proto_depIdxs = nil
}
