// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gamification/v1/gamification.proto

package gamificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GamificationService_InitializeUser_FullMethodName      = "/gamification.v1.GamificationService/InitializeUser"
	GamificationService_GetUserStats_FullMethodName        = "/gamification.v1.GamificationService/GetUserStats"
	GamificationService_AddXP_FullMethodName               = "/gamification.v1.GamificationService/AddXP"
	GamificationService_GetXPHistory_FullMethodName        = "/gamification.v1.GamificationService/GetXPHistory"
	GamificationService_LoseHeart_FullMethodName           = "/gamification.v1.GamificationService/LoseHeart"
	GamificationService_RefillHearts_FullMethodName        = "/gamification.v1.GamificationService/RefillHearts"
	GamificationService_CheckHearts_FullMethodName         = "/gamification.v1.GamificationService/CheckHearts"
	GamificationService_GetDailyGoal_FullMethodName        = "/gamification.v1.GamificationService/GetDailyGoal"
	GamificationService_UpdateDailyGoal_FullMethodName     = "/gamification.v1.GamificationService/UpdateDailyGoal"
	GamificationService_UpdateStreak_FullMethodName        = "/gamification.v1.GamificationService/UpdateStreak"
	GamificationService_GetStreakHistory_FullMethodName    = "/gamification.v1.GamificationService/GetStreakHistory"
	GamificationService_UseStreakFreeze_FullMethodName     = "/gamification.v1.GamificationService/UseStreakFreeze"
	GamificationService_ListAchievements_FullMethodName    = "/gamification.v1.GamificationService/ListAchievements"
	GamificationService_GetUserAchievements_FullMethodName = "/gamification.v1.GamificationService/GetUserAchievements"
	GamificationService_CheckAchievements_FullMethodName   = "/gamification.v1.GamificationService/CheckAchievements"
	GamificationService_OnStepCompleted_FullMethodName     = "/gamification.v1.GamificationService/OnStepCompleted"
	GamificationService_OnLessonCompleted_FullMethodName   = "/gamification.v1.GamificationService/OnLessonCompleted"
	GamificationService_OnCourseCompleted_FullMethodName   = "/gamification.v1.GamificationService/OnCourseCompleted"
	GamificationService_OnQuizCompleted_FullMethodName     = "/gamification.v1.GamificationService/OnQuizCompleted"
)

// GamificationServiceClient is the client API for GamificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GamificationService отвечает за XP, hearts, streaks, daily goals и
// achievements. Сервис не привязан к контейнеру контента (course/track/
// standalone) — он реагирует на действия пользователя.
type GamificationServiceClient interface {
	// === Stats ===
	InitializeUser(ctx context.Context, in *InitializeUserRequest, opts ...grpc.CallOption) (*UserStats, error)
	GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*UserStats, error)
	// === XP ===
	AddXP(ctx context.Context, in *AddXPRequest, opts ...grpc.CallOption) (*AddXPResponse, error)
	GetXPHistory(ctx context.Context, in *GetXPHistoryRequest, opts ...grpc.CallOption) (*XPHistoryResponse, error)
	// === Hearts ===
	LoseHeart(ctx context.Context, in *LoseHeartRequest, opts ...grpc.CallOption) (*Hearts, error)
	RefillHearts(ctx context.Context, in *RefillHeartsRequest, opts ...grpc.CallOption) (*Hearts, error)
	CheckHearts(ctx context.Context, in *CheckHeartsRequest, opts ...grpc.CallOption) (*Hearts, error)
	// === Daily Goal ===
	GetDailyGoal(ctx context.Context, in *GetDailyGoalRequest, opts ...grpc.CallOption) (*DailyGoal, error)
	UpdateDailyGoal(ctx context.Context, in *UpdateDailyGoalRequest, opts ...grpc.CallOption) (*DailyGoal, error)
	// === Streak ===
	UpdateStreak(ctx context.Context, in *UpdateStreakRequest, opts ...grpc.CallOption) (*Streak, error)
	GetStreakHistory(ctx context.Context, in *GetStreakHistoryRequest, opts ...grpc.CallOption) (*StreakHistory, error)
	UseStreakFreeze(ctx context.Context, in *UseStreakFreezeRequest, opts ...grpc.CallOption) (*Streak, error)
	// === Achievements ===
	ListAchievements(ctx context.Context, in *ListAchievementsRequest, opts ...grpc.CallOption) (*AchievementsResponse, error)
	GetUserAchievements(ctx context.Context, in *GetUserAchievementsRequest, opts ...grpc.CallOption) (*UserAchievementsResponse, error)
	CheckAchievements(ctx context.Context, in *CheckAchievementsRequest, opts ...grpc.CallOption) (*UnlockedAchievementsResponse, error)
	// === Event hooks (вызываются из course-service / quiz-service) ===
	// OnStepCompleted — пользователь успешно завершил шаг.
	OnStepCompleted(ctx context.Context, in *OnStepCompletedRequest, opts ...grpc.CallOption) (*OnStepCompletedResponse, error)
	// OnLessonCompleted — пользователь завершил все шаги урока.
	OnLessonCompleted(ctx context.Context, in *OnLessonCompletedRequest, opts ...grpc.CallOption) (*OnLessonCompletedResponse, error)
	// OnCourseCompleted — все уроки курса пройдены. Используется для
	// achievement-триггеров `courses_completed` и `languages`.
	OnCourseCompleted(ctx context.Context, in *OnCourseCompletedRequest, opts ...grpc.CallOption) (*OnCourseCompletedResponse, error)
	// OnQuizCompleted — пользователь завершил попытку квиза. Используется для
	// achievement-триггеров `quiz_completed` и `perfect_quizzes`.
	OnQuizCompleted(ctx context.Context, in *OnQuizCompletedRequest, opts ...grpc.CallOption) (*OnQuizCompletedResponse, error)
}

type gamificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGamificationServiceClient(cc grpc.ClientConnInterface) GamificationServiceClient {
	return &gamificationServiceClient{cc}
}

func (c *gamificationServiceClient) InitializeUser(ctx context.Context, in *InitializeUserRequest, opts ...grpc.CallOption) (*UserStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserStats)
	err := c.cc.Invoke(ctx, GamificationService_InitializeUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*UserStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserStats)
	err := c.cc.Invoke(ctx, GamificationService_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) AddXP(ctx context.Context, in *AddXPRequest, opts ...grpc.CallOption) (*AddXPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddXPResponse)
	err := c.cc.Invoke(ctx, GamificationService_AddXP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) GetXPHistory(ctx context.Context, in *GetXPHistoryRequest, opts ...grpc.CallOption) (*XPHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XPHistoryResponse)
	err := c.cc.Invoke(ctx, GamificationService_GetXPHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) LoseHeart(ctx context.Context, in *LoseHeartRequest, opts ...grpc.CallOption) (*Hearts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hearts)
	err := c.cc.Invoke(ctx, GamificationService_LoseHeart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) RefillHearts(ctx context.Context, in *RefillHeartsRequest, opts ...grpc.CallOption) (*Hearts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hearts)
	err := c.cc.Invoke(ctx, GamificationService_RefillHearts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) CheckHearts(ctx context.Context, in *CheckHeartsRequest, opts ...grpc.CallOption) (*Hearts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hearts)
	err := c.cc.Invoke(ctx, GamificationService_CheckHearts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) GetDailyGoal(ctx context.Context, in *GetDailyGoalRequest, opts ...grpc.CallOption) (*DailyGoal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyGoal)
	err := c.cc.Invoke(ctx, GamificationService_GetDailyGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) UpdateDailyGoal(ctx context.Context, in *UpdateDailyGoalRequest, opts ...grpc.CallOption) (*DailyGoal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyGoal)
	err := c.cc.Invoke(ctx, GamificationService_UpdateDailyGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) UpdateStreak(ctx context.Context, in *UpdateStreakRequest, opts ...grpc.CallOption) (*Streak, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Streak)
	err := c.cc.Invoke(ctx, GamificationService_UpdateStreak_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) GetStreakHistory(ctx context.Context, in *GetStreakHistoryRequest, opts ...grpc.CallOption) (*StreakHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreakHistory)
	err := c.cc.Invoke(ctx, GamificationService_GetStreakHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) UseStreakFreeze(ctx context.Context, in *UseStreakFreezeRequest, opts ...grpc.CallOption) (*Streak, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Streak)
	err := c.cc.Invoke(ctx, GamificationService_UseStreakFreeze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) ListAchievements(ctx context.Context, in *ListAchievementsRequest, opts ...grpc.CallOption) (*AchievementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AchievementsResponse)
	err := c.cc.Invoke(ctx, GamificationService_ListAchievements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) GetUserAchievements(ctx context.Context, in *GetUserAchievementsRequest, opts ...grpc.CallOption) (*UserAchievementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAchievementsResponse)
	err := c.cc.Invoke(ctx, GamificationService_GetUserAchievements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) CheckAchievements(ctx context.Context, in *CheckAchievementsRequest, opts ...grpc.CallOption) (*UnlockedAchievementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockedAchievementsResponse)
	err := c.cc.Invoke(ctx, GamificationService_CheckAchievements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) OnStepCompleted(ctx context.Context, in *OnStepCompletedRequest, opts ...grpc.CallOption) (*OnStepCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnStepCompletedResponse)
	err := c.cc.Invoke(ctx, GamificationService_OnStepCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) OnLessonCompleted(ctx context.Context, in *OnLessonCompletedRequest, opts ...grpc.CallOption) (*OnLessonCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnLessonCompletedResponse)
	err := c.cc.Invoke(ctx, GamificationService_OnLessonCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) OnCourseCompleted(ctx context.Context, in *OnCourseCompletedRequest, opts ...grpc.CallOption) (*OnCourseCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnCourseCompletedResponse)
	err := c.cc.Invoke(ctx, GamificationService_OnCourseCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamificationServiceClient) OnQuizCompleted(ctx context.Context, in *OnQuizCompletedRequest, opts ...grpc.CallOption) (*OnQuizCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnQuizCompletedResponse)
	err := c.cc.Invoke(ctx, GamificationService_OnQuizCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GamificationServiceServer is the server API for GamificationService service.
// All implementations must embed UnimplementedGamificationServiceServer
// for forward compatibility.
//
// GamificationService отвечает за XP, hearts, streaks, daily goals и
// achievements. Сервис не привязан к контейнеру контента (course/track/
// standalone) — он реагирует на действия пользователя.
type GamificationServiceServer interface {
	// === Stats ===
	InitializeUser(context.Context, *InitializeUserRequest) (*UserStats, error)
	GetUserStats(context.Context, *GetUserStatsRequest) (*UserStats, error)
	// === XP ===
	AddXP(context.Context, *AddXPRequest) (*AddXPResponse, error)
	GetXPHistory(context.Context, *GetXPHistoryRequest) (*XPHistoryResponse, error)
	// === Hearts ===
	LoseHeart(context.Context, *LoseHeartRequest) (*Hearts, error)
	RefillHearts(context.Context, *RefillHeartsRequest) (*Hearts, error)
	CheckHearts(context.Context, *CheckHeartsRequest) (*Hearts, error)
	// === Daily Goal ===
	GetDailyGoal(context.Context, *GetDailyGoalRequest) (*DailyGoal, error)
	UpdateDailyGoal(context.Context, *UpdateDailyGoalRequest) (*DailyGoal, error)
	// === Streak ===
	UpdateStreak(context.Context, *UpdateStreakRequest) (*Streak, error)
	GetStreakHistory(context.Context, *GetStreakHistoryRequest) (*StreakHistory, error)
	UseStreakFreeze(context.Context, *UseStreakFreezeRequest) (*Streak, error)
	// === Achievements ===
	ListAchievements(context.Context, *ListAchievementsRequest) (*AchievementsResponse, error)
	GetUserAchievements(context.Context, *GetUserAchievementsRequest) (*UserAchievementsResponse, error)
	CheckAchievements(context.Context, *CheckAchievementsRequest) (*UnlockedAchievementsResponse, error)
	// === Event hooks (вызываются из course-service / quiz-service) ===
	// OnStepCompleted — пользователь успешно завершил шаг.
	OnStepCompleted(context.Context, *OnStepCompletedRequest) (*OnStepCompletedResponse, error)
	// OnLessonCompleted — пользователь завершил все шаги урока.
	OnLessonCompleted(context.Context, *OnLessonCompletedRequest) (*OnLessonCompletedResponse, error)
	// OnCourseCompleted — все уроки курса пройдены. Используется для
	// achievement-триггеров `courses_completed` и `languages`.
	OnCourseCompleted(context.Context, *OnCourseCompletedRequest) (*OnCourseCompletedResponse, error)
	// OnQuizCompleted — пользователь завершил попытку квиза. Используется для
	// achievement-триггеров `quiz_completed` и `perfect_quizzes`.
	OnQuizCompleted(context.Context, *OnQuizCompletedRequest) (*OnQuizCompletedResponse, error)
	mustEmbedUnimplementedGamificationServiceServer()
}

// UnimplementedGamificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGamificationServiceServer struct{}

func (UnimplementedGamificationServiceServer) InitializeUser(context.Context, *InitializeUserRequest) (*UserStats, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeUser not implemented")
}
func (UnimplementedGamificationServiceServer) GetUserStats(context.Context, *GetUserStatsRequest) (*UserStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedGamificationServiceServer) AddXP(context.Context, *AddXPRequest) (*AddXPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddXP not implemented")
}
func (UnimplementedGamificationServiceServer) GetXPHistory(context.Context, *GetXPHistoryRequest) (*XPHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetXPHistory not implemented")
}
func (UnimplementedGamificationServiceServer) LoseHeart(context.Context, *LoseHeartRequest) (*Hearts, error) {
	return nil, status.Error(codes.Unimplemented, "method LoseHeart not implemented")
}
func (UnimplementedGamificationServiceServer) RefillHearts(context.Context, *RefillHeartsRequest) (*Hearts, error) {
	return nil, status.Error(codes.Unimplemented, "method RefillHearts not implemented")
}
func (UnimplementedGamificationServiceServer) CheckHearts(context.Context, *CheckHeartsRequest) (*Hearts, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHearts not implemented")
}
func (UnimplementedGamificationServiceServer) GetDailyGoal(context.Context, *GetDailyGoalRequest) (*DailyGoal, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyGoal not implemented")
}
func (UnimplementedGamificationServiceServer) UpdateDailyGoal(context.Context, *UpdateDailyGoalRequest) (*DailyGoal, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDailyGoal not implemented")
}
func (UnimplementedGamificationServiceServer) UpdateStreak(context.Context, *UpdateStreakRequest) (*Streak, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStreak not implemented")
}
func (UnimplementedGamificationServiceServer) GetStreakHistory(context.Context, *GetStreakHistoryRequest) (*StreakHistory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreakHistory not implemented")
}
func (UnimplementedGamificationServiceServer) UseStreakFreeze(context.Context, *UseStreakFreezeRequest) (*Streak, error) {
	return nil, status.Error(codes.Unimplemented, "method UseStreakFreeze not implemented")
}
func (UnimplementedGamificationServiceServer) ListAchievements(context.Context, *ListAchievementsRequest) (*AchievementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAchievements not implemented")
}
func (UnimplementedGamificationServiceServer) GetUserAchievements(context.Context, *GetUserAchievementsRequest) (*UserAchievementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAchievements not implemented")
}
func (UnimplementedGamificationServiceServer) CheckAchievements(context.Context, *CheckAchievementsRequest) (*UnlockedAchievementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAchievements not implemented")
}
func (UnimplementedGamificationServiceServer) OnStepCompleted(context.Context, *OnStepCompletedRequest) (*OnStepCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnStepCompleted not implemented")
}
func (UnimplementedGamificationServiceServer) OnLessonCompleted(context.Context, *OnLessonCompletedRequest) (*OnLessonCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnLessonCompleted not implemented")
}
func (UnimplementedGamificationServiceServer) OnCourseCompleted(context.Context, *OnCourseCompletedRequest) (*OnCourseCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnCourseCompleted not implemented")
}
func (UnimplementedGamificationServiceServer) OnQuizCompleted(context.Context, *OnQuizCompletedRequest) (*OnQuizCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnQuizCompleted not implemented")
}
func (UnimplementedGamificationServiceServer) mustEmbedUnimplementedGamificationServiceServer() {}
func (UnimplementedGamificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeGamificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GamificationServiceServer will
// result in compilation errors.
type UnsafeGamificationServiceServer interface {
	mustEmbedUnimplementedGamificationServiceServer()
}

func RegisterGamificationServiceServer(s grpc.ServiceRegistrar, srv GamificationServiceServer) {
	// If the following call panics, it indicates UnimplementedGamificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GamificationService_ServiceDesc, srv)
}

func _GamificationService_InitializeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).InitializeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_InitializeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).InitializeUser(ctx, req.(*InitializeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).GetUserStats(ctx, req.(*GetUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_AddXP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddXPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).AddXP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_AddXP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).AddXP(ctx, req.(*AddXPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_GetXPHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetXPHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).GetXPHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_GetXPHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).GetXPHistory(ctx, req.(*GetXPHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_LoseHeart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoseHeartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).LoseHeart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_LoseHeart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).LoseHeart(ctx, req.(*LoseHeartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_RefillHearts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefillHeartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).RefillHearts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_RefillHearts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).RefillHearts(ctx, req.(*RefillHeartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_CheckHearts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHeartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).CheckHearts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_CheckHearts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).CheckHearts(ctx, req.(*CheckHeartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_GetDailyGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).GetDailyGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_GetDailyGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).GetDailyGoal(ctx, req.(*GetDailyGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_UpdateDailyGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDailyGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).UpdateDailyGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_UpdateDailyGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).UpdateDailyGoal(ctx, req.(*UpdateDailyGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_UpdateStreak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStreakRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).UpdateStreak(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_UpdateStreak_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).UpdateStreak(ctx, req.(*UpdateStreakRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_GetStreakHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreakHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).GetStreakHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_GetStreakHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).GetStreakHistory(ctx, req.(*GetStreakHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_UseStreakFreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseStreakFreezeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).UseStreakFreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_UseStreakFreeze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).UseStreakFreeze(ctx, req.(*UseStreakFreezeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_ListAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAchievementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).ListAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_ListAchievements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).ListAchievements(ctx, req.(*ListAchievementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_GetUserAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAchievementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).GetUserAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_GetUserAchievements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).GetUserAchievements(ctx, req.(*GetUserAchievementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_CheckAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAchievementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).CheckAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_CheckAchievements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).CheckAchievements(ctx, req.(*CheckAchievementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_OnStepCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnStepCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).OnStepCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_OnStepCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).OnStepCompleted(ctx, req.(*OnStepCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_OnLessonCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnLessonCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).OnLessonCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_OnLessonCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).OnLessonCompleted(ctx, req.(*OnLessonCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_OnCourseCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCourseCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).OnCourseCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_OnCourseCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).OnCourseCompleted(ctx, req.(*OnCourseCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GamificationService_OnQuizCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnQuizCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamificationServiceServer).OnQuizCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamificationService_OnQuizCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamificationServiceServer).OnQuizCompleted(ctx, req.(*OnQuizCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GamificationService_ServiceDesc is the grpc.ServiceDesc for GamificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GamificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gamification.v1.GamificationService",
	HandlerType: (*GamificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeUser",
			Handler:    _GamificationService_InitializeUser_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _GamificationService_GetUserStats_Handler,
		},
		{
			MethodName: "AddXP",
			Handler:    _GamificationService_AddXP_Handler,
		},
		{
			MethodName: "GetXPHistory",
			Handler:    _GamificationService_GetXPHistory_Handler,
		},
		{
			MethodName: "LoseHeart",
			Handler:    _GamificationService_LoseHeart_Handler,
		},
		{
			MethodName: "RefillHearts",
			Handler:    _GamificationService_RefillHearts_Handler,
		},
		{
			MethodName: "CheckHearts",
			Handler:    _GamificationService_CheckHearts_Handler,
		},
		{
			MethodName: "GetDailyGoal",
			Handler:    _GamificationService_GetDailyGoal_Handler,
		},
		{
			MethodName: "UpdateDailyGoal",
			Handler:    _GamificationService_UpdateDailyGoal_Handler,
		},
		{
			MethodName: "UpdateStreak",
			Handler:    _GamificationService_UpdateStreak_Handler,
		},
		{
			MethodName: "GetStreakHistory",
			Handler:    _GamificationService_GetStreakHistory_Handler,
		},
		{
			MethodName: "UseStreakFreeze",
			Handler:    _GamificationService_UseStreakFreeze_Handler,
		},
		{
			MethodName: "ListAchievements",
			Handler:    _GamificationService_ListAchievements_Handler,
		},
		{
			MethodName: "GetUserAchievements",
			Handler:    _GamificationService_GetUserAchievements_Handler,
		},
		{
			MethodName: "CheckAchievements",
			Handler:    _GamificationService_CheckAchievements_Handler,
		},
		{
			MethodName: "OnStepCompleted",
			Handler:    _GamificationService_OnStepCompleted_Handler,
		},
		{
			MethodName: "OnLessonCompleted",
			Handler:    _GamificationService_OnLessonCompleted_Handler,
		},
		{
			MethodName: "OnCourseCompleted",
			Handler:    _GamificationService_OnCourseCompleted_Handler,
		},
		{
			MethodName: "OnQuizCompleted",
			Handler:    _GamificationService_OnQuizCompleted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gamification/v1/gamification.proto",
}
