// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: step_validation/v1/step_validation.proto

package step_validationv1

import (
	v1 "github.com/elearning/shared/pkg/proto/gamification/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StepAttempt — запись о попытке прохождения шага.
type StepAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	LessonId      string                 `protobuf:"bytes,4,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	StepType      string                 `protobuf:"bytes,5,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"` // translate, match_pairs, ...
	Answer        *structpb.Struct       `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,7,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Score         float64                `protobuf:"fixed64,8,opt,name=score,proto3" json:"score,omitempty"` // 0.0–1.0
	TimeSpentMs   int32                  `protobuf:"varint,9,opt,name=time_spent_ms,json=timeSpentMs,proto3" json:"time_spent_ms,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepAttempt) Reset() {
	*x = StepAttempt{}
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepAttempt) ProtoMessage() {}

func (x *StepAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepAttempt.ProtoReflect.Descriptor instead.
func (*StepAttempt) Descriptor() ([]byte, []int) {
	return file_step_validation_v1_step_validation_proto_rawDescGZIP(), []int{0}
}

func (x *StepAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StepAttempt) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StepAttempt) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepAttempt) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *StepAttempt) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *StepAttempt) GetAnswer() *structpb.Struct {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *StepAttempt) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *StepAttempt) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StepAttempt) GetTimeSpentMs() int32 {
	if x != nil {
		return x.TimeSpentMs
	}
	return 0
}

func (x *StepAttempt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SubmitAnswerRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StepId string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Ответ пользователя — структура зависит от типа шага.
	// Описание схем — в docs/tasks/phase-2-step-formats.md.
	Answer      *structpb.Struct `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	TimeSpentMs int32            `protobuf:"varint,4,opt,name=time_spent_ms,json=timeSpentMs,proto3" json:"time_spent_ms,omitempty"`
	// Phase 0 поля для course-service.MarkStepComplete.
	SourceType    string `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // course | track | standalone
	SourceId      string `protobuf:"bytes,6,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`       // optional: course_id или track_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_step_validation_v1_step_validation_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetAnswer() *structpb.Struct {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *SubmitAnswerRequest) GetTimeSpentMs() int32 {
	if x != nil {
		return x.TimeSpentMs
	}
	return 0
}

func (x *SubmitAnswerRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *SubmitAnswerRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type SubmitAnswerResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	IsCorrect bool                   `protobuf:"varint,1,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Score     float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	// Канонический правильный ответ (показать пользователю при ошибке).
	// Структура зависит от типа шага.
	CorrectAnswer *structpb.Struct `protobuf:"bytes,3,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	Explanation   string           `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Attempt       *StepAttempt     `protobuf:"bytes,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Side-effects.
	// gamification = nil, если course-service шаг и xp/hearts уже
	// обновлены через legacy MarkStepComplete (не наш случай в Phase 2),
	// или если is_correct=false и LoseHeart не вернул AddXPResponse.
	Gamification *v1.AddXPResponse `protobuf:"bytes,6,opt,name=gamification,proto3,oneof" json:"gamification,omitempty"`
	// hearts — обновлённый Hearts-snapshot после LoseHeart (только при
	// is_correct=false). Полезно фронту для немедленного показа.
	Hearts        *v1.Hearts `protobuf:"bytes,7,opt,name=hearts,proto3,oneof" json:"hearts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_step_validation_v1_step_validation_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitAnswerResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *SubmitAnswerResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitAnswerResponse) GetCorrectAnswer() *structpb.Struct {
	if x != nil {
		return x.CorrectAnswer
	}
	return nil
}

func (x *SubmitAnswerResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *SubmitAnswerResponse) GetAttempt() *StepAttempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

func (x *SubmitAnswerResponse) GetGamification() *v1.AddXPResponse {
	if x != nil {
		return x.Gamification
	}
	return nil
}

func (x *SubmitAnswerResponse) GetHearts() *v1.Hearts {
	if x != nil {
		return x.Hearts
	}
	return nil
}

type ListAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttemptsRequest) Reset() {
	*x = ListAttemptsRequest{}
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttemptsRequest) ProtoMessage() {}

func (x *ListAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttemptsRequest.ProtoReflect.Descriptor instead.
func (*ListAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_step_validation_v1_step_validation_proto_rawDescGZIP(), []int{3}
}

func (x *ListAttemptsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAttemptsRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ListAttemptsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAttemptsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAttemptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      []*StepAttempt         `protobuf:"bytes,1,rep,name=attempts,proto3" json:"attempts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttemptsResponse) Reset() {
	*x = ListAttemptsResponse{}
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttemptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttemptsResponse) ProtoMessage() {}

func (x *ListAttemptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_step_validation_v1_step_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttemptsResponse.ProtoReflect.Descriptor instead.
func (*ListAttemptsResponse) Descriptor() ([]byte, []int) {
	return file_step_validation_v1_step_validation_proto_rawDescGZIP(), []int{4}
}

func (x *ListAttemptsResponse) GetAttempts() []*StepAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *ListAttemptsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_step_validation_v1_step_validation_proto protoreflect.FileDescriptor

const file_step_validation_v1_step_validation_proto_rawDesc = "" +
	"\n" +
	"(step_validation/v1/step_validation.proto\x12\x12step_validation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\"gamification/v1/gamification.proto\"\xce\x02\n" +
	"\vStepAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x1b\n" +
	"\tlesson_id\x18\x04 \x01(\tR\blessonId\x12\x1b\n" +
	"\tstep_type\x18\x05 \x01(\tR\bstepType\x12/\n" +
	"\x06answer\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06answer\x12\x1d\n" +
	"\n" +
	"is_correct\x18\a \x01(\bR\tisCorrect\x12\x14\n" +
	"\x05score\x18\b \x01(\x01R\x05score\x12\"\n" +
	"\rtime_spent_ms\x18\t \x01(\x05R\vtimeSpentMs\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xda\x01\n" +
	"\x13SubmitAnswerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12/\n" +
	"\x06answer\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06answer\x12\"\n" +
	"\rtime_spent_ms\x18\x04 \x01(\x05R\vtimeSpentMs\x12\x1f\n" +
	"\vsource_type\x18\x05 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x06 \x01(\tR\bsourceId\"\x83\x03\n" +
	"\x14SubmitAnswerResponse\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x01 \x01(\bR\tisCorrect\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12>\n" +
	"\x0ecorrect_answer\x18\x03 \x01(\v2\x17.google.protobuf.StructR\rcorrectAnswer\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x129\n" +
	"\aattempt\x18\x05 \x01(\v2\x1f.step_validation.v1.StepAttemptR\aattempt\x12G\n" +
	"\fgamification\x18\x06 \x01(\v2\x1e.gamification.v1.AddXPResponseH\x00R\fgamification\x88\x01\x01\x124\n" +
	"\x06hearts\x18\a \x01(\v2\x17.gamification.v1.HeartsH\x01R\x06hearts\x88\x01\x01B\x0f\n" +
	"\r_gamificationB\t\n" +
	"\a_hearts\"u\n" +
	"\x13ListAttemptsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"i\n" +
	"\x14ListAttemptsResponse\x12;\n" +
	"\battempts\x18\x01 \x03(\v2\x1f.step_validation.v1.StepAttemptR\battempts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xdd\x01\n" +
	"\x15StepValidationService\x12a\n" +
	"\fSubmitAnswer\x12'.step_validation.v1.SubmitAnswerRequest\x1a(.step_validation.v1.SubmitAnswerResponse\x12a\n" +
	"\fListAttempts\x12'.step_validation.v1.ListAttemptsRequest\x1a(.step_validation.v1.ListAttemptsResponseB\xde\x01\n" +
	"\x16com.step_validation.v1B\x13StepValidationProtoP\x01ZJgithub.com/elearning/shared/pkg/proto/step_validation/v1;step_validationv1\xa2\x02\x03SXX\xaa\x02\x11StepValidation.V1\xca\x02\x11StepValidation\\V1\xe2\x02\x1dStepValidation\\V1\\GPBMetadata\xea\x02\x12StepValidation::V1b\x06proto3"

var (
	file_step_validation_v1_step_validation_proto_rawDescOnce sync.Once
	file_step_validation_v1_step_validation_proto_rawDescData []byte
)

func file_step_validation_v1_step_validation_proto_rawDescGZIP() []byte {
	file_step_validation_v1_step_validation_proto_rawDescOnce.Do(func() {
		file_step_validation_v1_step_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_step_validation_v1_step_validation_proto_rawDesc), len(file_step_validation_v1_step_validation_proto_rawDesc)))
	})
	return file_step_validation_v1_step_validation_proto_rawDescData
}

var file_step_validation_v1_step_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_step_validation_v1_step_validation_proto_goTypes = []any{
	(*StepAttempt)(nil),           // 0: step_validation.v1.StepAttempt
	(*SubmitAnswerRequest)(nil),   // 1: step_validation.v1.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil),  // 2: step_validation.v1.SubmitAnswerResponse
	(*ListAttemptsRequest)(nil),   // 3: step_validation.v1.ListAttemptsRequest
	(*ListAttemptsResponse)(nil),  // 4: step_validation.v1.ListAttemptsResponse
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*v1.AddXPResponse)(nil),      // 7: gamification.v1.AddXPResponse
	(*v1.Hearts)(nil),             // 8: gamification.v1.Hearts
}
var file_step_validation_v1_step_validation_proto_depIdxs = []int32{
	5,  // 0: step_validation.v1.StepAttempt.answer:type_name -> google.protobuf.Struct
	6,  // 1: step_validation.v1.StepAttempt.created_at:type_name -> google.protobuf.Timestamp
	5,  // 2: step_validation.v1.SubmitAnswerRequest.answer:type_name -> google.protobuf.Struct
	5,  // 3: step_validation.v1.SubmitAnswerResponse.correct_answer:type_name -> google.protobuf.Struct
	0,  // 4: step_validation.v1.SubmitAnswerResponse.attempt:type_name -> step_validation.v1.StepAttempt
	7,  // 5: step_validation.v1.SubmitAnswerResponse.gamification:type_name -> gamification.v1.AddXPResponse
	8,  // 6: step_validation.v1.SubmitAnswerResponse.hearts:type_name -> gamification.v1.Hearts
	0,  // 7: step_validation.v1.ListAttemptsResponse.attempts:type_name -> step_validation.v1.StepAttempt
	1,  // 8: step_validation.v1.StepValidationService.SubmitAnswer:input_type -> step_validation.v1.SubmitAnswerRequest
	3,  // 9: step_validation.v1.StepValidationService.ListAttempts:input_type -> step_validation.v1.ListAttemptsRequest
	2,  // 10: step_validation.v1.StepValidationService.SubmitAnswer:output_type -> step_validation.v1.SubmitAnswerResponse
	4,  // 11: step_validation.v1.StepValidationService.ListAttempts:output_type -> step_validation.v1.ListAttemptsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_step_validation_v1_step_validation_proto_init() }
func file_step_validation_v1_step_validation_proto_init() {
	if File_step_validation_v1_step_validation_proto != nil {
		return
	}
	file_step_validation_v1_step_validation_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_step_validation_v1_step_validation_proto_rawDesc), len(file_step_validation_v1_step_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_step_validation_v1_step_validation_proto_goTypes,
		DependencyIndexes: file_step_validation_v1_step_validation_proto_depIdxs,
		MessageInfos:      file_step_validation_v1_step_validation_proto_msgTypes,
	}.Build()
	File_step_validation_v1_step_validation_proto = out.File
	file_step_validation_v1_step_validation_proto_goTypes = nil
	file_step_validation_v1_step_validation_proto_depIdxs = nil
}
