# A1 classic content, part 1: Greetings, Family, Food, Numbers.

from gen_a1_classic_topics_helpers import dlg, narr, choice

TOPICS_PART1 = [
# ============ T01 GREETINGS ============
{
 "code": "A1_T01_GREETINGS",
 "title": {"ru": "Приветствия", "en": "Greetings"},
 "desc": {"ru": "Первые слова: поздороваться, спросить дела, познакомиться и попрощаться.",
          "en": "Your first words: greet, ask how things are, meet people and say goodbye."},
 "lessons": [
 {  "title_ru": "Здравствуйте!", "title_en": "Hello!",
    "obj_ru": "Выучить базовые приветствия и прощания.",
    "obj_en": "Learn basic greetings and goodbyes.",
    "vocab": [("hello", "здравствуйте"), ("hi", "привет"), ("goodbye", "до свидания"),
              ("bye", "пока"), ("good morning", "доброе утро"), ("good night", "доброй ночи"),
              ("see you", "до встречи")],
    "quiz": ("Как сказать «до свидания»?", "Goodbye",
             ["Hello", "Good morning", "Good night"],
             "Goodbye — «до свидания», так прощаются."),
    "translate": ("Доброе утро!", "Good morning!", ["evening", "night"]),
    "fill": ("Good ___!", "morning", ["night", "bye"], "Доброе утро!"),
    "tap": ("Good night!", ["morning", "see"]),
    "listening": "Hello! Goodbye!",
    "shadowing": ("Good morning!", "Доброе утро!"),
    "story": ("First Day", [
        dlg("Anna", "Hello!", "Привет!"),
        dlg("Tom", "Hi! Good morning!", "Привет! Доброе утро!"),
        choice("Анна уходит. Что сказать Тому?",
               [("Goodbye!", True), ("Good morning!", False), ("Good night!", False)])]),
    "definition": ("hello", "слово для приветствия",
                   ["слово для прощания", "время суток", "число"],
                   "hello — «здравствуйте», слово-приветствие."),
    "listen_choose": ("Good ___!", "Good morning!", "morning", ["night", "bye"],
                      "morning — «утро»."),
    "missing": ("Good ___!", "morning", "mo", "morning — утро."),
    "voice": ["hello", "hi", "morning", "night", "goodbye"],
    "chat": ([("Anna", "Hello! I am Anna.")], "You",
             "Hi, Anna!", ["Goodbye, Anna!", "Good night, Anna!"],
             "На приветствие отвечают приветствием: Hi, Anna!"),
 },
 {  "title_ru": "Как дела?", "title_en": "How are you?",
    "obj_ru": "Спрашивать и отвечать о делах, благодарить.",
    "obj_en": "Ask and answer how things are, say thanks.",
    "vocab": [("how", "как"), ("fine", "отлично"), ("thanks", "спасибо"),
              ("please", "пожалуйста"), ("welcome", "добро пожаловать"),
              ("OK", "в порядке"), ("and you", "а у тебя")],
    "quiz": ("Как спросить «Как дела?»", "How are you?",
             ["What is your name?", "How old are you?", "Where are you from?"],
             "How are you? — «Как дела?»"),
    "translate": ("Спасибо, у меня всё отлично!", "Thanks, I am fine!", ["you", "how"]),
    "fill": ("I am ___, thanks.", "fine", ["how", "please"], "Я в порядке, спасибо."),
    "tap": ("How are you?", ["is", "what"]),
    "listening": "I am fine, thanks!",
    "shadowing": ("How are you?", "Как дела?"),
    "story": ("Small Talk", [
        dlg("Anna", "Hi, Tom! How are you?", "Привет, Том! Как дела?"),
        dlg("Tom", "I am fine, thanks. And you?", "Отлично, спасибо. А у тебя?"),
        choice("Что ответить Анне?",
               [("I am fine too!", True), ("Good night!", False), ("You are welcome!", False)])]),
    "definition": ("thanks", "слово благодарности",
                   ["вопрос о делах", "приветствие", "прощание"],
                   "thanks — «спасибо»."),
    "listen_choose": ("I am ___, thanks.", "I am fine, thanks.", "fine", ["how", "please"],
                      "fine — «отлично, в порядке»."),
    "missing": ("___ are you?", "How", "ho", "How are you? — Как дела?"),
    "voice": ["how", "fine", "thanks", "please", "welcome"],
    "chat": ([("Anna", "How are you?")], "You",
             "I am fine, thanks!", ["My name is Anna.", "Good morning!"],
             "На вопрос о делах отвечаем: I am fine, thanks!"),
 },
 {  "title_ru": "Как тебя зовут?", "title_en": "What Is Your Name?",
    "obj_ru": "Знакомиться: спрашивать и называть имя.",
    "obj_en": "Meet people: ask and give your name.",
    "vocab": [("name", "имя"), ("my", "мой"), ("your", "твой"),
              ("who", "кто"), ("nice", "приятно"), ("meet", "знакомиться"),
              ("friend", "друг")],
    "quiz": ("Как спросить имя?", "What is your name?",
             ["How are you?", "Where do you live?", "How old are you?"],
             "What is your name? — «Как тебя зовут?»"),
    "translate": ("Меня зовут Анна.", "My name is Anna.", ["her", "who"]),
    "fill": ("My ___ is Tom.", "name", ["friend", "fine"], "Моё имя — Том."),
    "tap": ("Nice to meet you!", ["see", "good"]),
    "listening": "What is your name?",
    "shadowing": ("My name is Anna.", "Меня зовут Анна."),
    "story": ("New Friend", [
        dlg("Anna", "Hello! What is your name?", "Привет! Как тебя зовут?"),
        dlg("Tom", "My name is Tom. Nice to meet you!", "Меня зовут Том. Приятно познакомиться!"),
        choice("Что ответить Тому?",
               [("Nice to meet you too!", True), ("Good night!", False), ("I am fine!", False)])]),
    "definition": ("friend", "человек, с которым дружат",
                   ["член семьи", "город", "еда"],
                   "friend — «друг»."),
    "listen_choose": ("My ___ is Anna.", "My name is Anna.", "name", ["friend", "fine"],
                      "name — «имя»."),
    "missing": ("Nice to ___ you!", "meet", "me", "Nice to meet you! — Приятно познакомиться!"),
    "voice": ["name", "my", "your", "nice", "meet"],
    "chat": ([("Tom", "What is your name?")], "You",
             "My name is Anna.", ["I am fine!", "Goodbye!"],
             "На вопрос об имени отвечаем: My name is …"),
 },
],
},
# ============ T02 FAMILY ============
{
 "code": "A1_T02_FAMILY",
 "title": {"ru": "Семья", "en": "Family"},
 "desc": {"ru": "Члены семьи, родственники и разговоры о семье.",
          "en": "Family members, relatives and talking about your family."},
 "lessons": [
 {  "title_ru": "Моя семья", "title_en": "My Family",
    "obj_ru": "Назвать членов семьи.",
    "obj_en": "Name your family members.",
    "vocab": [("mother", "мама"), ("father", "папа"), ("sister", "сестра"),
              ("brother", "брат"), ("son", "сын"), ("daughter", "дочь"),
              ("family", "семья")],
    "quiz": ("Кто такая daughter?", "дочь",
             ["сын", "сестра", "мама"], "daughter — «дочь»."),
    "translate": ("Это моя мама.", "This is my mother.", ["your", "father"]),
    "fill": ("I have one ___ and one sister.", "brother", ["mother", "family"],
             "У меня есть брат и сестра."),
    "tap": ("This is my family.", ["are", "the"]),
    "listening": "I have a brother and a sister.",
    "shadowing": ("This is my mother.", "Это моя мама."),
    "story": ("Family Photo", [
        narr("Tom shows a photo.", "Том показывает фото."),
        dlg("Anna", "Who is this?", "Кто это?"),
        dlg("Tom", "This is my sister. Her name is Kate.", "Это моя сестра. Её зовут Кейт."),
        choice("Кто Кейт для Тома?",
               [("His sister", True), ("His mother", False), ("His daughter", False)])]),
    "definition": ("family", "родители и дети вместе",
                   ["школа", "город", "работа"], "family — «семья»."),
    "listen_choose": ("My father and my ___ are my parents.",
                      "My father and my mother are my parents.",
                      "mother", ["daughter", "sister"], "mother — «мама»."),
    "missing": ("My mother's son is my ___.", "brother", "br", "brother — брат."),
    "voice": ["mother", "father", "sister", "brother", "family"],
    "chat": ([("Anna", "Is Kate your sister?")], "You",
             "Yes, she is my sister.", ["Yes, she is my mother.", "No, he is my brother."],
             "Кейт — она (she), поэтому отвечаем про сестру."),
 },
 {  "title_ru": "Родственники", "title_en": "Relatives",
    "obj_ru": "Назвать родственников: бабушка, дедушка, тётя, дядя.",
    "obj_en": "Name relatives: grandmother, grandfather, aunt, uncle.",
    "vocab": [("grandmother", "бабушка"), ("grandfather", "дедушка"), ("aunt", "тётя"),
              ("uncle", "дядя"), ("cousin", "двоюродный брат"), ("parents", "родители"),
              ("wife", "жена")],
    "quiz": ("Кто такой grandfather?", "дедушка",
             ["дядя", "отец", "сын"], "grandfather — «дедушка»."),
    "translate": ("Мои родители живут в Лондоне.", "My parents live in London.",
                  ["his", "lives"]),
    "fill": ("My father's mother is my ___.", "grandmother", ["aunt", "wife"],
             "Бабушка — мама папы."),
    "tap": ("My grandmother is old.", ["young", "are"]),
    "listening": "My aunt and my uncle live near us.",
    "shadowing": ("I love my grandmother.", "Я люблю свою бабушку."),
    "story": ("Visit to Grandparents", [
        narr("Anna visits her grandparents.", "Анна навещает бабушку и дедушку."),
        dlg("Grandmother", "Hello, Anna! How are you?", "Привет, Анна! Как дела?"),
        dlg("Anna", "I am fine, thanks! And you?", "Отлично, спасибо! А у вас?"),
        choice("Кого навещает Анна?",
               [("Her grandmother and grandfather", True), ("Her aunt and uncle", False),
                ("Her parents", False)])]),
    "definition": ("parents", "мама и папа",
                   ["бабушка и дедушка", "брат и сестра", "тётя и дядя"],
                   "parents — «родители»."),
    "listen_choose": ("My mother's brother is my ___.", "My mother's brother is my uncle.",
                      "uncle", ["cousin", "father"], "uncle — «дядя»."),
    "missing": ("My mother's sister is my ___.", "aunt", "au", "aunt — тётя."),
    "voice": ["grandmother", "grandfather", "aunt", "uncle", "cousin"],
    "chat": ([("Tom", "This is my uncle John.")], "You",
             "Nice to meet you!", ["I am fine!", "Good night!"],
             "При знакомстве говорят: Nice to meet you!"),
 },
 {  "title_ru": "Семейная жизнь", "title_en": "Family Life",
    "obj_ru": "Рассказать о семье простыми фразами.",
    "obj_en": "Talk about your family with simple phrases.",
    "vocab": [("love", "любить"), ("live", "жить"), ("together", "вместе"),
              ("married", "женаты"), ("child", "ребёнок"), ("old", "старый"),
              ("young", "молодой")],
    "quiz": ("Как сказать «Мы живём вместе»?", "We live together",
             ["We love together", "We live married", "We are together old"],
             "live — «жить», together — «вместе»."),
    "translate": ("Я люблю свою семью.", "I love my family.", ["live", "likes"]),
    "fill": ("My grandfather is ___.", "old", ["young", "together"], "Мой дедушка старый."),
    "tap": ("We live together.", ["love", "are"]),
    "listening": "They are married and live together.",
    "shadowing": ("I love my family.", "Я люблю свою семью."),
    "story": ("A Big Family", [
        narr("Tom's family is big.", "Семья Тома большая."),
        dlg("Anna", "Do you have brothers or sisters?", "У тебя есть братья или сёстры?"),
        dlg("Tom", "Yes, I have two sisters and one brother.", "Да, у меня две сестры и один брат."),
        choice("Сколько сестёр у Тома?",
               [("Two", True), ("One", False), ("Three", False)])]),
    "definition": ("together", "вместе, не поодиночке",
                   ["по одному", "быстро", "далеко"], "together — «вместе»."),
    "listen_choose": ("We ___ together.", "We live together.", "live", ["love", "old"],
                      "live — «жить» (love — любить: похожие слова!)."),
    "missing": ("My parents are ___.", "married", "ma", "married — женаты/замужем."),
    "voice": ["love", "live", "together", "young", "old"],
    "chat": ([("Anna", "Do you live with your parents?")], "You",
             "Yes, we live together.", ["We love together.", "We are old."],
             "Отвечаем: Yes, we live together."),
 },
],
},
# ============ T03 FOOD ============
{
 "code": "A1_T03_FOOD",
 "title": {"ru": "Еда и напитки", "en": "Food and Drinks"},
 "desc": {"ru": "Еда, напитки, приёмы пищи и заказ в кафе.",
          "en": "Food, drinks, meals and ordering at a cafe."},
 "lessons": [
 {  "title_ru": "Еда", "title_en": "Food",
    "obj_ru": "Назвать базовые продукты.",
    "obj_en": "Name basic foods.",
    "vocab": [("bread", "хлеб"), ("milk", "молоко"), ("water", "вода"),
              ("apple", "яблоко"), ("cheese", "сыр"), ("egg", "яйцо"),
              ("rice", "рис")],
    "quiz": ("Что такое water?", "вода",
             ["хлеб", "молоко", "сок"], "water — «вода»."),
    "translate": ("Я хочу воды.", "I want water.", ["milk", "bread"]),
    "fill": ("I eat ___ for breakfast.", "bread", ["water", "milk"],
             "Я ем хлеб на завтрак."),
    "tap": ("I like cheese.", ["eat", "my"]),
    "listening": "I drink water.",
    "shadowing": ("I want bread and cheese.", "Я хочу хлеба и сыра."),
    "story": ("Breakfast", [
        narr("It is morning. Tom is hungry.", "Утро. Том голоден."),
        dlg("Anna", "What do you want for breakfast?", "Что ты хочешь на завтрак?"),
        dlg("Tom", "I want bread and cheese, please.", "Я хочу хлеба и сыра, пожалуйста."),
        choice("Что Том хочет на завтрак?",
               [("Bread and cheese", True), ("Milk and rice", False),
                ("Water and an egg", False)])]),
    "definition": ("apple", "фрукт — красный или зелёный",
                   ["овощ", "напиток", "мясо"], "apple — «яблоко»."),
    "listen_choose": ("I drink ___.", "I drink milk.", "milk", ["bread", "cheese"],
                      "milk пьют — drink milk."),
    "missing": ("I eat an ___.", "apple", "ap", "an apple — яблоко."),
    "voice": ["bread", "milk", "water", "apple", "cheese"],
    "chat": ([("Anna", "Do you want water or milk?")], "You",
             "Water, please.", ["Bread, please.", "I eat water."],
             "Выбираем напиток: Water, please."),
 },
 {  "title_ru": "Приёмы пищи", "title_en": "Meals",
    "obj_ru": "Назвать приёмы пищи и напитки.",
    "obj_en": "Name meals and drinks.",
    "vocab": [("breakfast", "завтрак"), ("lunch", "обед"), ("dinner", "ужин"),
              ("tea", "чай"), ("coffee", "кофе"), ("juice", "сок"),
              ("hungry", "голодный")],
    "quiz": ("Какой приём пищи вечером?", "dinner",
             ["breakfast", "lunch", "tea"], "dinner — «ужин»."),
    "translate": ("На завтрак я пью кофе.", "For breakfast I drink coffee.",
                  ["tea", "drinks"]),
    "fill": ("I am ___! Let's eat.", "hungry", ["dinner", "juice"], "Я голоден!"),
    "tap": ("I drink tea in the morning.", ["eat", "coffee"]),
    "listening": "I have lunch with my sister.",
    "shadowing": ("I am hungry!", "Я голоден!"),
    "story": ("At Lunch", [
        narr("It is lunch time.", "Время обеда."),
        dlg("Anna", "Are you hungry?", "Ты голодна?"),
        dlg("Tom", "Yes! I want rice and juice.", "Да! Я хочу рис и сок."),
        choice("Что Том хочет?",
               [("Rice and juice", True), ("Tea and coffee", False),
                ("Bread and water", False)])]),
    "definition": ("hungry", "хочет есть",
                   ["хочет пить", "устал", "сытый"], "hungry — «голодный»."),
    "listen_choose": ("I am ___. I want food.", "I am hungry.", "hungry",
                      ["lunch", "dinner"], "hungry — «голодный»."),
    "missing": ("___ is the first meal of the day.", "Breakfast", "br",
                "breakfast — завтрак, первый приём пищи."),
    "voice": ["breakfast", "lunch", "dinner", "tea", "coffee"],
    "chat": ([("Anna", "Are you hungry?")], "You",
             "Yes, I am hungry!", ["Yes, I am lunch!", "No, I am dinner."],
             "hungry — прилагательное: I am hungry."),
 },
 {  "title_ru": "В кафе", "title_en": "At the Cafe",
    "obj_ru": "Заказать напиток и попросить счёт.",
    "obj_en": "Order a drink and ask for the bill.",
    "vocab": [("menu", "меню"), ("order", "заказ"), ("bill", "счёт"),
              ("delicious", "вкусный"), ("thirsty", "хочет пить"),
              ("waiter", "официант"), ("sugar", "сахар")],
    "quiz": ("Кто приносит меню в кафе?", "waiter",
             ["bill", "sugar", "menu"], "waiter — «официант»."),
    "translate": ("Можно счёт, пожалуйста?", "The bill, please.", ["menu", "delicious"]),
    "fill": ("This tea is ___!", "delicious", ["hungry", "order"], "Этот чай вкусный!"),
    "tap": ("I want coffee with sugar.", ["tea", "eat"]),
    "listening": "Can I have the menu, please?",
    "shadowing": ("The bill, please.", "Счёт, пожалуйста."),
    "story": ("In a Cafe", [
        narr("Anna and Tom are in a cafe.", "Анна и Том в кафе."),
        dlg("Waiter", "Hello! Do you want tea or coffee?", "Здравствуйте! Чай или кофе?"),
        dlg("Anna", "Tea with sugar, please.", "Чай с сахаром, пожалуйста."),
        choice("Что заказала Анна?",
               [("Tea with sugar", True), ("Coffee with milk", False),
                ("Bread with cheese", False)])]),
    "definition": ("bill", "бумажка с суммой за еду",
                   ["список блюд", "напиток", "официант"], "bill — «счёт» для оплаты."),
    "listen_choose": ("I want ___ in my tea.", "I want sugar in my tea.", "sugar",
                      ["bill", "menu"], "sugar — «сахар», его кладут в чай."),
    "missing": ("The ___ brings the menu.", "waiter", "wa", "waiter — официант."),
    "voice": ["menu", "order", "bill", "delicious", "sugar"],
    "chat": ([("Waiter", "Do you want coffee or tea?")], "You",
             "Coffee, please.", ["Hungry, please.", "Bill, please."],
             "Напиток заказывают так: Coffee, please."),
 },
],
},
# ============ T04 NUMBERS ============
{
 "code": "A1_T04_NUMBERS",
 "title": {"ru": "Числа", "en": "Numbers"},
 "desc": {"ru": "Счёт от нуля до двенадцати, «сколько?», первый и второй.",
          "en": "Count from zero to twelve, ask \"how many?\", first and second."},
 "lessons": [
 {  "title_ru": "От одного до семи", "title_en": "One to Seven",
    "obj_ru": "Считать от одного до семи.",
    "obj_en": "Count from one to seven.",
    "vocab": [("one", "один"), ("two", "два"), ("three", "три"),
              ("four", "четыре"), ("five", "пять"), ("six", "шесть"),
              ("seven", "семь")],
    "quiz": ("Сколько будет three + two?", "five",
             ["four", "six", "seven"], "3 + 2 = 5 (five)."),
    "translate": ("У меня два брата.", "I have two brothers.", ["three", "one"]),
    "fill": ("One, two, ___, four.", "three", ["five", "seven"], "Раз, два, три, четыре."),
    "tap": ("I have three apples.", ["two", "eat"]),
    "listening": "Five, six, seven.",
    "shadowing": ("One, two, three!", "Раз, два, три!"),
    "story": ("Counting Apples", [
        narr("Anna has apples.", "У Анны есть яблоки."),
        dlg("Tom", "How many apples do you have?", "Сколько у тебя яблок?"),
        dlg("Anna", "I have five apples!", "У меня пять яблок!"),
        choice("Сколько яблок у Анны?",
               [("Five", True), ("Four", False), ("Seven", False)])]),
    "definition": ("seven", "число после шести",
                   ["число после четырёх", "число перед пятью", "число один"],
                   "seven — «семь», идёт после six."),
    "listen_choose": ("___, two, three.", "One, two, three.", "one", ["five", "six"],
                      "Порядок: one, two, three."),
    "missing": ("Two and two is ___.", "four", "fo", "2 + 2 = 4 (four)."),
    "voice": ["one", "two", "three", "four", "five"],
    "chat": ([("Tom", "How many sisters do you have?")], "You",
             "I have one sister.", ["I have sister five.", "I am one sister."],
             "Отвечаем с числом: I have one sister."),
 },
 {  "title_ru": "От восьми до двенадцати", "title_en": "Eight to Twelve",
    "obj_ru": "Считать от восьми до двенадцати, узнать возраст.",
    "obj_en": "Count from eight to twelve, talk about age.",
    "vocab": [("eight", "восемь"), ("nine", "девять"), ("ten", "десять"),
              ("eleven", "одиннадцать"), ("twelve", "двенадцать"), ("zero", "ноль"),
              ("number", "число")],
    "quiz": ("Какое число идёт после ten?", "eleven",
             ["nine", "twelve", "zero"], "После 10 идёт 11 (eleven)."),
    "translate": ("Мне девять лет.", "I am nine.", ["ten", "eight"]),
    "fill": ("Nine, ten, ___, twelve.", "eleven", ["eight", "zero"], "9, 10, 11, 12."),
    "tap": ("I am eleven years old.", ["ten", "nine"]),
    "listening": "Eight, nine, ten.",
    "shadowing": ("Ten, eleven, twelve.", "Десять, одиннадцать, двенадцать."),
    "story": ("Age", [
        dlg("Anna", "How old are you, Tom?", "Сколько тебе лет, Том?"),
        dlg("Tom", "I am eleven. And you?", "Мне одиннадцать. А тебе?"),
        dlg("Anna", "I am twelve!", "Мне двенадцать!"),
        choice("Сколько лет Анне?",
               [("Twelve", True), ("Eleven", False), ("Ten", False)])]),
    "definition": ("zero", "число «ничего»",
                   ["число после девяти", "число перед двумя", "десять"],
                   "zero — «ноль»."),
    "listen_choose": ("___ is after eleven.", "Twelve is after eleven.", "twelve",
                      ["ten", "zero"], "twelve — «двенадцать», после eleven."),
    "missing": ("___, nine, ten.", "eight", "ei", "eight — восемь."),
    "voice": ["eight", "nine", "ten", "eleven", "twelve"],
    "chat": ([("Anna", "How old are you?")], "You",
             "I am ten years old.", ["I have ten years.", "I am years ten."],
             "Возраст: I am + число (+ years old)."),
 },
 {  "title_ru": "Сколько?", "title_en": "How Many?",
    "obj_ru": "Спрашивать количество, сравнивать: больше, меньше, половина.",
    "obj_en": "Ask about quantity, compare: more, less, half.",
    "vocab": [("how many", "сколько"), ("count", "считать"), ("more", "больше"),
              ("less", "меньше"), ("first", "первый"), ("second", "второй"),
              ("half", "половина")],
    "quiz": ("Как спросить количество?", "How many?",
             ["How old are you?", "How are you?", "What is your name?"],
             "How many? — «сколько?» про количество."),
    "translate": ("У меня больше яблок.", "I have more apples.", ["less", "many"]),
    "fill": ("Cut the apple in ___.", "half", ["first", "more"], "Разрежь яблоко пополам."),
    "tap": ("How many eggs do you have?", ["much", "is"]),
    "listening": "I have more bread.",
    "shadowing": ("How many apples do you have?", "Сколько у тебя яблок?"),
    "story": ("Counting Books", [
        narr("Tom counts his books.", "Том считает свои книги."),
        dlg("Anna", "How many books do you have?", "Сколько у тебя книг?"),
        dlg("Tom", "I have twelve books!", "У меня двенадцать книг!"),
        choice("Что делает Том?",
               [("He counts his books", True), ("He eats his books", False),
                ("He reads the menu", False)])]),
    "definition": ("half", "одна из двух равных частей",
                   ["две части", "первая часть", "все части"], "half — «половина»."),
    "listen_choose": ("___ brothers do you have?", "How many brothers do you have?",
                      "how many", ["how old", "how are"],
                      "how many — «сколько» про количество."),
    "missing": ("One, two, three — I can ___!", "count", "co", "count — считать."),
    "voice": ["count", "more", "less", "first", "second"],
    "chat": ([("Anna", "How many books do you have?")], "You",
             "I have twelve books.", ["I am twelve books.", "I have count books."],
             "Отвечаем количеством: I have twelve books."),
 },
],
},
]
