# A1 classic content, part 2: Colors, Home, Daily Routine.

from gen_a1_classic_topics_helpers import dlg, narr, choice

TOPICS_PART2 = [
# ============ T05 COLORS ============
{
 "code": "A1_T05_COLORS",
 "title": {"ru": "Цвета", "en": "Colors"},
 "desc": {"ru": "Основные цвета и описание предметов: большой, новый, красивый.",
          "en": "Basic colors and describing things: big, new, beautiful."},
 "lessons": [
 {  "title_ru": "Основные цвета", "title_en": "Basic Colors",
    "obj_ru": "Назвать основные цвета.",
    "obj_en": "Name the basic colors.",
    "vocab": [("red", "красный"), ("blue", "синий"), ("green", "зелёный"),
              ("yellow", "жёлтый"), ("black", "чёрный"), ("white", "белый"),
              ("color", "цвет")],
    "quiz": ("Какого цвета банан?", "yellow",
             ["red", "black", "white"], "Банан жёлтый — yellow."),
    "translate": ("У меня зелёное яблоко.", "I have a green apple.", ["red", "blue"]),
    "fill": ("The sky is ___.", "blue", ["yellow", "black"], "Небо синее."),
    "tap": ("I like the red apple.", ["green", "eat"]),
    "listening": "Black and white.",
    "shadowing": ("What is your favorite color?", "Какой твой любимый цвет?"),
    "story": ("Colors Around", [
        narr("Anna looks around.", "Анна смотрит вокруг."),
        dlg("Tom", "What color is the apple?", "Какого цвета яблоко?"),
        dlg("Anna", "It is red!", "Оно красное!"),
        choice("Какого цвета яблоко?",
               [("Red", True), ("Blue", False), ("Black", False)])]),
    "definition": ("color", "то, что видим: красный, синий…",
                   ["число", "еда", "имя"], "color — «цвет»."),
    "listen_choose": ("The sun is ___.", "The sun is yellow.", "yellow",
                      ["green", "white"], "Солнце жёлтое — yellow."),
    "missing": ("The apple is ___.", "red", "re", "red — красный."),
    "voice": ["red", "blue", "green", "yellow", "black"],
    "chat": ([("Tom", "What color do you like?")], "You",
             "I like green.", ["I am green.", "I eat green."],
             "like + цвет: I like green."),
 },
 {  "title_ru": "Ещё цвета", "title_en": "More Colors",
    "obj_ru": "Назвать дополнительные цвета, светлый и тёмный.",
    "obj_en": "Name more colors, light and dark.",
    "vocab": [("orange", "оранжевый"), ("pink", "розовый"), ("purple", "фиолетовый"),
              ("brown", "коричневый"), ("grey", "серый"), ("light", "светлый"),
              ("dark", "тёмный")],
    "quiz": ("Какого цвета солнце и апельсин?", "orange",
             ["pink", "grey", "brown"], "orange — «оранжевый»."),
    "translate": ("Кот серый.", "The cat is grey.", ["dark", "brown"]),
    "fill": ("The night is ___, the day is light.", "dark", ["pink", "purple"],
             "Ночь тёмная, день светлый."),
    "tap": ("I have a brown cat.", ["dog", "black"]),
    "listening": "The brown cat is small.",
    "shadowing": ("I like purple.", "Мне нравится фиолетовый."),
    "story": ("New Paint", [
        narr("Tom paints a picture.", "Том рисует картину."),
        dlg("Anna", "What colors do you have?", "Какие цвета у тебя есть?"),
        dlg("Tom", "Red, blue, orange and brown!", "Красный, синий, оранжевый и коричневый!"),
        choice("Какого цвета НЕТ у Тома?",
               [("Purple", True), ("Red", False), ("Brown", False)])]),
    "definition": ("grey", "цвет туч и мышей",
                   ["цвет неба летом", "цвет банана", "цвет травы"],
                   "grey — «серый»."),
    "listen_choose": ("My ___ cat is big.", "My grey cat is big.", "grey",
                      ["light", "pink"], "grey — «серый»."),
    "missing": ("An orange is ___.", "orange", "or",
                "orange — оранжевый (и фрукт, и цвет)."),
    "voice": ["orange", "pink", "purple", "brown", "grey"],
    "chat": ([("Anna", "Do you like pink?")], "You",
             "No, I like blue.", ["No, I am blue.", "Yes, I eat pink."],
             "Отвечаем о вкусе: I like blue."),
 },
 {  "title_ru": "Описываем предметы", "title_en": "Describing Things",
    "obj_ru": "Описать предметы: большой, маленький, новый, любимый.",
    "obj_en": "Describe things: big, small, new, favorite.",
    "vocab": [("big", "большой"), ("small", "маленький"), ("new", "новый"),
              ("old", "старый"), ("beautiful", "красивый"), ("bright", "яркий"),
              ("favorite", "любимый")],
    "quiz": ("Антоним к small?", "big",
             ["new", "bright", "favorite"], "big — «большой», антоним small."),
    "translate": ("Какой красивый цвет!", "What a beautiful color!", ["big", "new"]),
    "fill": ("My ___ color is blue.", "favorite", ["old", "small"],
             "Мой любимый цвет — синий."),
    "tap": ("I have a small green apple.", ["big", "red"]),
    "listening": "My cat is small and black.",
    "shadowing": ("It is my favorite color!", "Это мой любимый цвет!"),
    "story": ("Two Cats", [
        narr("Anna has two cats.", "У Анны два кота."),
        dlg("Tom", "Tell me about your cats!", "Расскажи о своих котах!"),
        dlg("Anna", "One is big and brown, one is small and black.",
            "Один большой и коричневый, другой маленький и чёрный."),
        choice("Какой кот чёрный?",
               [("The small cat", True), ("The big cat", False), ("The brown cat", False)])]),
    "definition": ("bright", "очень светлый, много света",
                   ["очень тёмный", "очень старый", "очень маленький"],
                   "bright — «яркий»."),
    "listen_choose": ("My ___ car is red.", "My new car is red.", "new",
                      ["old", "small"], "new — «новый»."),
    "missing": ("The sun is ___ and yellow.", "bright", "br", "bright — яркий."),
    "voice": ["big", "small", "new", "old", "beautiful"],
    "chat": ([("Tom", "What is your favorite color?")], "You",
             "My favorite color is green.", ["I favorite green.", "Green favorite my is."],
             "Порядок слов: My favorite color is …"),
 },
],
},
# ============ T06 HOME ============
{
 "code": "A1_T06_HOME",
 "title": {"ru": "Дом", "en": "Home"},
 "desc": {"ru": "Комнаты, мебель и дела по дому.",
          "en": "Rooms, furniture and things you do at home."},
 "lessons": [
 {  "title_ru": "Комнаты", "title_en": "Rooms",
    "obj_ru": "Назвать комнаты в доме.",
    "obj_en": "Name the rooms in a house.",
    "vocab": [("house", "дом"), ("room", "комната"), ("kitchen", "кухня"),
              ("bathroom", "ванная"), ("bedroom", "спальня"), ("garden", "сад"),
              ("door", "дверь")],
    "quiz": ("Где готовят еду?", "in the kitchen",
             ["in the bedroom", "in the bathroom", "in the garden"],
             "kitchen — «кухня»."),
    "translate": ("Мой дом большой.", "My house is big.", ["small", "are"]),
    "fill": ("I sleep in my ___.", "bedroom", ["kitchen", "garden"],
             "Я сплю в спальне."),
    "tap": ("The kitchen is small.", ["house", "big"]),
    "listening": "My house has five rooms.",
    "shadowing": ("Welcome to my house!", "Добро пожаловать в мой дом!"),
    "story": ("New House", [
        narr("Tom has a new house.", "У Тома новый дом."),
        dlg("Anna", "How many rooms are in your house?", "Сколько комнат в твоём доме?"),
        dlg("Tom", "Five rooms and a small garden!", "Пять комнат и маленький сад!"),
        choice("Что есть у дома Тома?",
               [("A garden", True), ("A pool", False), ("Ten rooms", False)])]),
    "definition": ("garden", "место с растениями у дома",
                   ["место для сна", "место для машины", "место для еды"],
                   "garden — «сад»."),
    "listen_choose": ("I cook in the ___.", "I cook in the kitchen.", "kitchen",
                      ["bathroom", "door"], "Готовят на кухне — kitchen."),
    "missing": ("Open the ___, please!", "door", "do", "door — дверь."),
    "voice": ["house", "room", "kitchen", "bathroom", "garden"],
    "chat": ([("Anna", "Do you have a garden?")], "You",
             "Yes, I have a small garden.", ["Yes, I am a garden.", "I am garden small."],
             "have + существительное: I have a small garden."),
 },
 {  "title_ru": "Мебель", "title_en": "Furniture",
    "obj_ru": "Назвать мебель.",
    "obj_en": "Name the furniture.",
    "vocab": [("table", "стол"), ("chair", "стул"), ("bed", "кровать"),
              ("sofa", "диван"), ("window", "окно"), ("lamp", "лампа"),
              ("mirror", "зеркало")],
    "quiz": ("На чём спят?", "a bed",
             ["a table", "a chair", "a mirror"], "bed — «кровать»."),
    "translate": ("Кот на диване.", "The cat is on the sofa.", ["table", "in"]),
    "fill": ("I sit on a ___.", "chair", ["bed", "lamp"], "Я сижу на стуле."),
    "tap": ("The lamp is near the window.", ["door", "table"]),
    "listening": "My bed is near the window.",
    "shadowing": ("The book is on the table.", "Книга на столе."),
    "story": ("Where Is the Cat?", [
        narr("Anna looks for her cat.", "Анна ищет своего кота."),
        dlg("Anna", "Tom! Where is my cat?", "Том! Где мой кот?"),
        dlg("Tom", "It is on your bed!", "Он на твоей кровати!"),
        choice("Где кот?",
               [("On the bed", True), ("On the table", False), ("In the garden", False)])]),
    "definition": ("mirror", "видишь в нём себя",
                   ["на нём спят", "на нём сидят", "через него смотрят на улицу"],
                   "mirror — «зеркало»."),
    "listen_choose": ("The ___ is on the table.", "The lamp is on the table.", "lamp",
                      ["sofa", "chair"], "Лампа маленькая — она стоит на столе."),
    "missing": ("I look at my face in the ___.", "mirror", "mi", "mirror — зеркало."),
    "voice": ["table", "chair", "bed", "window", "mirror"],
    "chat": ([("Anna", "Where is the lamp?")], "You",
             "It is on the table.", ["It is a lamp.", "I am on the table."],
             "Отвечаем местом: It is on the table."),
 },
 {  "title_ru": "Дома", "title_en": "At Home",
    "obj_ru": "Рассказать, что вы делаете дома.",
    "obj_en": "Say what you do at home.",
    "vocab": [("cook", "готовить"), ("clean", "убирать"), ("rest", "отдыхать"),
              ("sleep", "спать"), ("watch", "смотреть"), ("quiet", "тихий"),
              ("cozy", "уютный")],
    "quiz": ("Что делают с едой на кухне?", "cook",
             ["clean", "watch", "rest"], "cook — «готовить»."),
    "translate": ("Я смотрю телевизор вечером.", "I watch TV in the evening.",
                  ["cook", "morning"]),
    "fill": ("I ___ my room on Sunday.", "clean", ["cook", "watch"],
             "Я убираю комнату в воскресенье."),
    "tap": ("I sleep in my cozy bed.", ["eat", "kitchen"]),
    "listening": "I cook dinner and watch TV.",
    "shadowing": ("My home is quiet and cozy.", "Мой дом тихий и уютный."),
    "story": ("Sunday at Home", [
        narr("It is Sunday. Tom is at home.", "Воскресенье. Том дома."),
        dlg("Anna", "What do you do at home?", "Что ты делаешь дома?"),
        dlg("Tom", "I cook, clean and rest!", "Я готовлю, убираю и отдыхаю!"),
        choice("Что делает Том дома?",
               [("He cooks and rests", True), ("He sleeps all day", False),
                ("He is not at home", False)])]),
    "definition": ("cozy", "тёплый и удобный",
                   ["громкий и большой", "холодный и тёмный", "новый и быстрый"],
                   "cozy — «уютный»."),
    "listen_choose": ("I ___ TV in the evening.", "I watch TV in the evening.",
                      "watch", ["cook", "sleep"], "watch TV — смотреть телевизор."),
    "missing": ("Be ___! The baby sleeps.", "quiet", "qu", "quiet — тихий."),
    "voice": ["cook", "clean", "rest", "watch", "quiet"],
    "chat": ([("Anna", "What do you do in the evening?")], "You",
             "I watch TV and rest.", ["I sleep TV.", "I am watch evening."],
             "Глаголы подряд: watch TV and rest."),
 },
],
},
# ============ T07 DAILY ROUTINE ============
{
 "code": "A1_T07_ROUTINE",
 "title": {"ru": "Мой день", "en": "My Day"},
 "desc": {"ru": "Утро, день и вечер: распорядок дня простыми фразами.",
          "en": "Morning, day and evening: your daily routine in simple phrases."},
 "lessons": [
 {  "title_ru": "Утро", "title_en": "Morning",
    "obj_ru": "Рассказать о утренних делах.",
    "obj_en": "Talk about your morning.",
    "vocab": [("morning", "утро"), ("wake up", "просыпаться"), ("get up", "вставать"),
              ("wash", "умываться"), ("dress", "одеваться"), ("early", "рано"),
              ("alarm", "будильник")],
    "quiz": ("Что звенит утром?", "the alarm",
             ["the bed", "the evening", "the breakfast"], "alarm — «будильник»."),
    "translate": ("Я встаю рано.", "I get up early.", ["morning", "night"]),
    "fill": ("I ___ at seven in the morning.", "wake up", ["wash", "dress"],
             "Я просыпаюсь в семь утра."),
    "tap": ("I wash and dress.", ["eat", "sleep"]),
    "listening": "My alarm rings early!",
    "shadowing": ("I wake up early.", "Я просыпаюсь рано."),
    "story": ("Tom's Morning", [
        narr("The alarm rings.", "Будильник звенит."),
        narr("Tom wakes up and gets up.", "Том просыпается и встаёт."),
        dlg("Tom", "Good morning! I wash, dress and eat breakfast!",
            "Доброе утро! Я умываюсь, одеваюсь и завтракаю!"),
        choice("Что делает Том после будильника?",
               [("He gets up", True), ("He sleeps", False), ("He cooks dinner", False)])]),
    "definition": ("early", "до обычного времени, не поздно",
                   ["после обычного времени", "ночью", "вечером"],
                   "early — «рано»."),
    "listen_choose": ("I ___ with cold water.", "I wash with cold water.", "wash",
                      ["dress", "get up"], "wash — «умываться»."),
    "missing": ("My ___ rings at six!", "alarm", "al", "alarm — будильник."),
    "voice": ["morning", "early", "wash", "dress", "alarm"],
    "chat": ([("Anna", "Do you wake up early?")], "You",
             "Yes, I wake up at six.", ["Yes, I early wake.", "I am early."],
             "Порядок: wake up early / at six."),
 },
 {  "title_ru": "День и работа", "title_en": "Day and Work",
    "obj_ru": "Рассказать о занятиях днём.",
    "obj_en": "Talk about your day activities.",
    "vocab": [("day", "день"), ("work", "работать"), ("study", "учиться"),
              ("busy", "занятый"), ("tired", "уставший"), ("meeting", "встреча"),
              ("break", "перерыв")],
    "quiz": ("Как сказать «я работаю»?", "I work",
             ["I busy", "I meeting", "I tired"], "work — «работать» (глагол)."),
    "translate": ("Я занят весь день.", "I am busy all day.", ["tired", "work"]),
    "fill": ("I am ___: I work and study!", "busy", ["tired", "break"],
             "Я занят: работаю и учусь!"),
    "tap": ("I work in the day.", ["night", "am"]),
    "listening": "I have a short break at work.",
    "shadowing": ("I am busy all day.", "Я занят весь день."),
    "story": ("Busy Day", [
        narr("Tom has a busy day.", "У Тома насыщенный день."),
        dlg("Anna", "Are you tired?", "Ты устал?"),
        dlg("Tom", "Yes! I work, study and have three meetings!",
            "Да! Я работаю, учусь и у меня три встречи!"),
        choice("Почему Том устал?",
               [("He is busy", True), ("He is hungry", False), ("He is early", False)])]),
    "definition": ("break", "короткий отдых от работы",
                   ["долгий сон", "новая работа", "встреча"],
                   "break — «перерыв»."),
    "listen_choose": ("I am ___ after work.", "I am tired after work.", "tired",
                      ["busy", "study"], "tired — «уставший»."),
    "missing": ("Let's take a ___!", "break", "br", "take a break — взять перерыв."),
    "voice": ["work", "study", "busy", "tired", "meeting"],
    "chat": ([("Anna", "Are you busy today?")], "You",
             "Yes, I have a meeting.", ["Yes, I am meeting have.", "I busy am."],
             "have + a meeting: у меня встреча."),
 },
 {  "title_ru": "Вечер", "title_en": "Evening",
    "obj_ru": "Рассказать о вечере и отходе ко сну.",
    "obj_en": "Talk about your evening and bedtime.",
    "vocab": [("evening", "вечер"), ("night", "ночь"), ("come home", "приходить домой"),
              ("relax", "расслабляться"), ("go to bed", "ложиться спать"),
              ("usually", "обычно"), ("late", "поздно")],
    "quiz": ("Когда ложатся спать — утром или …?", "at night",
             ["in the kitchen", "at work", "early morning"],
             "go to bed at night — ложатся спать ночью."),
    "translate": ("Обычно я прихожу домой поздно.", "Usually I come home late.",
                  ["early", "night"]),
    "fill": ("I go to ___ at ten.", "bed", ["home", "work"], "Я ложусь спать в десять."),
    "tap": ("In the evening I relax.", ["morning", "cook"]),
    "listening": "I usually come home at six.",
    "shadowing": ("Good night! I go to bed.", "Доброй ночи! Я ложусь спать."),
    "story": ("Evening Routine", [
        narr("It is evening. Anna comes home.", "Вечер. Анна приходит домой."),
        narr("She cooks dinner and relaxes.", "Она готовит ужин и отдыхает."),
        dlg("Anna", "Usually I go to bed late, but not today!",
            "Обычно я ложусь поздно, но не сегодня!"),
        choice("Что делает Анна вечером?",
               [("She relaxes", True), ("She works", False), ("She wakes up", False)])]),
    "definition": ("usually", "большую часть времени, как всегда",
                   ["один раз", "никогда", "сегодня"], "usually — «обычно»."),
    "listen_choose": ("I ___ late on Saturday.", "I come home late on Saturday.",
                      "come home", ["go to bed", "relax"],
                      "come home — «приходить домой»."),
    "missing": ("I ___ watch TV in the evening.", "usually", "us",
                "usually — «обычно», стоит перед глаголом."),
    "voice": ["evening", "night", "usually", "late", "relax"],
    "chat": ([("Tom", "When do you go to bed?")], "You",
             "I usually go to bed at eleven.", ["I go usually bed at eleven.",
                                                "I bed at eleven usually go."],
             "usually стоит перед go."),
 },
],
},
]
