# A1 classic content, part 3: City, Shopping, Time.

from gen_a1_classic_topics_helpers import dlg, narr, choice

TOPICS_PART3 = [
# ============ T08 CITY ============
{
 "code": "A1_T08_CITY",
 "title": {"ru": "Город", "en": "City"},
 "desc": {"ru": "Места в городе, направления и транспорт.",
          "en": "Places in the city, directions and transport."},
 "lessons": [
 {  "title_ru": "Места", "title_en": "Places",
    "obj_ru": "Назвать места в городе.",
    "obj_en": "Name places in the city.",
    "vocab": [("city", "город"), ("street", "улица"), ("shop", "магазин"),
              ("school", "школа"), ("park", "парк"), ("hospital", "больница"),
              ("cafe", "кафе")],
    "quiz": ("Куда идут учиться дети?", "to school",
             ["to the hospital", "to the park", "to the shop"],
             "school — «школа»."),
    "translate": ("Парк рядом с моим домом.", "The park is near my house.",
                  ["far", "street"]),
    "fill": ("I buy bread in the ___.", "shop", ["school", "park"],
             "Я покупаю хлеб в магазине."),
    "tap": ("My school is on this street.", ["city", "house"]),
    "listening": "The hospital is a big building.",
    "shadowing": ("I walk in the park.", "Я гуляю в парке."),
    "story": ("In the City", [
        narr("Anna walks in the city.", "Анна гуляет по городу."),
        dlg("Tom", "What is in your city?", "Что есть в твоём городе?"),
        dlg("Anna", "A big park, two schools and many shops!",
            "Большой парк, две школы и много магазинов!"),
        choice("Что есть в городе Анны?",
               [("A park and shops", True), ("A hospital and cafes", False),
                ("A garden and rooms", False)])]),
    "definition": ("hospital", "место, где лечат людей",
                   ["место, где учатся", "место, где покупают еду", "место, где гуляют"],
                   "hospital — «больница»."),
    "listen_choose": ("The ___ is near my house.", "The cafe is near my house.",
                      "cafe", ["school", "city"], "cafe — «кафе»."),
    "missing": ("Children learn at ___.", "school", "sc", "school — школа."),
    "voice": ["city", "street", "shop", "school", "park"],
    "chat": ([("Anna", "Is there a cafe near here?")], "You",
             "Yes, the cafe is on Green Street.", ["Yes, I am a cafe.",
                                                   "The street is a cafe."],
             "Отвечаем, где: on Green Street."),
 },
 {  "title_ru": "Направления", "title_en": "Directions",
    "obj_ru": "Понимать указания: налево, направо, прямо.",
    "obj_en": "Understand directions: left, right, straight.",
    "vocab": [("left", "налево"), ("right", "направо"), ("straight", "прямо"),
              ("near", "рядом"), ("far", "далеко"), ("corner", "угол"),
              ("map", "карта")],
    "quiz": ("Противоположность right (направо)?", "left",
             ["straight", "near", "corner"], "left — «налево»."),
    "translate": ("Иди прямо и потом налево.", "Go straight and then left.",
                  ["right", "far"]),
    "fill": ("The shop is ___: I walk two minutes!", "near", ["far", "straight"],
             "Магазин рядом: иду две минуты!"),
    "tap": ("Turn right at the corner.", ["map", "street"]),
    "listening": "The park is far from my house.",
    "shadowing": ("Go straight, then turn left.", "Идите прямо, потом налево."),
    "story": ("Looking for the Cafe", [
        narr("Tom looks for a cafe.", "Том ищет кафе."),
        dlg("Tom", "Excuse me! Where is the cafe?", "Извините! Где кафе?"),
        dlg("Woman", "Go straight and turn left at the corner.",
            "Идите прямо и поверните налево на углу."),
        choice("Куда повернуть Тому?",
               [("Left at the corner", True), ("Right at the park", False),
                ("Straight to the hospital", False)])]),
    "definition": ("map", "показывает улицы и дороги",
                   ["показывает еду", "показывает время", "лечит людей"],
                   "map — «карта»."),
    "listen_choose": ("Turn ___ at the corner.", "Turn right at the corner.",
                      "right", ["near", "map"], "turn right — повернуть направо."),
    "missing": ("My house is ___: ten minutes by bus.", "far", "fa", "far — далеко."),
    "voice": ["left", "right", "straight", "near", "far"],
    "chat": ([("Tom", "Where is the park?")], "You",
             "Go straight, then turn right.", ["The park goes straight.",
                                                "Right is the park turn."],
             "Даём направление: Go straight, then turn right."),
 },
 {  "title_ru": "Транспорт", "title_en": "Transport",
    "obj_ru": "Назвать транспорт и рассказать, как вы ездите.",
    "obj_en": "Name transport and say how you travel.",
    "vocab": [("bus", "автобус"), ("car", "машина"), ("train", "поезд"),
              ("taxi", "такси"), ("walk", "идти пешком"), ("stop", "остановка"),
              ("station", "станция")],
    "quiz": ("На чём ездят по рельсам?", "a train",
             ["a taxi", "a bus", "a car"], "train — «поезд»."),
    "translate": ("Я еду на автобусе.", "I go by bus.", ["car", "train"]),
    "fill": ("The bus ___ is near the shop.", "stop", ["station", "walk"],
             "Остановка автобуса рядом с магазином."),
    "tap": ("I walk to school.", ["bus", "drive"]),
    "listening": "The train comes at eight.",
    "shadowing": ("I go by taxi.", "Я еду на такси."),
    "story": ("To the Station", [
        narr("Anna goes to the station.", "Анна едет на станцию."),
        dlg("Tom", "Do you go by bus?", "Ты едешь на автобусе?"),
        dlg("Anna", "No, I walk. The station is near!", "Нет, я иду пешком. Станция рядом!"),
        choice("Как Анна добирается?",
               [("She walks", True), ("By bus", False), ("By taxi", False)])]),
    "definition": ("walk", "идти пешком",
                   ["ехать на машине", "летать", "спать"], "walk — «идти пешком»."),
    "listen_choose": ("I go to work by ___.", "I go to work by car.", "car",
                      ["stop", "station"], "by car — «на машине»."),
    "missing": ("We wait for the bus at the ___.", "stop", "st",
                "bus stop — автобусная остановка."),
    "voice": ["bus", "car", "train", "taxi", "walk"],
    "chat": ([("Anna", "How do you go to school?")], "You",
             "I go by bus.", ["I bus go.", "I am by bus school."],
             "by + транспорт: I go by bus."),
 },
],
},
# ============ T09 SHOPPING ============
{
 "code": "A1_T09_SHOPPING",
 "title": {"ru": "Покупки", "en": "Shopping"},
 "desc": {"ru": "Магазины, одежда, цены и оплата.",
          "en": "Shops, clothes, prices and paying."},
 "lessons": [
 {  "title_ru": "В магазине", "title_en": "In the Shop",
    "obj_ru": "Говорить о покупках и ценах.",
    "obj_en": "Talk about shopping and prices.",
    "vocab": [("buy", "покупать"), ("sell", "продавать"), ("price", "цена"),
              ("money", "деньги"), ("cheap", "дешёвый"), ("expensive", "дорогой"),
              ("market", "рынок")],
    "quiz": ("Антоним к expensive?", "cheap",
             ["market", "money", "price"], "cheap — «дешёвый», антоним expensive."),
    "translate": ("У меня нет денег.", "I have no money.", ["price", "buy"]),
    "fill": ("What is the ___ of this bread?", "price", ["market", "money"],
             "Какова цена этого хлеба?"),
    "tap": ("I buy bread at the market.", ["sell", "shop"]),
    "listening": "This apple is cheap!",
    "shadowing": ("I want to buy cheese.", "Я хочу купить сыр."),
    "story": ("At the Market", [
        narr("Anna is at the market.", "Анна на рынке."),
        dlg("Seller", "Apples! Cheap apples!", "Яблоки! Дешёвые яблоки!"),
        dlg("Anna", "I buy five apples, please!", "Пять яблок, пожалуйста!"),
        choice("Что делает Анна?",
               [("She buys apples", True), ("She sells apples", False),
                ("She eats money", False)])]),
    "definition": ("market", "место, где продают еду и вещи",
                   ["место, где спят", "вид транспорта", "цвет"],
                   "market — «рынок»."),
    "listen_choose": ("This car is ___!", "This car is expensive!", "expensive",
                      ["cheap", "market"], "expensive — «дорогой»."),
    "missing": ("I ___ bread and milk.", "buy", "bu", "buy — покупать."),
    "voice": ["buy", "sell", "price", "money", "cheap"],
    "chat": ([("Anna", "Is this bread cheap?")], "You",
             "Yes, it is cheap!", ["Yes, it is expensive cheap.", "It cheap is."],
             "Отвечаем: Yes, it is cheap!"),
 },
 {  "title_ru": "Одежда", "title_en": "Clothes",
    "obj_ru": "Назвать одежду и размер.",
    "obj_en": "Name clothes and sizes.",
    "vocab": [("shirt", "рубашка"), ("shoes", "обувь"), ("size", "размер"),
              ("jacket", "куртка"), ("hat", "шляпа"), ("dress", "платье"),
              ("wear", "носить")],
    "quiz": ("Что надевают на голову?", "a hat",
             ["shoes", "a dress", "a shirt"], "hat — «шляпа»."),
    "translate": ("У меня новая куртка.", "I have a new jacket.", ["old", "wear"]),
    "fill": ("What ___ do you wear: small or big?", "size", ["price", "market"],
             "Какой размер вы носите: маленький или большой?"),
    "tap": ("I wear a white shirt.", ["black", "buy"]),
    "listening": "Her dress is beautiful!",
    "shadowing": ("I like your new shoes!", "Мне нравятся твои новые туфли!"),
    "story": ("New Shirt", [
        narr("Tom buys a new shirt.", "Том покупает новую рубашку."),
        dlg("Anna", "What size is it?", "Какой это размер?"),
        dlg("Tom", "It is my size. And it is cheap!", "Это мой размер. И она дешёвая!"),
        choice("Какая рубашка у Тома?",
               [("New and cheap", True), ("Old and expensive", False),
                ("Big and black", False)])]),
    "definition": ("wear", "иметь на себе одежду",
                   ["покупать одежду", "продавать одежду", "стирать одежду"],
                   "wear — «носить» (одежду)."),
    "listen_choose": ("I wear a ___ on my head.", "I wear a hat on my head.",
                      "hat", ["dress", "shoes"], "hat — «на голове»."),
    "missing": ("I wear a blue ___ to school.", "shirt", "sh", "shirt — рубашка."),
    "voice": ["shirt", "shoes", "jacket", "dress", "wear"],
    "chat": ([("Anna", "I like your jacket!")], "You",
             "Thank you! It is new.", ["Yes, I wear your jacket.", "I jacket thanks."],
             "Благодарим: Thank you! It is new."),
 },
 {  "title_ru": "Оплата", "title_en": "Paying",
    "obj_ru": "Спросить цену и оплатить покупку.",
    "obj_en": "Ask the price and pay for your purchase.",
    "vocab": [("pay", "платить"), ("card", "карта"), ("cash", "наличные"),
              ("discount", "скидка"), ("receipt", "чек"), ("how much", "сколько стоит"),
              ("change", "сдача")],
    "quiz": ("Чем платят: картой или …?", "cash",
             ["receipt", "discount", "change"], "cash — «наличные»; card — «карта»."),
    "translate": ("Сколько стоит эта шляпа?", "How much is this hat?",
                  ["price", "buy"]),
    "fill": ("Can I pay by ___?", "card", ["receipt", "discount"],
             "Можно заплатить картой?"),
    "tap": ("How much is this dress?", ["hat", "buy"]),
    "listening": "I pay cash and take my change.",
    "shadowing": ("How much is it?", "Сколько это стоит?"),
    "story": ("Paying", [
        narr("Anna buys a hat.", "Анна покупает шляпу."),
        dlg("Seller", "The hat is cheap today: big discount!",
            "Шляпа сегодня дешёвая: большая скидка!"),
        dlg("Anna", "Great! I pay by card.", "Отлично! Плачу картой."),
        choice("Чем платит Анна?",
               [("By card", True), ("Cash", False), ("With change", False)])]),
    "definition": ("discount", "цена становится меньше",
                   ["цена становится больше", "новая цена", "плата за доставку"],
                   "discount — «скидка»."),
    "listen_choose": ("Take your ___, please.", "Take your receipt, please.",
                      "receipt", ["discount", "card"],
                      "receipt — «чек», его дают после оплаты."),
    "missing": ("I pay with money in my hands: I pay ___.", "cash", "ca",
                "cash — наличные."),
    "voice": ["pay", "card", "cash", "receipt", "change"],
    "chat": ([("Seller", "Cash or card?")], "You",
             "Card, please.", ["I am card.", "Receipt, please."],
             "Отвечаем способом оплаты: Card, please."),
 },
],
},
# ============ T10 TIME ============
{
 "code": "A1_T10_TIME",
 "title": {"ru": "Время", "en": "Time"},
 "desc": {"ru": "Дни недели, «сегодня и завтра», месяцы и времена года.",
          "en": "Days of the week, \"today and tomorrow\", months and seasons."},
 "lessons": [
 {  "title_ru": "Дни недели", "title_en": "Days of the Week",
    "obj_ru": "Назвать семь дней недели.",
    "obj_en": "Name the seven days of the week.",
    "vocab": [("Monday", "понедельник"), ("Tuesday", "вторник"), ("Wednesday", "среда"),
              ("Thursday", "четверг"), ("Friday", "пятница"), ("Saturday", "суббота"),
              ("Sunday", "воскресенье")],
    "quiz": ("Какой день после Monday?", "Tuesday",
             ["Sunday", "Friday", "Wednesday"], "После понедельника — вторник (Tuesday)."),
    "translate": ("В субботу я дома.", "On Saturday I am at home.",
                  ["Monday", "week"]),
    "fill": ("___ is the first day of the week.", "Monday", ["Friday", "Sunday"],
             "Понедельник — первый день недели."),
    "tap": ("I rest on Sunday.", ["work", "Saturday"]),
    "listening": "We meet on Friday.",
    "shadowing": ("See you on Monday!", "Увидимся в понедельник!"),
    "story": ("Busy Week", [
        narr("Tom plans his week.", "Том планирует неделю."),
        dlg("Anna", "What do you do on Monday?", "Что ты делаешь в понедельник?"),
        dlg("Tom", "I work on Monday and study on Wednesday.",
            "Я работаю в понедельник и учусь в среду."),
        choice("Когда Том учится?",
               [("On Wednesday", True), ("On Monday", False), ("On Sunday", False)])]),
    "definition": ("Saturday", "шестой день недели, выходной",
                   ["первый день недели", "день перед пятницей", "рабочий день после среды"],
                   "Saturday — «суббота», выходной."),
    "listen_choose": ("We have a meeting on ___.", "We have a meeting on Thursday.",
                      "Thursday", ["Tuesday", "Sunday"], "Thursday — четверг."),
    "missing": ("___ is after Friday.", "Saturday", "sa",
                "После пятницы — суббота."),
    "voice": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    "chat": ([("Anna", "When do we meet?")], "You",
             "On Friday, at six.", ["In Friday at six.", "Friday we in at."],
             "Дни недели с предлогом on: on Friday."),
 },
 {  "title_ru": "Сегодня и завтра", "title_en": "Today and Tomorrow",
    "obj_ru": "Говорить о сегодня, завтра и вчера.",
    "obj_en": "Talk about today, tomorrow and yesterday.",
    "vocab": [("today", "сегодня"), ("tomorrow", "завтра"), ("yesterday", "вчера"),
              ("week", "неделя"), ("now", "сейчас"), ("weekend", "выходные"),
              ("free", "свободный")],
    "quiz": ("Какой день был до сегодня?", "yesterday",
             ["tomorrow", "now", "weekend"], "yesterday — «вчера»."),
    "translate": ("Завтра я свободен.", "Tomorrow I am free.", ["today", "busy"]),
    "fill": ("I am busy ___, but tomorrow I am free.", "today", ["yesterday", "now"],
             "Сегодня я занят, но завтра свободен."),
    "tap": ("What do you do on the weekend?", ["today", "work"]),
    "listening": "The week has seven days.",
    "shadowing": ("I am free now!", "Сейчас я свободен!"),
    "story": ("Plans", [
        dlg("Anna", "Are you free today?", "Ты свободен сегодня?"),
        dlg("Tom", "No, I am busy today. And tomorrow I work!",
            "Нет, сегодня я занят. А завтра работаю!"),
        dlg("Anna", "And on the weekend?", "А на выходных?"),
        choice("Когда Том свободен?",
               [("On the weekend", True), ("Today", False), ("Tomorrow", False)])]),
    "definition": ("weekend", "суббота и воскресенье",
                   ["пять рабочих дней", "один день", "весь месяц"],
                   "weekend — «выходные»."),
    "listen_choose": ("___ is Tuesday.", "Today is Tuesday.", "today",
                      ["yesterday", "week"], "today — «сегодня»."),
    "missing": ("See you ___!", "tomorrow", "to", "tomorrow — завтра."),
    "voice": ["today", "tomorrow", "yesterday", "now", "free"],
    "chat": ([("Anna", "Are you free tomorrow?")], "You",
             "Yes, I am free tomorrow!", ["Yes, I free tomorrow am.",
                                           "Tomorrow free yes I."],
             "Порядок: I am free tomorrow."),
 },
 {  "title_ru": "Месяцы и сезоны", "title_en": "Months and Seasons",
    "obj_ru": "Назвать месяцы и времена года.",
    "obj_en": "Name months and seasons.",
    "vocab": [("month", "месяц"), ("year", "год"), ("January", "январь"),
              ("spring", "весна"), ("summer", "лето"), ("autumn", "осень"),
              ("winter", "зима")],
    "quiz": ("Какой сезон самый холодный?", "winter",
             ["summer", "spring", "autumn"], "winter — «зима»."),
    "translate": ("Мой день рождения в январе.", "My birthday is in January.",
                  ["month", "spring"]),
    "fill": ("The ___ has twelve months.", "year", ["month", "winter"],
             "В году двенадцать месяцев."),
    "tap": ("I like summer.", ["winter", "month"]),
    "listening": "My birthday is in spring.",
    "shadowing": ("January is the first month.", "Январь — первый месяц."),
    "story": ("Seasons", [
        narr("Anna likes all seasons.", "Анне нравятся все времена года."),
        dlg("Tom", "What is your favorite season?", "Какое твоё любимое время года?"),
        dlg("Anna", "Summer! The park is green and bright.",
            "Лето! Парк зелёный и яркий."),
        choice("Какой сезон любимый у Анны?",
               [("Summer", True), ("Winter", False), ("Autumn", False)])]),
    "definition": ("spring", "сезон после зимы, всё цветёт",
                   ["сезон после лета", "самый холодный сезон", "месяц года"],
                   "spring — «весна»."),
    "listen_choose": ("My birthday is in ___.", "My birthday is in January.",
                      "January", ["spring", "year"],
                      "in January — «в январе» (месяц)."),
    "missing": ("December is the last ___ of the year.", "month", "mo",
                "month — месяц."),
    "voice": ["month", "year", "spring", "summer", "winter"],
    "chat": ([("Tom", "When is your birthday?")], "You",
             "My birthday is in spring.", ["My birthday is spring on.",
                                            "In my birthday is spring."],
             "Месяц/сезон с предлогом in: in spring."),
 },
],
},
]
