#!/usr/bin/env python3
"""A2 regenerated content: LISTENING AND SHADOWING (10 tracks x 3 lessons).

Grammar arc per topic: L1 past simple + present perfect,
L2 future forms + comparatives, L3 modals / first conditional.
"""

TRACKS = {
    "A2_LISTENING_SHADOWING_CONNECTED_EVERYDAY_CONVERSATIONS": [
        {
            "t": ("Разговор старых знакомых", "Old Acquaintances Talking"),
            "o": ("Понимать связную речь о прошлом, используя past simple и present perfect.",
                  "Understand connected speech about the past using past simple and present perfect."),
            "v": [("by the way", "кстати"), ("to run into", "случайно встретить"),
                  ("It's been ages", "прошла уйма времени"), ("to keep in touch", "держать связь"),
                  ("neighbourhood", "район"), ("to hear from", "получать весточку от"),
                  ("how about", "как насчёт")],
            "q": ("Which reply is natural when someone says 'It's been ages'?",
                  "Yes, I last saw you at Marina's wedding!",
                  ["Yes, I will saw you tomorrow at wedding.", "Yes, the ages are seeing us."]),
            "tr": ("Кстати, я случайно встретил нашего старого учителя на прошлой неделе.",
                   "By the way, I ran into our old teacher last week.",
                   ["did", "run", "tomorrow"]),
            "fill": ("We have ___ from Lena since she moved.", "heard",
                     ["hear", "hearing"], "Мы не получали вестей от Лены с её переезда."),
            "tap": ("It has been ages since we last spoke properly.", ["was", "did"]),
            "sh": ("You look great! Have you changed your hair? We should keep in touch this time — how about coffee next week?",
                   "Ты отлично выглядишь! Ты сменила причёску? Давай в этот раз держаться связи — как насчёт кофе на следующей неделе?"),
            "st": ("At the Supermarket", [
                ("Voice 1", "Wait — is that you, Kirill? It's been ages!", "Подожди — это ты, Кирилл? Сколько лет!"),
                ("Voice 2", "Anna! I did not recognise you with the short hair. How have you been?",
                 "Аня! Я не узнал тебя с короткой стрижкой. Как ты?"),
                ("What does Anna probably answer?", [
                    ("Really well — I have changed jobs since we last met.", True),
                    ("Really good, I change jobs tomorrow yesterday.", False),
                    ("The hair is recognising me.", False)])]),
            "d": ("to run into", "To meet someone by chance",
                  ["To visit someone after making an appointment", "To write a message to an old friend"]),
            "lw": ("I have ___ an old classmate today.", "I have run into an old classmate today.",
                   "run into", ["ran into", "running into"]),
            "mw": ("Let's keep ___ touch from now on.", "in", "in"),
            "ch": ([("Acquaintance", "We should catch up one day!")], "You",
                   "Definitely — it has been ages. I have moved, but my number is the same.",
                   ["We caught up yesterday tomorrow.", "The day is catching us."]),
        },
        {
            "t": ("Договариваемся о встрече", "Making Arrangements"),
            "o": ("Понимать договорённости о будущем и сравнивать варианты.",
                  "Understand future arrangements and compare options."),
            "v": [("Are you free...?", "Ты свободен...?"), ("to suit", "подходить (о времени)"),
                  ("instead", "вместо"), ("to make it", "смочь прийти"),
                  ("to put off", "перенести (на потом)"), ("either ... or", "либо ... либо"),
                  ("the sooner the better", "чем раньше, тем лучше")],
            "q": ("Which sentence offers an alternative politely?",
                  "Saturday doesn't suit me — could we do Sunday instead?",
                  ["Saturday suits me not, do Sunday yesterday.", "Sunday is suiting Saturday instead me."]),
            "tr": ("В четверг я занят, но могу в пятницу — чем раньше, тем лучше.",
                   "I am busy on Thursday, but I can make it on Friday — the sooner the better.",
                   ["did", "was", "yesterday"]),
            "fill": ("Let's ___ the picnic until the weather improves.", "put off",
                     ["puts off", "putting off"], "Давай перенесём пикник до улучшения погоды."),
            "tap": ("Either Saturday or Sunday suits me fine.", ["was", "did"]),
            "sh": ("I cannot make it at six, but seven works — if that is too late, we can put the meeting off to the morning.",
                   "Я не смогу в шесть, но семь подходит — если это поздно, перенесём встречу на утро."),
            "st": ("Finding a Time", [
                ("Voice 1", "Are you free on Thursday evening?", "Ты свободен в четверг вечером?"),
                ("Voice 2", "Not really. Either Friday or the weekend would be better.",
                 "Не очень. Либо пятница, либо выходные подойдут лучше."),
                ("What does Voice 1 say?", [
                    ("Then let's say Friday at seven — the sooner the better.", True),
                    ("Then we say Friday yesterday at seven.", False),
                    ("Then Thursday is being free on Friday.", False)])]),
            "d": ("to make it", "To manage to come to an event",
                  ["To create something with your hands", "To be late for a meeting again"]),
            "lw": ("Could we meet on Sunday ___ ?", "Could we meet on Sunday instead?",
                   "instead", ["instead of", "insteadly"]),
            "mw": ("Seven o'clock ___ me fine.", "suits", "su"),
            "ch": ([("Friend", "Can you come to dinner on Wednesday?")], "You",
                   "I'd love to, but I can't make it — could we put it off to next week?",
                   ["I made it yesterday tomorrow.", "Wednesday is dining me."]),
        },
        {
            "t": ("Если разговор заходит о планах", "When the Talk Turns to Plans"),
            "o": ("Следить за разговором о планах, используя should и первое условное.",
                  "Follow a conversation about plans using should and the first conditional."),
            "v": [("to sound like a plan", "звучит как план"), ("to be up to", "собираться, замышлять"),
                  ("no rush", "не спеши (не срочно)"), ("to count on", "рассчитывать на"),
                  ("in case", "на случай"), ("to decide later", "решить позже"),
                  ("for now", "пока (что)")],
            "q": ("Which reply means 'let's wait before deciding'?",
                  "Let's decide later — there's no rush.",
                  ["Let's decide it yesterday already now.", "The decision is deciding us later."]),
            "tr": ("Если погода испортится, у нас должен быть запасной вариант на этот случай.",
                   "If the weather turns bad, we should have a backup option just in case.",
                   ["did", "turned", "yesterday"]),
            "fill": ("You can ___ me — I will be there at eight.", "count on",
                     ["counts on", "counting on"], "Можешь на меня рассчитывать — я буду там в восемь."),
            "tap": ("That sounds like a plan — for now.", ["was", "did"]),
            "sh": ("If you are not sure about Sunday, no problem — decide later, and I will keep the second ticket just in case.",
                   "Если не уверен насчёт воскресенья, ничего — реши позже, а я придержу второй билет на всякий случай."),
            "st": ("Weekend Ideas", [
                ("Voice 1", "What are you up to this weekend?", "Что ты задумал на эти выходные?"),
                ("Voice 2", "Nothing fixed. If the weather is fine, I might cycle to the forest.",
                 "Ничего определённого. Если погода будет хорошей, могу поехать в лес на велосипеде."),
                ("What does Voice 1 answer?", [
                    ("Sounds like a plan — count me in if you go on Sunday.", True),
                    ("Sounded like a plan yesterday tomorrow.", False),
                    ("The forest is cycling you on Sunday.", False)])]),
            "d": ("to count on", "To rely on someone or something",
                  ["To count things quickly in your head", "To cancel plans without telling anyone"]),
            "lw": ("I will keep the tickets ___ case you change your mind.",
                   "I will keep the tickets in case you change your mind.",
                   "in", ["on", "at"]),
            "mw": ("You can count ___ me any time.", "on", "on"),
            "ch": ([("Friend", "Shall we book the tickets tonight?")], "You",
                   "No rush — if we book on Friday, the price will be the same.",
                   ["I booked them yesterday tomorrow.", "The tickets are rushing us."]),
        },
    ],

    "A2_LISTENING_SHADOWING_DIRECTIONS_AND_LOCATION_DETAILS": [
        {
            "t": ("Как пройти: вчерашний маршрут", "Directions: Yesterday's Route"),
            "o": ("Понимать объяснения маршрута, используя past simple и present perfect.",
                  "Understand route explanations using past simple and present perfect."),
            "v": [("opposite", "напротив"), ("behind", "за (позади)"),
                  ("to go past", "пройти мимо"), ("roundabout", "круговое движение"),
                  ("landmark", "ориентир"), ("to take the second left", "свернуть на втором повороте налево"),
                  ("you can't miss it", "вы его не пропустите")],
            "q": ("Which phrase means the place is easy to see?",
                  "You can't miss it — it's the bright green door.",
                  ["You can miss it easy yesterday.", "The door is missing you greenly."]),
            "tr": ("Мы прошли мимо аптеки и свернули на втором повороте налево.",
                   "We went past the pharmacy and took the second left.",
                   ["did", "go", "tomorrow"]),
            "fill": ("The bakery is ___ the church, across the road.", "opposite",
                     ["opposites", "oppositely"], "Пекарня напротив церкви, через дорогу."),
            "tap": ("Have you passed the roundabout yet?", ["was", "did"]),
            "sh": ("Go past the post office, and the studio is behind the tall glass building — you can't miss it.",
                   "Пройдите мимо почты, и студия за высоким стеклянным зданием — вы её не пропустите."),
            "st": ("Giving Directions", [
                ("Visitor", "Excuse me, how do I get to the museum?", "Извините, как пройти в музей?"),
                ("Local", "Go past the bakery, take the second left, and the museum is opposite the park.",
                 "Пройдите мимо пекарни, на втором повороте налево, и музей напротив парка."),
                ("What should the visitor watch for?", [
                    ("A bakery and then a park as landmarks.", True),
                    ("A museum and then a bakery yesterday.", False),
                    ("The left turn is missing the park.", False)])]),
            "d": ("roundabout", "A circular road where cars turn around a centre point",
                  ["A place where two railways cross", "A bridge for walking over a motorway"]),
            "lw": ("We have gone ___ the market already.", "We have gone past the market already.",
                   "past", ["passed", "passing"]),
            "mw": ("The bank is ___ the supermarket.", "behind", "be"),
            "ch": ([("Visitor", "Is the station far from here?")], "You",
                   "Ten minutes on foot — go past the cinema, and you can't miss it.",
                   ["I went there yesterday tomorrow.", "The station is footing me."]),
        },
        {
            "t": ("Маршрут на завтра", "Tomorrow's Route"),
            "o": ("Слушать инструкции о будущем маршруте и сравнивать пути.",
                  "Listen to future route instructions and compare ways."),
            "v": [("the fastest way", "самый быстрый путь"), ("to avoid", "избегать"),
                  ("traffic jam", "пробка"), ("more direct", "прямее"),
                  ("to follow the signs", "следовать указателям"), ("shortcut", "короткий путь"),
                  ("less crowded", "менее людный")],
            "q": ("Which route description compares two ways correctly?",
                  "The road by the river is less crowded than the highway.",
                  ["The river road is crowdeder than highway.", "The river road is most crowded than the highway."]),
            "tr": ("Завтра я поеду через центр, потому что мост будут ремонтировать.",
                   "Tomorrow I am going to drive through the centre because they are repairing the bridge.",
                   ["did", "drove", "yesterday"]),
            "fill": ("The metro is ___ direct than the bus during rush hour.", "more",
                     ["most", "much"], "Метро прямее автобуса в час пик."),
            "tap": ("Follow the signs to the old town.", ["was", "did"]),
            "sh": ("If you take the shortcut through the park, you will arrive ten minutes earlier and avoid the traffic jam.",
                   "Если пойти коротким путём через парк, приедешь на десять минут раньше и избежишь пробки."),
            "st": ("Two Ways to the Airport", [
                ("Voice 1", "Should I take the highway or the old road tomorrow?", "Мне завтра ехать по шоссе или по старой дороге?"),
                ("Voice 2", "The highway is faster, but the old road is less crowded in the morning.",
                 "Шоссе быстрее, но старая дорога менее людная утром."),
                ("What does Voice 1 decide?", [
                    ("Then I am going to take the old road and follow the airport signs.", True),
                    ("Then I took the old road yesterday tomorrow.", False),
                    ("Then the highway is taking me.", False)])]),
            "d": ("shortcut", "A quicker way between two places",
                  ["The longest possible route to a place", "A road only for bicycles and buses"]),
            "lw": ("I am going to ___ the ring road.", "I am going to avoid the ring road.",
                   "avoid", ["avoided", "avoiding"]),
            "mw": ("The night bus is ___ crowded.", "less", "le"),
            "ch": ([("Friend", "Which entrance should we use?")], "You",
                   "The north one — if we follow the blue signs, it will be the fastest way.",
                   ["We used it yesterday tomorrow.", "The entrance is using us."]),
        },
        {
            "t": ("Если заблудился", "If You Get Lost"),
            "o": ("Понимать советы о ориентировании, используя should и первое условное.",
                  "Understand orientation advice using should and the first conditional."),
            "v": [("to double back", "вернуться назад"), ("lost", "потерявшийся"),
                  ("to check the GPS", "проверить GPS"), ("to ask a local", "спросить местного"),
                  ("nearby", "поблизости"), ("dead end", "тупик"),
                  ("to retrace your steps", "вернуться по своим следам")],
            "q": ("Which advice is correct when you take a wrong turn?",
                  "You should double back to the last landmark.",
                  ["You should to double back yesterday.", "You must doubling back last turn."]),
            "tr": ("Если пойдёшь налево, упрёшься в тупик — лучше вернуться назад.",
                   "If you turn left, you will reach a dead end — you should double back.",
                   ["did", "turned", "yesterday"]),
            "fill": ("If the street name does not ___ the map, retrace your steps.",
                     "match", ["will match", "matched"], "Если название улицы не совпадает с картой, вернись по своим следам."),
            "tap": ("You should ask a local — they know the shortcuts.", ["mustn't", "went"]),
            "sh": ("If you have walked for fifteen minutes without landmarks, you should check the GPS or ask someone nearby.",
                   "Если шёл пятнадцать минут без ориентиров, стоит проверить GPS или спросить кого-то рядом."),
            "st": ("The Dead End", [
                ("Voice 1", "This street ends at a fence — I think we are lost.", "Улица заканчивается забором — кажется, мы заблудились."),
                ("Voice 2", "Have we passed any shop we remember?", "Мы проходили какой-нибудь магазин, который помним?"),
                ("What does Voice 1 suggest?", [
                    ("Yes, the bakery — let's retrace our steps to it.", True),
                    ("Yes, we pass it tomorrow yesterday.", False),
                    ("The fence is walking us back.", False)])]),
            "d": ("dead end", "A street or path that you cannot continue along",
                  ["A road that goes around the whole city", "A crossing with traffic lights"]),
            "lw": ("If you feel ___ , check the GPS.", "If you feel lost, check the GPS.",
                   "lost", ["lose", "loosen"]),
            "mw": ("We should ask a ___ for directions.", "local", "lo"),
            "ch": ([("Friend", "The house numbers look wrong.")], "You",
                   "Maybe we missed the turn — if we double back to the bridge, we will find the street.",
                   ["I doubled back yesterday tomorrow.", "The numbers are housing us."]),
        },
    ],

    "A2_LISTENING_SHADOWING_PERSONAL_EXPERIENCES": [
        {
            "t": ("Истории из жизни", "Life Stories"),
            "o": ("Понимать рассказы о прошлом, используя past simple и present perfect.",
                  "Understand stories about the past using past simple and present perfect."),
            "v": [("childhood", "детство"), ("to move house", "переехать (в другой дом)"),
                  ("used to", "раньше (было)"), ("memory", "воспоминание"),
                  ("to grow up", "вырасти"), ("the first time", "первый раз"),
                  ("since then", "с тех пор")],
            "q": ("Which sentence talks about a childhood habit?",
                  "We used to play football in this yard every day.",
                  ["We use to played here yesterday.", "The yard is playing us daily."]),
            "tr": ("Я вырос в маленьком городе, а потом мы переехали в столицу.",
                   "I grew up in a small town, and then we moved house to the capital.",
                   ["did", "grow", "tomorrow"]),
            "fill": ("She has lived in five cities ___ she left home.", "since",
                     ["for", "ago"], "Она пожила в пяти городах с тех пор, как уехала из дома."),
            "tap": ("Since then I have never eaten oysters again.", ["was", "did"]),
            "sh": ("When I was a child, we used to spend every summer at the lake, and I have kept those memories all my life.",
                   "В детстве мы проводили каждое лето у озера, и я храню эти воспоминания всю жизнь."),
            "st": ("An Old Photo", [
                ("Voice 1", "Look at this photo — it was my first day at school.", "Посмотри на это фото — мой первый день в школе."),
                ("Voice 2", "You look so serious! Where did you grow up?", "Той такой серьёзный! Где ты вырос?"),
                ("What does Voice 1 answer?", [
                    ("In a village near the sea. We moved house when I was ten.", True),
                    ("I grew up tomorrow yesterday near the sea.", False),
                    ("The photo is growing me serious.", False)])]),
            "d": ("memory", "Something you remember from the past",
                  ["A plan you make for next summer", "A photo you are going to take tomorrow"]),
            "lw": ("I have kept this ___ since childhood.", "I have kept this medal since childhood.",
                   "medal", ["medals", "medalled"]),
            "mw": ("We ___ to swim in this river.", "used", "us"),
            "ch": ([("Friend", "Have you ever changed schools?")], "You",
                   "Twice — I still remember how nervous I was the first time.",
                   ["I changed them yesterday tomorrow.", "The schools are changing me."]),
        },
        {
            "t": ("Планы, о которых рассказывают", "Plans People Talk About"),
            "o": ("Понимать рассказы о планах и сравнивать жизненные пути.",
                  "Understand talks about plans and compare life paths."),
            "v": [("to settle down", "осесть, обосноваться"), ("career change", "смена карьеры"),
                  ("more challenging", "сложнее (вызов)"), ("to apply for", "подать заявку на"),
                  ("abroad", "за границей"), ("to be ready for", "быть готовым к"),
                  ("gap year", "перерыв на год (между учёбой)")],
            "q": ("Which sentence compares two paths correctly?",
                  "Moving abroad is more challenging than changing jobs at home.",
                  ["Moving abroad is challenginger than jobs.", "Abroad is most challenging than home."]),
            "tr": ("В следующем году она собирается взять перерыв и пожить за границей.",
                   "Next year she is going to take a gap year and live abroad.",
                   ["did", "took", "yesterday"]),
            "fill": ("A career change is ___ risky at thirty than at fifty.", "less",
                     ["least", "little"], "Смена карьеры в тридцать менее рискованна, чем в пятьдесят."),
            "tap": ("They are going to settle down in the countryside.", ["was", "did"]),
            "sh": ("If you are ready for a big change, a career switch will feel less scary than it sounds.",
                   "Если ты готов к большим переменам, смена карьеры будет менее страшной, чем звучит."),
            "st": ("Plans Over Coffee", [
                ("Voice 1", "I have some news — I am going to apply for a job in Berlin.", "У меня новость — я собираюсь подать заявку на работу в Берлине."),
                ("Voice 2", "Really? That is a big step. Are you ready for such a change?",
                 "Серьёзно? Это большой шаг. Ты готова к таким переменам?"),
                ("What does Voice 1 say?", [
                    ("I think so — it is more challenging, but I have planned it for a year.", True),
                    ("Yes, I was ready for it yesterday tomorrow.", False),
                    ("Berlin is applying for me.", False)])]),
            "d": ("to settle down", "To start living a stable life in one place",
                  ["To travel non-stop for several years", "To change your flat every month"]),
            "lw": ("He is going to ___ for a master's programme.", "He is going to apply for a master's programme.",
                   "apply", ["applied", "applying"]),
            "mw": ("Living abroad is ___ comfortable now.", "more", "mo"),
            "ch": ([("Friend", "What would you do with a gap year?")], "You",
                   "I would learn Spanish — if I stay in one place, progress will be faster.",
                   ["I took it yesterday tomorrow.", "The year is gapping me."]),
        },
        {
            "t": ("Опыт, который учит", "Experience That Teaches"),
            "o": ("Понимать рассказы об уроках жизни, используя should и первое условное.",
                  "Understand life-lesson stories using should and the first conditional."),
            "v": [("lesson", "урок"), ("to regret", "сожалеть"),
                  ("mistake", "ошибка"), ("to take a risk", "рискнуть"),
                  ("worth it", "того стоило"), ("to look back", "оглядываться назад"),
                  ("to learn from", "извлечь урок из")],
            "q": ("Which sentence describes a lesson learned?",
                  "If I had asked for help, the move would have been easier — now I always ask.",
                  ["I asked help yesterday, and now never ask.", "The help is moving me easier."]),
            "tr": ("Если ты не рискнёшь, то потом будешь об этом жалеть.",
                   "If you do not take the risk, you will regret it later.",
                   ["did", "took", "yesterday"]),
            "fill": ("Looking back, that mistake ___ the best lesson of my career.", "was"
                     , ["were", "been"], "Оглядываясь назад, та ошибка была лучшим уроком моей карьеры."),
            "tap": ("You should learn from mistakes, not fear them.", ["mustn't", "went"]),
            "sh": ("I almost turned down the job offer, but a friend said: if you never take risks, you will never know.",
                   "Я чуть не отказался от предложения о работе, но друг сказал: если никогда не рискуешь, никогда не узнаешь."),
            "st": ("The Rejected Offer", [
                ("Voice 1", "Have I told you about my first job interview? I turned the offer down.",
                 "Я рассказывал о своём первом собеседовании? Я отказался от предложения."),
                ("Voice 2", "Why? Do you regret it?", "Почему? Сожалеешь?"),
                ("What does Voice 1 answer?", [
                    ("A little — but I learned from it, and the next risk was worth it.", True),
                    ("Yes, I regret it tomorrow yesterday.", False),
                    ("The interview is regretting me down.", False)])]),
            "d": ("to regret", "To feel sad about something you did or did not do",
                  ["To feel happy about a past decision", "To plan a future change carefully"]),
            "lw": ("If you ___ a risk, you will never grow.", "If you never take a risk, you will never grow.",
                   "take", ["will take", "took"]),
            "mw": ("It was difficult, but it was ___ it.", "worth", "wo"),
            "ch": ([("Friend", "I failed my first driving test.")], "You",
                   "So did I — if you learn from it, the second attempt will be easier.",
                   ["I passed it yesterday tomorrow.", "The test is failing me."]),
        },
    ],

    "A2_LISTENING_SHADOWING_PHONE_CALLS_AND_VOICE_MESSAGES": [
        {
            "t": ("Голосовые на этой неделе", "Voice Messages This Week"),
            "o": ("Понимать голосовые сообщения, используя past simple и present perfect.",
                  "Understand voice messages using past simple and present perfect."),
            "v": [("to call back", "перезвонить"), ("signal", "сигнал (связи)"),
                  ("to cut off", "оборваться (о связи)"), ("voicemail", "голосовая почта"),
                  ("battery", "батарея"), ("to hang up", "положить трубку"),
                  ("missed call", "пропущенный звонок")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The signal has cut off three times during our call.",
                  ["The signal has cut off yesterday three times.", "The signal cut off already now three times."]),
            "tr": ("Я оставил голосовое, потому что у тебя разрядился телефон.",
                   "I left a voicemail because your phone had run out of battery.",
                   ["did", "leave", "tomorrow"]),
            "fill": ("Sorry, I have to ___ — someone is at the door.", "hang up",
                     ["hangs up", "hanging up"], "Извини, мне нужно положить трубку — кто-то у двери."),
            "tap": ("She has sent three voice messages this morning.", ["was", "did"]),
            "sh": ("Hi! You have three missed calls from me — my battery died, so call back when you can, and do not hang up too early!",
                   "Привет! У тебя три пропущенных от меня — батарея села, так что перезвони, когда сможешь, и не сбрасывай сразу!"),
            "st": ("The Broken Call", [
                ("Voice 1", "Hello? Hello? The signal is terrible here...", "Алло? Алло? Здесь ужасный сигнал..."),
                ("Voice 2", "I can barely hear you — you are cutting off.", "Я тебя едва слышу — связь обрывается."),
                ("What do they decide?", [
                    ("Let's hang up and I will call you back from the landline.", True),
                    ("Let's hang up it tomorrow yesterday.", False),
                    ("The signal is calling the landline back.", False)])]),
            "d": ("voicemail", "A recorded message left when someone does not answer",
                  ["A text message sent late at night", "A photo shared in a group chat"]),
            "lw": ("I have ___ you a voice message.", "I have sent you a voice message.",
                   "sent", ["send", "sending"]),
            "mw": ("My phone has run out of ___ .", "battery", "ba"),
            "ch": ([("Friend", "Why didn't you pick up?")], "You",
                   "Sorry — I have been in the metro, and the signal cut off halfway.",
                   ["I picked it up yesterday tomorrow.", "The phone is picking me."]),
        },
        {
            "t": ("Звонок по делу", "A Business-like Call"),
            "o": ("Понимать телефонные договорённости и сравнивать способы связи.",
                  "Understand phone arrangements and compare ways of communicating."),
            "v": [("to confirm", "подтвердить"), ("more convenient", "удобнее"),
                  ("to text", "написать SMS/в чат"), ("reception", "приём (связи)"),
                  ("in writing", "в письменном виде"), ("loud", "громкий"),
                  ("to arrange", "договориться")],
            "q": ("Which sentence compares communication ways correctly?",
                  "Email is more convenient than a call for detailed information.",
                  ["Email is convenienter than calls.", "Email is most convenient than a call."]),
            "tr": ("Я отправлю детали письмом — по телефону слишком шумно.",
                   "I will send the details by email — it is too loud for a phone call.",
                   ["did", "sent", "yesterday"]),
            "fill": ("Texting is ___ in a noisy place than calling.", "easier",
                     ["easiest", "more easy"], "В шумном месте писать в чате легче, чем звонить."),
            "tap": ("Let me confirm everything in writing after the call.", ["was", "did"]),
            "sh": ("If reception is bad at your place, we can arrange the details by text instead of a long call.",
                   "Если у тебя плохой приём, договоримся о деталях в чате вместо долгого звонка."),
            "st": ("Arranging by Phone", [
                ("Voice 1", "So, the delivery is on Thursday between two and four, right?", "Итак, доставка в четверг с двух до четырёх, верно?"),
                ("Voice 2", "Exactly. Shall I confirm the time in writing?", "Точно. Подтвердить время письменно?"),
                ("What does Voice 1 answer?", [
                    ("Yes, please — a text is more convenient for me.", True),
                    ("Yes, you confirmed it yesterday tomorrow.", False),
                    ("The delivery is texting the time.", False)])]),
            "d": ("reception", "How well your phone receives a signal",
                  ["The place where you buy a new phone", "The sound your ringtone makes"]),
            "lw": ("I will ___ the time by text.", "I will confirm the time by text.",
                   "confirm", ["confirms", "confirming"]),
            "mw": ("A quick text is ___ than voicemail.", "clearer", "cl"),
            "ch": ([("Friend", "Call me tonight to discuss it?")], "You",
                   "Better in writing — if I text you, you will have all the addresses.",
                   ["I called you yesterday tomorrow.", "Tonight is calling me."]),
        },
        {
            "t": ("Телефонный этикет", "Phone Etiquette"),
            "o": ("Понимать советы о телефонном общении, используя should и первое условное.",
                  "Understand phone etiquette advice using should and the first conditional."),
            "v": [("to identify yourself", "назвать себя"), ("bad connection", "плохая связь"),
                  ("to speak up", "говорить громче"), ("polite", "вежливый"),
                  ("to disturb", "беспокоить"), ("suitable time", "подходящее время"),
                  ("brief", "краткий")],
            "q": ("Which sentence gives correct phone advice?",
                  "You should state your name at the beginning of a business call.",
                  ["You should to state it yesterday.", "You must stating your name last call."]),
            "tr": ("Если позвонишь в неподходящее время, попроси прощения и уточни, когда удобно.",
                   "If you call at an unsuitable time, you should apologise and ask when it is convenient.",
                   ["did", "called", "yesterday"]),
            "fill": ("If the person cannot hear you, ___ .", "speak up",
                     ["speaks up", "speaking up"], "Если человек тебя не слышит, говори громче."),
            "tap": ("You should keep business calls brief and polite.", ["mustn't", "went"]),
            "sh": ("If you call someone new, you should identify yourself first — otherwise they will not know who is speaking.",
                   "Если звонишь новому человеку, сначала стоит представиться — иначе собеседник не поймёт, с кем говорит."),
            "st": ("The Wrong Moment", [
                ("Voice 1", "Hello, this is Marina from the clinic. Is this a suitable time to talk?",
                 "Здравствуйте, это Марина из клиники. Сейчас удобное время для разговора?"),
                ("Voice 2", "I am driving — could you call back in half an hour?", "Я за рулём — можно перезвонить через полчаса?"),
                ("What does Marina answer?", [
                    ("Of course, I will call at four — sorry to disturb you.", True),
                    ("I called you back yesterday tomorrow.", False),
                    ("The driving is calling the clinic.", False)])]),
            "d": ("to disturb", "To interrupt someone, often at a bad moment",
                  ["To help someone remember a meeting", "To send a polite reminder by email"]),
            "lw": ("If it is urgent, ___ up, please.", "If it is urgent, speak up, please.",
                   "speak", ["will speak", "spoke"]),
            "mw": ("You should identify ___ first.", "yourself", "you"),
            "ch": ([("Friend", "He never says his name when he calls.")], "You",
                   "Annoying — if he identified himself, I would not hang up on him.",
                   ["He said it yesterday tomorrow.", "His name is calling me."]),
        },
    ],

    "A2_LISTENING_SHADOWING_PUBLIC_ANNOUNCEMENTS": [
        {
            "t": ("Объявления, которые уже прозвучали", "Announcements That Have Already Sounded"),
            "o": ("Понимать объявления, используя past simple и present perfect.",
                  "Understand announcements using past simple and present perfect."),
            "v": [("attention, please", "внимание, пожалуйста"), ("platform change", "изменение платформы"),
                  ("to apologise for", "извиниться за"), ("delay", "задержка"),
                  ("final call", "последний вызов (посадка)"), ("to make one's way to", "проследовать к"),
                  ("boarding", "посадка")],
            "q": ("Which phrase do you hear just before gates close?",
                  "This is the final call for flight BA 229.",
                  ["This is first call for yesterday flight.", "The gates are calling the flight finally."]),
            "tr": ("Пассажирам извинились за задержку и попросили пройти к выходу B12.",
                   "The passengers have received an apology for the delay and were asked to make their way to gate B12.",
                   ["did", "apologise", "tomorrow"]),
            "fill": ("The announcement said the train ___ from a different platform.", "departed",
                     ["has depart", "departing"], "В объявлении сказали, что поезд отправляется с другой платформы."),
            "tap": ("Have you heard the platform change announcement?", ["was", "did"]),
            "sh": ("Attention, please: the 14:15 service to Bristol has been delayed — we apologise for the inconvenience and will update you shortly.",
                   "Внимание: рейс 14:15 в Бристоль задержан — приносим извинения за неудобства и скоро сообщим подробности."),
            "st": ("At the Station", [
                ("Announcement", "Attention, please. The 10:30 train to Oxford now leaves from platform nine.",
                 "Внимание. Поезд 10:30 в Оксфорд теперь отправляется с девятой платформы."),
                ("Passenger", "Did you hear that? We have been waiting at the wrong platform.",
                 "Ты слышал? Мы ждали не на той платформе."),
                ("What should they do?", [
                    ("Hurry — boarding starts in three minutes.", True),
                    ("To wait at the old platform tomorrow yesterday.", False),
                    ("The announcement is waiting for the train.", False)])]),
            "d": ("final call", "The last announcement before boarding closes",
                  ["The first announcement of the day", "A call made after the plane has left"]),
            "lw": ("They have ___ for the delay.", "They have apologised for the delay.",
                   "apologised", ["apologise", "apologising"]),
            "mw": ("Please make your ___ to gate five.", "way", "wa"),
            "ch": ([("Announcement", "This is the final call for passenger Ivanov.")], "You",
                   "That's me — if I run now, I will catch the gate before it closes.",
                   ["I ran there yesterday tomorrow.", "The call is gating me."]),
        },
        {
            "t": ("Что объявят завтра", "What Will Be Announced Tomorrow"),
            "o": ("Понимать объявления о будущем и сравнивать варианты проезда.",
                  "Understand future announcements and compare travel options."),
            "v": [("replacement bus", "автобус-заменитель"), ("more frequent", "чаще"),
                  ("to run", "ходить (о транспорте)"), ("every ten minutes", "каждые десять минут"),
                  ("to be subject to", "зависеть от (обстоятельств)"), ("at short notice", "в последний момент"),
                  ("timetable", "расписание")],
            "q": ("Which announcement compares two services correctly?",
                  "The express is more frequent than the slow service in the morning.",
                  ["The express is frequenter than slow service.", "The express is most frequent than the slow one."]),
            "tr": ("Завтра вместо поезда будет ходить автобус каждые двадцать минут.",
                   "Tomorrow a replacement bus will run every twenty minutes instead of the train.",
                   ["did", "ran", "yesterday"]),
            "fill": ("The shuttle runs ___ fifteen minutes on Sundays.", "every",
                     ["each", "all"], "Шаттл ходит каждые пятнадцать минут по воскресеньям."),
            "tap": ("Extra trains are going to run during the festival.", ["was", "did"]),
            "sh": ("Because of engineering works, buses will replace trains this weekend — the buses are less frequent, so please allow extra time.",
                   "Из-за путевых работ поезда заменят автобусами — автобусы ходят реже, поэтому заложите дополнительное время."),
            "st": ("Weekend Works", [
                ("Announcement", "On Sunday, buses will replace all trains between Central and Northgate.",
                 "В воскресенье автобусы заменят все поезда между Центральным и Нортгейтом."),
                ("Passenger", "How often will the buses run?", "Как часто будут ходить автобусы?"),
                ("What is the likely answer?", [
                    ("Every twenty minutes — less frequent than the trains, I am afraid.", True),
                    ("Every twenty minutes tomorrow yesterday.", False),
                    ("The buses are training the minute.", False)])]),
            "d": ("replacement bus", "A bus used when a train service is not running",
                  ["A bus that follows the same route for tourists", "An extra carriage added to a train"]),
            "lw": ("The night service is going to ___ twice an hour.", "The night service is going to run twice an hour.",
                   "run", ["ran", "running"]),
            "mw": ("Morning trains are ___ frequent.", "more", "mo"),
            "ch": ([("Announcement", "This service is subject to cancellation.")], "You",
                   "Then I should check the app — if it is cancelled, the taxi will cost a fortune.",
                   ["It cancelled me yesterday tomorrow.", "The service is subjecting me."]),
        },
        {
            "t": ("Если объявление касается тебя", "If the Announcement Concerns You"),
            "o": ("Понимать инструкции в объявлениях, используя should и первое условное.",
                  "Understand announcement instructions using should and the first conditional."),
            "v": [("to follow instructions", "следовать инструкциям"), ("unattended", "беспризорный (оставленный без присмотра)"),
                  ("to evacuate", "эвакуироваться"), ("emergency exit", "аварийный выход"),
                  ("to report to", "явиться к"), ("in an orderly manner", "организованно"),
                  ("staff member", "сотрудник")],
            "q": ("Which sentence gives a safety instruction?",
                  "You should leave the building through the emergency exits.",
                  ["You should to leave it yesterday.", "You must leaving yesterday through exits."]),
            "tr": ("Если вы увидите оставленную без присмотра сумку, сообщите об этом персоналу.",
                   "If you see an unattended bag, you should report it to a staff member.",
                   ["did", "saw", "yesterday"]),
            "fill": ("If the alarm ___ , evacuate in an orderly manner.", "sounds",
                     ["will sound", "sounded"], "Если сработает сигнализация, эвакуируйтесь организованно."),
            "tap": ("You should follow the instructions of the staff.", ["mustn't", "went"]),
            "sh": ("If you cannot hear this announcement clearly, you should move closer to a staff member and ask for help.",
                   "Если вы плохо слышите объявление, подойдите ближе к сотруднику и попросите помощи."),
            "st": ("The Unattended Bag", [
                ("Announcement", "Attention: a bag has been found unattended near the main entrance.",
                 "Внимание: у главного входа найдена сумка без присмотра."),
                ("Passenger", "That is my bag! I left it by the pillar for a minute.",
                 "Это моя сумка! Я на минуту оставил её у колонны."),
                ("What should the passenger do?", [
                    ("Report to the staff and describe the bag.", True),
                    ("To report it tomorrow yesterday again.", False),
                    ("The bag is announcing the passenger.", False)])]),
            "d": ("to evacuate", "To leave a building or area quickly and safely",
                  ["To enter a station through the main doors", "To wait calmly for a delayed train"]),
            "lw": ("If the alarm ___, follow the green signs.", "If the alarm sounds, follow the green signs.",
                   "sounds", ["will sound", "sounded"]),
            "mw": ("Please report any unattended luggage ___ the staff.", "to", "to"),
            "ch": ([("Announcement", "Will passenger Smith please report to the information desk?")], "You",
                   "That's me — if I go now, I will find out what happened to my connection.",
                   ["I reported me yesterday tomorrow.", "The desk is passing me by."]),
        },
    ],

    "A2_LISTENING_SHADOWING_QUESTIONS_AND_FOLLOW_UP_ANSWERS": [
        {
            "t": ("Вопросы о прошлом", "Questions About the Past"),
            "o": ("Понимать вопросы и ответы о прошлом, используя past simple и present perfect.",
                  "Understand past questions and answers using past simple and present perfect."),
            "v": [("How long...?", "Как долго...?"), ("What happened next?", "Что было дальше?"),
                  ("to find out", "выяснить"), ("the reason why", "причина, по которой"),
                  ("to explain", "объяснить"), ("How come?", "Как так получилось?"),
                  ("detail", "деталь")],
            "q": ("Which question asks about duration?",
                  "How long have you worked here?",
                  ["How long you work here yesterday?", "How long did you worked tomorrow?"]),
            "tr": ("Как так получилось, что ты не знал о встрече?",
                   "How come you did not know about the meeting?",
                   ["did", "know", "tomorrow"]),
            "fill": ("She explained the reason ___ she had left early.", "why",
                     ["because", "how"], "Она объяснила причину, по которой ушла раньше."),
            "tap": ("Have you found out what happened next?", ["was", "did"]),
            "sh": ("How long have you lived in this city? What made you move here, and do you remember your first week?",
                   "Как долго ты живёшь в этом городе? Что заставило тебя переехать, и помнишь ли свою первую неделю?"),
            "st": ("Small Talk Questions", [
                ("Voice 1", "You mentioned a trip to Georgia. How long did you stay?", "Ты упоминала поездку в Грузию. Как долго ты была там?"),
                ("Voice 2", "Two weeks. We found out about the mountain trains only after we arrived!",
                 "Две недели. Мы узнали о горных поездах только после приезда!"),
                ("What does Voice 1 ask next?", [
                    ("What happened after you found out about them?", True),
                    ("What happens after you found it tomorrow?", False),
                    ("Is the trip asking about the trains?", False)])]),
            "d": ("How come...?", "A friendly way to ask why something happened",
                  ["A polite way to ask for the time", "A formal way to end a conversation"]),
            "lw": ("How ___ have you known each other?", "How long have you known each other?",
                   "long", ["much", "many"]),
            "mw": ("I still do not know the ___ why he called.", "reason", "re"),
            "ch": ([("Friend", "Did you ask her about the concert?")], "You",
                   "Yes — it turned out she has never been to one, so we are going together.",
                   ["I asked her yesterday tomorrow.", "The concert is asking her."]),
        },
        {
            "t": ("Вопросы о планах", "Questions About Plans"),
            "o": ("Понимать вопросы о будущем и уточнять детали.",
                  "Understand future questions and clarify details."),
            "v": [("What about you?", "А ты?"), ("to be planning to", "планировать"),
                  ("more specific", "конкретнее"), ("either way", "в любом случае"),
                  ("to make sure", "убедиться"), ("to depend on", "зависеть от"),
                  ("as well", "тоже")],
            "q": ("Which question asks about a future plan politely?",
                  "Are you planning to stay for the dinner as well?",
                  ["You are planning stay yesterday dinner?", "Is the dinner planning you as well?"]),
            "tr": ("Поедешь ли ты летом к морю, зависит от работы или от денег?",
                   "Whether you go to the sea in summer — does it depend on work or on money?",
                   ["did", "went", "yesterday"]),
            "fill": ("Could you be ___ specific about the dates?", "more",
                     ["most", "much"], "Можешь быть конкретнее насчёт дат?"),
            "tap": ("Are you planning to move as well?", ["was", "did"]),
            "sh": ("Are you planning to join us on Saturday? It depends on the weather, I know, but either way let me know by Thursday.",
                   "Ты планируешь присоединиться в субботу? Я знаю, всё зависит от погоды, но в любом случае дай знать до четверга."),
            "st": ("Clarifying a Plan", [
                ("Voice 1", "Are you planning to take the early train on Friday?", "Ты планируешь ехать ранним поездом в пятницу?"),
                ("Voice 2", "Probably. Why — are you going the same way?", "Наверное. А что — ты едешь тем же маршрутом?"),
                ("What does Voice 1 say?", [
                    ("Yes, so let's make sure we book seats together.", True),
                    ("Yes, we booked together yesterday tomorrow.", False),
                    ("The train is planning us both.", False)])]),
            "d": ("either way", "Used when both possibilities lead to the same result",
                  ["A phrase for counting two things together", "A way to say you disagree politely"]),
            "lw": ("Are you ___ to stay for lunch?", "Are you planning to stay for lunch?",
                   "planning", ["plan", "planned"]),
            "mw": ("It ___ on the traffic, unfortunately.", "depends", "de"),
            "ch": ([("Friend", "What are you doing this weekend?")], "You",
                   "Nothing special — what about you? If you are free, we could try the new climbing wall.",
                   ["I did it yesterday tomorrow.", "The weekend is doing me."]),
        },
        {
            "t": ("Уточняющие вопросы", "Follow-up Questions"),
            "o": ("Понимать уточняющие вопросы, используя should и первое условное.",
                  "Understand follow-up questions using should and the first conditional."),
            "v": [("to mean", "иметь в виду"), ("to check", "уточнить"),
                  ("correct me if I'm wrong", "поправь, если я не прав"), ("in other words", "другими словами"),
                  ("to sum up", "подытожить"), ("to make sense", "иметь смысл"),
                  ("exactly", "именно")],
            "q": ("Which phrase checks understanding politely?",
                  "So, in other words, the meeting has moved to Friday?",
                  ["So the meeting moved yesterday Friday, yes?", "In other words is the meeting Friday yesterday?"]),
            "tr": ("Если я правильно понял, ты остаёшься ещё на неделю?",
                   "Correct me if I am wrong — you are staying for one more week?",
                   ["did", "understood", "yesterday"]),
            "fill": ("If the plan ___ sense, let's start tomorrow.", "makes",
                     ["will make", "made"], "Если план имеет смысл, начнём завтра."),
            "tap": ("To sum up, we should wait for the final answer.", ["mustn't", "went"]),
            "sh": ("Let me check if I understood you: if we order today, the delivery comes on Thursday — is that exactly what you mean?",
                   "Позволь уточнить: если закажем сегодня, доставка придёт в четверг — именно это ты имеешь в виду?"),
            "st": ("Checking the Details", [
                ("Voice 1", "So we should send the draft to the client, in other words?", "Итак, нам следует отправить черновик клиенту, другими словами?"),
                ("Voice 2", "Not exactly — we should wait for the designer's final version first.",
                 "Не совсем — сначала стоит дождаться финальной версии от дизайнера."),
                ("What does Voice 1 ask?", [
                    ("Ah, I see. So if the version comes today, we send it this evening?", True),
                    ("So we sent it yesterday evening already?", False),
                    ("Is the designer wording the client?", False)])]),
            "d": ("to make sense", "To be clear and logical",
                  ["To be strange and difficult to understand", "To cost too much money"]),
            "lw": ("If I ___ you correctly, we start on Monday.", "If I understood you correctly, we start on Monday.",
                   "understood", ["understand", "understanding"]),
            "mw": ("To ___ up, we all agree.", "sum", "su"),
            "ch": ([("Friend", "So the party starts at nine, right?")], "You",
                   "Exactly — and if you bring the salad, I will handle the drinks.",
                   ["It started yesterday tomorrow.", "The party is nining us."]),
        },
    ],

    "A2_LISTENING_SHADOWING_RESTAURANT_CONVERSATIONS": [
        {
            "t": ("За столом на этой неделе", "At the Table This Week"),
            "o": ("Понимать разговоры в ресторане, используя past simple и present perfect.",
                  "Understand restaurant talk using past simple and present perfect."),
            "v": [("to be starving", "умирать с голоду"), ("to order", "заказать"),
                  ("to recommend", "порекомендовать"), ("special of the day", "блюдо дня"),
                  ("rare / medium / well-done", "с кровью / средне / прожарено"),
                  ("to book a table", "забронировать столик"), ("starter", "закуска")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "We have already ordered the starters.",
                  ["We have ordered them yesterday.", "We order starters already now."]),
            "tr": ("Я был так голоден, что взял и закуску, и блюдо дня.",
                   "I was so starving that I ordered both a starter and the special of the day.",
                   ["did", "be", "tomorrow"]),
            "fill": ("The waiter ___ the fish of the day last time we came.", "recommended",
                     ["has recommend", "recommending"], "Официант порекомендовал рыбу дня в прошлый раз."),
            "tap": ("Have you booked a table for Saturday?", ["was", "did"]),
            "sh": ("We have booked a table by the window, and the waiter has just brought the menu — the special today is grilled salmon.",
                   "Мы забронировали столик у окна, и официант только что принёс меню — блюдо дня лосось на гриле."),
            "st": ("Ordering Dinner", [
                ("Waiter", "Are you ready to order, or do you need a few more minutes?",
                 "Вы готовы заказать или вам нужно ещё пару минут?"),
                ("Guest", "Almost. What is the special of the day?", "Почти. Что у вас блюдо дня?"),
                ("What does the waiter say?", [
                    ("Grilled salmon with vegetables — our chef has prepared it since morning.", True),
                    ("The salmon grilled itself yesterday.", False),
                    ("The special is ordering the guests.", False)])]),
            "d": ("special of the day", "A dish the restaurant offers only today",
                  ["A dish that is always on the menu", "A discount on all drinks this week"]),
            "lw": ("I have ___ a table for four.", "I have booked a table for four.",
                   "booked", ["book", "booking"]),
            "mw": ("I would like my steak ___ , please.", "medium", "me"),
            "ch": ([("Waiter", "How would you like your steak?")], "You",
                   "Medium, please — last time well-done was too dry for me.",
                   ["I liked it yesterday tomorrow.", "The steak is doing me."]),
        },
        {
            "t": ("Куда пойдём в пятницу", "Where We Will Go on Friday"),
            "o": ("Сравнить рестораны и спланировать ужин.",
                  "Compare restaurants and plan a dinner."),
            "v": [("more affordable", "дешевле (по карману)"), ("portions", "порции"),
                  ("to split the bill", "разделить счёт"), ("quieter", "тише"),
                  ("vegetarian options", "вегетарианские позиции"), ("to try out", "попробовать (новое место)"),
                  ("busy", "оживлённый (людный)")],
            "q": ("Which sentence compares two restaurants correctly?",
                  "The new place is more affordable than the one on the square.",
                  ["The new place is affordabler than that one.", "The place is most affordable than square."]),
            "tr": ("Мы собираемся попробовать новое место — порции там больше, а цены ниже.",
                   "We are going to try out a new place — the portions are bigger and the prices are lower.",
                   ["did", "tried", "yesterday"]),
            "fill": ("The corner cafe is ___ than the chain one.", "quieter",
                     ["quietest", "more quiet"], "Угловое кафе тише сетевого."),
            "tap": ("They are going to split the bill as usual.", ["was", "did"]),
            "sh": ("If we arrive before seven, the kitchen will be less busy and we will get the table by the window.",
                   "Если прийти до семи, кухня будет менее загружена, и мы получим столик у окна."),
            "st": ("Friday Dinner", [
                ("Voice 1", "Should we try the new Thai place on Friday?", "Попробовать новое тайское место в пятницу?"),
                ("Voice 2", "I have read the reviews. It is busier but cheaper than our usual one.",
                 "Я читал отзывы. Там люднее, но дешевле нашего обычного."),
                ("What does Voice 1 say?", [
                    ("Then let's book early — do they have vegetarian options?", True),
                    ("Then we booked it yesterday tomorrow.", False),
                    ("Is the Thai place reading us reviews?", False)])]),
            "d": ("to split the bill", "Each person pays their own part of the bill",
                  ["One person pays the whole bill", "The restaurant gives a discount for groups"]),
            "lw": ("We are going to ___ the bill.", "We are going to split the bill.",
                   "split", ["splitted", "splitting"]),
            "mw": ("Home cooking is ___ affordable.", "more", "mo"),
            "ch": ([("Friend", "Shall we invite the whole team?")], "You",
                   "Why not — if we book the long table, they will even bring the birthday dessert for free.",
                   ["I invited them yesterday tomorrow.", "The team is dining us."]),
        },
        {
            "t": ("Если еда пришла не той", "If the Dish Comes Wrong"),
            "o": ("Понимать решение проблем в ресторане, используя should и первое условное.",
                  "Understand solving restaurant problems using should and the first conditional."),
            "v": [("to complain", "пожаловаться"), ("to send back", "вернуть (блюдо)"),
                  ("cold", "холодный (о еде)"), ("to make a mistake", "ошибиться"),
                  ("on the house", "за счёт заведения"), ("apology", "извинение"),
                  ("tip", "чаевые")],
            "q": ("Which sentence gives correct restaurant advice?",
                  "You should complain politely if the dish is cold.",
                  ["You should to complain it yesterday.", "You must complaining last dinner."]),
            "tr": ("Если блюдо принесли холодным, вежливо верните его — повар переделает.",
                   "If the dish arrives cold, you should send it back politely — the chef will remake it.",
                   ["did", "arrived", "yesterday"]),
            "fill": ("If the waiter ___ a mistake, the dessert will be on the house.",
                     "made", ["will make", "makes"], "Если официант ошибся, десерт будет за счёт заведения."),
            "tap": ("You should still leave a tip if they fixed the problem.", ["mustn't", "went"]),
            "sh": ("If you send the dish back calmly and explain the problem, the staff will respect you and fix it faster.",
                   "Если спокойно вернуть блюдо и объяснить проблему, персонал отнесётся с уважением и исправит быстрее."),
            "st": ("The Cold Soup", [
                ("Guest", "Excuse me, the soup is cold — could you warm it up?", "Извините, суп холодный — можно его подогреть?"),
                ("Waiter", "I am terribly sorry. I will take it back right away.", "Мне очень жаль. Я сразу заберу его."),
                ("What might the waiter add?", [
                    ("And your coffee will be on the house, of course.", True),
                    ("And your coffee was on the house yesterday.", False),
                    ("The soup is warming the kitchen up.", False)])]),
            "d": ("on the house", "Given free by the restaurant",
                  ["Cooked at home before the dinner", "The most expensive dish on the menu"]),
            "lw": ("If the order is wrong, ___ it back.", "If the order is wrong, send it back.",
                   "send", ["will send", "sent"]),
            "mw": ("They made a ___ with our table.", "mistake", "mi"),
            "ch": ([("Friend", "They forgot my whole main course!")], "You",
                   "Call the waiter — if you ask now, it will still arrive before our desserts.",
                   ["He forgot it yesterday tomorrow.", "The course is forgetting us."]),
        },
    ],

    "A2_LISTENING_SHADOWING_ROUTINES_AND_RECENT_CHANGES": [
        {
            "t": ("Что изменилось в режиме", "What Has Changed in the Routine"),
            "o": ("Понимать рассказы об изменениях режима, используя past simple и present perfect.",
                  "Understand routine changes using past simple and present perfect."),
            "v": [("to switch to", "переключиться на"), ("daily routine", "ежедневный режим"),
                  ("to work from home", "работать из дома"), ("used to", "раньше"),
                  ("to give up", "отказаться от"), ("schedule", "расписание"),
                  ("noticeable", "заметный")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have switched to morning workouts this month.",
                  ["I have switched to them last month.", "I switch to workouts already this month."]),
            "tr": ("Раньше я работал из офиса, а теперь перешёл на удалёнку.",
                   "I used to work from the office, but now I have switched to working from home.",
                   ["did", "use", "tomorrow"]),
            "fill": ("Last spring she ___ up her evening coffee.", "gave",
                     ["has give", "giving"], "Прошлой весной она отказалась от вечернего кофе."),
            "tap": ("The change in his schedule has been noticeable.", ["was", "did"]),
            "sh": ("I used to start my day with news scrolling, but I have given it up, and my mornings have become much calmer.",
                   "Раньше я начинал день с ленты новостей, но отказался от этого, и мои утра стали гораздо спокойнее."),
            "st": ("New Schedule", [
                ("Voice 1", "You are at the gym so early these days!", "Ты в последнее время так рано в зале!"),
                ("Voice 2", "Yes, I have switched to morning sessions — my evenings are free now.",
                 "Да, я перешёл на утренние тренировки — вечера теперь свободны."),
                ("What does Voice 1 ask?", [
                    ("How long have you kept the new routine?", True),
                    ("How long did you kept it tomorrow?", False),
                    ("Is the gym switching you mornings?", False)])]),
            "d": ("noticeable", "Easy to see or feel",
                  ["Very small and hard to see", "Hidden behind other changes"]),
            "lw": ("I have ___ to a new schedule.", "I have switched to a new schedule.",
                   "switched", ["switch", "switching"]),
            "mw": ("She used ___ work evenings.", "to", "to"),
            "ch": ([("Friend", "Do you still commute every day?")], "You",
                   "No — I have been working from home since spring, and it has changed everything.",
                   ["I commuted yesterday tomorrow.", "The commute is homing me."]),
        },
        {
            "t": ("Новый режим с месяца", "A New Regime From This Month"),
            "o": ("Понимать планы изменения режима и сравнивать расписания.",
                  "Understand routine plans and compare schedules."),
            "v": [("to adjust", "подстроить"), ("more balanced", "сбалансированнее"),
                  ("sleep pattern", "режим сна"), ("to squeeze in", "втиснуть (в расписание)"),
                  ("flexible", "гибкий"), ("time slot", "временной слот"),
                  ("earlier", "раньше")],
            "q": ("Which sentence compares two schedules correctly?",
                  "The new timetable is more balanced than the old one.",
                  ["The new timetable is balanceder than old.", "The timetable is most balanced than old."]),
            "tr": ("С этого месяца я собираюсь вставать раньше и втискивать спорт до работы.",
                   "From this month I am going to get up earlier and squeeze in some sport before work.",
                   ["did", "got", "yesterday"]),
            "fill": ("A flexible schedule is ___ for parents.", "better",
                     ["best", "more good"], "Гибкий график лучше для родителей."),
            "tap": ("We are going to adjust our sleep patterns.", ["was", "did"]),
            "sh": ("If I move my time slot to the morning, my afternoons will be calmer and I will sleep better.",
                   "Если перенести мой слот на утро, вечера будут спокойнее, и я стану лучше спать."),
            "st": ("Adjusting the Day", [
                ("Voice 1", "How are you going to fit in the course with your job?", "Как ты впишешь курс в график с работой?"),
                ("Voice 2", "I am going to use the morning slot — seven to eight, before the office.",
                 "Собираюсь занять утренний слот — с семи до восьми, до офиса."),
                ("What does Voice 1 say?", [
                    ("That sounds more balanced than evening classes.", True),
                    ("It sounded balanced yesterday tomorrow.", False),
                    ("The course is slotting your job.", False)])]),
            "d": ("to squeeze in", "To find time for something in a busy day",
                  ["To cancel an activity to free your evening", "To make your lunch break longer"]),
            "lw": ("I am going to ___ in a walk at lunch.", "I am going to squeeze in a walk at lunch.",
                   "squeeze", ["squeezed", "squeezing"]),
            "mw": ("Mornings are ___ for me than evenings.", "easier", "ea"),
            "ch": ([("Friend", "When will you start the new routine?")], "You",
                   "Next week — if I prepare everything on Sunday, Monday will be easy.",
                   ["I started it yesterday tomorrow.", "The routine is starting me."]),
        },
        {
            "t": ("Если режим не работает", "If the Routine Does Not Work"),
            "o": ("Понимать советы о режиме дня, используя should и первое условное.",
                  "Understand routine advice using should and the first conditional."),
            "v": [("to stick to", "придерживаться"), ("to slip back", "скатиться обратно (к старому)"),
                  ("willpower", "сила воли"), ("reminder", "напоминание"),
                  ("small win", "маленькая победа"), ("to give up", "бросить"),
                  ("consistently", "последовательно")],
            "q": ("Which sentence gives correct routine advice?",
                  "You should stick to the same time every day.",
                  ["You should to stick it yesterday.", "You must sticking same time last week."]),
            "tr": ("Если ты будешь следовать режиму последовательно, срывов станет меньше.",
                   "If you follow the routine consistently, you will slip back less often.",
                   ["did", "followed", "yesterday"]),
            "fill": ("If you miss a day, just ___ the next one.", "continue",
                     ["will continue", "continued"], "Если пропустил день, просто продолжай со следующего."),
            "tap": ("You should count every small win.", ["mustn't", "went"]),
            "sh": ("If you set a reminder for the first month, the routine will become a habit before your willpower runs out.",
                   "Если поставить напоминание на первый месяц, режим станет привычкой до того, как закончится сила воли."),
            "st": ("The Slipped Week", [
                ("Voice 1", "I slipped back into late nights last week.", "На прошлой неделе я снова скатился в поздние отбои."),
                ("Voice 2", "It happens. What should you change?", "Бывает. Что стоит изменить?"),
                ("What is the good advice?", [
                    ("Set an evening reminder — it has helped me a lot.", True),
                    ("You must set it yesterday already.", False),
                    ("The late nights are slipping you back.", False)])]),
            "d": ("consistently", "In the same regular way over time",
                  ["Only on Mondays and holidays", "Whenever you feel like it"]),
            "lw": ("If you ___ to the plan, results will come.", "If you stick to the plan, results will come.",
                   "stick", ["will stick", "stuck"]),
            "mw": ("Every ___ win counts.", "small", "sm"),
            "ch": ([("Friend", "I keep breaking my evening routine.")], "You",
                   "Make it smaller — if the routine takes ten minutes, you will rarely skip it.",
                   ["I broke it yesterday tomorrow.", "The routine is breaking me."]),
        },
    ],

    "A2_LISTENING_SHADOWING_SCHEDULES_AND_ARRANGEMENTS": [
        {
            "t": ("Наши договорённости", "Our Arrangements"),
            "o": ("Понимать договорённости, используя present continuous и present perfect.",
                  "Understand arrangements using present continuous and present perfect."),
            "v": [("to make an appointment", "договориться о встрече"), ("to reschedule", "перенести"),
                  ("to confirm", "подтвердить"), ("agenda", "повестка"),
                  ("to pencil in", "предварительно записать (в график)"), ("double booking", "двойное бронирование"),
                  ("calendar", "календарь")],
            "q": ("Which sentence uses the present continuous for an arrangement?",
                  "We are seeing the accountant at eleven on Tuesday.",
                  ["We see the accountant yesterday at eleven.", "We has seen them tomorrow already."]),
            "tr": ("Я перенёс встречу с зубным на четверг, потому что получилось двойное бронирование.",
                   "I rescheduled the dentist appointment to Thursday because of a double booking.",
                   ["did", "reschedule", "tomorrow"]),
            "fill": ("She has ___ the meeting in her calendar.", "pencilled in",
                     ["pencil in", "pencilling in"], "Она предварительно записала встречу в календарь."),
            "tap": ("We are meeting the investors on Friday.", ["was", "did"]),
            "sh": ("I have pencilled in a call for Wednesday, but if the agenda is not ready, we can reschedule to next week.",
                   "Я предварительно записал звонок на среду, но если повестка не будет готова, перенесём на следующую неделю."),
            "st": ("The Double Booking", [
                ("Voice 1", "Are we still on for lunch on Thursday?", "Мы всё ещё встречаемся на обед в четверг?"),
                ("Voice 2", "Ah — I have double-booked myself. Could we move to Friday?",
                 "Ох — у меня двойное бронирование. Можем перенести на пятницу?"),
                ("What does Voice 1 answer?", [
                    ("Friday works — let me confirm in the evening.", True),
                    ("Friday worked yesterday already.", False),
                    ("The lunch is booking myself on Friday.", False)])]),
            "d": ("to pencil in", "To add something to your diary, not finally",
                  ["To cancel a plan completely", "To confirm a booking with a payment"]),
            "lw": ("I have ___ the dentist to Monday.", "I have moved the dentist to Monday.",
                   "moved", ["move", "moving"]),
            "mw": ("We are ___ the lawyer at three.", "seeing", "se"),
            "ch": ([("Friend", "Is our Friday plan still on?")], "You",
                   "Yes — I have confirmed the table, and I am picking you up at seven.",
                   ["I confirmed it yesterday tomorrow.", "Friday is planning us."]),
        },
        {
            "t": ("Расписание на следующую неделю", "Next Week's Timetable"),
            "o": ("Планировать неделю и сравнивать расписания.",
                  "Plan the week and compare schedules."),
            "v": [("time block", "блок времени"), ("back-to-back", "подряд (один за другим)"),
                  ("more productive", "продуктивнее"), ("to leave a gap", "оставить окно"),
                  ("busier", "занятее"), ("to plan ahead", "планировать заранее"),
                  ("buffer", "буфер (запас времени)")],
            "q": ("Which sentence compares two schedules correctly?",
                  "Tuesday is busier than Monday this week.",
                  ["Tuesday is busierest than Monday.", "Tuesday is most busy than Monday."]),
            "tr": ("В среду у меня три встречи подряд, поэтому я оставлю окно в обед.",
                   "On Wednesday I have three back-to-back meetings, so I am going to leave a gap at lunch.",
                   ["did", "had", "yesterday"]),
            "fill": ("Short breaks are ___ important than the meetings themselves.", "just as",
                     ["more most", "much as"], "Короткие перерывы так же важны, как сами встречи."),
            "tap": ("We are going to plan the trip ahead this time.", ["was", "did"]),
            "sh": ("If you leave a buffer between the calls, the day will be calmer and you will finish on time.",
                   "Если оставлять буфер между звонками, день пройдёт спокойнее, и вы закончите вовремя."),
            "st": ("A Busy Wednesday", [
                ("Voice 1", "How does Wednesday look for the workshop?", "Как среда выглядит для воркшопа?"),
                ("Voice 2", "Busy — three calls back-to-back. But the afternoon has a gap.",
                 "Занята — три звонка подряд. Но во второй половине есть окно."),
                ("What does Voice 1 suggest?", [
                    ("Then let's put the workshop into that time block.", True),
                    ("Then we put it yesterday tomorrow.", False),
                    ("The Wednesday is workshoping the calls.", False)])]),
            "d": ("back-to-back", "One directly after another with no break",
                  ["Planned with long breaks between", "Spread across different weeks"]),
            "lw": ("I am going to ___ ahead for December.", "I am going to plan ahead for December.",
                   "plan", ["planned", "planning"]),
            "mw": ("Mornings are ___ productive for me.", "more", "mo"),
            "ch": ([("Friend", "Can we meet early next week?")], "You",
                   "Let's see — if I move the Monday block, Tuesday morning will open up.",
                   ["We met yesterday tomorrow.", "The week is meeting us early."]),
        },
        {
            "t": ("Если планы рухнут", "If the Plans Fall Apart"),
            "o": ("Понимать обсуждение переносов, используя should и первое условное.",
                  "Understand rescheduling talks using should and the first conditional."),
            "v": [("to fall through", "сорваться (о планах)"), ("plan B", "запасной план"),
                  ("to inform", "известить"), ("last-minute", "в последний момент"),
                  ("to wait for", "ждать (подтверждения)"), ("priority", "приоритет"),
                  ("as a backup", "как запасной вариант")],
            "q": ("Which sentence gives correct advice about plans?",
                  "You should have a plan B for outdoor events.",
                  ["You should to have plan B yesterday.", "You must having plan B last event."]),
            "tr": ("Если пикник сорвётся в последний момент, у нас будет план Б.",
                   "If the picnic falls through at the last minute, we will have a plan B.",
                   ["did", "fell", "yesterday"]),
            "fill": ("If the client ___ the meeting, we will use the time for the report.",
                     "cancels", ["will cancel", "cancelled"], "Если клиент отменит встречу, потратим время на отчёт."),
            "tap": ("You should inform everyone about the change at once.", ["mustn't", "went"]),
            "sh": ("If the flights fall through, the train is our backup — it takes longer, but it is more reliable in winter.",
                   "Если сорвутся перелёты, поезд — наш запасной вариант: он дольше, но зимой надёжнее."),
            "st": ("The Cancelled Visit", [
                ("Voice 1", "The client visit has fallen through for Thursday.", "Визит клиента на четверг сорвался."),
                ("Voice 2", "Last minute again? What should we do with the booked room?", "Опять в последний момент? Что делать с забронированным залом?"),
                ("What does Voice 1 propose?", [
                    ("Let's use it for the team workshop as a backup.", True),
                    ("We used it yesterday tomorrow already.", False),
                    ("The room is falling through the visit.", False)])]),
            "d": ("to fall through", "To fail to happen as planned",
                  ["To happen exactly as planned", "To be postponed by one hour only"]),
            "lw": ("If the event ___ through, we will stay home.", "If the event falls through, we will stay home.",
                   "falls", ["will fall", "fell"]),
            "mw": ("You should keep Friday ___ a backup.", "as", "as"),
            "ch": ([("Friend", "Our speaker just cancelled!")], "You",
                   "Keep calm — if we split her talk into two shorter ones, the agenda will survive.",
                   ["She cancelled yesterday tomorrow.", "The talk is cancelling us."]),
        },
    ],

    "A2_LISTENING_SHADOWING_SHOPPING_AND_SERVICE_CONVERSATIONS": [
        {
            "t": ("Покупки и сервис", "Shopping and Service"),
            "o": ("Понимать сервисные разговоры, используя past simple и present perfect.",
                  "Understand service conversations using past simple and present perfect."),
            "v": [("to pay by card", "платить картой"), ("loyalty card", "карта лояльности"),
                  ("to ask for a refund", "попросить возврат"), ("out of stock", "нет в наличии"),
                  ("to order in", "заказать (под заказ)"), ("receipt", "чек"),
                  ("to try on", "примерить")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The shampoo has been out of stock since Friday.",
                  ["The shampoo is out of stock yesterday.", "The shampoo out of stock already since Friday."]),
            "tr": ("Я попросил возврат, потому что зарядка перестала работать через неделю.",
                   "I asked for a refund because the charger stopped working after a week.",
                   ["did", "ask", "tomorrow"]),
            "fill": ("She tried on the dress and ___ it immediately.", "bought",
                     ["has buy", "buying"], "Она примерила платье и сразу купила."),
            "tap": ("Have you shown your loyalty card?", ["was", "did"]),
            "sh": ("I have forgotten my loyalty card, but the cashier has found my number by phone and applied the discount.",
                   "Я забыл карту лояльности, но кассир нашёл мой номер по телефону и применил скидку."),
            "st": ("At the Checkout", [
                ("Cashier", "Would you like to pay by card or cash?", "Будете платить картой или наличными?"),
                ("Customer", "Card, please. And could you check my loyalty points?", "Картой. И можно проверить мои бонусные баллы?"),
                ("What does the cashier say?", [
                    ("You have collected two hundred points — that is ten euros off.", True),
                    ("You collected them yesterday tomorrow.", False),
                    ("The points are paying by card.", False)])]),
            "d": ("loyalty card", "A shop card that gives you points or discounts",
                  ["A bank card for online payments", "A gift card bought for a friend"]),
            "lw": ("I have ___ for a refund at the desk.", "I have asked for a refund at the desk.",
                   "asked", ["ask", "asking"]),
            "mw": ("Can I pay ___ card?", "by", "by"),
            "ch": ([("Assistant", "The blue one is out of stock, I'm afraid.")], "You",
                   "Could you order it in? I have waited for this model since autumn.",
                   ["You ordered it yesterday tomorrow.", "The model is stocking me."]),
        },
        {
            "t": ("Выбираем услугу", "Choosing a Service"),
            "o": ("Сравнивать услуги и планировать покупку.",
                  "Compare services and plan a purchase."),
            "v": [("package deal", "пакетное предложение"), ("more flexible", "гибче"),
                  ("subscription", "подписка"), ("to compare offers", "сравнить предложения"),
                  ("hidden fee", "скрытый платёж"), ("more suitable", "подходящeе (более)"),
                  ("to sign up", "оформить (подписку)")],
            "q": ("Which sentence compares two offers correctly?",
                  "The yearly subscription is more flexible than the monthly one.",
                  ["The yearly one is flexibler than monthly.", "The subscription is most flexible than monthly."]),
            "tr": ("Мы собираемся оформить годовую подписку — так выходит на треть дешевле.",
                   "We are going to sign up for the yearly subscription — it works out a third cheaper.",
                   ["did", "signed", "yesterday"]),
            "fill": ("This plan is ___ for students than the business one.", "more suitable",
                     ["most suitable", "much suitable"], "Этот тариф больше подходит студентам, чем бизнес-тариф."),
            "tap": ("They are going to compare three offers before deciding.", ["was", "did"]),
            "sh": ("If you read the small print, you will spot the hidden fees before signing up.",
                   "Если прочитать мелкий шрифт, найдёте скрытые платежи до оформления."),
            "st": ("Choosing a Gym Plan", [
                ("Voice 1", "There is a package deal — gym plus pool for one price.", "Есть пакет — зал плюс бассейн за одну цену."),
                ("Voice 2", "Sounds good, but is it more flexible than the basic plan?", "Звучит неплохо, но это гибче базового плана?"),
                ("What does Voice 1 say?", [
                    ("Less flexible, but cheaper if you go twice a week.", True),
                    ("It was flexible yesterday tomorrow.", False),
                    ("The pool is packaging the gym.", False)])]),
            "d": ("hidden fee", "A charge you do not expect at first",
                  ["The price written on the main page", "A discount for the first month"]),
            "lw": ("We are going to ___ for the basic plan.", "We are going to sign up for the basic plan.",
                   "sign up", ["signed up", "signing up"]),
            "mw": ("The family plan is ___ expensive per person.", "less", "le"),
            "ch": ([("Assistant", "Would you like the package with insurance?")], "You",
                   "Let me compare offers first — if the insurance is in the basic one, I will skip it.",
                   ["I compared them yesterday tomorrow.", "The package is insuring me."]),
        },
        {
            "t": ("Если сервис подвёл", "If the Service Fails"),
            "o": ("Понимать жалобы и решения, используя should и первое условное.",
                  "Understand complaints and solutions using should and the first conditional."),
            "v": [("to charge too much", "списать слишком много"), ("to sort out", "разобраться с"),
                  ("refund", "возврат средств"), ("to insist on", "настаивать на"),
                  ("compensation", "компенсация"), ("politely but firmly", "вежливо, но твёрдо"),
                  ("manager", "менеджер")],
            "q": ("Which sentence gives correct advice?",
                  "You should ask for the manager if the staff cannot help.",
                  ["You should to ask him yesterday.", "You must asking manager last time."]),
            "tr": ("Если с тебя списали лишнее, вежливо, но твёрдо попроси возврат.",
                   "If they have charged you too much, you should politely but firmly ask for a refund.",
                   ["did", "charged", "yesterday"]),
            "fill": ("If the refund does not arrive in a week, ___ on speaking to the manager.",
                     "insist", ["will insist", "insisted"], "Если возврат не придёт за неделю, настаивай на разговоре с менеджером."),
            "tap": ("You should keep the receipt as proof.", ["mustn't", "went"]),
            "sh": ("If you explain the mistake calmly, they will sort it out on the spot in most cases.",
                   "Если спокойно объяснить ошибку, в большинстве случаев её решат на месте."),
            "st": ("The Double Charge", [
                ("Customer", "I think you have charged me twice for the same item.", "Кажется, вы дважды списали одну и ту же позицию."),
                ("Assistant", "Let me check... You are right, I am sorry. I will sort it out now.",
                 "Сейчас проверю... Вы правы, извините. Сейчас всё исправлю."),
                ("What does the customer ask?", [
                    ("Could I get the refund to the same card, please?", True),
                    ("Did I get the refund tomorrow yesterday?", False),
                    ("Is the item charging me twice itself?", False)])]),
            "d": ("compensation", "Something given to make up for a mistake",
                  ["An extra item you buy at full price", "A thank-you letter with no offer"]),
            "lw": ("If they ___ too much, ask for a refund.", "If they charge too much, ask for a refund.",
                   "charge", ["will charge", "charged"]),
            "mw": ("You should insist ___ your rights.", "on", "on"),
            "ch": ([("Friend", "The dry cleaner lost my shirt!")], "You",
                   "Take the receipt — if you show it, they will offer compensation today.",
                   ["They lost it yesterday tomorrow.", "The shirt is drying me."]),
        },
    ],
}
