#!/usr/bin/env python3
"""A2 regenerated content: STUDY (10 tracks x 3 lessons).

Grammar arc per topic: L1 past simple + present perfect,
L2 future forms + comparatives, L3 modals / first conditional.
"""

TRACKS = {
    "A2_STUDY_CLASSROOM_DISCUSSIONS": [
        {
            "t": ("Что мы обсудили", "What We Discussed"),
            "o": ("Рассказать о дискуссии на занятии, используя past simple и present perfect.",
                  "Talk about a class discussion using past simple and present perfect."),
            "v": [("to express an opinion", "выразить мнение"), ("to agree with", "согласиться с"),
                  ("point of view", "точка зрения"), ("to interrupt", "перебить"),
                  ("argument", "аргумент"), ("to take part in", "принять участие в"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "We have discussed three topics so far today.",
                  ["We have discussed three topics yesterday.", "We discuss three topics already so far."]),
            "tr": ("Я выразил свою точку зрения, а потом согласился с аргументом однокурсницы.",
                   "I expressed my point of view and then agreed with my classmate's argument.",
                   ["did", "express", "tomorrow"]),
            "fill": ("Yesterday she ___ with the professor for the first time.", "disagreed",
                     ["has disagree", "disagreeing"], "Вчера она впервые не согласилась с профессором."),
            "tap": ("Two students have already taken part in the debate.", ["was", "did"]),
            "sh": ("We have had a lively discussion today: everyone expressed an opinion, and nobody interrupted anyone.",
                   "У нас сегодня прошла оживлённая дискуссия: каждый выразил мнение, и никто никого не перебивал."),
            "st": ("After the Seminar", [
                ("Voice 1", "Did you take part in the discussion about remote learning?", "Ты участвовал в дискуссии про дистанционное обучение?"),
                ("Voice 2", "Yes! It was the best seminar we have had so far.", "Да! Это лучший семинар, что у нас был."),
                ("What does Voice 1 ask?", [
                    ("Whose argument did you find the strongest?", True),
                    ("Whose argument have you found tomorrow?", False),
                    ("Is the seminar discussing you?", False)])]),
            "d": ("point of view", "A person's own opinion about something",
                  ["A fact that everyone knows is true", "A question the teacher asks the class"]),
            "lw": ("I have ___ my opinion twice today.", "I have expressed my opinion twice today.",
                   "expressed", ["express", "expressing"]),
            "mw": ("She agreed ___ his argument.", "with", "wi"),
            "ch": ([("Classmate", "The discussion moved so fast!")], "You",
                   "I know — I have written down three ideas I want to reuse in my essay.",
                   ["I write them yesterday tomorrow.", "The discussion is essaying me."]),
        },
        {
            "t": ("Дискуссия на следующей неделе", "Next Week's Discussion"),
            "o": ("Подготовиться к дискуссии и сравнить форматы занятий.",
                  "Prepare for a discussion and compare class formats."),
            "v": [("debate", "дебаты"), ("more engaging", "захватывающий (более)"),
                  ("to prepare arguments", "подготовить аргументы"), ("to lead a discussion", "вести дискуссию"),
                  ("to split into groups", "разделиться на группы"), ("online forum", "онлайн-форум"),
                  ("in advance", "заранее")],
            "q": ("Which sentence compares two class formats correctly?",
                  "Small-group debates are more engaging than lectures.",
                  ["Debates are engager than lectures.", "Debates are most engaging than lectures."]),
            "tr": ("На следующей неделе мы собираемся провести дебаты о социальных сетях.",
                   "Next week we are going to have a debate about social media.",
                   ["did", "had", "yesterday"]),
            "fill": ("Reading the text ___ advance makes the discussion easier.", "in",
                     ["at", "on"], "Прочитать текст заранее делает дискуссию легче."),
            "tap": ("We are going to split into two groups.", ["was", "did"]),
            "sh": ("If you prepare two arguments in advance, you will feel much calmer during the debate.",
                   "Если заранее подготовить два аргумента, на дебатах будет гораздо спокойнее."),
            "st": ("Preparing for a Debate", [
                ("Voice 1", "The debate is on Thursday. How are you preparing?", "Дебаты в четверг. Как ты готовишься?"),
                ("Voice 2", "I have collected three arguments and will practise with a friend tonight.",
                 "Я собрал три аргумента и сегодня вечером потренируюсь с другом."),
                ("What does Voice 1 offer?", [
                    ("Our group is meeting on Wednesday — join us for practice.", True),
                    ("Our group met yesterday tomorrow.", False),
                    ("The debate is preparing your friend.", False)])]),
            "d": ("debate", "A formal discussion where two sides argue different opinions",
                  ["A quiet talk between two friends", "A test with multiple-choice questions"]),
            "lw": ("We are going to ___ into four groups.", "We are going to split into four groups.",
                   "split", ["splitted", "splitting"]),
            "mw": ("Discussions are ___ engaging than lectures.", "more", "mo"),
            "ch": ([("Classmate", "Who will lead the next discussion?")], "You",
                   "Maria — and if she needs help, I am going to be the timekeeper.",
                   ["I led it yesterday tomorrow.", "The discussion is leading Maria."]),
        },
        {
            "t": ("Правила хорошей дискуссии", "Rules of a Good Discussion"),
            "o": ("Объяснить правила дискуссий, используя should и первое условное.",
                  "Explain discussion rules using should and the first conditional."),
            "v": [("to listen actively", "активно слушать"), ("to take turns", "говорить по очереди"),
                  ("respectful", "уважительный"), ("to support", "поддержать (аргументом)"),
                  ("evidence", "доказательство / довод"), ("to raise a hand", "поднять руку"),
                  ("to disagree politely", "вежливо не согласиться")],
            "q": ("Which sentence is a discussion rule?",
                  "You should wait for your turn before speaking.",
                  ["You should to wait your turn yesterday.", "You must waiting turn last class."]),
            "tr": ("Если ты поддержишь мнение примером, аргумент станет убедительнее.",
                   "If you support your opinion with an example, your argument will be more convincing.",
                   ["did", "supported", "yesterday"]),
            "fill": ("If you ___ a claim, bring evidence.", "make",
                     ["will make", "made"], "Если высказываешь утверждение, приводи доводы."),
            "tap": ("You should raise your hand in a big class.", ["mustn't", "went"]),
            "sh": ("If everyone takes turns and listens actively, even a shy student will join the discussion.",
                   "Если все говорят по очереди и активно слушают, даже стеснительный студент включится в дискуссию."),
            "st": ("The Interrupted Speaker", [
                ("Voice 1", "I was interrupted three times during my argument.", "Меня перебивали трижды за время выступления."),
                ("Voice 2", "That is not fair. What should the group do about it?", "Это нечестно. Что группе с этим делать?"),
                ("What is the rule they need?", [
                    ("We should take turns — one speaker at a time.", True),
                    ("We must taking turns yesterday.", False),
                    ("The interruption is speaking me three times.", False)])]),
            "d": ("evidence", "Facts or examples that support an opinion",
                  ["A strong feeling about the topic", "A question you cannot answer"]),
            "lw": ("If you ___ your point, slow down.", "If you make your point, slow down.",
                   "make", ["will make", "made"]),
            "mw": ("Disagree ___ , but do it politely.", "freely", "fr"),
            "ch": ([("Classmate", "I never know when to speak.")], "You",
                   "Raise your hand — if the leader sees you, she will give you the floor right away.",
                   ["I raised it yesterday tomorrow.", "The floor is handing me."]),
        },
    ],

    "A2_STUDY_DICTIONARIES_AND_ONLINE_RESOURCES": [
        {
            "t": ("Как я искал слово", "How I Looked Up a Word"),
            "o": ("Рассказать о работе со словарями, используя past simple и present perfect.",
                  "Talk about using dictionaries using past simple and present perfect."),
            "v": [("to look up", "посмотреть (в словаре)"), ("definition", "определение"),
                  ("example sentence", "пример употребления"), ("pronunciation", "произношение"),
                  ("bilingual dictionary", "двуязычный словарь"), ("to add to favourites", "добавить в избранное"),
                  ("offline mode", "офлайн-режим")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have added twenty words to my favourites this week.",
                  ["I have added twenty words last week.", "I add twenty words already this week."]),
            "tr": ("Я посмотрел определение и сохранил примеры употребления в избранное.",
                   "I looked up the definition and have saved the example sentences to my favourites.",
                   ["did", "look", "tomorrow"]),
            "fill": ("Yesterday the app ___ without internet, in offline mode.", "worked",
                     ["has work", "working"], "Вчера приложение работало без интернета, в офлайн-режиме."),
            "tap": ("She has checked the pronunciation of all new words.", ["was", "did"]),
            "sh": ("The dictionary has shown three different meanings, so I have read the example sentences to choose the right one.",
                   "Словарь показал три разных значения, поэтому я прочитал примеры, чтобы выбрать верное."),
            "st": ("The Confusing Word", [
                ("Voice 1", "What does 'address' mean here — a place or a speech?", "Что значит 'address' здесь — место или речь?"),
                ("Voice 2", "Let me check... The dictionary has two definitions for it.",
                 "Сейчас проверю... В словаре два определения."),
                ("What does Voice 2 advise?", [
                    ("Read the example sentences — they show which meaning fits.", True),
                    ("Read the examples tomorrow yesterday.", False),
                    ("Is the word meaning the dictionary?", False)])]),
            "d": ("definition", "The explanation of what a word means",
                  ["The translation of a word into your language", "The part of speech of a word"]),
            "lw": ("I have ___ up five words today.", "I have looked up five words today.",
                   "looked", ["look", "looking"]),
            "mw": ("Check the ___ in the audio dictionary.", "pronunciation", "pro"),
            "ch": ([("Friend", "Paper dictionary or an app?")], "You",
                   "The app — I have used it daily for a year, and the offline mode always works.",
                   ["I used it yesterday tomorrow.", "The dictionary is apping me."]),
        },
        {
            "t": ("Выбираем инструменты", "Choosing the Tools"),
            "o": ("Сравнить учебные ресурсы и спланировать работу с ними.",
                  "Compare study resources and plan how to use them."),
            "v": [("flashcard app", "приложение с карточками"), ("more convenient", "удобнее"),
                  ("audio course", "аудиокурс"), ("grammar reference", "грамматический справочник"),
                  ("to subscribe to a channel", "подписаться на канал"), ("ad-free", "без рекламы"),
                  ("database", "база данных")],
            "q": ("Which sentence compares two resources correctly?",
                  "A flashcard app is more convenient than paper cards on a bus.",
                  ["An app is convenienter than paper.", "An app is most convenient than cards."]),
            "tr": ("Я собираюсь подписаться на канал про грамматику — там есть справочник.",
                   "I am going to subscribe to a grammar channel — it has a full reference there.",
                   ["did", "subscribed", "yesterday"]),
            "fill": ("The ad-free version is ___ distracting.", "less",
                     ["least", "little"], "Версия без рекламы меньше отвлекает."),
            "tap": ("We are going to use the university database for the paper.", ["was", "did"]),
            "sh": ("If you use one app for new words and one for grammar, you will not get lost between ten tools.",
                   "Если пользоваться одним приложением для новых слов и одним для грамматики, не запутаешься между десятью инструментами."),
            "st": ("Too Many Apps", [
                ("Voice 1", "I have installed six study apps this month.", "В этом месяце я установил шесть учебных приложений."),
                ("Voice 2", "Six? Do you actually open them all?", "Шесть? Ты правда открываешь их все?"),
                ("What does Voice 2 advise?", [
                    ("Keep two — the ones you open daily without reminders.", True),
                    ("Keep them all yesterday tomorrow.", False),
                    ("The apps are installing you daily.", False)])]),
            "d": ("grammar reference", "A book or page that explains grammar rules",
                  ["A novel you read for pleasure", "A dictionary with word translations"]),
            "lw": ("I am going to ___ to the new channel.", "I am going to subscribe to the new channel.",
                   "subscribe", ["subscribed", "subscribing"]),
            "mw": ("The audio course is ___ for listening than videos.", "better", "be"),
            "ch": ([("Friend", "Which dictionary should I install?")], "You",
                   "The blue one — if you use the offline mode, it works even in the metro.",
                   ["I installed it yesterday tomorrow.", "The dictionary is installing me."]),
        },
        {
            "t": ("Если ресурс не помогает", "If the Resource Does Not Help"),
            "o": ("Дать советы о выборе ресурсов, используя should и первое условное.",
                  "Give resource-choice advice using should and the first conditional."),
            "v": [("to waste time on", "тратить время на"), ("useless", "бесполезный"),
                  ("to check the source", "проверить источник"), ("reliable", "надёжный"),
                  ("outdated", "устаревший"), ("to switch to", "переключиться на"),
                  ("review", "отзыв")],
            "q": ("Which sentence gives correct advice?",
                  "You should check whether the source is up to date.",
                  ["You should to check it yesterday.", "You must checking sources last time."]),
            "tr": ("Если ресурс устарел, ты выучишь неправильные правила.",
                   "If the resource is outdated, you will learn incorrect rules.",
                   ["did", "was", "yesterday"]),
            "fill": ("If an explanation confuses you, ___ to another source.",
                     "switch", ["will switch", "switched"], "Если объяснение запутывает, переключись на другой источник."),
            "tap": ("You should read the reviews before paying.", ["mustn't", "went"]),
            "sh": ("If a video has no examples, you should find a different one — real sentences make rules clear.",
                   "Если в видео нет примеров, стоит найти другое — реальные предложения делают правила понятными."),
            "st": ("The Confusing Explanation", [
                ("Voice 1", "This grammar page has explained the rule in a very strange way.", "Эта страница объяснила правило очень странно."),
                ("Voice 2", "Is it a reliable site? When was it updated?", "Это надёжный сайт? Когда его обновляли?"),
                ("What does Voice 1 discover?", [
                    ("Last updated in 2015 — I should find something newer.", True),
                    ("It updated tomorrow yesterday.", False),
                    ("The rule is confusing the site itself.", False)])]),
            "d": ("outdated", "Old and no longer correct",
                  ["Fresh and checked this year", "Written specially for your textbook"]),
            "lw": ("If the reviews are bad, ___ to another app.", "If the reviews are bad, switch to another app.",
                   "switch", ["will switch", "switched"]),
            "mw": ("Do not ___ time on useless drills.", "waste", "wa"),
            "ch": ([("Friend", "This course promises fluent English in a month.")], "You",
                   "Be careful — if a promise sounds magical, the course is usually useless.",
                   ["I bought it yesterday tomorrow.", "The month is fluenting me."]),
        },
    ],

    "A2_STUDY_GROUP_PROJECTS": [
        {
            "t": ("Как прошёл наш проект", "How Our Project Went"),
            "o": ("Рассказать о групповом проекте, используя past simple и present perfect.",
                  "Talk about a group project using past simple and present perfect."),
            "v": [("to divide tasks", "разделить задачи"), ("deadline", "срок"),
                  ("to contribute", "внести вклад"), ("slide deck", "презентация (набор слайдов)"),
                  ("to proofread", "вычитать"), ("to merge", "объединить (файлы/части)"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "Our group has finished the research part so far.",
                  ["Our group has finished it last week.", "We finish the research already so far."]),
            "tr": ("Мы разделили задачи в понедельник, а презентацию уже объединили.",
                   "We divided the tasks on Monday, and we have already merged the slide deck.",
                   ["did", "divide", "tomorrow"]),
            "fill": ("Last night I ___ the final text of the report.", "proofread",
                     ["has proofread", "proofreading"], "Прошлой ночью я вычитал финальный текст отчёта."),
            "tap": ("Each member has contributed to the presentation.", ["was", "did"]),
            "sh": ("We have met four times this month, and every meeting has moved the project forward.",
                   "Мы встречались четыре раза за месяц, и каждая встреча двигала проект вперёд."),
            "st": ("Before Submission", [
                ("Voice 1", "Has everyone uploaded their parts?", "Все загрузили свои части?"),
                ("Voice 2", "Three of us have. Kirill promised to send his slides by nine.",
                 "Трое уже. Кирилл обещал прислать слайды к девяти."),
                ("What does Voice 1 say?", [
                    ("Good — I have proofread the introduction already.", True),
                    ("Good, I proofread it tomorrow yesterday.", False),
                    ("Is the introduction uploading Kirill?", False)])]),
            "d": ("to merge", "To combine several files or parts into one",
                  ["To delete the extra copies of a file", "To print a document for the whole group"]),
            "lw": ("We have ___ all the parts into one file.", "We have merged all the parts into one file.",
                   "merged", ["merge", "merging"]),
            "mw": ("She has ___ a lot to the project.", "contributed", "co"),
            "ch": ([("Classmate", "Who did the design?")], "You",
                   "Lena did — she has made all the charts, and we have checked the numbers twice.",
                   ["She did them yesterday tomorrow.", "The design is charting us."]),
        },
        {
            "t": ("Планируем следующий проект", "Planning the Next Project"),
            "o": ("Спланировать проект и сравнить роли в группе.",
                  "Plan a project and compare group roles."),
            "v": [("team leader", "тимлид"), ("more responsible", "ответственнее"),
                  ("to assign roles", "распределить роли"), ("shared folder", "общая папка"),
                  ("to set a timeline", "составить график"), ("editor", "редактор"),
                  ("fair", "справедливый")],
            "q": ("Which sentence compares two roles correctly?",
                  "The editor's role is more demanding than the timekeeper's.",
                  ["Editor is demandinger than timekeeper.", "Editor is most demanding than timekeeper."]),
            "tr": ("Мы собираемся распределить роли на следующей встрече и завести общую папку.",
                   "We are going to assign the roles at the next meeting and set up a shared folder.",
                   ["did", "assigned", "yesterday"]),
            "fill": ("A clear timeline is ___ than vague promises.", "better",
                     ["best", "more good"], "Чёткий график лучше расплывчатых обещаний."),
            "tap": ("I am going to be the editor this time.", ["was", "did"]),
            "sh": ("If we set a timeline with three checkpoints, the project will not pile up in the last week.",
                   "Если составить график с тремя контрольными точками, проект не навалится всей массой в последнюю неделю."),
            "st": ("Assigning Roles", [
                ("Voice 1", "Who wants to be the team leader this time?", "Кто теперь хочет быть тимлидом?"),
                ("Voice 2", "You did the design last time — I can lead if nobody minds.",
                 "Прошлый раз дизайн делал ты — могу вести я, если никто не против."),
                ("What does Voice 1 answer?", [
                    ("Good idea — and I am going to be the editor.", True),
                    ("Good idea, I was editor yesterday tomorrow.", False),
                    ("Is the leader minding the design?", False)])]),
            "d": ("shared folder", "An online folder all group members can use",
                  ["A private folder only the leader opens", "A printed copy of the final report"]),
            "lw": ("We are going to ___ roles today.", "We are going to assign roles today.",
                   "assign", ["assigned", "assigning"]),
            "mw": ("Leading a team is ___ stressful than editing.", "more", "mo"),
            "ch": ([("Classmate", "How should we divide the work?")], "You",
                   "By strengths — if everyone takes what they do best, the quality will be higher.",
                   ["We divided it yesterday tomorrow.", "The work is dividing us."]),
        },
        {
            "t": ("Если кто-то не сдаёт работу", "If Someone Does Not Deliver"),
            "o": ("Обсудить проблемы в группе, используя should и первое условное.",
                  "Discuss group problems using should and the first conditional."),
            "v": [("to fall behind", "отставать"), ("to remind", "напомнить"),
                  ("to rely on", "полагаться на"), ("honest", "честный"),
                  ("to split up the work", "переделить работу"), ("consequence", "последствие"),
                  ("as early as possible", "как можно раньше")],
            "q": ("Which sentence gives correct group advice?",
                  "You should tell the leader about problems as early as possible.",
                  ["You should to tell him yesterday.", "You must telling leader last week."]),
            "tr": ("Если один отстанет, вся группа рискует сорвать срок.",
                   "If one person falls behind, the whole group risks missing the deadline.",
                   ["did", "fell", "yesterday"]),
            "fill": ("If you cannot finish your part, ___ the others immediately.",
                     "tell", ["will tell", "told"], "Если не можешь закончить свою часть, сразу скажи остальным."),
            "tap": ("You should not rely on memory — set reminders.", ["mustn't", "went"]),
            "sh": ("If the group splits up the unfinished work early, a small delay will not become a disaster.",
                   "Если группа заранее переделит незаконченную работу, небольшая задержка не станет катастрофой."),
            "st": ("The Missing Part", [
                ("Voice 1", "Mark has not sent his part, and the deadline is tomorrow.", "Марк не прислал свою часть, а срок завтра."),
                ("Voice 2", "Has anyone reminded him?", "Кто-нибудь напоминал ему?"),
                ("What do they decide?", [
                    ("I will call him now — if he cannot do it, we will split up his part.", True),
                    ("I called him yesterday tomorrow already.", False),
                    ("The deadline is missing Mark's part.", False)])]),
            "d": ("to fall behind", "To progress more slowly than needed",
                  ["To finish your part earlier than planned", "To leave the group for another project"]),
            "lw": ("If a task is late, ___ the leader today.", "If a task is late, remind the leader today.",
                   "remind", ["will remind", "reminded"]),
            "mw": ("You should rely ___ the shared calendar.", "on", "on"),
            "ch": ([("Classmate", "I am afraid I will miss my part.")], "You",
                   "Tell us today — if we know early, we will help you finish it.",
                   ["He told us yesterday tomorrow.", "The part is missing you."]),
        },
    ],

    "A2_STUDY_NOTE_TAKING_BASICS": [
        {
            "t": ("Мои записи на лекциях", "My Lecture Notes"),
            "o": ("Рассказать о конспектах, используя past simple и present perfect.",
                  "Talk about notes using past simple and present perfect."),
            "v": [("to take notes", "делать записи"), ("abbreviation", "сокращение"),
                  ("margin", "поля (страницы)"), ("to highlight", "выделить маркером"),
                  ("to review notes", "повторить записи"), ("key point", "ключевая мысль"),
                  ("to miss (a point)", "пропустить (мысль)")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have reviewed all the notes from this module.",
                  ["I have reviewed them last module.", "I review the notes already now."]),
            "tr": ("На прошлой лекции я пропустил ключевую мысль, но друг дал свои записи.",
                   "I missed a key point at the last lecture, but a friend has shared his notes.",
                   ["did", "miss", "tomorrow"]),
            "fill": ("She wrote the dates in the ___ of every page.", "margin",
                     ["margins", "marginal"], "Она записывала даты на полях каждой страницы."),
            "tap": ("I have highlighted the main definitions in yellow.", ["was", "did"]),
            "sh": ("I used only abbreviations in class, so I have rewritten the notes the same evening while I still remembered everything.",
                   "На занятии я пользовался только сокращениями, поэтому в тот же вечер переписал записи, пока всё помнил."),
            "st": ("Comparing Notes", [
                ("Voice 1", "Could I copy your notes from Tuesday? I missed that lecture.", "Можно сфотографировать твои записи со вторника? Я пропустил ту лекцию."),
                ("Voice 2", "Sure — but I have used a lot of abbreviations.", "Конечно — только у меня много сокращений."),
                ("What does Voice 1 ask?", [
                    ("No problem — what does this arrow in the margin mean?", True),
                    ("No problem, it meant tomorrow yesterday.", False),
                    ("Is the abbreviation copying the lecture?", False)])]),
            "d": ("abbreviation", "A short form of a word or phrase",
                  ["A full sentence written at the top", "A drawing in the notebook margin"]),
            "lw": ("I have ___ the notes twice this week.", "I have reviewed the notes twice this week.",
                   "reviewed", ["review", "reviewing"]),
            "mw": ("___ the key points before the exam.", "Highlight", "Hi"),
            "ch": ([("Friend", "Your notes look so tidy!")], "You",
                   "I have rewritten them in the evening since September — it doubles as revision.",
                   ["I rewrote them yesterday tomorrow.", "The notes are tidying me."]),
        },
        {
            "t": ("Новый способ записывать", "A New Way of Taking Notes"),
            "o": ("Сравнить способы ведения записей и выбрать систему.",
                  "Compare note-taking systems and choose one."),
            "v": [("outline", "план (тезисный)"), ("mind map", "интеллект-карта"),
                  ("more visual", "нагляднее"), ("Cornell method", "метод Корнелла"),
                  ("to structure", "структурировать"), ("typed notes", "печатные записи"),
                  ("handwritten", "рукописный")],
            "q": ("Which sentence compares two note styles correctly?",
                  "A mind map is more visual than a plain outline.",
                  ["A mind map is visualer than outline.", "A mind map is most visual than outline."]),
            "tr": ("С этого месяца я собираюсь вести записи по методу Корнелла.",
                   "From this month I am going to take notes with the Cornell method.",
                   ["did", "took", "yesterday"]),
            "fill": ("Handwritten notes are ___ for memory than typed ones.", "better",
                     ["best", "more good"], "Рукописные записи запоминаются лучше печатных."),
            "tap": ("We are going to structure the topic as a mind map.", ["was", "did"]),
            "sh": ("If you leave a summary line at the bottom of each page, revision will take minutes, not hours.",
                   "Если оставлять строку-резюме внизу каждой страницы, повторение займёт минуты, а не часы."),
            "st": ("Choosing a System", [
                ("Voice 1", "Do you type your notes or write by hand?", "Ты печатаешь записи или пишешь от руки?"),
                ("Voice 2", "Handwritten — a mind map is also more visual for me than an outline.",
                 "От руки — и интеллект-карта для меня нагляднее плана."),
                ("What does Voice 1 say?", [
                    ("I am going to try mind maps for the history course then.", True),
                    ("I tried them yesterday tomorrow.", False),
                    ("The outline is mapping your hand.", False)])]),
            "d": ("mind map", "A diagram with the topic in the centre and ideas around it",
                  ["A numbered list of sentences", "A table with dates and names only"]),
            "lw": ("I am going to ___ the chapter first.", "I am going to structure the chapter first.",
                   "structure", ["structured", "structuring"]),
            "mw": ("Typed notes are ___ searchable.", "more", "mo"),
            "ch": ([("Friend", "How do you remember diagrams?")], "You",
                   "I redraw them from memory — if the map is wrong, I check the original.",
                   ["I drew them yesterday tomorrow.", "The diagrams are remembering me."]),
        },
        {
            "t": ("Если записи не помогают", "If the Notes Do Not Help"),
            "o": ("Дать советы о записях, используя should и первое условное.",
                  "Give note advice using should and the first conditional."),
            "v": [("to reread", "перечитать"), ("to summarise", "резюмировать"),
                  ("in your own words", "своими словами"), ("to copy blindly", "бездумно списывать"),
                  ("effective", "эффективный"), ("to review regularly", "регулярно повторять"),
                  ("cluttered", "захламлённый (о записях)")],
            "q": ("Which sentence gives correct advice?",
                  "You should write summaries in your own words.",
                  ["You should to write them yesterday.", "You must writing summaries last lecture."]),
            "tr": ("Если просто перечитывать записи, они почти не запоминаются.",
                   "If you only reread your notes, you will remember almost nothing.",
                   ["did", "reread", "yesterday"]),
            "fill": ("If you copy blindly, the material ___ sense later.",
                     "will not make", ["not make", "does not made"], "Если бездумно списывать, материал позже не сложится в систему."),
            "tap": ("You should review your notes within a day.", ["mustn't", "went"]),
            "sh": ("If you close the notebook and retell the topic aloud, you will remember much more than by rereading.",
                   "Если закрыть тетрадь и пересказать тему вслух, запомнится гораздо больше, чем при перечитывании."),
            "st": ("The Cluttered Notebook", [
                ("Voice 1", "My notes are so cluttered that I cannot study from them.", "Мои записи так захламлены, что по ним нельзя заниматься."),
                ("Voice 2", "Have you tried summarising each page in one sentence?", "Пробовал резюмировать каждую страницу одним предложением?"),
                ("What does Voice 1 decide?", [
                    ("Not yet — I will do it this evening, while it is fresh.", True),
                    ("I did it yesterday tomorrow already.", False),
                    ("The notebook is cluttering my studies.", False)])]),
            "d": ("cluttered", "Messy and hard to read",
                  ["Neat, with clear headings and margins", "Short, with one idea per line"]),
            "lw": ("If you ___ regularly, the exam will be easier.", "If you review regularly, the exam will be easier.",
                   "review", ["will review", "reviewed"]),
            "mw": ("Summarise it in your ___ words.", "own", "ow"),
            "ch": ([("Friend", "I forget everything right after the lecture.")], "You",
                   "Review the same day — if you wait a week, you will be learning it from scratch.",
                   ["I reviewed it yesterday tomorrow.", "The lecture is forgetting me."]),
        },
    ],

    "A2_STUDY_PREPARING_FOR_TESTS": [
        {
            "t": ("Как я готовился к тесту", "How I Prepared for the Test"),
            "o": ("Рассказать о подготовке к тесту, используя past simple и present perfect.",
                  "Talk about test preparation using past simple and present perfect."),
            "v": [("mock test", "пробный тест"), ("to revise", "повторять (материал)"),
                  ("weak spot", "слабое место"), ("to pass", "сдать"),
                  ("to fail", "провалить"), ("study plan", "план подготовки"),
                  ("flashcards", "карточки")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have already finished three mock tests.",
                  ["I have finished them last Friday.", "I finish three mocks already now."]),
            "tr": ("Я провалил пробный тест в марте, но с тех пор закрыл все слабые места.",
                   "I failed a mock test in March, but I have closed all my weak spots since then.",
                   ["did", "fail", "tomorrow"]),
            "fill": ("Last week she ___ for the exam every evening.", "revised",
                     ["has revise", "revising"], "На прошлой неделе она повторяла материал каждый вечер."),
            "tap": ("He has passed the listening part already.", ["was", "did"]),
            "sh": ("I made a study plan a month ago and have stuck to it — two mock tests are still left before the real exam.",
                   "Месяц назад я составил план подготовки и следовал ему — до настоящего экзамена осталось ещё два пробных теста."),
            "st": ("After the Mock Test", [
                ("Voice 1", "How was your mock test?", "Как прошёл твой пробный тест?"),
                ("Voice 2", "I passed overall, but the grammar part showed my weak spots.",
                 "В целом сдал, но часть по грамматике показала мои слабые места."),
                ("What does Voice 1 ask?", [
                    ("Have you made a plan to fix them before June?", True),
                    ("Did you make a plan tomorrow yesterday?", False),
                    ("Is the grammar mocking your weak spots?", False)])]),
            "d": ("mock test", "A practice test before the real one",
                  ["The final exam that counts for your grade", "A short quiz during a regular lesson"]),
            "lw": ("I have ___ all the vocabulary cards.", "I have revised all the vocabulary cards.",
                   "revised", ["revise", "revising"]),
            "mw": ("She has ___ the writing task twice.", "passed", "pa"),
            "ch": ([("Friend", "Did you pass the entrance test?")], "You",
                   "Yes — I have just checked the results online!",
                   ["I passed it yesterday tomorrow.", "The test is entering me."]),
        },
        {
            "t": ("Готовимся к экзамену", "Getting Ready for the Exam"),
            "o": ("Сравнить методы подготовки и спланировать ревизию.",
                  "Compare revision methods and plan your revision."),
            "v": [("cramming", "зубрёжка (накануне)"), ("more effective", "эффективнее"),
                  ("spaced repetition", "интервальное повторение"), ("study session", "учебная сессия"),
                  ("to concentrate", "концентрироваться"), ("practice papers", "прошлогольние варианты"),
                  ("break", "перерыв")],
            "q": ("Which sentence compares two methods correctly?",
                  "Spaced repetition is more effective than cramming the night before.",
                  ["Spaced repetition is effectiver than cramming.", "Spaced repetition is most effective than cramming."]),
            "tr": ("В этот раз я собираюсь повторять по 40 минут с перерывами.",
                   "This time I am going to revise in forty-minute sessions with breaks.",
                   ["did", "revised", "yesterday"]),
            "fill": ("Short daily sessions are ___ than one long Sunday.", "better",
                     ["best", "more good"], "Короткие ежедневные занятия лучше одного долгого воскресенья."),
            "tap": ("We are going to do two practice papers this week.", ["was", "did"]),
            "sh": ("If you use spaced repetition, the material will stay in your memory long after the exam.",
                   "Если использовать интервальное повторение, материал останется в памяти надолго после экзамена."),
            "st": ("Two Weeks Left", [
                ("Voice 1", "The exam is in two weeks. Should I start with the practice papers?",
                 "Экзамен через две недели. Начать с прошлогодних вариантов?"),
                ("Voice 2", "Diagnose first — do one paper now to find the weak topics.",
                 "Сначала диагностика — сделай один вариант сейчас, чтобы найти слабые темы."),
                ("What does Voice 1 decide?", [
                    ("Good plan — I am going to do one paper this evening.", True),
                    ("I did one yesterday tomorrow already.", False),
                    ("The exam is papering my weak topics.", False)])]),
            "d": ("cramming", "Learning everything in a rush just before a test",
                  ["Studying a little every day for weeks", "Repeating material with a partner regularly"]),
            "lw": ("I am going to ___ on the listening tasks.", "I am going to concentrate on the listening tasks.",
                   "concentrate", ["concentrated", "concentrating"]),
            "mw": ("Old exam papers are ___ useful than new textbooks.", "more", "mo"),
            "ch": ([("Friend", "I study six hours without a break.")], "You",
                   "Add breaks — if you rest every forty minutes, you will actually remember more.",
                   ["I rested yesterday tomorrow.", "The hours are breaking me."]),
        },
        {
            "t": ("Если волнуешься перед тестом", "If You Are Nervous Before a Test"),
            "o": ("Обсудить предэкзаменационную подготовку, используя should и первое условное.",
                  "Discuss pre-test preparation using should and the first conditional."),
            "v": [("to get nervous", "нервничать"), ("night before", "вечер накануне"),
                  ("to sleep well", "выспаться"), ("instructions", "инструкции"),
                  ("time limit", "лимит времени"), ("to arrive early", "прийти заранее"),
                  ("confident", "уверенный")],
            "q": ("Which sentence gives correct pre-test advice?",
                  "You should read all the instructions before starting.",
                  ["You should to read them yesterday.", "You must reading instructions last test."]),
            "tr": ("Если выспишься накануне, думаешь быстрее и ошибаешься меньше.",
                   "If you sleep well the night before, you will think faster and make fewer mistakes.",
                   ["did", "slept", "yesterday"]),
            "fill": ("If you ___ early, you will have time to calm down.",
                     "arrive", ["will arrive", "arrived"], "Если прийти заранее, будет время успокоиться."),
            "tap": ("You should check the time limit first.", ["mustn't", "went"]),
            "sh": ("If you have prepared steadily, the nervousness will fade after the first questions.",
                   "Если готовился стабильно, волнение уйдёт после первых вопросов."),
            "st": ("The Morning of the Test", [
                ("Voice 1", "I always get nervous before tests, even easy ones.", "Я всегда нервничаю перед тестами, даже лёгкими."),
                ("Voice 2", "Did you sleep last time, or did you revise all night?", "В прошлый раз ты спала или повторяла всю ночь?"),
                ("What does Voice 1 admit?", [
                    ("I revised all night and nearly fell asleep during the listening.", True),
                    ("I slept tomorrow yesterday all night.", False),
                    ("The test is sleeping through my listening.", False)])]),
            "d": ("time limit", "The maximum time you have to finish a test",
                  ["The date when results arrive", "The number of questions in one section"]),
            "lw": ("If you ___ the instructions, you lose points.", "If you skip the instructions, you lose points.",
                   "skip", ["will skip", "skipped"]),
            "mw": ("You should arrive ___ than everyone else.", "earlier", "ea"),
            "ch": ([("Friend", "My hands shake before every exam.")], "You",
                   "Take a short walk before entering — if your body is calm, your mind will follow.",
                   ["I walked yesterday tomorrow.", "The exam is shaking my hands."]),
        },
    ],

    "A2_STUDY_READING_FOR_MAIN_IDEAS": [
        {
            "t": ("О чём была статья", "What the Article Was About"),
            "o": ("Рассказать о прочитанном, используя past simple и present perfect.",
                  "Talk about a text using past simple and present perfect."),
            "v": [("main idea", "главная мысль"), ("topic sentence", "тематическое предложение"),
                  ("to skim", "просмотреть бегло"), ("supporting detail", "подробность (подтверждающая)"),
                  ("to come across", "наткнуться на"), ("heading", "заголовок"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have skimmed two chapters so far this evening.",
                  ["I have skimmed them yesterday evening.", "I skim two chapters already so far."]),
            "tr": ("Я бегло просмотрел статью и нашёл три подтверждающие детали.",
                   "I skimmed the article and have found three supporting details.",
                   ["did", "skim", "tomorrow"]),
            "fill": ("The first paragraph usually contains the ___ sentence.", "topic",
                     ["topics", "topical"], "Первый абзац обычно содержит тематическое предложение."),
            "tap": ("She has underlined the main idea of each paragraph.", ["was", "did"]),
            "sh": ("The heading promised tips on saving money, and the article has actually delivered them in the third section.",
                   "Заголовок обещал советы по экономии денег, и статья действительно выдала их в третьем разделе."),
            "st": ("After the Reading Class", [
                ("Voice 1", "What was the article about, in one sentence?", "О чём была статья, в одном предложении?"),
                ("Voice 2", "Remote work saves companies money — but only if they trust their staff.",
                 "Удалённая работа экономит компаниям деньги — но только если они доверяют сотрудникам."),
                ("What does Voice 1 ask?", [
                    ("Which details has the author used to support it?", True),
                    ("Which details did the author use tomorrow?", False),
                    ("Is the sentence saving the article money?", False)])]),
            "d": ("topic sentence", "The sentence that states the main idea of a paragraph",
                  ["A quote from another article", "The last question of the text"]),
            "lw": ("I have ___ the whole report in ten minutes.", "I have skimmed the whole report in ten minutes.",
                   "skimmed", ["skim", "skimming"]),
            "mw": ("Find the main ___ first, details later.", "idea", "id"),
            "ch": ([("Friend", "Did you read the whole chapter?")], "You",
                   "I skimmed it first — then I have read only the sections with the main ideas.",
                   ["I read it yesterday tomorrow.", "The chapter is skimming me."]),
        },
        {
            "t": ("Как читать быстрее", "How to Read Faster"),
            "o": ("Сравнить техники чтения и спланировать чтение на неделю.",
                  "Compare reading techniques and plan your weekly reading."),
            "v": [("scanning", "поиск по тексту (сканирование)"), ("faster", "быстрее"),
                  ("to guess from context", "догадаться по контексту"), ("subtitles", "подзаголовки"),
                  ("to slow down", "замедлиться"), ("more carefully", "внимательнее"),
                  ("reading speed", "скорость чтения")],
            "q": ("Which sentence compares two reading ways correctly?",
                  "Scanning for numbers is faster than reading every word.",
                  ["Scanning is more fast than reading.", "Scanning is fastest than reading."]),
            "tr": ("На этой неделе я собираюсь читать по одной статье в день.",
                   "This week I am going to read one article a day.",
                   ["did", "read", "yesterday"]),
            "fill": ("Guessing from context is ___ than stopping at every word.", "quicker",
                     ["quickest", "more quick"], "Догадываться по контексту быстрее, чем останавливаться на каждом слове."),
            "tap": ("We are going to scan the text for the dates first.", ["was", "did"]),
            "sh": ("If you read the subtitles first, you will know where to slow down and where to scan.",
                   "Если сначала прочитать подзаголовки, будет понятно, где замедлиться, а где сканировать."),
            "st": ("Reading a Long Text", [
                ("Voice 1", "This article is six pages long — do I read it all?", "Статья на шесть страниц — читать всё?"),
                ("Voice 2", "Start with the headings — then read carefully only the relevant section.",
                 "Начни с подзаголовков — внимательно прочитай только нужный раздел."),
                ("What does Voice 1 decide?", [
                    ("Good — I am going to scan for my topic first.", True),
                    ("I scanned it yesterday tomorrow already.", False),
                    ("The pages are heading my topic.", False)])]),
            "d": ("scanning", "Looking quickly through a text for specific information",
                  ["Reading every word from top to bottom", "Translating the text word by word"]),
            "lw": ("I am going to ___ for the key figure.", "I am going to scan for the key figure.",
                   "scan", ["scanned", "scanning"]),
            "mw": ("My reading speed is ___ than last year.", "higher", "hi"),
            "ch": ([("Friend", "I stop at every unknown word.")], "You",
                   "Try guessing from context — if the guess fails, you can check the word later.",
                   ["I guessed it yesterday tomorrow.", "The words are stopping me."]),
        },
        {
            "t": ("Если текст не понятен", "If the Text Is Unclear"),
            "o": ("Дать советы о чтении сложных текстов, используя should и первое условное.",
                  "Give advice on difficult texts using should and the first conditional."),
            "v": [("to re-read", "перечитать"), ("in other words", "другими словами"),
                  ("to paraphrase", "пересказать своими словами"), ("difficult", "сложный"),
                  ("to look for", "искать"), ("clue", "подсказка"),
                  ("to give up on", "сдаться на")],
            "q": ("Which sentence gives correct reading advice?",
                  "You should paraphrase each paragraph in your own words.",
                  ["You should to paraphrase it yesterday.", "You must paraphrasing paragraphs last text."]),
            "tr": ("Если перечитать сложный абзац медленно, смысл часто становится ясен.",
                   "If you re-read a difficult paragraph slowly, the meaning often becomes clear.",
                   ["did", "reread", "yesterday"]),
            "fill": ("If a sentence is unclear, look for ___ in the next one.",
                     "clues", ["will clue", "clued"], "Если предложение неясно, ищи подсказки в следующем."),
            "tap": ("You should not give up on hard texts at once.", ["mustn't", "went"]),
            "sh": ("If you paraphrase a paragraph in one sentence, you will immediately see what you have not understood.",
                   "Если пересказать абзац одним предложением, сразу станет видно, что именно не понял."),
            "st": ("The Impossible Paragraph", [
                ("Voice 1", "I have read this paragraph three times and still do not get it.", "Я трижды прочитал этот абзац и всё равно не понимаю."),
                ("Voice 2", "Try paraphrasing the first half aloud.", "Попробуй пересказать первую половину вслух."),
                ("What does Voice 1 discover?", [
                    ("Ah — now I see that I misunderstood the word 'claim'.", True),
                    ("I saw it tomorrow yesterday.", False),
                    ("The paragraph is paraphrasing me thrice.", False)])]),
            "d": ("clue", "Something that helps you find an answer or meaning",
                  ["A question nobody can answer", "A word you have never seen in any text"]),
            "lw": ("If the text stays unclear, ___ the main part.", "If the text stays unclear, re-read the main part.",
                   "re-read", ["will re-read", "re-readed"]),
            "mw": ("Say it in other ___ .", "words", "wo"),
            "ch": ([("Friend", "This article is above my level.")], "You",
                   "Do not give up — if you find the main idea, the details will follow.",
                   ["I found it yesterday tomorrow.", "The level is articling me."]),
        },
    ],

    "A2_STUDY_REVIEWING_LEARNING_PROGRESS": [
        {
            "t": ("Чего я достиг к концу месяца", "What I Achieved by the End of the Month"),
            "o": ("Оценить прогресс, используя past simple и present perfect.",
                  "Assess progress using past simple and present perfect."),
            "v": [("to make progress", "делать успехи"), ("milestone", "рубеж / веха"),
                  ("to achieve", "достичь"), ("progress report", "отчёт о прогрессе"),
                  ("to look back on", "оглянуться на"), ("fluent", "беглый (в речи)"),
                  ("by now", "к этому моменту")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have reached two of my three goals by now.",
                  ["I have reached them last month.", "I reach two goals already by now."]),
            "tr": ("Я начал в январе и к этому моменту прошёл половину учебника.",
                   "I started in January and have covered half of the textbook by now.",
                   ["did", "start", "tomorrow"]),
            "fill": ("Last month she ___ her first milestone.", "hit",
                     ["has hit", "hitting"], "В прошлом месяце она достигла первого рубежа."),
            "tap": ("We have made visible progress this term.", ["was", "did"]),
            "sh": ("Looking back on the term, I have become much more fluent, though my writing still needs work.",
                   "Оглядываясь на семестр, я стал гораздо беглее в речи, хотя письму ещё требуется работа."),
            "st": ("The Monthly Review", [
                ("Voice 1", "So, what does your progress report say?", "Итак, что говорит твой отчёт о прогрессе?"),
                ("Voice 2", "Positive: I have learned five hundred words. Negative: listening is still weak.",
                 "Позитив: я выучил пятьсот слов. Негатив: аудирование всё ещё слабое."),
                ("What does Voice 1 ask?", [
                    ("Have you planned something specific to fix the listening?", True),
                    ("Did you plan it tomorrow yesterday?", False),
                    ("Is the report listening to your words?", False)])]),
            "d": ("milestone", "An important stage in progress",
                  ["A small daily task on your list", "A mistake you made last week"]),
            "lw": ("I have ___ my main goal this term.", "I have achieved my main goal this term.",
                   "achieved", ["achieve", "achieving"]),
            "mw": ("She has made great ___ in speaking.", "progress", "pr"),
            "ch": ([("Friend", "Do you feel any different after the course?")], "You",
                   "Yes — I have become more fluent, and I have stopped being afraid of phone calls.",
                   ["I felt it yesterday tomorrow.", "The course is differing me."]),
        },
        {
            "t": ("План на следующий месяц", "The Plan for Next Month"),
            "o": ("Сравнить результаты и спланировать следующий этап.",
                  "Compare results and plan the next stage."),
            "v": [("goal", "цель"), ("more realistic", "реалистичнее"),
                  ("to set a target", "поставить цель"), ("habit tracker", "трекер привычек"),
                  ("to measure", "измерить"), ("smarter", "умнее (о целях)"),
                  ("weekly review", "недельная ревизия")],
            "q": ("Which sentence compares two goals correctly?",
                  "Twenty words a day is more realistic than a hundred.",
                  ["Twenty words is realister than hundred.", "Twenty words is most realistic than hundred."]),
            "tr": ("В следующем месяце я собираюсь измерять прогресс каждую неделю.",
                   "Next month I am going to measure my progress every week.",
                   ["did", "measured", "yesterday"]),
            "fill": ("A measurable goal is ___ than a vague dream.", "stronger",
                     ["strongest", "more strong"], "Измеримая цель сильнее расплывчатой мечты."),
            "tap": ("I am going to keep a habit tracker again.", ["was", "did"]),
            "sh": ("If you review your goals weekly, you will notice the weak spots before they become a habit of giving up.",
                   "Если проверять цели еженедельно, слабые места заметны раньше, чем отказ от них станет привычкой."),
            "st": ("Setting New Targets", [
                ("Voice 1", "My goal was 'speak better'. Guess what — I cannot even measure it.", "Моя цель была 'говорить лучше'. Угадай что — её даже не измерить."),
                ("Voice 2", "That is the problem. Try 'ten minutes of speaking daily'.", "В этом и проблема. Попробуй 'десять минут речи ежедневно'."),
                ("What does Voice 1 decide?", [
                    ("Good idea — that is going to be my next month's target.", True),
                    ("It was my target yesterday tomorrow.", False),
                    ("The goal is measuring me vaguely.", False)])]),
            "d": ("habit tracker", "A table or app where you mark daily actions",
                  ["A list of books you want to buy", "A grade report from your teacher"]),
            "lw": ("I am going to ___ a realistic target.", "I am going to set a realistic target.",
                   "set", ["setted", "setting"]),
            "mw": ("Weekly reviews are ___ useful than monthly ones.", "more", "mo"),
            "ch": ([("Friend", "How will you track your reading?")], "You",
                   "Pages per week — if I write the number down, the progress will be visible.",
                   ["I tracked it yesterday tomorrow.", "The reading is tracking my pages."]),
        },
        {
            "t": ("Если прогресса нет", "If There Is No Progress"),
            "o": ("Обсудить застой в учёбе, используя should и первое условное.",
                  "Discuss a study plateau using should and the first conditional."),
            "v": [("plateau", "плато (застой)"), ("to get stuck", "застрять"),
                  ("to change approach", "сменить подход"), ("frustrating", "разочаровывающий"),
                  ("to compare with", "сравнить с"), ("recording", "запись (аудио)"),
                  ("patience", "терпение")],
            "q": ("Which sentence gives correct advice about a plateau?",
                  "You should change your approach, not just work harder.",
                  ["You should to change it yesterday.", "You must changing approach last month."]),
            "tr": ("Если сравнить свои записи с записями полугодовой давности, прогресс виден сразу.",
                   "If you compare your current notes with those from six months ago, the progress is obvious.",
                   ["did", "compared", "yesterday"]),
            "fill": ("If you feel stuck, ___ your method first.", "change",
                     ["will change", "changed"], "Если чувствуешь, что застрял, сначала поменяй метод."),
            "tap": ("You should record yourself to hear the difference.", ["mustn't", "went"]),
            "sh": ("If you record yourself speaking each month, you will hear progress that daily practice hides.",
                   "Если записывать свою речь каждый месяц, услышишь прогресс, который скрывает ежедневная практика."),
            "st": ("The Frustrating Month", [
                ("Voice 1", "I have studied for a month and feel zero progress.", "Я месяц занимался и не чувствую никакого прогресса."),
                ("Voice 2", "Do you remember your first recordings?", "Помнишь свои первые записи?"),
                ("What does Voice 1 realise?", [
                    ("Oh — I have just listened to January, and the difference is huge.", True),
                    ("I listened to it tomorrow yesterday.", False),
                    ("The month is studying my progress.", False)])]),
            "d": ("plateau", "A long period without visible progress",
                  ["A quick jump to a new level", "The first week of a new course"]),
            "lw": ("If you ___ stuck, change the method.", "If you get stuck, change the method.",
                   "get", ["will get", "got"]),
            "mw": ("Have ___ — progress is not always visible.", "patience", "pa"),
            "ch": ([("Friend", "My test scores have stopped growing.")], "You",
                   "Change the approach — if you add listening practice, the scores will move again.",
                   ["They moved yesterday tomorrow.", "The scores are testing me."]),
        },
    ],

    "A2_STUDY_STUDY_GOALS_AND_PLANS": [
        {
            "t": ("Мои цели и что уже сделано", "My Goals and What Is Already Done"),
            "o": ("Рассказать о целях, используя past simple и present perfect.",
                  "Talk about goals using past simple and present perfect."),
            "v": [("long-term goal", "долгосрочная цель"), ("to break down into steps", "разбить на шаги"),
                  ("to tick off", "отметить (выполненным)"), ("so far", "до сих пор"),
                  ("by the end of", "к концу"), ("to commit to", "обязаться (делать)"),
                  ("checklist", "чек-лист")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have ticked off six of the ten steps so far.",
                  ["I have ticked them off last week.", "I tick six steps already so far."]),
            "tr": ("Я разбил большую цель на двенадцать шагов и отметил четыре.",
                   "I broke the big goal into twelve steps and have ticked off four.",
                   ["did", "broke", "tomorrow"]),
            "fill": ("In March she ___ to daily practice.", "committed",
                     ["has commit", "committing"], "В марте она обязалась практиковаться ежедневно."),
            "tap": ("We have completed the first module already.", ["was", "did"]),
            "sh": ("By the end of spring I promised myself the B1 exam — I have registered and paid this week.",
                   "К концу весны я обещал себе экзамен B1 — на этой неделе я зарегистрировался и оплатил."),
            "st": ("The Checklist", [
                ("Voice 1", "How is your language plan going?", "Как идёт твой языковой план?"),
                ("Voice 2", "Not bad — I have ticked off the grammar base and the first thousand words.",
                 "Неплохо — я отметил грамматическую базу и первую тысячу слов."),
                ("What does Voice 1 ask?", [
                    ("What is left for the next two months?", True),
                    ("What is left tomorrow yesterday?", False),
                    ("Is the plan ticking off your grammar?", False)])]),
            "d": ("long-term goal", "A big aim that takes months or years",
                  ["A task you finish in one evening", "A homework assignment for tomorrow"]),
            "lw": ("I have ___ the goal into small steps.", "I have broken the goal into small steps.",
                   "broken", ["broke", "breaking"]),
            "mw": ("She has ticked ___ three tasks.", "off", "of"),
            "ch": ([("Friend", "When is your exam, exactly?")], "You",
                   "June the fifteenth — I have booked it and have started the countdown.",
                   ["It was June yesterday tomorrow.", "The exam is datting me."]),
        },
        {
            "t": ("План на семестр", "The Semester Plan"),
            "o": ("Составить план и сравнить стратегии учёбы.",
                  "Make a plan and compare study strategies."),
            "v": [("weekly plan", "недельный план"), ("more specific", "конкретнее"),
                  ("to allocate time", "распределить время"), ("to overload", "перегрузить"),
                  ("achievable", "достижимый"), ("priority", "приоритет"),
                  ("to build in", "заложить (в план)")],
            "q": ("Which sentence compares two plans correctly?",
                  "'Read two chapters a week' is more specific than 'read more'.",
                  ["'Two chapters' is more specificest than 'read more'.", "'Two chapters' is most specific than 'more'."]),
            "tr": ("В этом семестре я собираюсь выделить утро на грамматику.",
                   "This semester I am going to allocate the mornings to grammar.",
                   ["did", "allocated", "yesterday"]),
            "fill": ("An overloaded plan is ___ dangerous than no plan.", "more",
                     ["most", "much"], "Перегруженный план опаснее отсутствия плана."),
            "tap": ("They are going to build in a review week before exams.", ["was", "did"]),
            "sh": ("If you build in one flexible evening a week, a single missed day will not destroy the whole plan.",
                   "Если заложить в план один гибкий вечер в неделю, один пропущенный день не разрушит весь план."),
            "st": ("Planning the Term", [
                ("Voice 1", "Should I plan all seven days of the week?", "Планировать все семь дней недели?"),
                ("Voice 2", "Six — the seventh is your safety net for missed tasks.",
                 "Шесть — седьмой это твоя подушка для пропущенных задач."),
                ("What does Voice 1 say?", [
                    ("Smart — I am going to plan six days and keep Sunday flexible.", True),
                    ("I planned seven yesterday tomorrow.", False),
                    ("The week is netting my safety.", False)])]),
            "d": ("achievable", "Possible to do in the time you have",
                  ["So difficult that nobody can do it", "So easy that it brings no progress"]),
            "lw": ("I am going to ___ two hours a day to reading.", "I am going to allocate two hours a day to reading.",
                   "allocate", ["allocated", "allocating"]),
            "mw": ("Speaking is my top ___ this term.", "priority", "pr"),
            "ch": ([("Friend", "How many hours a day should I study?")], "You",
                   "Two focused ones — if you overload the plan, you will quit by week three.",
                   ["I studied them yesterday tomorrow.", "The hours are prioritising me."]),
        },
        {
            "t": ("Если сорвался план", "If the Plan Falls Apart"),
            "o": ("Обсудить срыв планов, используя should и первое условное.",
                  "Discuss broken plans using should and the first conditional."),
            "v": [("to fall behind schedule", "отставать от графика"), ("to catch up", "наверстать"),
                  ("excuse", "оправдание"), ("to restart", "начать заново"),
                  ("from scratch", "с нуля"), ("all-or-nothing thinking", "мышление «всё или ничего»"),
                  ("to adjust", "скорректировать")],
            "q": ("Which sentence gives correct advice?",
                  "You should restart the plan instead of quitting it.",
                  ["You should to restart it yesterday.", "You must restarting plan last week."]),
            "tr": ("Если отстанешь на неделю, не бросай — просто скорректируй сроки.",
                   "If you fall behind by a week, do not quit — just adjust the deadlines.",
                   ["did", "fell", "yesterday"]),
            "fill": ("If you miss three days, ___ on the fourth.",
                     "restart", ["will restart", "restarted"], "Если пропустил три дня, начни заново на четвёртый."),
            "tap": ("You should catch up gradually, not in one night.", ["mustn't", "went"]),
            "sh": ("If you drop the all-or-nothing thinking, one missed day will feel like a pause, not a failure.",
                   "Если отбросить мышление «всё или ничего», один пропущенный день будет паузой, а не провалом."),
            "st": ("The Abandoned Plan", [
                ("Voice 1", "I missed a whole week, and now I want to quit the plan.", "Я пропустил целую неделю и теперь хочу бросить план."),
                ("Voice 2", "Why? Do you start from scratch when you miss a bus?", "Почему? Ты начинаешь путь заново, когда опаздываешь на автобус?"),
                ("What does Voice 1 realise?", [
                    ("Fair point — I should just continue from where I stopped.", True),
                    ("I continued it yesterday tomorrow already.", False),
                    ("The week is quitting my bus.", False)])]),
            "d": ("to catch up", "To do the work you missed",
                  ["To plan the work for next month", "To skip the topics you find boring"]),
            "lw": ("If you ___ behind, adjust the plan.", "If you fall behind, adjust the plan.",
                   "fall", ["will fall", "fell"]),
            "mw": ("Do not start from ___ — just continue.", "scratch", "sc"),
            "ch": ([("Friend", "I have not opened the textbook since Monday.")], "You",
                   "Open it now for ten minutes — if you restart small, the momentum will return.",
                   ["I opened it yesterday tomorrow.", "The textbook is Mondaying me."]),
        },
    ],

    "A2_STUDY_UNDERSTANDING_INSTRUCTIONS": [
        {
            "t": ("Инструкции на занятии", "Instructions in Class"),
            "o": ("Понимать учебные инструкции, используя past simple и present perfect.",
                  "Understand study instructions using past simple and present perfect."),
            "v": [("to hand in", "сдать (работу)"), ("word limit", "лимит слов"),
                  ("to underline", "подчеркнуть"), ("in pairs", "в парах"),
                  ("to refer to", "сослаться на"), ("rubric", "критерии оценки"),
                  ("due date", "крайний срок")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The teacher has explained the rubric twice already.",
                  ["The teacher has explained it last lesson.", "The teacher explain the rubric already twice."]),
            "tr": ("Преподаватель объяснил критерии и попросил сдать работу к пятнице.",
                   "The teacher explained the rubric and has asked us to hand in the essay by Friday.",
                   ["did", "explain", "tomorrow"]),
            "fill": ("We worked ___ in the last session.", "in pairs",
                     ["in pair", "pairing"], "На прошлом занятии мы работали в парах."),
            "tap": ("Have you read the instructions to the end?", ["was", "did"]),
            "sh": ("The task says 'underline the topic sentences and refer to paragraph two' — the due date is Monday, and the word limit is two hundred.",
                   "В задании сказано: «подчеркните тематические предложения и сошлитесь на второй абзац» — крайний срок понедельник, лимит слов двести."),
            "st": ("The Assignment", [
                ("Voice 1", "What exactly do we have to do for Monday?", "Что именно нужно сделать к понедельнику?"),
                ("Voice 2", "Underline the arguments and refer to the rubric — the teacher has posted it online.",
                 "Подчеркнуть аргументы и ориентироваться на критерии — преподаватель выложил их онлайн."),
                ("What does Voice 1 ask?", [
                    ("Is there a word limit this time?", True),
                    ("Is there a limit tomorrow yesterday?", False),
                    ("Is Monday underlining our arguments?", False)])]),
            "d": ("rubric", "The list of criteria used to grade your work",
                  ["The title you give your essay", "The deadline printed on the task sheet"]),
            "lw": ("I have ___ in my homework already.", "I have handed in my homework already.",
                   "handed", ["hand", "handing"]),
            "mw": ("The ___ date is the twelfth.", "due", "du"),
            "ch": ([("Teacher", "Any questions about the task?")], "You",
                   "Yes — should we work in pairs, or is it an individual assignment?",
                   ["I asked it yesterday tomorrow.", "The task is questioning me."]),
        },
        {
            "t": ("Следующее задание", "The Next Assignment"),
            "o": ("Понимать требования задания и сравнивать форматы.",
                  "Understand assignment requirements and compare formats."),
            "v": [("requirements", "требования"), ("clearer", "понятнее"),
                  ("to follow the steps", "следовать шагам"), ("multiple choice", "множественный выбор"),
                  ("open question", "открытый вопрос"), ("to count towards", "идти в зачёт (оценки)"),
                  ("instruction", "инструкция")],
            "q": ("Which sentence compares two task types correctly?",
                  "Multiple choice is quicker than an open question.",
                  ["Multiple choice is more quick than open question.", "Multiple choice is quickest than questions."]),
            "tr": ("В этот раз мы собираемся следовать инструкции шаг за шагом.",
                   "This time we are going to follow the instructions step by step.",
                   ["did", "followed", "yesterday"]),
            "fill": ("The presentation ___ towards the final grade.", "counts",
                     ["count", "counting"], "Презентация идёт в зачёт итоговой оценки."),
            "tap": ("They are going to add a listening section.", ["was", "did"]),
            "sh": ("If you read the requirements twice before starting, you will not redo the task from the beginning.",
                   "Если дважды прочитать требования до начала, не придётся переделывать работу с самого начала."),
            "st": ("Reading the Brief", [
                ("Voice 1", "The brief has three pages of requirements...", "В задании три страницы требований..."),
                ("Voice 2", "Read the headings first — they show the steps.", "Сначала прочитай заголовки — они показывают шаги."),
                ("What does Voice 1 say?", [
                    ("Right — step one is choosing the topic by Wednesday.", True),
                    ("Step one chose me tomorrow yesterday.", False),
                    ("The pages are briefing the steps.", False)])]),
            "d": ("open question", "A task where you write your own answer",
                  ["A task where you choose from given options", "A task where you match two lists"]),
            "lw": ("We are going to ___ the steps exactly.", "We are going to follow the steps exactly.",
                   "follow", ["followed", "following"]),
            "mw": ("The checklist makes everything ___ .", "clearer", "cl"),
            "ch": ([("Classmate", "Does the essay count towards the grade?")], "You",
                   "Yes, twenty per cent — if you read the rubric, you will see exactly how.",
                   ["It counted yesterday tomorrow.", "The essay is grading me."]),
        },
        {
            "t": ("Если инструкция непонятна", "If the Instruction Is Unclear"),
            "o": ("Уточнять задания, используя should и первое условное.",
                  "Clarify tasks using should and the first conditional."),
            "v": [("to misread", "прочитать неверно"), ("to ask for clarification", "попросить уточнение"),
                  ("to assume", "предположить"), ("worse", "хуже"),
                  ("to waste effort", "потратить усилия зря"), ("in advance", "заранее"),
                  ("to double-check", "перепроверить")],
            "q": ("Which sentence gives correct advice?",
                  "You should ask for clarification before you start writing.",
                  ["You should to ask it yesterday.", "You must asking clarification last time."]),
            "tr": ("Если неверно поймёшь задание, потеряешь часы работы.",
                   "If you misread the task, you will waste hours of work.",
                   ["did", "misreaded", "yesterday"]),
            "fill": ("If instructions are unclear, ___ the teacher directly.",
                     "message", ["will message", "messaged"], "Если инструкция неясна, напиши преподавателю напрямую."),
            "tap": ("You should never assume — double-check.", ["mustn't", "went"]),
            "sh": ("If you double-check the requirements on day one, you will not discover a missing section the night before the deadline.",
                   "Если перепроверить требования в первый день, не обнаружишь отсутствующий раздел накануне срока."),
            "st": ("The Wrong Format", [
                ("Voice 1", "I wrote a report, but the task asked for a letter — I misread one word.",
                 "Я написал отчёт, а требовалось письмо — я неверно прочитал одно слово."),
                ("Voice 2", "Ouch. Did you ask anyone before starting?", "Ой. Ты спрашивал кого-нибудь до начала?"),
                ("What is the lesson?", [
                    ("No — from now on, I will double-check the format in advance.", True),
                    ("No, I will double-checked it yesterday.", False),
                    ("The word is misreading my report.", False)])]),
            "d": ("to assume", "To think something is true without checking",
                  ["To verify the facts with the teacher", "To read the task twice before starting"]),
            "lw": ("If you ___ the task, you lose time.", "If you misread the task, you lose time.",
                   "misread", ["will misread", "misreaded"]),
            "mw": ("Ask for ___ early, not after the deadline.", "clarification", "cla"),
            "ch": ([("Friend", "I do not understand step three of the task.")], "You",
                   "Email the teacher today — if you wait till Friday, you will lose two days.",
                   ["I emailed her yesterday tomorrow.", "The step is tasking me."]),
        },
    ],

    "A2_STUDY_WRITING_SHORT_PARAGRAPHS": [
        {
            "t": ("Мой первый абзац", "My First Paragraph"),
            "o": ("Рассказать о написании текстов, используя past simple и present perfect.",
                  "Talk about writing using past simple and present perfect."),
            "v": [("topic sentence", "тематическое предложение"), ("supporting sentence", "поддерживающее предложение"),
                  ("linking word", "связующее слово"), ("draft", "черновик"),
                  ("to edit", "отредактировать"), ("paragraph", "абзац"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have written three drafts so far today.",
                  ["I have written three drafts yesterday.", "I write three drafts already so far."]),
            "tr": ("Я написал черновик, а затем отредактировал связующие слова.",
                   "I wrote the draft and then edited the linking words.",
                   ["did", "write", "tomorrow"]),
            "fill": ("The teacher circled my ___ sentence in red last time.", "topic",
                     ["topics", "topical"], "Преподаватель обвёл красным моё тематическое предложение в прошлый раз."),
            "tap": ("She has shortened her paragraph to five sentences.", ["was", "did"]),
            "sh": ("My first paragraph had no structure, but I have rewritten it with a topic sentence and two supporting ones.",
                   "Мой первый абзац не имел структуры, но я переписал его с тематическим предложением и двумя поддерживающими."),
            "st": ("After the Writing Class", [
                ("Voice 1", "How was your first attempt at academic paragraphs?", "Как прошла первая попытка академических абзацев?"),
                ("Voice 2", "Messy — I have read the feedback, and my sentences do not link.",
                 "Беспорядочно — я прочитал отзыв, мои предложения не связаны."),
                ("What does Voice 1 suggest?", [
                    ("Add linking words like 'however' and 'as a result'.", True),
                    ("I added them yesterday tomorrow.", False),
                    ("The paragraphs are linking my feedback.", False)])]),
            "d": ("linking word", "A word that connects ideas, like 'however'",
                  ["The main verb of a sentence", "A word that shows an object in a picture"]),
            "lw": ("I have ___ the draft twice.", "I have edited the draft twice.",
                   "edited", ["edit", "editing"]),
            "mw": ("Start with the ___ sentence.", "topic", "to"),
            "ch": ([("Friend", "How long should the paragraph be?")], "You",
                   "Four to six sentences — I have learned it the hard way after my ten-line monster.",
                   ["I learned it yesterday tomorrow.", "The paragraph is lining me."]),
        },
        {
            "t": ("Пишем лучше", "Writing Better"),
            "o": ("Сравнить версии текста и спланировать практику письма.",
                  "Compare text versions and plan writing practice."),
            "v": [("more concise", "лаконичнее"), ("to cut out", "вырезать (лишнее)"),
                  ("second draft", "второй черновик"), ("wordy", "многословный"),
                  ("to read aloud", "прочитать вслух"), ("clearer", "яснее"),
                  ("sentence variety", "разнообразие предложений")],
            "q": ("Which sentence compares two drafts correctly?",
                  "The second draft is more concise than the first.",
                  ["The second draft is conciser than first.", "The draft is most concise than the first one."]),
            "tr": ("На этой неделе я собираюсь писать по одному абзацу в день.",
                   "This week I am going to write one paragraph a day.",
                   ["did", "wrote", "yesterday"]),
            "fill": ("Short sentences are often ___ than long ones.", "clearer",
                     ["clearest", "more clear"], "Короткие предложения часто яснее длинных."),
            "tap": ("We are going to read our texts aloud in class.", ["was", "did"]),
            "sh": ("If you read the paragraph aloud, every wordy phrase will jump out immediately.",
                   "Если прочитать абзац вслух, каждая многословная фраза сразу бросится в глаза."),
            "st": ("The Two Drafts", [
                ("Voice 1", "Look — my first draft had ninety words; the second has sixty.", "Смотри — в первом черновике было девяносто слов, во втором шестьдесят."),
                ("Voice 2", "And is the meaning still there?", "И смысл сохранился?"),
                ("What does Voice 1 say?", [
                    ("Yes — I cut out the repetitions, and it reads better.", True),
                    ("Yes, I cut them tomorrow yesterday.", False),
                    ("The draft is wording my meaning.", False)])]),
            "d": ("wordy", "Using too many words for a simple idea",
                  ["Clear, short and easy to follow", "Rich in useful examples"]),
            "lw": ("I am going to ___ the empty phrases.", "I am going to cut out the empty phrases.",
                   "cut out", ["cutted out", "cutting out"]),
            "mw": ("The third draft is ___ than the second.", "shorter", "sh"),
            "ch": ([("Classmate", "How do you find weak sentences?")], "You",
                   "I read aloud — if I stumble, the sentence needs editing.",
                   ["I read it yesterday tomorrow.", "The sentence is stumbling me."]),
        },
        {
            "t": ("Если текст не складывается", "If the Text Does Not Come Together"),
            "o": ("Дать советы о письме, используя should и первое условное.",
                  "Give writing advice using should and the first conditional."),
            "v": [("writer's block", "творческий ступор"), ("to brainstorm", "побрейнштормить"),
                  ("outline first", "сначала план"), ("perfect", "идеальный"),
                  ("to polish", "полировать (текст)"), ("messy first draft", "грязный первый черновик"),
                  ("later", "позже")],
            "q": ("Which sentence gives correct writing advice?",
                  "You should write a messy first draft and polish it later.",
                  ["You should to write it yesterday.", "You must writing messy drafts last essay."]),
            "tr": ("Если сначала набросать план, ступор проходит быстрее.",
                   "If you sketch an outline first, the writer's block passes faster.",
                   ["did", "sketched", "yesterday"]),
            "fill": ("If you try to make the first draft ___ , you will never finish it.",
                     "perfect", ["perfectly", "perfecter"], "Если пытаться сделать идеальным первый черновик, он никогда не будет закончен."),
            "tap": ("You should brainstorm for five minutes before writing.", ["mustn't", "went"]),
            "sh": ("If you separate writing from editing, both stages will take half the time.",
                   "Если разделить письмо и редактуру, оба этапа займут вдвое меньше времени."),
            "st": ("The Blank Page", [
                ("Voice 1", "I have been staring at the page for an hour — nothing comes.", "Я час смотрю на страницу — ничего не приходит."),
                ("Voice 2", "Have you tried brainstorming without writing full sentences?", "Пробовал побрейнштормить без полных предложений?"),
                ("What does Voice 1 do?", [
                    ("Good idea — I will list my ideas as single words first.", True),
                    ("I listed them yesterday tomorrow already.", False),
                    ("The page is staring at my ideas.", False)])]),
            "d": ("writer's block", "The state when you cannot start writing",
                  ["The final check of a finished text", "A technique for choosing a title"]),
            "lw": ("If you ___ first, the writing flows.", "If you outline first, the writing flows.",
                   "outline", ["will outline", "outlined"]),
            "mw": ("Polish the text ___ , not during writing.", "later", "la"),
            "ch": ([("Friend", "I keep deleting my first sentences.")], "You",
                   "Stop deleting — write the messy draft to the end, and edit it tomorrow.",
                   ["I deleted them yesterday tomorrow.", "The sentences are deleting me."]),
        },
    ],
}
