#!/usr/bin/env python3
"""A2 regenerated content: SPEAKING PRACTICE (10 tracks x 3 lessons).

Grammar arc per topic: L1 past simple + present perfect,
L2 future forms + comparatives, L3 modals / first conditional.
"""

TRACKS = {
    "A2_SPEAKING_DAILY_HABITS_AND_CHANGES": [
        {
            "t": ("Как изменился мой день", "How My Day Has Changed"),
            "o": ("Рассказать об изменениях в привычках, используя past simple и present perfect.",
                  "Talk about habit changes using past simple and present perfect."),
            "v": [("to give up", "бросить (привычку)"), ("to take up", "начать (новое хобби)"),
                  ("used to", "раньше (делал)"), ("habit", "привычка"),
                  ("morning routine", "утренний ритуал"), ("lately", "в последнее время"),
                  ("to cut down on", "сократить (потребление)")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have given up late-night snacks this month.",
                  ["I have given up them last month.", "I give up snacks already lately."]),
            "tr": ("Раньше я пил три чашки кофе, а теперь сократил до одной.",
                   "I used to drink three cups of coffee, but now I have cut down to one.",
                   ["did", "drink", "yesterday"]),
            "fill": ("Last year she ___ up running in the mornings.", "took",
                     ["has take", "taking"], "В прошлом году она начала бегать по утрам."),
            "tap": ("He has changed his morning routine completely.", ["was", "did"]),
            "sh": ("I used to check my phone in bed, but I have stopped doing it, and my sleep is much better.",
                   "Раньше я листал телефон в кровати, но прекратил это делать, и сон стал гораздо лучше."),
            "st": ("A New Habit", [
                ("Anna", "You look much fitter lately. What has changed?", "В последнее время ты выглядишь стройнее. Что изменилось?"),
                ("Tom", "I have taken up swimming, and I go twice a week.", "Я начал плавать и хожу дважды в неделю."),
                ("What does Anna ask?", [
                    ("How long have you been doing it?", True),
                    ("How long did you do it tomorrow?", False),
                    ("Is the swimming doing you twice a week?", False)])]),
            "d": ("to take up", "To start a new hobby or activity",
                  ["To stop doing something you enjoyed", "To lend something to a friend"]),
            "lw": ("I have ___ up yoga this spring.", "I have taken up yoga this spring.",
                   "taken", ["take", "taking"]),
            "mw": ("She has cut ___ on sugar.", "down", "do"),
            "ch": ([("Friend", "Do you still work late every evening?")], "You",
                   "No, I have changed that — I finish at six now and feel much better.",
                   ["Yes, I change it tomorrow yesterday.", "The evenings are working me."]),
        },
        {
            "t": ("Новые привычки с понедельника", "New Habits From Monday"),
            "o": ("Рассказать о планах изменить привычки и сравнить подходы.",
                  "Talk about plans to change habits and compare approaches."),
            "v": [("gradually", "постепенно"), ("all at once", "всё сразу"),
                  ("more realistic", "реалистичнее"), ("to set a goal", "поставить цель"),
                  ("step by step", "шаг за шагом"), ("to track progress", "отслеживать прогресс"),
                  ("motivation", "мотивация")],
            "q": ("Which sentence compares two approaches correctly?",
                  "Changing habits gradually is more realistic than changing everything at once.",
                  ["Changing gradually is realister than at once.", "Changing gradually is most realistic than all at once."]),
            "tr": ("С понедельника я собираюсь вставать на полчаса раньше — постепенно.",
                   "From Monday I am going to get up half an hour earlier — gradually.",
                   ["did", "got", "yesterday"]),
            "fill": ("Small steps are ___ sustainable than big promises.", "more",
                     ["most", "much"], "Маленькие шаги устойчивее больших обещаний."),
            "tap": ("I am going to track my progress in a simple app.", ["was", "did"]),
            "sh": ("If you set one small goal at a time, you will keep your motivation much longer.",
                   "Если ставить одну маленькую цель за раз, мотивация сохранится гораздо дольше."),
            "st": ("The Monday Plan", [
                ("Anna", "I am going to change five things from Monday — diet, sport, sleep, everything!",
                 "С понедельника меняю пять вещей — питание, спорт, сон, всё!"),
                ("Tom", "All at once? That sounds hard.", "Всё сразу? Звучит тяжело."),
                ("What does Tom advise?", [
                    ("Maybe one change at a time is more realistic.", True),
                    ("Five changes were realistic yesterday tomorrow.", False),
                    ("Monday is changing Anna's things.", False)])]),
            "d": ("gradually", "Slowly, step by step over time",
                  ["Very quickly, in a single day", "Without any plan or goal"]),
            "lw": ("I am going to ___ one small goal.", "I am going to set one small goal.",
                   "set", ["setted", "setting"]),
            "mw": ("One habit at a time is ___ effective.", "more", "mo"),
            "ch": ([("Friend", "I want to start running every day.")], "You",
                   "Start with three days a week — if it feels easy, you will add more naturally.",
                   ["I started it yesterday tomorrow.", "The running is starting me."]),
        },
        {
            "t": ("Хорошая привычка или плохая", "Good Habit or Bad Habit"),
            "o": ("Обсудить привычки, используя should и первое условное.",
                  "Discuss habits using should and the first conditional."),
            "v": [("willpower", "сила воли"), ("to reward yourself", "наградить себя"),
                  ("to skip", "пропустить (занятие)"), ("regularly", "регулярно"),
                  ("to remind", "напомнить"), ("bad habit", "вредная привычка"),
                  ("to stick to", "придерживаться")],
            "q": ("Which sentence gives correct advice?",
                  "You should reward yourself when you keep a habit.",
                  ["You should to reward yourself yesterday.", "You must rewarding yourself last week."]),
            "tr": ("Если ты пропустишь занятие один раз, это не значит, что надо бросать.",
                   "If you skip the session once, it does not mean you should give up.",
                   ["did", "skipped", "yesterday"]),
            "fill": ("If you ___ your habit for a month, it will feel natural.",
                     "keep", ["will keep", "kept"], "Если поддерживать привычку месяц, она станет естественной."),
            "tap": ("You should put your trainers next to the door.", ["mustn't", "went"]),
            "sh": ("If you make the habit smaller, your willpower will need to work less, and you will stick to it.",
                   "Если сделать привычку меньше, сила воли будет нужна реже, и ты сможешь её придерживаться."),
            "st": ("The Skipped Day", [
                ("Anna", "I skipped my English practice yesterday, and today too.", "Я пропустила вчера практику английского, и сегодня тоже."),
                ("Tom", "That happens. What should you do next?", "Так бывает. Что делать дальше?"),
                ("What is the best advice?", [
                    ("You should do just five minutes today to restart.", True),
                    ("You must doing five minutes yesterday.", False),
                    ("The practice is skipping you back.", False)])]),
            "d": ("willpower", "The mental strength to do something difficult",
                  ["A reward you get for good results", "A habit you do without thinking"]),
            "lw": ("If you ___ yourself after each week, habits stick.", "If you reward yourself after each week, habits stick.",
                   "reward", ["will reward", "rewarded"]),
            "mw": ("You should stick ___ the plan for a month.", "to", "to"),
            "ch": ([("Friend", "I keep forgetting to do my exercises.")], "You",
                   "Set a phone reminder — if it rings at the same time daily, you will remember.",
                   ["I set it yesterday tomorrow.", "The exercises are forgetting me."]),
        },
    ],

    "A2_SPEAKING_DESCRIBING_PEOPLE": [
        {
            "t": ("Какой он человек", "What Kind of Person He Is"),
            "o": ("Описать характер человека, используя past simple и present perfect.",
                  "Describe someone's character using past simple and present perfect."),
            "v": [("easy-going", "легкий в общении"), ("stubborn", "упрямый"),
                  ("to get to know", "узнать поближе"), ("sense of humour", "чувство юмора"),
                  ("reliable", "надёжный"), ("quiet", "тихий / спокойный"),
                  ("confident", "уверенный")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have known her since our first job.",
                  ["I have known her last year.", "I know her since three years already."]),
            "tr": ("Сначала он показался тихим, но за месяц мы узнали его чувство юмора.",
                   "At first he seemed quiet, but within a month we have discovered his sense of humour.",
                   ["did", "seem", "yesterday"]),
            "fill": ("My grandmother has always been very ___ .", "reliable",
                     ["reliably", "reliables"], "Моя бабушка всегда была очень надёжной."),
            "tap": ("She has become much more confident this year.", ["was", "did"]),
            "sh": ("He used to be stubborn as a child, but he has grown into an easy-going adult.",
                   "В детстве он был упрямым, но вырос лёгким в общении человеком."),
            "st": ("The New Colleague", [
                ("Anna", "What is your new flatmate like?", "Какой твой новый сосед по квартире?"),
                ("Tom", "Very easy-going. We have shared the flat for two months already.", "Очень лёгкий в общении. Мы живём вместе уже два месяца."),
                ("What does Anna ask?", [
                    ("Has he ever annoyed you with anything?", True),
                    ("Did he has annoyed you tomorrow?", False),
                    ("Is the flat sharing him with you?", False)])]),
            "d": ("stubborn", "Not changing your opinion easily",
                  ["Always agreeing with everything", "Happy to try new ideas at once"]),
            "lw": ("She has ___ more talkative lately.", "She has become more talkative lately.",
                   "become", ["became", "becoming"]),
            "mw": ("I have known him ___ ten years.", "for", "fo"),
            "ch": ([("Friend", "Tell me about your new teacher.")], "You",
                   "She is strict but fair — the lessons have been the most useful I have ever had.",
                   ["She was it yesterday tomorrow.", "The teacher is telling me."]),
        },
        {
            "t": ("Кто на кого похож", "Who Takes After Whom"),
            "o": ("Сравнить людей по характеру и внешности.",
                  "Compare people by character and appearance."),
            "v": [("to look like", "быть похожим на"), ("to take after", "пойти в (родителя)"),
                  ("taller", "выше"), ("curly", "кудрявый"),
                  ("more patient", "терпеливее"), ("as calm as", "спокойный как"),
                  ("twins", "близнецы")],
            "q": ("Which sentence compares people correctly?",
                  "My brother is taller than my father.",
                  ["My brother is more tall than my father.", "My brother is tallest than my father."]),
            "tr": ("Младшая сестра пошла в маму — такая же спокойная и терпеливая.",
                   "My younger sister takes after our mother — she is just as calm and patient.",
                   ["did", "take", "yesterday"]),
            "fill": ("My cousin has ___ hair and green eyes.", "curly",
                     ["curls", "curlily"], "У моей кузины кудрявые волосы и зелёные глаза."),
            "tap": ("My son is going to be taller than me, I think.", ["was", "did"]),
            "sh": ("People say I look like my grandfather, but my character is more like my grandmother's.",
                   "Говорят, я похож на дедушку, но характер у меня скорее как у бабушки."),
            "st": ("Family Resemblance", [
                ("Anna", "Your daughter has curly hair — does she take after you?", "У твоей дочери кудрявые волосы — она в тебя?"),
                ("Tom", "Not me! Her mother has exactly the same hair.", "Не в меня! У её мамы точно такие же волосы."),
                ("What does Anna say?", [
                    ("And what about her character — is she as patient as you?", True),
                    ("And her character was patient tomorrow yesterday.", False),
                    ("Is the hair taking after the character?", False)])]),
            "d": ("to take after", "To be similar to an older relative",
                  ["To look after someone's pet for a week", "To follow someone into a room"]),
            "lw": ("He is going to ___ after his grandfather.", "He is going to take after his grandfather.",
                   "take", ["took", "taking"]),
            "mw": ("My mother is ___ patient than me.", "more", "mo"),
            "ch": ([("Friend", "Do you look like your sister?")], "You",
                   "A little, but she is taller and much more confident than me.",
                   ["I looked like her yesterday tomorrow.", "My sister is looking me."]),
        },
        {
            "t": ("Не суди по внешности", "Do Not Judge by Appearance"),
            "o": ("Дать советы о впечатлениях о людях, используя should и первое условное.",
                  "Give advice about impressions using should and the first conditional."),
            "v": [("first impression", "первое впечатление"), ("to judge", "судить"),
                  ("appearance", "внешность"), ("to get to know", "узнать (человека)"),
                  ("shy", "стеснительный"), ("to turn out", "оказаться"),
                  ("kind", "добрый")],
            "q": ("Which sentence gives correct advice?",
                  "You should not judge people by their appearance.",
                  ["You should to judge them yesterday.", "You not should judging people last week."]),
            "tr": ("Если ты дашь человеку второй шанс, он может оказаться очень добрым.",
                   "If you give a person a second chance, they may turn out to be very kind.",
                   ["did", "gave", "yesterday"]),
            "fill": ("If she ___ shy at first, talk to her about books.", "seems",
                     ["will seem", "seemed"], "Если она покажется стеснительной, поговори с ней о книгах."),
            "tap": ("You should look further than the first impression.", ["mustn't", "went"]),
            "sh": ("If you talk to him for five minutes, your first impression will completely change.",
                   "Если поговорить с ним пять минут, первое впечатление полностью изменится."),
            "st": ("The Quiet Neighbour", [
                ("Anna", "Our new neighbour seemed unfriendly on day one.", "Новый сосед показался недружелюбным в первый день."),
                ("Tom", "Has he done anything since then?", "Он с тех пор что-нибудь сделал?"),
                ("What does Anna say?", [
                    ("Yes — he has helped me carry the shopping twice, so I was wrong about him.", True),
                    ("Yes, he helps me tomorrow yesterday.", False),
                    ("The first impression is carrying the shopping.", False)])]),
            "d": ("shy", "Not comfortable talking to new people",
                  ["Very loud at every party", "Always the first to start a conversation"]),
            "lw": ("If you ___ to know him, you will like him.", "If you get to know him, you will like him.",
                   "get", ["will get", "got"]),
            "mw": ("You should not judge people ___ their looks.", "by", "by"),
            "ch": ([("Friend", "My new classmate never talks to anyone.")], "You",
                   "Give her time — if you ask about her drawings, she will open up.",
                   ["She talked yesterday tomorrow.", "The classmate is judging me."]),
        },
    ],

    "A2_SPEAKING_EVERYDAY_PROBLEMS_AND_SOLUTIONS": [
        {
            "t": ("Мелкие беды недели", "This Week's Small Disasters"),
            "o": ("Рассказать о бытовых проблемах, используя past simple и present perfect.",
                  "Talk about everyday problems using past simple and present perfect."),
            "v": [("to leak", "протекать"), ("to flood", "залить (водой)"),
                  ("to break", "сломаться"), ("plumber", "сантехник"),
                  ("to solve", "решить (проблему)"), ("handyman", "мастер на все руки"),
                  ("in the end", "в итоге")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The washing machine has broken down again.",
                  ["The washing machine has broke yesterday.", "The machine break down already again."]),
            "tr": ("Кран протекал всю ночь, и к утру мы вызвали сантехника.",
                   "The tap leaked all night, and by morning we had called a plumber.",
                   ["did", "leaks", "tomorrow"]),
            "fill": ("Last winter the pipes ___ and the kitchen floor was wet.", "froze",
                     ["has frozen", "freezing"], "Прошлой зимой трубы замёрзли, и пол на кухне был мокрым."),
            "tap": ("I have just fixed the lamp myself.", ["was", "did"]),
            "sh": ("The neighbour's washing machine has flooded our bathroom, and the handyman has already come twice.",
                   "Стиральная машина соседей затопила нашу ванную, и мастер уже приходил дважды."),
            "st": ("The Leaking Fridge", [
                ("Anna", "There is water under the fridge again.", "Под холодильником снова вода."),
                ("Tom", "The technician came on Monday, didn't he?", "Техник же приходил в понедельник?"),
                ("What does Anna say?", [
                    ("Yes, but the problem has not gone away — we should call the shop.", True),
                    ("Yes, but it will gone away tomorrow yesterday.", False),
                    ("The fridge is calling the technician itself.", False)])]),
            "d": ("plumber", "A person whose job is fixing water pipes",
                  ["A person who repairs cars in a garage", "A person who paints house walls"]),
            "lw": ("The pipe has ___ again.", "The pipe has leaked again.",
                   "leaked", ["leak", "leaking"]),
            "mw": ("We have called a ___ twice this month.", "handyman", "ha"),
            "ch": ([("Friend", "My laptop screen went black yesterday.")], "You",
                   "That happened to me too — I have found a cheap repair shop near the station.",
                   ["It happens me tomorrow yesterday.", "The screen is calling the shop."]),
        },
        {
            "t": ("Куда обратиться", "Where to Turn"),
            "o": ("Сравнить способы решения бытовых проблем и спланировать действия.",
                  "Compare ways of solving household problems and plan actions."),
            "v": [("cheaper", "дешевле"), ("to repair yourself", "починить самому"),
                  ("to call a professional", "вызвать специалиста"), ("to watch a tutorial", "посмотреть обучающее видео"),
                  ("more dangerous", "опаснее"), ("instruction manual", "инструкция"),
                  ("to save money", "сэкономить деньги")],
            "q": ("Which sentence compares two ways correctly?",
                  "Fixing it yourself is cheaper than calling a professional.",
                  ["Fixing yourself is more cheap than a professional.", "Fixing yourself is cheapest than calling."]),
            "tr": ("Я собираюсь посмотреть видео-инструкцию и попробовать починить сам.",
                   "I am going to watch a tutorial and try to fix it myself.",
                   ["did", "watched", "yesterday"]),
            "fill": ("Repairing electricity yourself is ___ than calling an electrician.", "more dangerous",
                     ["dangerousest", "much"], "Чинить электричество самому опаснее, чем вызывать электрика."),
            "tap": ("We are going to read the instruction manual first.", ["was", "did"]),
            "sh": ("If you watch a good tutorial first, you will save fifty euros on a simple repair.",
                   "Если сначала посмотреть хорошее обучающее видео, сэкономишь пятьдесят евро на простом ремонте."),
            "st": ("DIY or Not?", [
                ("Anna", "The door handle is broken. Should we call someone?", "Ручка двери сломана. Вызвать кого-то?"),
                ("Tom", "A professional is expensive, and the handle is a simple part.", "Специалист дорогой, а ручка — простая деталь."),
                ("What does Anna decide?", [
                    ("Then we are going to watch a tutorial and try it ourselves.", True),
                    ("Then we watched a tutorial yesterday tomorrow.", False),
                    ("The handle is repairing the door.", False)])]),
            "d": ("tutorial", "A video that shows you how to do something",
                  ["A film about old houses", "An advertisement for repair services"]),
            "lw": ("I am going to ___ it myself.", "I am going to repair it myself.",
                   "repair", ["repaired", "repairing"]),
            "mw": ("Calling a professional is ___ for gas problems.", "safer", "sa"),
            "ch": ([("Friend", "The tap is dripping — is it hard to fix?")], "You",
                   "Usually no — if you watch a five-minute tutorial, you will manage it.",
                   ["I fixed it yesterday tomorrow.", "The tap is dripping me."]),
        },
        {
            "t": ("Если проблема не решается", "If the Problem Will Not Go Away"),
            "o": ("Обсудить затяжные проблемы, используя should и первое условное.",
                  "Discuss stubborn problems using should and the first conditional."),
            "v": [("to give up", "сдаваться"), ("to ask for help", "попросить помощи"),
                  ("neighbour", "сосед"), ("to make worse", "усугубить"),
                  ("patient", "терпеливый"), ("temporary solution", "временное решение"),
                  ("properly", "как следует")],
            "q": ("Which sentence gives correct advice?",
                  "You should ask for help before the problem gets worse.",
                  ["You should to ask yesterday before.", "You must asking help last week."]),
            "tr": ("Если мы просто заклеим трубу изолентой, проблема вернётся через неделю.",
                   "If we just tape the pipe, the problem will come back in a week.",
                   ["did", "taped", "yesterday"]),
            "fill": ("If you ___ the machine now, the repair will cost more later.",
                     "ignore", ["will ignore", "ignored"], "Если игнорировать поломку сейчас, ремонт позже обойдётся дороже."),
            "tap": ("You should fix the cause, not the symptom.", ["mustn't", "went"]),
            "sh": ("If the temporary solution has not worked for a month, you should call a professional properly.",
                   "Если временное решение не сработало за месяц, стоит как следует вызвать специалиста."),
            "st": ("The Third Visit", [
                ("Anna", "This is the third time the lock has stuck this month.", "Это третий раз за месяц, когда замок заедает."),
                ("Tom", "The oil is only a temporary solution.", "Масло — лишь временное решение."),
                ("What should they do?", [
                    ("We should change the lock completely before winter.", True),
                    ("We must changed it yesterday already.", False),
                    ("The lock is oiling itself monthly.", False)])]),
            "d": ("temporary", "Lasting only for a short time",
                  ["Working well for many years", "Bought with a lifetime guarantee"]),
            "lw": ("If the noise ___ , we will talk to the neighbours.", "If the noise continues, we will talk to the neighbours.",
                   "continues", ["will continue", "continued"]),
            "mw": ("You should ask your ___ for help.", "neighbour", "ne"),
            "ch": ([("Friend", "The radiator is cold again this winter.")], "You",
                   "Bleed it once — if it stays cold after that, we should call the building service.",
                   ["I bled it yesterday tomorrow.", "The radiator is wintering us."]),
        },
    ],

    "A2_SPEAKING_FAMILY_LIFE": [
        {
            "t": ("Новости из семьи", "Family News"),
            "o": ("Поделиться семейными новостями, используя past simple и present perfect.",
                  "Share family news using past simple and present perfect."),
            "v": [("to get married", "пожениться"), ("to move out", "переехать (от родителей)"),
                  ("grandparents", "бабушка и дедушка"), ("to have a baby", "родить ребёнка"),
                  ("cousin", "двоюродный брат/сестра"), ("to visit", "навестить"),
                  ("family gathering", "семейный сбор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "My sister has just had a baby.",
                  ["My sister has a baby last month.", "My sister just has had a baby yesterday."]),
            "tr": ("Мой брат переехал в другой город, когда женился.",
                   "My brother moved to another city when he got married.",
                   ["did", "moves", "tomorrow"]),
            "fill": ("We ___ our grandparents every summer when we were children.", "visited",
                     ["has visit", "visiting"], "Мы навещали бабушку с дедушкой каждое лето в детстве."),
            "tap": ("The whole family has gathered at our house today.", ["was", "did"]),
            "sh": ("My cousin has bought a house near the lake, and the family gathering this year has moved there.",
                   "Мой двоюродный брат купил дом у озера, и семейный сбор в этом году переехал туда."),
            "st": ("Sunday Call", [
                ("Anna", "Any news from your family this week?", "Есть новости от семьи на этой неделе?"),
                ("Tom", "Yes! My cousin has got engaged, and my parents have already met the fiancée.",
                 "Да! Мой кузен сделал предложение, а родители уже познакомились с невестой."),
                ("What does Anna ask?", [
                    ("When did they meet her — at the weekend?", True),
                    ("When do they met her tomorrow?", False),
                    ("Is the news meeting the fiancée?", False)])]),
            "d": ("to get married", "To become someone's husband or wife",
                  ["To go on a first date with someone", "To divorce after many years"]),
            "lw": ("She has ___ into a new flat.", "She has moved into a new flat.",
                   "moved", ["move", "moving"]),
            "mw": ("They have ___ a baby girl.", "had", "ha"),
            "ch": ([("Friend", "How is your brother doing?")], "You",
                   "Great — he has changed jobs and has moved closer to our parents.",
                   ["He is fine yesterday tomorrow.", "The brother is doing me."]),
        },
        {
            "t": ("Планы на семейный праздник", "Planning a Family Celebration"),
            "o": ("Спланировать семейное событие и сравнить варианты.",
                  "Plan a family event and compare options."),
            "v": [("to host", "принять (гостей)"), ("potluck dinner", "ужин, куда каждый приносит блюдо"),
                  ("more fun", "веселее"), ("to invite", "пригласить"),
                  ("anniversary", "годовщина"), ("to cook", "готовить"),
                  ("to hire a venue", "арендовать зал")],
            "q": ("Which sentence compares two celebration ideas correctly?",
                  "A garden party is more fun than a formal restaurant dinner.",
                  ["A garden party is funner than a dinner.", "A garden party is most fun than dinner."]),
            "tr": ("В этом году мы собираемся устроить ужин, куда каждый принесёт своё блюдо.",
                   "This year we are going to host a potluck dinner.",
                   ["did", "hosted", "yesterday"]),
            "fill": ("A homemade cake is ___ personal than a shop one.", "more",
                     ["most", "much"], "Домашний торт более личный, чем покупной."),
            "tap": ("We are going to invite all the cousins.", ["was", "did"]),
            "sh": ("If we celebrate in the garden, the children will have more space to play.",
                   "Если отметить в саду, у детей будет больше места для игр."),
            "st": ("The Anniversary", [
                ("Anna", "It is our grandparents' fiftieth anniversary in May.", "В мае пятидесятилетие наших бабушки и дедушки."),
                ("Tom", "Should we book a restaurant or host it at home?", "Забронировать ресторан или устроить дома?"),
                ("What does Anna prefer?", [
                    ("At home — it is more work, but it feels more personal.", True),
                    ("A restaurant was more personal yesterday tomorrow.", False),
                    ("The anniversary is hosting a restaurant.", False)])]),
            "d": ("potluck dinner", "A meal where every guest brings one dish",
                  ["A dinner cooked only by the hosts", "A dinner ordered from a restaurant"]),
            "lw": ("We are going to ___ twenty guests.", "We are going to invite twenty guests.",
                   "invite", ["invited", "inviting"]),
            "mw": ("Grandma's cake is ___ than the bakery's.", "better", "be"),
            "ch": ([("Friend", "Are you hosting New Year this year?")], "You",
                   "Yes — if everyone brings one dish, the cooking will be much easier.",
                   ["I hosted it yesterday tomorrow.", "New Year is hosting us."]),
        },
        {
            "t": ("Семейные правила", "Family Rules"),
            "o": ("Обсудить правила в семье, используя should и первое условное.",
                  "Discuss family rules using should and the first conditional."),
            "v": [("to share chores", "делить домашние дела"), ("screen time", "время у экрана"),
                  ("fair", "справедливый"), ("to negotiate", "договориться"),
                  ("bedtime", "время отхода ко сну"), ("pocket money", "карманные деньги"),
                  ("to respect", "уважать")],
            "q": ("Which sentence expresses a family rule?",
                  "Children should help with the chores at the weekend.",
                  ["Children should to help yesterday.", "Children must helping last weekend."]),
            "tr": ("если дети будут помогать по дому, у родителей будет больше времени на семью.",
                   "If the children help with the housework, the parents will have more time for the family.",
                   ["did", "helped", "yesterday"]),
            "fill": ("If everyone ___ the chores, the flat will be clean by evening.",
                     "shares", ["will share", "shared"], "Если все поделят домашние дела, квартира будет чистой к вечеру."),
            "tap": ("You should respect each other's free time.", ["mustn't", "went"]),
            "sh": ("If we agree on the screen-time rules together, the children will follow them more easily.",
                   "Если договориться о правилах экранного времени вместе, детям будет проще их соблюдать."),
            "st": ("The Chore Chart", [
                ("Anna", "I do all the cleaning alone, and it is not fair.", "Я делаю всю уборку одна, и это несправедливо."),
                ("Tom", "What should we change?", "Что нам изменить?"),
                ("What does Anna propose?", [
                    ("If we make a chore chart, everyone will have one task.", True),
                    ("If we will make a chart, everyone had a task yesterday.", False),
                    ("The cleaning is charting us weekly.", False)])]),
            "d": ("pocket money", "Small regular money that parents give children",
                  ["The money a family spends on food", "A bank loan for a new flat"]),
            "lw": ("If you ___ your bedtime, you will feel better.", "If you keep your bedtime, you will feel better.",
                   "keep", ["will keep", "kept"]),
            "mw": ("We should share the ___ fairly.", "chores", "ch"),
            "ch": ([("Friend", "My kids watch cartoons all evening.")], "You",
                   "Set a simple rule — if they finish homework first, they will get their screen time without arguments.",
                   ["They watched them yesterday tomorrow.", "The cartoons are ruling the kids."]),
        },
    ],

    "A2_SPEAKING_FUTURE_PLANS": [
        {
            "t": ("Что я уже сделал для цели", "What I Have Already Done for the Goal"),
            "o": ("Рассказать о подготовке к планам, используя past simple и present perfect.",
                  "Talk about preparation for plans using past simple and present perfect."),
            "v": [("to save up", "копить (деньги)"), ("to apply for a course", "подать документы на курс"),
                  ("goal", "цель"), ("to enrol", "записаться (на учёбу)"),
                  ("to book in advance", "забронировать заранее"), ("step", "шаг"),
                  ("achieved", "достигнутый")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have saved up half of the money for the car.",
                  ["I have saved up it last month.", "I save up half already now."]),
            "tr": ("Я записался на курсы вождения и уже прошёл теорию.",
                   "I enrolled in a driving course and have already passed the theory.",
                   ["did", "enrols", "tomorrow"]),
            "fill": ("She applied for the language course three weeks ___ .", "ago",
                     ["since", "before"], "Она подала документы на языковой курс три недели назад."),
            "tap": ("We have taken the first step towards our goal.", ["was", "did"]),
            "sh": ("I started saving in January, and I have already reached a third of my goal.",
                   "Я начал копить в январе и уже достиг трети своей цели."),
            "st": ("The Big Plan", [
                ("Anna", "So, the plan is to open a small cafe next year. What have you done so far?",
                 "Итак, план — открыть небольшое кафе в следующем году. Что ты уже сделал?"),
                ("Tom", "I have written the business plan and found two possible locations.",
                 "Я написал бизнес-план и нашёл два возможных места."),
                ("What does Anna ask?", [
                    ("Have you compared the rents yet?", True),
                    ("Did you has compared them tomorrow?", False),
                    ("Is the plan opening the cafe itself?", False)])]),
            "d": ("to enrol", "To officially join a course or school",
                  ["To leave a course before it finishes", "To teach a course to others"]),
            "lw": ("I have ___ in a cooking course.", "I have enrolled in a cooking course.",
                   "enrolled", ["enrol", "enrolling"]),
            "mw": ("She has saved ___ 500 euros.", "up", "up"),
            "ch": ([("Friend", "How are your plans for the move going?")], "You",
                   "Slowly but surely — I have packed the books and have sold the old sofa.",
                   ["I pack them yesterday tomorrow.", "The plans are moving me."]),
        },
        {
            "t": ("Планы на год", "Plans for the Year"),
            "o": ("Рассказать о планах и сравнить варианты будущего.",
                  "Talk about plans and compare future options."),
            "v": [("to move abroad", "переехать за границу"), ("safer", "безопаснее (вариант)"),
                  ("more exciting", "интереснее"), ("to change jobs", "сменить работу"),
                  ("to be going to", "собираться"), ("opportunity", "возможность"),
                  ("in five years", "через пять лет")],
            "q": ("Which sentence talks about a plan?",
                  "I am going to change jobs in September.",
                  ["I changed jobs in September last year.", "I has changed jobs tomorrow already."]),
            "tr": ("Мы собираемся переехать к морю, хотя жизнь там дороже.",
                   "We are going to move to the coast, although life there is more expensive.",
                   ["did", "moved", "yesterday"]),
            "fill": ("Staying in the same job is ___ than starting a business.", "safer",
                     ["safest", "more safe"], "Остаться на той же работе безопаснее, чем открыть своё дело."),
            "tap": ("They are going to buy a small house in the village.", ["was", "did"]),
            "sh": ("If I get this opportunity, I am going to take it, even if it is the harder choice.",
                   "Если представится такая возможность, я ею воспользуюсь, даже если это более сложный выбор."),
            "st": ("Two Paths", [
                ("Anna", "Next year I can either study abroad or stay and work.", "В следующем году я могу либо учиться за границей, либо остаться и работать."),
                ("Tom", "Studying is more expensive, but it opens more doors.", "Учёба дороже, но открывает больше дверей."),
                ("What does Anna think?", [
                    ("True — and if I stay, I will always wonder about the other path.", True),
                    ("True, and I stayed there yesterday tomorrow.", False),
                    ("Is the path studying me next year?", False)])]),
            "d": ("opportunity", "A chance to do something good",
                  ["A problem that blocks your plans", "A rule that limits your choices"]),
            "lw": ("I am going to ___ jobs in autumn.", "I am going to change jobs in autumn.",
                   "change", ["changed", "changing"]),
            "mw": ("The city job is ___ paid than the village one.", "better", "be"),
            "ch": ([("Friend", "Any big plans for the summer?")], "You",
                   "Yes — we are going to visit my in-laws, and if we save enough, we will add a week by the sea.",
                   ["We visited them yesterday tomorrow.", "The summer is planning us."]),
        },
        {
            "t": ("Если план не сбудется", "If the Plan Does Not Work Out"),
            "o": ("Обсудить запасные планы, используя should и первое условное.",
                  "Discuss backup plans using should and the first conditional."),
            "v": [("plan B", "запасной план"), ("to fail", "провалиться (о плане)"),
                  ("to prepare for the worst", "готовиться к худшему"), ("to learn from", "извлечь урок из"),
                  ("to adapt", "адаптироваться"), ("positive", "позитивный"),
                  ("to give up", "сдаваться")],
            "q": ("Which sentence gives correct advice?",
                  "You should always have a plan B.",
                  ["You should to have it yesterday.", "You must having it last year."]),
            "tr": ("Если план провалится, мы извлечём урок и попробуем снова.",
                   "If the plan fails, we will learn from it and try again.",
                   ["did", "failed", "yesterday"]),
            "fill": ("If the visa ___ refused, we will travel inside the country.",
                     "is", ["will be", "was"], "Если виза будет отклонена, мы попутешествуем по стране."),
            "tap": ("You should prepare for both outcomes.", ["mustn't", "went"]),
            "sh": ("If one door closes, another one will open — but only for people who keep looking.",
                   "Если одна дверь закрывается, откроется другая — но только для тех, кто продолжает искать."),
            "st": ("The Rejected Application", [
                ("Anna", "The embassy has refused our visa application.", "Посольство отклонило нашу заявку на визу."),
                ("Tom", "That is disappointing. What is our plan B?", "Это разочаровывает. Каков наш запасной план?"),
                ("What does Anna say?", [
                    ("If we cannot appeal, we will discover our own region instead.", True),
                    ("If we appealed it tomorrow yesterday, all was fine.", False),
                    ("The visa is planning our region.", False)])]),
            "d": ("plan B", "An alternative plan if the first one fails",
                  ["The first and best plan you make", "A plan you never intend to use"]),
            "lw": ("If the course ___ , we will find a tutor.", "If the course is full, we will find a tutor.",
                   "is full", ["will be full", "was full"]),
            "mw": ("You should never give ___ after one failure.", "up", "up"),
            "ch": ([("Friend", "I did not pass the entrance exam.")], "You",
                   "Do not give up — if you try again in spring, you will be twice as prepared.",
                   ["I passed it yesterday tomorrow.", "The exam is giving up me."]),
        },
    ],

    "A2_SPEAKING_HEALTH_AND_FEELINGS": [
        {
            "t": ("Как я себя чувствую", "How I Have Been Feeling"),
            "o": ("Рассказать о самочувствии, используя past simple и present perfect.",
                  "Talk about health using past simple and present perfect."),
            "v": [("to catch a cold", "простудиться"), ("symptoms", "симптомы"),
                  ("to recover", "поправиться"), ("prescription", "рецепт"),
                  ("to feel dizzy", "чувствовать головокружение"), ("appointment with a doctor", "приём у врача"),
                  ("twice a year", "дважды в год")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have had a sore throat since Monday.",
                  ["I have a sore throat yesterday.", "I have sore throat since Monday already."]),
            "tr": ("Я простудился на прошлой неделе, но уже почти выздоровел.",
                   "I caught a cold last week, but I have almost recovered.",
                   ["did", "catch", "tomorrow"]),
            "fill": ("The doctor ___ me a prescription for the cough.", "gave",
                     ["has give", "giving"], "Врач выписал мне рецепт от кашля."),
            "tap": ("She has already made an appointment with the doctor.", ["was", "did"]),
            "sh": ("The symptoms have almost disappeared, but I have stayed at home for the whole week.",
                   "Симптомы почти исчезли, но я оставался дома всю неделю."),
            "st": ("At the Surgery", [
                ("Doctor", "What seems to be the problem today?", "Что вас беспокоит сегодня?"),
                ("Patient", "I have had a headache and felt dizzy since Tuesday.",
                 "У меня болит голова и кружится с вторника."),
                ("What does the doctor ask?", [
                    ("Have you taken any medicine so far?", True),
                    ("Did you has taken it tomorrow?", False),
                    ("Is the headache visiting you today?", False)])]),
            "d": ("prescription", "A doctor's paper that lets you get medicine",
                  ["A note that frees you from work", "A list of exercises from a trainer"]),
            "lw": ("I have ___ a cold twice this winter.", "I have caught a cold twice this winter.",
                   "caught", ["catch", "catching"]),
            "mw": ("He has ___ from the flu.", "recovered", "re"),
            "ch": ([("Friend", "You sound terrible!")], "You",
                   "Thanks — I have had this cough for a week, and I am seeing the doctor tomorrow.",
                   ["I sound it yesterday tomorrow.", "The cough is sounding me."]),
        },
        {
            "t": ("Здоровые привычки", "Healthy Habits"),
            "o": ("Сравнить подходы к здоровью и рассказать о планах.",
                  "Compare health approaches and talk about plans."),
            "v": [("workout", "тренировка"), ("more energetic", "энергичнее"),
                  ("to join a gym", "записаться в спортзал"), ("balanced diet", "сбалансированное питание"),
                  ("to cut out", "полностью убрать (из рациона)"), ("sleep schedule", "режим сна"),
                  ("regularly", "регулярно")],
            "q": ("Which sentence compares two options correctly?",
                  "Exercising outdoors is more enjoyable than a gym for me.",
                  ["Outdoors is enjoyabler than the gym.", "Outdoors is most enjoyable than gym."]),
            "tr": ("Я собираюсь записаться в спортзал и наладить режим сна.",
                   "I am going to join a gym and fix my sleep schedule.",
                   ["did", "joined", "yesterday"]),
            "fill": ("A balanced diet is ___ important than any supplement.", "more",
                     ["most", "much"], "Сбалансированное питание важнее любых добавок."),
            "tap": ("He is going to work out three times a week.", ["was", "did"]),
            "sh": ("If you walk to work instead of driving, you will feel more energetic without a gym.",
                   "Если ходить на работу пешком вместо машины, будешь энергичнее без спортзала."),
            "st": ("The Fitness Decision", [
                ("Anna", "Have you decided — the gym or the swimming pool?", "Ты решил — спортзал или бассейн?"),
                ("Tom", "The pool is more expensive, but swimming is easier on my knees.",
                 "Бассейн дороже, но плавание легче для моих коленей."),
                ("What does Tom decide?", [
                    ("I am going to join the pool from Monday.", True),
                    ("I joined it yesterday tomorrow.", False),
                    ("The knees are swimming in the pool.", False)])]),
            "d": ("balanced diet", "Eating different healthy foods in the right amounts",
                  ["Eating only one type of food all week", "Skipping meals to lose weight fast"]),
            "lw": ("I am going to ___ a gym this month.", "I am going to join a gym this month.",
                   "join", ["joined", "joining"]),
            "mw": ("She feels ___ after the workouts.", "stronger", "st"),
            "ch": ([("Friend", "I want to start eating better.")], "You",
                   "Start small — if you add one vegetable meal a day, you will not even miss the old food.",
                   ["I started it yesterday tomorrow.", "The food is eating me."]),
        },
        {
            "t": ("Если заболеешь", "If You Fall Ill"),
            "o": ("Объяснить действия при болезни, используя should и первое условное.",
                  "Explain what to do when ill using should and the first conditional."),
            "v": [("to stay in bed", "оставаться в постели"), ("fever", "жар"),
                  ("to call in sick", "сообщить о болезни на работе"), ("medicine", "лекарство"),
                  ("rest", "отдых"), ("to get worse", "ухудшиться"),
                  ("within a week", "в течение недели")],
            "q": ("Which sentence gives correct advice?",
                  "You should call in sick if you have a fever.",
                  ["You should to call yesterday.", "You must calling in sick last week."]),
            "tr": ("Если жар не пройдёт за три дня, обратитесь к врачу.",
                   "If the fever does not go within three days, you should see a doctor.",
                   ["did", "went", "yesterday"]),
            "fill": ("If you ___ medicine with food, it will not upset your stomach.",
                     "take", ["will take", "took"], "Если принимать лекарство с едой, оно не будет раздражать желудок."),
            "tap": ("You should rest and drink plenty of liquids.", ["mustn't", "went"]),
            "sh": ("If you go to work with a fever, you will recover more slowly and may infect your colleagues.",
                   "Если пойти на работу с жаром, выздоровление пойдёт медленнее, и можно заразить коллег."),
            "st": ("The Monday Fever", [
                ("Anna", "I feel awful, but the report is due today.", "Мне ужасно плохо, но отчёт нужно сдать сегодня."),
                ("Tom", "If you have a fever, you should call in sick.", "Если у тебя жар, стоит взять больничный."),
                ("What does Anna decide?", [
                    ("You are right — if I stay in bed, I will be back by Thursday.", True),
                    ("I will stayed in bed yesterday tomorrow.", False),
                    ("The report is having my fever.", False)])]),
            "d": ("to call in sick", "To phone work to say you are ill",
                  ["To arrive at work later than usual", "To cancel a meeting because of a holiday"]),
            "lw": ("If the symptoms ___ worse, call an ambulance.", "If the symptoms get worse, call an ambulance.",
                   "get", ["will get", "got"]),
            "mw": ("You should take the ___ twice a day.", "medicine", "me"),
            "ch": ([("Friend", "My headache has lasted two days.")], "You",
                   "You should see a doctor — if it is a migraine, they can prescribe something stronger.",
                   ["I saw one yesterday tomorrow.", "The headache is prescribing me."]),
        },
    ],

    "A2_SPEAKING_HOBBIES_AND_FREE_TIME": [
        {
            "t": ("Моё хобби сейчас", "My Hobby Now"),
            "o": ("Рассказать о хобби, используя past simple и present perfect.",
                  "Talk about hobbies using past simple and present perfect."),
            "v": [("to be into", "увлекаться"), ("to join a club", "вступить в клуб"),
                  ("pottery", "гончарное дело"), ("to improve", "улучшиться"),
                  ("collection", "коллекция"), ("hobby", "хобби"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have collected over a hundred stamps so far.",
                  ["I have collected them last year.", "I collect hundred stamps already so far."]),
            "tr": ("Я увлёкся фотографией год назад и уже продал две работы.",
                   "I got into photography a year ago and have already sold two prints.",
                   ["did", "get", "tomorrow"]),
            "fill": ("She ___ the chess club at university.", "joined",
                     ["has join", "joining"], "Она вступила в шахматный клуб в университете."),
            "tap": ("He has improved a lot since the autumn.", ["was", "did"]),
            "sh": ("I started pottery in spring, and I have already made a full dinner set for my mother.",
                   "Я начал заниматься гончаркой весной и уже сделал полный обеденный сервиз для мамы."),
            "st": ("The New Hobby", [
                ("Anna", "I hear you have taken up pottery. How is it going?", "Слышала, ты занялся гончаркой. Как дела?"),
                ("Tom", "Great! My first cups looked like stones, but I have improved a lot.",
                 "Отлично! Мои первые чашки были как камни, но я сильно продвинулся."),
                ("What does Anna ask?", [
                    ("Have you sold anything at the local market yet?", True),
                    ("Did you has sold anything tomorrow?", False),
                    ("Are the cups improving you at the market?", False)])]),
            "d": ("pottery", "Making pots and cups from clay",
                  ["Taking photos of old buildings", "Collecting tickets from concerts"]),
            "lw": ("I have ___ a photography club.", "I have joined a photography club.",
                   "joined", ["join", "joining"]),
            "mw": ("She has painted ten portraits ___ far.", "so", "so"),
            "ch": ([("Friend", "What do you do at the weekends?")], "You",
                   "I am into birdwatching — I have spotted forty species this year already.",
                   ["I watched birds yesterday tomorrow.", "The weekends are doing me."]),
        },
        {
            "t": ("Что попробую в этом году", "What I Will Try This Year"),
            "o": ("Рассказать о новых увлечениях и сравнить занятия.",
                  "Talk about new activities and compare them."),
            "v": [("to sign up for", "записаться на"), ("more creative", "творческий (более)"),
                  ("less expensive", "дешевле"), ("to try out", "испытать, попробовать"),
                  ("beginner course", "курс для начинающих"), ("equipment", "снаряжение"),
                  ("to enjoy", "наслаждаться")],
            "q": ("Which sentence compares two hobbies correctly?",
                  "Climbing is less expensive than sailing in the long run.",
                  ["Climbing is expensiver than sailing.", "Climbing is most expensive than sailing."]),
            "tr": ("В этом году я собираюсь записаться на курс керамики для начинающих.",
                   "This year I am going to sign up for a beginner pottery course.",
                   ["did", "signed", "yesterday"]),
            "fill": ("Painting is ___ relaxing than gaming for me.", "more",
                     ["most", "much"], "Живопись для меня расслабляет сильнее, чем игры."),
            "tap": ("They are going to try out kayaking in July.", ["was", "did"]),
            "sh": ("If you choose a hobby with cheap equipment, you will not be sad if you give it up.",
                   "Если выбрать хобби с дешёвым снаряжением, будет не жалко его бросить."),
            "st": ("Choosing a Course", [
                ("Anna", "There are two evening courses: painting and climbing. Which one?",
                 "Есть два вечерних курса: живопись и скалолазание. Куда пойти?"),
                ("Tom", "Painting is more creative, but climbing is better for fitness.",
                 "Живопись творческая, но скалолазание полезнее для формы."),
                ("What does Anna decide?", [
                    ("I am going to try climbing first and painting in winter.", True),
                    ("I tried them yesterday tomorrow already.", False),
                    ("The courses are choosing me.", False)])]),
            "d": ("equipment", "The special things you need for a sport or hobby",
                  ["The clothes you wear to a birthday party", "The books you read at university"]),
            "lw": ("I am going to ___ for a dance class.", "I am going to sign up for a dance class.",
                   "sign up", ["signed up", "signing up"]),
            "mw": ("Cycling is ___ expensive than skiing.", "less", "le"),
            "ch": ([("Friend", "Is the guitar course worth it?")], "You",
                   "Yes — if you practise ten minutes daily, you will play simple songs in a month.",
                   ["I practised it yesterday tomorrow.", "The guitar is courting me."]),
        },
        {
            "t": ("Если хочется бросить", "When You Feel Like Quitting"),
            "o": ("Обсудить мотивацию в хобби, используя should и первое условное.",
                  "Discuss hobby motivation using should and the first conditional."),
            "v": [("to quit", "бросить (занятие)"), ("progress", "прогресс"),
                  ("to practise regularly", "заниматься регулярно"), ("teacher", "преподаватель"),
                  ("to take a break", "сделать перерыв"), ("motivation", "мотивация"),
                  ("to compare", "сравнивать")],
            "q": ("Which sentence gives correct advice?",
                  "You should take a break instead of quitting completely.",
                  ["You should to take a break yesterday.", "You must taking breaks last month."]),
            "tr": ("Если ты будешь сравнивать себя с профессионалами, быстро потеряешь мотивацию.",
                   "If you compare yourself with professionals, you will lose motivation quickly.",
                   ["did", "compared", "yesterday"]),
            "fill": ("If you practise a little every day, you ___ steady progress.",
                     "will make", ["make", "made"], "Если заниматься понемногу каждый день, прогресс будет стабильным."),
            "tap": ("You should celebrate small wins in your hobby.", ["mustn't", "went"]),
            "sh": ("If you play music with friends, practising will feel like fun, not homework.",
                   "Если играть музыку с друзьями, практика будет ощущаться как развлечение, а не домашка."),
            "st": ("The Plateau", [
                ("Anna", "I have played the piano for a year, but I am not getting better.", "Я год играю на пианино, но не становлюсь лучше."),
                ("Tom", "Everyone hits a plateau. What should you do about it?", "У всех бывает плато. Что с этим делать?"),
                ("What is the good advice?", [
                    ("You should change the pieces you play and add something fun.", True),
                    ("You must changed the pieces yesterday.", False),
                    ("The piano is plateauing you every year.", False)])]),
            "d": ("plateau", "A period when progress stops for a while",
                  ["A quick jump to a very high level", "The first lesson of a beginner course"]),
            "lw": ("If you ___ regularly, progress will come.", "If you practise regularly, progress will come.",
                   "practise", ["will practise", "practised"]),
            "mw": ("You should take a ___ from competitions.", "break", "br"),
            "ch": ([("Friend", "I am thinking of quitting Spanish.")], "You",
                   "Take a two-week break first — if you miss it, you will return with new energy.",
                   ["I quit it yesterday tomorrow.", "Spanish is thinking of me."]),
        },
    ],

    "A2_SPEAKING_PAST_WEEKEND_ACTIVITIES": [
        {
            "t": ("Как прошли выходные", "How the Weekend Went"),
            "o": ("Рассказать о прошедших выходных, используя past simple и present perfect.",
                  "Talk about last weekend using past simple and present perfect."),
            "v": [("to hang out with", "проводить время с"), ("to sleep in", "спать допоздна"),
                  ("to go hiking", "ходить в поход"), ("to bake", "печь"),
                  ("all of a sudden", "вдруг, неожиданно"), ("to take photos", "фотографировать"),
                  ("whole day", "целый день")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have just uploaded the photos from the trip.",
                  ["I have uploaded them last weekend.", "I upload the photos already just."]),
            "tr": ("Мы спали допоздна, а потом внезапно решили пойти в поход.",
                   "We slept in, and then all of a sudden we decided to go hiking.",
                   ["did", "sleep", "tomorrow"]),
            "fill": ("On Sunday morning she ___ bread for the whole family.", "baked",
                     ["has bake", "baking"], "В воскресенье утром она испекла хлеб для всей семьи."),
            "tap": ("They have never spent a whole day at the lake before.", ["was", "did"]),
            "sh": ("We hung out with friends on Saturday, and on Sunday I have finally cleaned the whole flat.",
                   "В субботу мы тусовались с друзьями, а в воскресенье я наконец убрал всю квартиру."),
            "st": ("Monday Chatter", [
                ("Anna", "How was your weekend? Did you do anything special?", "Как выходные? Делали что-то особенное?"),
                ("Tom", "We went hiking in the hills. Have you seen my photos?", "Мы ходили в поход в холмы. Ты видела мои фото?"),
                ("What does Anna answer?", [
                    ("Not yet — upload them to the shared album!", True),
                    ("Yes, I see them tomorrow yesterday.", False),
                    ("The hills are hiking your photos.", False)])]),
            "d": ("to sleep in", "To stay in bed later than usual in the morning",
                  ["To go to bed earlier than usual", "To work at the weekend instead of resting"]),
            "lw": ("I have ___ the photos to the cloud.", "I have uploaded the photos to the cloud.",
                   "uploaded", ["upload", "uploading"]),
            "mw": ("We went ___ in the mountains.", "hiking", "hi"),
            "ch": ([("Friend", "What did you do on Saturday night?")], "You",
                   "We hung out at Marina's place — I have never laughed so much this year.",
                   ["I hanged out yesterday tomorrow.", "Saturday night is doing me."]),
        },
        {
            "t": ("Следующие выходные", "Next Weekend"),
            "o": ("Спланировать выходные и сравнить варианты отдыха.",
                  "Plan the weekend and compare leisure options."),
            "v": [("to look forward to", "предвкушать"), ("more peaceful", "спокойнее (более)"),
                  ("to visit relatives", "навестить родственников"), ("picnic", "пикник"),
                  ("to stay in", "остаться дома"), ("weather forecast", "прогноз погоды"),
                  ("to book tickets", "купить билеты заранее")],
            "q": ("Which sentence compares two weekend plans correctly?",
                  "A picnic in the park is more peaceful than a shopping mall.",
                  ["A picnic is peacefuller than a mall.", "A picnic is most peaceful than a mall."]),
            "tr": ("В эти выходные мы собираемся устроить пикник, если прогноз не подведёт.",
                   "We are going to have a picnic this weekend if the forecast is right.",
                   ["did", "had", "yesterday"]),
            "fill": ("Staying in with a book is ___ than a noisy party for me.", "nicer",
                     ["nicest", "more nice"], "Посидеть дома с книгой для меня приятнее шумной вечеринки."),
            "tap": ("We are going to visit my in-laws on Sunday.", ["was", "did"]),
            "sh": ("If the weather holds, we are going to cycle to the lake and stay until sunset.",
                   "Если погода сохранится, мы поедем на велосипедах к озеру и останемся до заката."),
            "st": ("Weekend Choices", [
                ("Anna", "So, what are we doing this weekend?", "Итак, что делаем в эти выходные?"),
                ("Tom", "We can visit your parents or stay in and finish the series.", "Можно навестить твоих родителей или остаться и досмотреть сериал."),
                ("What does Anna say?", [
                    ("Let's visit them — we have not seen them since Easter.", True),
                    ("We saw them tomorrow yesterday already.", False),
                    ("The weekend is visiting our parents.", False)])]),
            "d": ("picnic", "An outdoor meal with food you bring yourself",
                  ["A dinner in a fancy restaurant", "A quick lunch at the office desk"]),
            "lw": ("We are going to ___ a picnic by the river.", "We are going to have a picnic by the river.",
                   "have", ["had", "having"]),
            "mw": ("A quiet weekend is ___ stressful.", "less", "le"),
            "ch": ([("Friend", "Any plans for Saturday?")], "You",
                   "We are going to the open-air cinema — if it rains, we will switch to the indoor one.",
                   ["I went there yesterday tomorrow.", "Saturday is planning us."]),
        },
        {
            "t": ("Если выходные испортились", "If the Weekend Is Spoiled"),
            "o": ("Обсудить планы на выходные, используя should и первое условное.",
                  "Discuss weekend contingencies using should and the first conditional."),
            "v": [("to cancel", "отменить"), ("backup plan", "запасной план"),
                  ("to complain", "жаловаться"), ("to make the most of", "извлечь максимум из"),
                  ("rainy day", "дождливый день"), ("board game", "настольная игра"),
                  ("cosy", "уютный")],
            "q": ("Which sentence gives correct advice?",
                  "You should have a backup plan for outdoor events.",
                  ["You should to have it yesterday.", "You must having plans last weekend."]),
            "tr": ("Если пикник отменится, мы устроим уютный вечер с настольными играми.",
                   "If the picnic is cancelled, we will have a cosy board-game evening.",
                   ["did", "cancelled", "yesterday"]),
            "fill": ("If it ___ all weekend, the concert will move indoors.",
                     "rains", ["will rain", "rained"], "Если будет дождить все выходные, концерт перенесут внутрь."),
            "tap": ("You should make the most of any weather.", ["mustn't", "went"]),
            "sh": ("If your plans fall through, complaining will not help — a board game will.",
                   "Если планы сорвутся, жалобы не помогут — поможет настольная игра."),
            "st": ("The Washed-out Picnic", [
                ("Anna", "The forecast shows rain for Saturday.", "Прогноз показывает дождь на субботу."),
                ("Tom", "So the picnic is off? What should we do instead?", "Значит, пикника не будет? Чем заняться вместо?"),
                ("What does Anna suggest?", [
                    ("If it rains, we should host a board-game afternoon at our place.", True),
                    ("If it will rain, we hosted it yesterday.", False),
                    ("The rain is picnicking on Saturday.", False)])]),
            "d": ("cosy", "Warm and comfortable (about a place or time)",
                  ["Cold and windy, typical for the coast", "Too hot for sleeping well"]),
            "lw": ("If they ___ the show, we will get refunds.", "If they cancel the show, we will get refunds.",
                   "cancel", ["will cancel", "cancelled"]),
            "mw": ("You should make the most ___ the day.", "of", "of"),
            "ch": ([("Friend", "Our trip got cancelled because of the storm.")], "You",
                   "That is a pity — if you are free Sunday, we will have a games evening instead.",
                   ["We cancelled it yesterday tomorrow.", "The storm is tripping us."]),
        },
    ],

    "A2_SPEAKING_SHARING_EXPERIENCES": [
        {
            "t": ("Никогда не забуду", "I Will Never Forget"),
            "o": ("Поделиться ярким опытом, используя past simple и present perfect.",
                  "Share a memorable experience using past simple and present perfect."),
            "v": [("memorable", "запоминающийся"), ("for the first time", "впервые"),
                  ("to try", "попробовать"), ("abroad", "за границей"),
                  ("the best ... ever", "лучший ... когда-либо"), ("to recommend", "порекомендовать"),
                  ("exciting", "захватывающий")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "It is the most exciting thing I have ever done.",
                  ["It is the most exciting thing I did ever it.", "It is exciting the most thing I do already."]),
            "tr": ("Я впервые попробовал серфинг, и это был лучший день лета.",
                   "I tried surfing for the first time, and it was the best day of the summer.",
                   ["did", "try", "tomorrow"]),
            "fill": ("She saw the northern lights ___ the first time in Norway.", "for",
                     ["since", "at"], "Она впервые увидела северное сияние в Норвегии."),
            "tap": ("He has never travelled abroad before this trip.", ["was", "did"]),
            "sh": ("I have just come back from the mountains, and the sunrise above the clouds was unforgettable.",
                   "Я только что вернулся из гор, и рассвет над облаками был незабываемым."),
            "st": ("The Story", [
                ("Anna", "You look excited. Did something happen?", "Ты выглядишь взволнованным. Что-то случилось?"),
                ("Tom", "Yes! I have just passed my driving test — on the second attempt.",
                 "Да! Я только что сдал экзамен на вождение — со второй попытки."),
                ("What does Anna say?", [
                    ("Congratulations! Have you already told your parents?", True),
                    ("Congrats! Did you told them tomorrow?", False),
                    ("Is the test driving you again?", False)])]),
            "d": ("memorable", "Worth remembering for a long time",
                  ["Boring and easy to forget", "Too difficult to talk about"]),
            "lw": ("I have ___ scuba diving in Egypt.", "I have tried scuba diving in Egypt.",
                   "tried", ["try", "trying"]),
            "mw": ("It was the ___ meal I have ever had.", "best", "be"),
            "ch": ([("Friend", "Have you ever been to Japan?")], "You",
                   "Yes, twice — the second trip was even more memorable than the first.",
                   ["I go there yesterday tomorrow.", "Japan is being me."]),
        },
        {
            "t": ("Куда я бы вернулся", "Where I Would Return"),
            "o": ("Сравнить впечатления от мест и рассказать о желании вернуться.",
                  "Compare experiences of places and talk about returning."),
            "v": [("to come back to", "вернуться в"), ("more impressive", "впечатляющий (более)"),
                  ("crowded", "многолюдный"), ("authentic", "аутентичный"),
                  ("next time", "в следующий раз"), ("to explore", "исследовать"),
                  ("off the beaten path", "вдали от туристических троп")],
            "q": ("Which sentence compares two places correctly?",
                  "The small town was more authentic than the capital.",
                  ["The town was authenticer than the capital.", "The town was most authentic than capital."]),
            "tr": ("В следующий раз мы собираемся поехать в места вдали от туристических троп.",
                   "Next time we are going to explore places off the beaten path.",
                   ["did", "explored", "yesterday"]),
            "fill": ("The local market felt ___ authentic than the mall.", "more",
                     ["most", "much"], "Местный рынок показался аутентичнее торгового центра."),
            "tap": ("I am going to come back to this country for sure.", ["was", "did"]),
            "sh": ("The mountains were less crowded than the coast, and the food was more impressive.",
                   "В горах было меньше людей, чем на побережье, а еда впечатляла сильнее."),
            "st": ("Trip Comparison", [
                ("Anna", "Which did you like more — Lisbon or Porto?", "Что понравилось больше — Лиссабон или Порту?"),
                ("Tom", "Porto is smaller, but it felt more authentic.", "Порту меньше, но ощущался более аутентичным."),
                ("What does Anna ask?", [
                    ("Would you go back there next spring?", True),
                    ("Did you go back tomorrow yesterday?", False),
                    ("Is Porto liking you more already?", False)])]),
            "d": ("off the beaten path", "Far from the places most tourists visit",
                  ["In the very centre of the old town", "Next to the most famous museum"]),
            "lw": ("We are going to ___ the north coast.", "We are going to explore the north coast.",
                   "explore", ["explored", "exploring"]),
            "mw": ("This cafe is ___ touristy than the one online.", "less", "le"),
            "ch": ([("Friend", "Was the festival worth the trip?")], "You",
                   "Absolutely — we are going to return next year, and this time we will book earlier.",
                   ["It was worth it yesterday tomorrow.", "The festival is tripping us."]),
        },
        {
            "t": ("Расскажи так, чтобы поверили", "Tell It So People Believe You"),
            "o": ("Дать советы о рассказах об опыте, используя should и первое условное.",
                  "Give advice about storytelling using should and the first conditional."),
            "v": [("detail", "деталь"), ("to keep it short", "говорить кратко"),
                  ("to exaggerate", "преувеличивать"), ("listener", "слушатель"),
                  ("to pause", "сделать паузу"), ("question", "вопрос"),
                  ("to involve the listener", "вовлечь слушателя")],
            "q": ("Which sentence gives correct advice?",
                  "You should add one or two vivid details.",
                  ["You should to add details yesterday.", "You must adding details last time."]),
            "tr": ("Если добавить пару ярких деталей, история станет живее.",
                   "If you add one or two vivid details, the story will come alive.",
                   ["did", "added", "yesterday"]),
            "fill": ("If your story ___ too long, people will lose interest.",
                     "is", ["will be", "was"], "Если история слишком длинная, люди потеряют интерес."),
            "tap": ("You should sometimes pause for effect.", ["mustn't", "went"]),
            "sh": ("If you ask the listener a question, they will stay with you until the end.",
                   "Если задать слушателю вопрос, он останется с тобой до конца."),
            "st": ("The Boring Story", [
                ("Anna", "I told the team about my trip, but everyone looked bored.", "Я рассказала команде о поездке, но все выглядели скучающими."),
                ("Tom", "How did you tell it — with all the flight details?", "Как ты рассказывала — со всеми деталями перелёта?"),
                ("What is Tom's advice?", [
                    ("Next time you should start with the most surprising moment.", True),
                    ("Next time you must starting with the end.", False),
                    ("The story is boring the team itself.", False)])]),
            "d": ("to exaggerate", "To make things sound bigger than they were",
                  ["To describe things exactly as they happened", "To refuse to tell a story at all"]),
            "lw": ("If you ___ it short, it will work better.", "If you keep it short, it will work better.",
                   "keep", ["will keep", "kept"]),
            "mw": ("You should not exaggerate ___ every story.", "in", "in"),
            "ch": ([("Friend", "Nobody listens when I tell stories.")], "You",
                   "Try asking them a question at the start — if they answer, they will listen further.",
                   ["They listened yesterday tomorrow.", "The stories are listening to me."]),
        },
    ],

    "A2_SPEAKING_SHOPPING_CONVERSATIONS": [
        {
            "t": ("Удачная покупка", "A Successful Purchase"),
            "o": ("Рассказать о покупках, используя past simple и present perfect.",
                  "Talk about shopping using past simple and present perfect."),
            "v": [("bargain", "выгодная покупка"), ("to try on", "примерить"),
                  ("fitting room", "примерочная"), ("to fit", "подходить по размеру"),
                  ("receipt", "чек"), ("to order online", "заказать онлайн"),
                  ("in the end", "в итоге")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have already spent my monthly clothes budget.",
                  ["I have spent it last month.", "I spend the budget already now."]),
            "tr": ("Я примерил пять курток и в итоге купил самую дешёвую.",
                   "I tried on five jackets and in the end bought the cheapest one.",
                   ["did", "try", "tomorrow"]),
            "fill": ("The shoes did not ___ , so I took a bigger size.", "fit",
                     ["fits", "fitting"], "Туфли не подошли, и я взял размер побольше."),
            "tap": ("She has just ordered a new phone online.", ["was", "did"]),
            "sh": ("I found a real bargain at the market — a wool coat for twenty euros, and it fits perfectly.",
                   "Я нашёл реальную выгоду на рынке — шерстяное пальто за двадцать евро, и оно идеально сидит."),
            "st": ("In the Fitting Room", [
                ("Assistant", "How does the dress fit?", "Как сидит платье?"),
                ("Customer", "The top is fine, but the skirt is a bit tight.", "Верх в порядке, но юбка немного тесновата."),
                ("What does the assistant offer?", [
                    ("I will bring one size up — the colour has been very popular this week.", True),
                    ("I brought it yesterday tomorrow.", False),
                    ("The dress is fitting one size up.", False)])]),
            "d": ("bargain", "Something bought for a lower price than usual",
                  ["The most expensive item in the shop", "Something you return the next day"]),
            "lw": ("I have ___ the receipt, unfortunately.", "I have lost the receipt, unfortunately.",
                   "lost", ["lose", "losing"]),
            "mw": ("She has paid ___ card.", "by", "by"),
            "ch": ([("Assistant", "Would you like to try it on?")], "You",
                   "Yes, please — where is the fitting room? I have never shopped here before.",
                   ["I tried it on yesterday tomorrow.", "The shop is trying me on."]),
        },
        {
            "t": ("Что купить дальше", "What to Buy Next"),
            "o": ("Спланировать покупку и сравнить варианты.",
                  "Plan a purchase and compare options."),
            "v": [("to compare prices", "сравнить цены"), ("second-hand", "вторичка / б/у"),
                  ("brand new", "совершенно новый"), ("more durable", "прочнее"),
                  ("customer reviews", "отзывы покупателей"), ("to wait for a sale", "дождаться распродажи"),
                  ("value for money", "соответствие цене")],
            "q": ("Which sentence compares two products correctly?",
                  "This rucksack is more durable than the cheaper one.",
                  ["This rucksack is durabler than that one.", "This rucksack is most durable than that."]),
            "tr": ("Я собираюсь дождаться распродажи и купить куртку со скидкой.",
                   "I am going to wait for a sale and buy the jacket at a discount.",
                   ["did", "waited", "yesterday"]),
            "fill": ("A second-hand bike is often ___ value for money than a new one.", "better",
                     ["best", "more good"], "Б/у велосипед часто выгоднее нового."),
            "tap": ("We are going to compare prices in three shops.", ["was", "did"]),
            "sh": ("If you read the customer reviews first, you will avoid the models that break quickly.",
                   "Если сначала почитать отзывы, вы избежите моделей, которые быстро ломаются."),
            "st": ("New or Second-hand?", [
                ("Anna", "I need a new bike. Should I buy second-hand?", "Мне нужен велосипед. Взять б/у?"),
                ("Tom", "A second-hand one is cheaper, but this brand is more durable new.", "Б/у дешевле, но эта марка прочнее новой."),
                ("What does Anna decide?", [
                    ("I am going to look at both and compare the prices.", True),
                    ("I looked at them yesterday tomorrow.", False),
                    ("The bike is buying me second-hand.", False)])]),
            "d": ("second-hand", "Not new; owned by someone before",
                  ["Fresh from the factory this month", "Reserved in the shop yesterday"]),
            "lw": ("We are going to ___ prices online.", "We are going to compare prices online.",
                   "compare", ["compared", "comparing"]),
            "mw": ("The reviews are ___ helpful than the ads.", "more", "mo"),
            "ch": ([("Friend", "Is this brand worth the money?")], "You",
                   "Check the reviews — if it lasts five years, it will be good value for money.",
                   ["It was worth it yesterday tomorrow.", "The brand is moneying me."]),
        },
        {
            "t": ("Если покупка не подошла", "If the Purchase Does Not Fit"),
            "o": ("Объяснить возврат и обмен, используя should и первое условное.",
                  "Explain returns and exchanges using should and the first conditional."),
            "v": [("to return", "вернуть (товар)"), ("exchange", "обмен"),
                  ("warranty", "гарантия"), ("to keep the receipt", "хранить чек"),
                  ("to complain politely", "вежливо пожаловаться"), ("faulty", "бракованный"),
                  ("within the period", "в течение срока")],
            "q": ("Which sentence gives correct advice?",
                  "You should keep the receipt until you are sure the item works.",
                  ["You should to keep it yesterday.", "You must keeping it last purchase."]),
            "tr": ("Если товар бракованный, магазин обязан вернуть деньги или обменять его.",
                   "If the item is faulty, the shop must refund you or exchange it.",
                   ["did", "was", "yesterday"]),
            "fill": ("If you ___ the receipt, the exchange will take two minutes.",
                     "show", ["will show", "showed"], "Если показать чек, обмен займёт две минуты."),
            "tap": ("You should check the warranty period.", ["mustn't", "went"]),
            "sh": ("If you complain politely but firmly, most shops will solve the problem quickly.",
                   "Если жаловаться вежливо, но твёрдо, большинство магазинов быстро решит проблему."),
            "st": ("The Faulty Kettle", [
                ("Customer", "This kettle has stopped working after two weeks.", "Этот чайник перестал работать через две недели."),
                ("Shop assistant", "Do you have the receipt and the box?", "У вас есть чек и коробка?"),
                ("What does the customer say?", [
                    ("Yes, both — I would like an exchange rather than a refund.", True),
                    ("Yes, I have them tomorrow yesterday.", False),
                    ("The kettle is refunding the receipt.", False)])]),
            "d": ("warranty", "A promise to repair or replace something that breaks",
                  ["A discount for the next purchase", "A free delivery to your home"]),
            "lw": ("If the item is ___ , bring it back.", "If the item is faulty, bring it back.",
                   "faulty", ["fault", "falsely"]),
            "mw": ("You should return it ___ thirty days.", "within", "wi"),
            "ch": ([("Friend", "The online order arrived damaged.")], "You",
                   "Take photos — if you show them the damage, they will send a replacement for free.",
                   ["I photographed it yesterday tomorrow.", "The order is damaging me."]),
        },
    ],
}
