#!/usr/bin/env python3
"""A2 regenerated content: TRAVEL (10 tracks x 3 lessons).

Grammar arc per topic: L1 past simple + present perfect,
L2 future forms + comparatives, L3 modals / first conditional.
"""

TRACKS = {
    "A2_TRAVEL_AIRPORT_CHECK_IN_AND_SECURITY": [
        {
            "t": ("Регистрация в аэропорту", "At the Check-in Desk"),
            "o": ("Рассказать о регистрации на рейс, используя past simple и present perfect.",
                  "Talk about check-in using past simple and present perfect."),
            "v": [("check-in desk", "стойка регистрации"), ("boarding pass", "посадочный талон"),
                  ("luggage", "багаж"), ("to weigh", "взвесить"),
                  ("aisle seat", "место у прохода"), ("overweight", "перевес (багажа)"),
                  ("to print", "распечатать")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The airline has already changed our gate twice.",
                  ["The airline has changed the gate yesterday.", "The airline change the gate already twice."]),
            "tr": ("Мой чемодан весил двадцать три килограмма, и я заплатил за перевес.",
                   "My suitcase weighed twenty-three kilos, and I paid for the extra weight.",
                   ["did", "weighs", "tomorrow"]),
            "fill": ("She ___ in online and printed the boarding pass at home.", "checked",
                     ["has check", "checking"], "Она зарегистрировалась онлайн и распечатала посадочный талон дома."),
            "tap": ("We have already passed through security.", ["was", "did"]),
            "sh": ("I have checked in online, but the desk has printed a different seat for me.",
                   "Я зарегистрировался онлайн, но на стойке мне распечатали другое место."),
            "st": ("The Overweight Suitcase", [
                ("Agent", "Good morning. May I see your passport, please?", "Доброе утро. Можно ваш паспорт?"),
                ("Traveller", "Here it is. Is the flight on time?", "Вот, пожалуйста. Рейс по расписанию?"),
                ("What does the agent say next?", [
                    ("Yes, it is. Your suitcase is two kilos overweight, I'm afraid.", True),
                    ("Yes, it was overweight yesterday tomorrow.", False),
                    ("The suitcase is flying itself.", False)])]),
            "d": ("boarding pass", "The document that lets you get on a plane",
                  ["A ticket you buy at a museum entrance", "A passport photo you carry separately"]),
            "lw": ("I have ___ in for the evening flight.", "I have checked in for the evening flight.",
                   "checked", ["check", "checking"]),
            "mw": ("She has chosen an ___ seat.", "aisle", "ai"),
            "ch": ([("Agent", "Would you like a window or an aisle seat?")], "You",
                   "An aisle seat, please — I have already travelled with a window seat twice.",
                   ["A window seat, I take it tomorrow yesterday.", "The seat is choosing me."]),
        },
        {
            "t": ("Завтра вылетаем", "Flying Out Tomorrow"),
            "o": ("Обсудить подготовку к вылету, используя формы будущего и сравнения.",
                  "Discuss departure preparations using future forms and comparatives."),
            "v": [("departure time", "время вылета"), ("to arrive in advance", "приехать заранее"),
                  ("earlier", "раньше"), ("hand luggage", "ручная кладь"),
                  ("security rules", "правила безопасности"), ("liquid", "жидкость"),
                  ("faster", "быстрее")],
            "q": ("Which sentence talks about a future plan?",
                  "We are going to leave for the airport at six tomorrow.",
                  ["We left for the airport at six yesterday.", "We has left at six tomorrow already."]),
            "tr": ("Мы приедем в аэропорт заранее, потому что утром контроль безопасности дольше.",
                   "We are going to arrive at the airport in advance because security takes longer in the morning.",
                   ["did", "arrived", "yesterday"]),
            "fill": ("Travelling with hand luggage only is ___ than checking in a suitcase.", "quicker",
                     ["quickest", "more quick"], "Путешествовать только с ручной кладью быстрее, чем сдавать чемодан."),
            "tap": ("I am going to put all liquids into the transparent bag.", ["was", "did"]),
            "sh": ("If we arrive two hours before departure, we will have time for a coffee after security.",
                   "Если приехать за два часа до вылета, останется время на кофе после контроля."),
            "st": ("Morning Plans", [
                ("Anna", "What time are we leaving for the airport tomorrow?", "Во сколько завтра выезжаем в аэропорт?"),
                ("Tom", "The taxi is coming at six — the flight leaves at half past eight.",
                 "Такси приедет в шесть — рейс в восемь тридцать."),
                ("What does Anna ask?", [
                    ("Is two and a half hours enough for this airport?", True),
                    ("Did two hours were enough yesterday?", False),
                    ("Is the taxi flying with us tomorrow?", False)])]),
            "d": ("hand luggage", "The small bag you can take onto the plane",
                  ["The big suitcase you give at the check-in desk", "A bag the airline lost last month"]),
            "lw": ("We are ___ to check in online tonight.", "We are going to check in online tonight.",
                   "going", ["went", "gone"]),
            "mw": ("Online check-in is ___ than the desk.", "faster", "fa"),
            "ch": ([("Friend", "Do we need to print the boarding passes?")], "You",
                   "No — if we check in on the app, the mobile pass will be enough.",
                   ["Yes, I printed them yesterday tomorrow.", "The passes are printing us."]),
        },
        {
            "t": ("На контроле безопасности", "At the Security Check"),
            "o": ("Объяснить правила досмотра, используя should и первое условное.",
                  "Explain security rules using should and the first conditional."),
            "v": [("to take out", "достать"), ("belt", "ремень"),
                  ("tray", "лоток"), ("scanner", "сканер"),
                  ("to beep", "запищать"), ("sharp objects", "острые предметы"),
                  ("to remove", "снять")],
            "q": ("Which sentence expresses a rule at security?",
                  "You must take your laptop out of the bag.",
                  ["You must to take it out yesterday.", "You musts take it out last week."]),
            "tr": ("Если у вас в багаже окажутся острые предметы, их заберут на контроле.",
                   "If there are sharp objects in your luggage, they will be taken away at the check.",
                   ["did", "was", "yesterday"]),
            "fill": ("If the scanner ___, the officer will check you again.", "beeps",
                     ["will beep", "beeped"], "Если сканер запищит, сотрудник проверит вас ещё раз."),
            "tap": ("You should remove your belt before the scanner.", ["mustn't", "went"]),
            "sh": ("If you take out your laptop and liquids first, you will pass through security much faster.",
                   "Если сначала достать ноутбук и жидкости, вы пройдете контроль гораздо быстрее."),
            "st": ("The Beeping Scanner", [
                ("Officer", "Please put your bag in the tray and take out your laptop.",
                 "Пожалуйста, положите сумку в лоток и достаньте ноутбук."),
                ("Traveller", "Sorry, I forgot about the liquids in my pocket.", "Извините, я забыл про жидкости в кармане."),
                ("What does the officer say?", [
                    ("That's fine, but next time you should check your pockets first.", True),
                    ("You must checking your pockets yesterday.", False),
                    ("The pocket is beeping the liquids.", False)])]),
            "d": ("tray", "A plastic box where you put your things at security",
                  ["A seat next to the window on the plane", "A shop in the departure area"]),
            "lw": ("If the machine ___, step aside, please.", "If the machine beeps, step aside, please.",
                   "beeps", ["will beep", "beeped"]),
            "mw": ("You must remove ___ objects from hand luggage.", "sharp", "sh"),
            "ch": ([("Officer", "Do you have any liquids in your bag?")], "You",
                   "Only a small one — if it is under one hundred millilitres, it will be fine, won't it?",
                   ["Yes, I have it tomorrow yesterday.", "The liquids are checking me."]),
        },
    ],

    "A2_TRAVEL_DIRECTIONS_AND_GETTING_AROUND": [
        {
            "t": ("Как мы добрались", "How We Got There"),
            "o": ("Рассказать о маршруте, используя past simple и present perfect.",
                  "Describe a route using past simple and present perfect."),
            "v": [("to turn left", "повернуть налево"), ("crossroads", "перекрёсток"),
                  ("pedestrian zone", "пешеходная зона"), ("straight ahead", "прямо впереди"),
                  ("to get lost", "заблудиться"), ("map", "карта"),
                  ("finally", "наконец")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "We have walked around the old town for two hours already.",
                  ["We have walked there yesterday.", "We walk for two hours already now."]),
            "tr": ("Мы повернули налево у собора и наконец нашли нужную улицу.",
                   "We turned left at the cathedral and finally found the right street.",
                   ["did", "turns", "tomorrow"]),
            "fill": ("Yesterday we ___ lost near the station.", "got",
                     ["has get", "getting"], "Вчера мы заблудились около вокзала."),
            "tap": ("She has already downloaded an offline map.", ["was", "did"]),
            "sh": ("We took the second turning on the right, and the museum has appeared straight ahead of us.",
                   "Мы свернули во второй поворот направо, и музей оказался прямо перед нами."),
            "st": ("Lost Near the Station", [
                ("Anna", "I think we have walked past this church already.", "Кажется, мы уже проходили мимо этой церкви."),
                ("Tom", "You are right — we got lost at the last crossroads.", "Ты права — мы заблудились на прошлом перекрёстке."),
                ("What should they do?", [
                    ("We should ask someone for directions or check the map.", True),
                    ("We must asking someone yesterday.", False),
                    ("The church is walking past us again.", False)])]),
            "d": ("crossroads", "A place where two or more roads cross",
                  ["A bridge over a wide river", "The last stop of a city bus"]),
            "lw": ("We have ___ past the theatre twice.", "We have walked past the theatre twice.",
                   "walked", ["walk", "walking"]),
            "mw": ("The museum is straight ___ .", "ahead", "ah"),
            "ch": ([("Tourist", "Excuse me, how do we get to the main square?")], "You",
                   "Go straight ahead and turn left at the crossroads — it has taken me five minutes before.",
                   ["I went there yesterday tomorrow.", "The square is getting me."]),
        },
        {
            "t": ("Куда пойдём завтра", "Where We Will Go Tomorrow"),
            "o": ("Спланировать маршрут на завтра и сравнить пути.",
                  "Plan tomorrow's route and compare ways."),
            "v": [("the quickest way", "самый быстрый путь"), ("on foot", "пешком"),
                  ("by tram", "на трамвае"), ("more scenic", "живописнее"),
                  ("to recommend", "порекомендовать"), ("walking distance", "пешая доступность"),
                  ("to save time", "сэкономить время")],
            "q": ("Which sentence compares two routes correctly?",
                  "The road along the river is more scenic than the main street.",
                  ["The road is scenicer than the street.", "The road is most scenic than the street."]),
            "tr": ("Завтра мы пойдём пешком вдоль реки — это живописнее, чем главный проспект.",
                   "Tomorrow we are going to walk along the river — it is more scenic than the main avenue.",
                   ["did", "walked", "yesterday"]),
            "fill": ("The museum is within ___ distance from our hotel.", "walking",
                     ["walk", "walked"], "Музей в пешей доступности от нашего отеля."),
            "tap": ("We are going to take the tram to the castle.", ["was", "did"]),
            "sh": ("If we take the tram instead of the bus, we will save about fifteen minutes.",
                   "Если поехать трамваем вместо автобуса, сэкономим примерно пятнадцать минут."),
            "st": ("Two Routes", [
                ("Anna", "Should we go to the castle on foot or by tram?", "Идти к замку пешком или на трамвае?"),
                ("Tom", "On foot is more scenic, but it takes forty minutes.", "Пешком живописнее, но это сорок минут."),
                ("What does Anna decide?", [
                    ("Then we are going to walk there and take the tram back.", True),
                    ("Then we walked there yesterday tomorrow.", False),
                    ("The castle is deciding our route.", False)])]),
            "d": ("on foot", "Walking, not using transport",
                  ["Travelling by city tram", "Driving a rented car"]),
            "lw": ("We are going to ___ time with the tram.", "We are going to save time with the tram.",
                   "save", ["saved", "saving"]),
            "mw": ("The river route is ___ scenic.", "more", "mo"),
            "ch": ([("Friend", "Is the old town far from here?")], "You",
                   "No, it is within walking distance — about fifteen minutes if we cross the bridge.",
                   ["It was far yesterday tomorrow.", "The town is walking to us."]),
        },
        {
            "t": ("Если заблудились", "If You Get Lost"),
            "o": ("Дать советы о ориентировании, используя should и первое условное.",
                  "Give orientation advice using should and the first conditional."),
            "v": [("landmark", "ориентир"), ("to ask for directions", "спросить дорогу"),
                  ("street name sign", "указатель с названием улицы"), ("polite", "вежливый"),
                  ("confident", "уверенный"), ("to check the map", "посмотреть на карту"),
                  ("the way back", "путь обратно")],
            "q": ("Which sentence gives correct advice?",
                  "You should remember a landmark near your hotel.",
                  ["You should to remember it yesterday.", "You must remembering it last week."]),
            "tr": ("Если ты запомнишь ориентир рядом с отелем, ты легко найдёшь обратный путь.",
                   "If you remember a landmark near your hotel, you will easily find the way back.",
                   ["did", "remembered", "yesterday"]),
            "fill": ("If you ___ someone for directions, be polite and speak slowly.",
                     "ask", ["will ask", "asked"], "Если спросить кого-то дорогу, делай это вежливо и медленно."),
            "tap": ("You should check the map before every long walk.", ["mustn't", "went"]),
            "sh": ("If you take a photo of the street name sign near your hotel, you will always show it to locals.",
                   "Если сфотографировать табличку с названием улицы у отеля, всегда можно показать её местным."),
            "st": ("A Wrong Turn", [
                ("Tom", "This street looks different from the map.", "Эта улица выглядит не так, как на карте."),
                ("Anna", "Maybe we turned right instead of left at the bakery.", "Может, мы повернули направо вместо налево у пекарни."),
                ("What does Tom suggest?", [
                    ("We should ask in that shop — the assistant will know the area.", True),
                    ("We must asking in the shop yesterday.", False),
                    ("The street is looking at the map differently.", False)])]),
            "d": ("landmark", "A building or place that is easy to recognise",
                  ["A small shop that changes its name often", "A bus that goes around the city centre"]),
            "lw": ("If you ___ the map first, you will not get lost.", "If you check the map first, you will not get lost.",
                   "check", ["will check", "checked"]),
            "mw": ("You should ask ___ directions politely.", "for", "fo"),
            "ch": ([("Tourist", "I cannot find the way back to my hotel.")], "You",
                   "You should look for the cathedral tower — if you walk towards it, the hotel is right behind it.",
                   ["I found it yesterday tomorrow.", "The hotel is finding me."]),
        },
    ],

    "A2_TRAVEL_HOTEL_STAYS_AND_REQUESTS": [
        {
            "t": ("Заселение и первые впечатления", "Check-in and First Impressions"),
            "o": ("Рассказать о заселении в отель, используя past simple и present perfect.",
                  "Talk about hotel check-in using past simple and present perfect."),
            "v": [("reception", "стойка приёма"), ("room key", "ключ от номера"),
                  ("to book", "забронировать"), ("spacious", "просторный"),
                  ("view", "вид (из окна)"), ("towels", "полотенца"),
                  ("since morning", "с утра")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The room has not been cleaned yet today.",
                  ["The room has not cleaned yesterday.", "The room not cleaned already today."]),
            "tr": ("Я забронировал номер на неделю, но вид из окна оказался не такой, как на фото.",
                   "I booked the room for a week, but the view turned out to be different from the photos.",
                   ["did", "book", "tomorrow"]),
            "fill": ("We ___ in at three o'clock yesterday afternoon.", "checked",
                     ["has check", "checking"], "Мы заселились вчера в три часа дня."),
            "tap": ("The receptionist has already brought extra towels.", ["was", "did"]),
            "sh": ("We have stayed at this hotel twice, and the rooms have always been clean and spacious.",
                   "Мы дважды останавливались в этом отеле, и номера всегда были чистыми и просторными."),
            "st": ("The Other View", [
                ("Guest", "Excuse me, I booked a room with a sea view, but my window faces the car park.",
                 "Извините, я бронировал номер с видом на море, а моё окно выходит на парковку."),
                ("Receptionist", "Let me check. You are right — I'm sorry about that.",
                 "Сейчас проверю. Вы правы — извините за это."),
                ("What does the receptionist offer?", [
                    ("We have a sea-view room free from tomorrow morning.", True),
                    ("We has a free room yesterday already.", False),
                    ("The car park is booking the room itself.", False)])]),
            "d": ("reception", "The place in a hotel where you check in and ask questions",
                  ["A restaurant on the top floor", "The car park behind the hotel"]),
            "lw": ("She has ___ our passports at reception.", "She has taken our passports at reception.",
                   "taken", ["take", "taking"]),
            "mw": ("The room has been ready ___ ten o'clock.", "since", "si"),
            "ch": ([("Receptionist", "How was your first night?")], "You",
                   "Very good, thank you — the room is more spacious than the one we had last year.",
                   ["It was good yesterday tomorrow.", "The night is sleeping us."]),
        },
        {
            "t": ("Просьбы в отеле", "Requests at the Hotel"),
            "o": ("Вежливо просить об услугах и сравнивать номера.",
                  "Make polite requests and compare rooms."),
            "v": [("to request", "попросить (об услуге)"), ("wake-up call", "звонок-будильник"),
                  ("quieter", "тише"), ("to move rooms", "переехать в другой номер"),
                  ("extra pillow", "дополнительная подушка"), ("more comfortable", "удобнее"),
                  ("to charge", "списать (деньги)")],
            "q": ("Which request is the most polite?",
                  "Could I have an extra pillow, please?",
                  ["Send a pillow to room 12 now.", "You will bring me a pillow."]),
            "tr": ("Не могли бы вы разбудить нас в шесть утра? У нас ранний поезд.",
                   "Could you give us a wake-up call at six? We have an early train.",
                   ["did", "can", "yesterday"]),
            "fill": ("A room away from the lift is ___ .", "quieter",
                     ["quietest", "more quiet"], "Номер подальше от лифта тише."),
            "tap": ("I am going to request a late check-out tomorrow.", ["was", "did"]),
            "sh": ("If you ask at reception the evening before, a late check-out will often cost less.",
                   "Если попросить на стойке накануне вечером, поздний выезд часто стоит дешевле."),
            "st": ("The Noisy Room", [
                ("Guest", "I'm afraid room 405 is very noisy — I hear the street all night.",
                 "Боюсь, номер 405 очень шумный — улицу слышно всю ночь."),
                ("Receptionist", "I'm sorry. We can move you to a quieter room on the courtyard side.",
                 "Извините. Мы можем переселить вас в более тихий номер во двор."),
                ("What does the guest ask?", [
                    ("That would be great. Could you also send an extra pillow?", True),
                    ("Great. You sent a pillow yesterday tomorrow.", False),
                    ("The room is moving itself to the courtyard.", False)])]),
            "d": ("wake-up call", "A phone call from reception to wake you up",
                  ["A loud alarm clock you bring from home", "A morning newspaper left at your door"]),
            "lw": ("Could I ___ a late check-out?", "Could I request a late check-out?",
                   "request", ["requested", "requesting"]),
            "mw": ("The twin room is ___ comfortable for two friends.", "more", "mo"),
            "ch": ([("Receptionist", "Is everything all right with your room?")], "You",
                   "Almost — could you send one more blanket? The nights are colder than we expected.",
                   ["Yes, you sent it yesterday tomorrow.", "The room is asking about me."]),
        },
        {
            "t": ("Если что-то не так", "When Something Is Wrong"),
            "o": ("Решить проблемы в отеле, используя should и первое условное.",
                  "Solve hotel problems using should and the first conditional."),
            "v": [("broken", "сломанный"), ("to complain", "пожаловаться"),
                  ("to fix", "починить"), ("maintenance", "техобслуживание"),
                  ("immediately", "немедленно"),
                  ("apology", "извинение"), ("to offer", "предложить")],
            "q": ("Which sentence gives correct advice?",
                  "You should report problems at reception immediately.",
                  ["You should to report them yesterday.", "You must reporting them last night."]),
            "tr": ("Если кондиционер не починят сегодня, мы попросим другой номер.",
                   "If they do not fix the air conditioning today, we will ask for another room.",
                   ["did", "fixed", "yesterday"]),
            "fill": ("If the shower ___ not work, call reception.", "does",
                     ["will", "do"], "Если душ не работает, позвоните на стойку."),
            "tap": ("You should check the room before you unpack.", ["mustn't", "went"]),
            "sh": ("If you complain politely, the hotel will usually offer a discount or a better room.",
                   "Если пожаловаться вежливо, отель обычно предложит скидку или номер получше."),
            "st": ("The Broken Shower", [
                ("Guest", "The shower in room 302 has not worked since we arrived.",
                 "Душ в номере 302 не работает с нашего приезда."),
                ("Receptionist", "I'm very sorry. Our technician has looked at two rooms already today.",
                 "Очень извиняюсь. Наш техник сегодня уже посмотрел два номера."),
                ("What does the guest ask?", [
                    ("Could he fix it before dinner, or should we change rooms?", True),
                    ("Did he fix it tomorrow before dinner?", False),
                    ("Is the shower complaining about us?", False)])]),
            "d": ("to complain", "To say clearly that something is not good enough",
                  ["To thank the staff for good service", "To book a table for dinner quietly"]),
            "lw": ("If the TV ___ , we will call you again.", "If the TV breaks, we will call you again.",
                   "breaks", ["will break", "broke"]),
            "mw": ("You should report it ___ once.", "at", "at"),
            "ch": ([("Friend", "The wifi in our room is very slow.")], "You",
                   "Tell reception — if enough guests complain, they will fix the router today.",
                   ["I told them yesterday tomorrow.", "The wifi is complaining to us."]),
        },
    ],

    "A2_TRAVEL_PUBLIC_TRANSPORT_AND_CONNECTIONS": [
        {
            "t": ("Поездка на поезде", "A Train Journey"),
            "o": ("Рассказать о поездке на транспорте, используя past simple и present perfect.",
                  "Talk about a transport journey using past simple and present perfect."),
            "v": [("platform", "платформа"), ("single ticket", "билет в одну сторону"),
                  ("return ticket", "билет туда-обратно"), ("to miss", "опоздать на (транспорт)"),
                  ("timetable", "расписание"), ("carriage", "вагон"),
                  ("on time", "по расписанию")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The train has just arrived at platform four.",
                  ["The train has arrived yesterday at four.", "The train arrive just now already."]),
            "tr": ("Мы почти опоздали на поезд, но он задержался на десять минут.",
                   "We almost missed the train, but it was ten minutes late.",
                   ["did", "miss", "tomorrow"]),
            "fill": ("She bought a ___ ticket because she returns on Sunday.", "return",
                     ["returns", "returning"], "Она купила обратный билет, потому что возвращается в воскресенье."),
            "tap": ("The train has already left platform two.", ["was", "did"]),
            "sh": ("We took the fast train from platform six, and it has brought us to the coast in two hours.",
                   "Мы сели на скорый поезд с шестой платформы, и он довёз нас до побережья за два часа."),
            "st": ("The Missed Connection", [
                ("Anna", "Our train to the airport has just left — we are on the wrong platform!",
                 "Наш поезд в аэропорт только что ушёл — мы не на той платформе!"),
                ("Tom", "When did you notice?", "Когда ты заметила?"),
                ("What does Anna say?", [
                    ("A minute ago. There is another train in twenty minutes, hasn't there?", True),
                    ("Tomorrow. Another train came yesterday.", False),
                    ("The platform is missing the train instead.", False)])]),
            "d": ("platform", "The area where you get on and off a train",
                  ["A place to park cars near the station", "A ticket office inside the building"]),
            "lw": ("The train has ___ from platform two.", "The train has departed from platform two.",
                   "departed", ["depart", "departing"]),
            "mw": ("I have bought a ___ ticket by mistake.", "single", "si"),
            "ch": ([("Local", "Does this tram go to the old town?")], "You",
                   "Yes, but it turns before the bridge — I have taken it twice and always changed at the gate.",
                   ["Yes, I take it yesterday tomorrow.", "The old town is taking this tram."]),
        },
        {
            "t": ("Как доберёмся завтра", "How We Will Get There Tomorrow"),
            "o": ("Спланировать поездку на транспорте и сравнить варианты.",
                  "Plan a transport trip and compare options."),
            "v": [("day pass", "дневной проездной"), ("cheaper", "дешевле"),
                  ("direct", "прямой (без пересадок)"), ("to change", "сделать пересадку"),
                  ("more convenient", "удобнее"), ("night bus", "ночной автобус"),
                  ("traffic", "дорожное движение")],
            "q": ("Which sentence compares two options correctly?",
                  "The metro is faster than the bus in the morning.",
                  ["The metro is more fast than the bus.", "The metro is fastest than the bus."]),
            "tr": ("Мы собираемся купить дневной проездной — так дешевле, чем четыре билета.",
                   "We are going to buy a day pass — it is cheaper than four single tickets.",
                   ["did", "bought", "yesterday"]),
            "fill": ("A direct train is ___ convenient than one with two changes.", "more",
                     ["most", "much"], "Прямой поезд удобнее поезда с двумя пересадками."),
            "tap": ("We are going to take the night bus to save one hotel night.", ["was", "did"]),
            "sh": ("If we leave before seven, we will avoid the worst morning traffic on the ring road.",
                   "Если выехать до семи, избежим худшего утреннего трафика на кольцевой."),
            "st": ("Metro or Bus?", [
                ("Tom", "Should we take the metro or the bus to the stadium?", "Ехать на стадион на метро или автобусе?"),
                ("Anna", "The metro does not get stuck in traffic.", "Метро не стоит в пробках."),
                ("What do they decide?", [
                    ("Then we are going to take the metro and walk ten minutes.", True),
                    ("Then we took the metro yesterday tomorrow.", False),
                    ("The stadium is taking us by metro.", False)])]),
            "d": ("day pass", "A ticket for unlimited travel during one day",
                  ["A ticket for one single journey", "A monthly card for local residents"]),
            "lw": ("We are going to ___ at Central Station.", "We are going to change at Central Station.",
                   "change", ["changed", "changing"]),
            "mw": ("The night bus is ___ than a taxi.", "cheaper", "ch"),
            "ch": ([("Friend", "Is the last tram before midnight?")], "You",
                   "Yes — if we catch the eleven o'clock one, we will be home by half past.",
                   ["I caught it yesterday tomorrow.", "Midnight is catching the tram."]),
        },
        {
            "t": ("Если опоздаем на пересадку", "If We Miss the Connection"),
            "o": ("Обсудить пересадки, используя should и первое условное.",
                  "Discuss connections using should and the first conditional."),
            "v": [("connection", "пересадка (на другой рейс)"), ("to run late", "опаздывать"),
                  ("valid", "действительный"), ("to check", "проверить"),
                  ("alternative", "альтернатива"), ("platform change", "изменение платформы"),
                  ("in plenty of time", "с запасом времени")],
            "q": ("Which sentence gives correct advice?",
                  "You should leave at least twenty minutes for a connection.",
                  ["You should to leave twenty minutes yesterday.", "You must leaving time last week."]),
            "tr": ("Если поезд опоздает, мы не успеем на последний автобус из аэропорта.",
                   "If the train runs late, we will not catch the last bus from the airport.",
                   ["did", "ran", "yesterday"]),
            "fill": ("If you ___ your ticket before boarding, it will stay valid.", "validate",
                     ["will validate", "validated"], "Если прокомпостировать билет до посадки, он останется действительным."),
            "tap": ("You should check the platform number twice.", ["mustn't", "went"]),
            "sh": ("If we buy flexible tickets, a missed connection will not ruin the whole journey.",
                   "Если купить гибкие билеты, пропущенная пересадка не разрушит всю поездку."),
            "st": ("Ten Minutes Only", [
                ("Anna", "We have only ten minutes for the connection in Lyon.", "У нас всего десять минут на пересадку в Лионе."),
                ("Tom", "That is tight. What happens if the first train is late?",
                 "Это впритык. Что будет, если первый поезд опоздает?"),
                ("What is the plan?", [
                    ("If we miss it, we should take the next regional train.", True),
                    ("If we will miss it, we took it yesterday.", False),
                    ("The connection is missing the trains.", False)])]),
            "d": ("connection", "A second vehicle you must catch to continue a journey",
                  ["The last stop of a single train line", "A bus that circles the airport every night"]),
            "lw": ("If the first train ___ , we will call the hotel.", "If the first train runs late, we will call the hotel.",
                   "runs late", ["will run late", "ran late"]),
            "mw": ("You should arrive ___ plenty of time.", "in", "in"),
            "ch": ([("Friend", "Our train is delayed by twenty minutes.")], "You",
                   "We should tell the conductor — if the delay is their fault, the next ticket will be free.",
                   ["I told him yesterday tomorrow.", "The minutes are delaying us."]),
        },
    ],

    "A2_TRAVEL_RESTAURANTS_AND_SPECIAL_REQUESTS": [
        {
            "t": ("Ужин, который запомнился", "A Dinner to Remember"),
            "o": ("Рассказать о посещении ресторана, используя past simple и present perfect.",
                  "Talk about a restaurant visit using past simple and present perfect."),
            "v": [("starter", "закуска"), ("main course", "основное блюдо"),
                  ("bill", "счёт"), ("to tip", "оставить чаевые"),
                  ("vegetarian", "вегетарианский"), ("dessert", "десерт"),
                  ("reservation", "бронь")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "We have already ordered the starters.",
                  ["We have ordered them yesterday.", "We order the starters already now."]),
            "tr": ("Мы заказали закуски и основные блюда, но десерт оставили на потом.",
                   "We ordered the starters and the main courses, but we have left the dessert for later.",
                   ["did", "order", "tomorrow"]),
            "fill": ("Last night the restaurant ___ our reservation by mistake.", "lost",
                     ["has lose", "losing"], "Вчера вечером ресторан по ошибке потерял нашу бронь."),
            "tap": ("She has just asked for the bill.", ["was", "did"]),
            "sh": ("We asked for a table by the window, and the waiter has brought the menu with vegetarian dishes already marked.",
                   "Мы попросили столик у окна, и официант принёс меню, где вегетарианские блюда уже отмечены."),
            "st": ("The Busy Friday", [
                ("Waiter", "Good evening. Do you have a reservation?", "Добрый вечер. У вас есть бронь?"),
                ("Guest", "Yes, under the name Petrov for eight o'clock.", "Да, на фамилию Петров, на восемь."),
                ("What does the waiter say?", [
                    ("Ah yes, a table for two by the window. Has anyone taken your coat?", True),
                    ("Yes, your table has arrived yesterday.", False),
                    ("The reservation is eating the dinner.", False)])]),
            "d": ("starter", "The first small dish of a meal",
                  ["The biggest dish of the evening", "The drink you order at the bar"]),
            "lw": ("We have ___ a table for tonight.", "We have booked a table for tonight.",
                   "booked", ["book", "booking"]),
            "mw": ("Could we have the ___ , please?", "bill", "bi"),
            "ch": ([("Waiter", "Are you ready to order?")], "You",
                   "Almost — could we get a few more minutes? We have not chosen the main courses yet.",
                   ["Yes, we order yesterday tomorrow.", "The menu is ordering us."]),
        },
        {
            "t": ("Выбираем ресторан", "Choosing a Restaurant"),
            "o": ("Сравнить рестораны и заказать еду с особыми пожеланиями.",
                  "Compare restaurants and order food with special requests."),
            "v": [("special request", "особая просьба (к блюду)"), ("allergy", "аллергия"),
                  ("spicy", "острый"), ("more popular", "популярнее"),
                  ("to recommend", "порекомендовать"), ("portion", "порция"),
                  ("to try", "попробовать")],
            "q": ("Which sentence compares two restaurants correctly?",
                  "The bistro by the market is more popular than the one on the square.",
                  ["The bistro is popularer than the other one.", "The bistro is most popular than the square one."]),
            "tr": ("Не могли бы вы приготовить это без орехов? У моего сына аллергия.",
                   "Could you prepare this without nuts? My son has an allergy.",
                   ["did", "can", "yesterday"]),
            "fill": ("This local dish is ___ than the tourist menu.", "cheaper",
                     ["cheapest", "more cheap"], "Это местное блюдо дешевле туристического меню."),
            "tap": ("We are going to try the seafood restaurant tonight.", ["was", "did"]),
            "sh": ("If you tell the waiter about your allergy, the kitchen will adapt almost any dish.",
                   "Если сказать официанту об аллергии, кухня адаптирует почти любое блюдо."),
            "st": ("The Special Request", [
                ("Guest", "I would love the grilled fish, but is it very spicy?", "Я бы взял рыбу на гриле, но она очень острая?"),
                ("Waiter", "The sauce is spicy, but the kitchen can serve it separately.",
                 "Соус острый, но кухня может подать его отдельно."),
                ("What does the guest decide?", [
                    ("Perfect — I will take it with the sauce on the side.", True),
                    ("Perfect, I took it yesterday tomorrow.", False),
                    ("The fish is deciding about the sauce.", False)])]),
            "d": ("allergy", "A condition when some food makes you ill",
                  ["A strong liking for one particular dish", "A skill of cooking without a recipe"]),
            "lw": ("We are going to ___ the local stew.", "We are going to try the local stew.",
                   "try", ["tried", "trying"]),
            "mw": ("The portions here are ___ than at the hotel.", "bigger", "bi"),
            "ch": ([("Waiter", "Would you like anything to drink first?")], "You",
                   "A bottle of still water, please — if the house wine is dry, we will try that too.",
                   ["I drank it yesterday tomorrow.", "The water is drinking me."]),
        },
        {
            "t": ("Если блюдо не то", "If the Dish Is Wrong"),
            "o": ("Решить проблему с заказом, используя should и первое условное.",
                  "Solve an order problem using should and the first conditional."),
            "v": [("to send back", "вернуть (блюдо)"), ("rare", "недожаренный (о мясе)"),
                  ("to apologise", "извиниться"), ("mix-up", "путаница"),
                  ("on the house", "за счёт заведения"), ("patient", "терпеливый"),
                  ("instead", "вместо этого")],
            "q": ("Which sentence gives correct advice?",
                  "You should send the dish back politely if it is not what you ordered.",
                  ["You should to send it back yesterday.", "You must sending it back last week."]),
            "tr": ("Если вы вернёте блюдо вежливо, повар приготовит новое без вопросов.",
                   "If you send the dish back politely, the chef will cook a new one without questions.",
                   ["did", "sent", "yesterday"]),
            "fill": ("If the waiter ___ the order, they usually offer a free dessert.",
                     "mixes up", ["will mix up", "mixed up"], "Если официант перепутает заказ, обычно предлагают бесплатный десерт."),
            "tap": ("You should check the dish before you start eating.", ["mustn't", "went"]),
            "sh": ("If the kitchen made a mistake, the dessert will probably be on the house.",
                   "Если кухня ошиблась, десерт, скорее всего, будет за счёт заведения."),
            "st": ("The Wrong Dish", [
                ("Guest", "Excuse me, I ordered the vegetarian risotto, and this has chicken in it.",
                 "Извините, я заказывал вегетарианское ризотто, а тут курица."),
                ("Waiter", "I'm so sorry — there has been a mix-up with the table numbers.",
                 "Очень извиняюсь — произошла путаница с номерами столиков."),
                ("What does the waiter offer?", [
                    ("I will bring the risotto in ten minutes, and your drinks will be on the house.", True),
                    ("I brought it yesterday tomorrow already.", False),
                    ("The chicken is ordering the risotto back.", False)])]),
            "d": ("on the house", "Free, paid for by the restaurant",
                  ["Cooked at home and brought with you", "The most expensive dish on the menu"]),
            "lw": ("If the meat is too ___ , send it back.", "If the meat is too rare, send it back.",
                   "rare", ["rarely", "rarest"]),
            "mw": ("You should say it politely ___ of angrily.", "instead", "in"),
            "ch": ([("Friend", "They brought me the wrong soup.")], "You",
                   "Call the waiter — if you explain calmly, they will change it quickly.",
                   ["He changed it yesterday tomorrow.", "The soup is calling the waiter."]),
        },
    ],

    "A2_TRAVEL_SHOPPING_SOUVENIRS_AND_SERVICES": [
        {
            "t": ("Покупки и сувениры", "Shopping and Souvenirs"),
            "o": ("Рассказать о покупках, используя past simple и present perfect.",
                  "Talk about shopping using past simple and present perfect."),
            "v": [("souvenir", "сувенир"), ("to bargain", "торговаться"),
                  ("receipt", "чек"), ("handmade", "ручной работы"),
                  ("to pay by card", "платить картой"), ("discount", "скидка"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have bought six postcards so far.",
                  ["I have bought six postcards yesterday.", "I buy six postcards so far already."]),
            "tr": ("Я купил подарок ручной работы и заплатил картой, но чек потерял.",
                   "I bought a handmade gift and paid by card, but I have lost the receipt.",
                   ["did", "buy", "tomorrow"]),
            "fill": ("She ___ a small discount at the market yesterday.", "asked for",
                     ["has ask for", "asking for"], "Вчера на рынке она попросила небольшую скидку."),
            "tap": ("We have already spent all our cash on souvenirs.", ["was", "did"]),
            "sh": ("The market has opened at eight, and by nine the best handmade goods have almost gone.",
                   "Рынок открылся в восемь, а к девяти лучшие изделия ручной работы почти разошлись."),
            "st": ("The Last Souvenir", [
                ("Anna", "Look at these ceramics! Have you bought anything for your parents yet?",
                 "Смотри на эту керамику! Ты уже купил что-нибудь родителям?"),
                ("Tom", "Not yet. Did you see the price of those lamps?", "Ещё нет. Ты видела цену тех ламп?"),
                ("What does Anna say?", [
                    ("Yes, but they are handmade — I think we should get one.", True),
                    ("Yes, I buy them yesterday tomorrow.", False),
                    ("The ceramics are buying our parents.", False)])]),
            "d": ("receipt", "The paper that proves you paid for something",
                  ["A list of things you want to buy", "A map of the shopping street"]),
            "lw": ("I have ___ for a discount politely.", "I have asked for a discount politely.",
                   "asked", ["ask", "asking"]),
            "mw": ("Could I pay ___ card?", "by", "by"),
            "ch": ([("Seller", "These scarves are handmade, madam.")], "You",
                   "They are beautiful — I have already bought two, but this blue one is the nicest.",
                   ["I bought it yesterday tomorrow.", "The scarves are buying me."]),
        },
        {
            "t": ("Что купим завтра", "What We Will Buy Tomorrow"),
            "o": ("Спланировать покупки и сравнить места для них.",
                  "Plan purchases and compare shopping places."),
            "v": [("market", "рынок"), ("duty-free", "duty-free / беспошлинный"),
                  ("more original", "оригинальнее"), ("to wrap", "упаковать"),
                  ("as a gift", "в подарок"), ("weight limit", "лимит веса (багажа)"),
                  ("to leave space", "оставить место (в чемодане)")],
            "q": ("Which sentence compares two shopping places correctly?",
                  "The market is more original than the airport shops.",
                  ["The market is originaler than the shops.", "The market is most original than the shops."]),
            "tr": ("Завтра мы пойдём на рынок — там подарки оригинальнее, чем в аэропорту.",
                   "Tomorrow we are going to the market — the gifts there are more original than at the airport.",
                   ["did", "went", "yesterday"]),
            "fill": ("The market prices are ___ than in the shopping centre.", "lower",
                     ["lowest", "more low"], "Цены на рынке ниже, чем в торговом центре."),
            "tap": ("I am going to buy the tea as a gift for my colleagues.", ["was", "did"]),
            "sh": ("If you leave some space in your suitcase, you will not sit on your souvenirs on the way home.",
                   "Если оставить в чемодане место, не придётся сидеть на сувенирах по дороге домой."),
            "st": ("The Heavy Suitcase", [
                ("Anna", "I want to buy this ceramic set, but my suitcase is already full.",
                 "Хочу купить этот керамический набор, но чемодан уже полон."),
                ("Tom", "What is your weight limit?", "Какой у тебя лимит веса?"),
                ("What should Anna do?", [
                    ("If I wear my heaviest jacket, I can take the set.", True),
                    ("I worn it yesterday tomorrow.", False),
                    ("The suitcase is buying the ceramics.", False)])]),
            "d": ("to wrap", "To cover something in paper as a present",
                  ["To pay extra for heavy luggage", "To open a box before giving it"]),
            "lw": ("They are going to ___ it as a gift.", "They are going to wrap it as a gift.",
                   "wrap", ["wrapped", "wrapping"]),
            "mw": ("The market is ___ than duty-free.", "cheaper", "ch"),
            "ch": ([("Friend", "Where should I buy the local honey?")], "You",
                   "At the Saturday market — if you go before ten, the choice will be better.",
                   ["I bought it yesterday tomorrow.", "The honey is buying me."]),
        },
        {
            "t": ("Если нужно вернуть покупку", "If You Need a Return"),
            "o": ("Объяснить возврат товара, используя should и первое условное.",
                  "Explain returns using should and the first conditional."),
            "v": [("to refund", "вернуть деньги"), ("exchange", "обмен"),
                  ("faulty", "бракованный"), ("to keep the receipt", "сохранить чек"),
                  ("size", "размер"), ("unworn", "ненадеванный"),
                  ("within fourteen days", "в течение четырнадцати дней")],
            "q": ("Which sentence gives correct advice?",
                  "You should keep the receipt until you are home.",
                  ["You should to keep it yesterday.", "You must keeping it last week."]),
            "tr": ("Если товар бракованный, магазин обязан вернуть деньги.",
                   "If the goods are faulty, the shop must give you a refund.",
                   ["did", "was", "yesterday"]),
            "fill": ("If you want an ___, bring the unworn item with the receipt.",
                     "exchange", ["exchanging", "exchanged"], "Если нужен обмен, принесите неношеную вещь с чеком."),
            "tap": ("You should check souvenirs for cracks before buying.", ["mustn't", "went"]),
            "sh": ("If you keep all your receipts in one envelope, any return will take five minutes.",
                   "Если хранить все чеки в одном конверте, любой возврат займёт пять минут."),
            "st": ("The Cracked Vase", [
                ("Tourist", "I bought this vase yesterday, and it has a crack on the side.",
                 "Я купил эту вазу вчера, а на ней трещина сбоку."),
                ("Seller", "Do you have the receipt with you?", "Чек с вами?"),
                ("What does the tourist show?", [
                    ("Yes, here it is — could I exchange it for an intact one?", True),
                    ("Yes, I have it tomorrow yesterday.", False),
                    ("The crack is buying a new vase.", False)])]),
            "d": ("exchange", "To change an item you bought for a different one",
                  ["To get your money back completely", "To sell your old things to a shop"]),
            "lw": ("If the item is ___ , they will refund you.", "If the item is faulty, they will refund you.",
                   "faulty", ["fault", "falsely"]),
            "mw": ("You should keep the ___ for two weeks.", "receipt", "re"),
            "ch": ([("Friend", "The jumper I bought is too small.")], "You",
                   "Take it back — if it is unworn and you have the receipt, they will exchange it.",
                   ["I exchanged it yesterday tomorrow.", "The jumper is returning me."]),
        },
    ],

    "A2_TRAVEL_SIGHTSEEING_AND_LOCAL_ACTIVITIES": [
        {
            "t": ("Экскурсия, которая удалась", "The Tour That Worked Out"),
            "o": ("Рассказать об экскурсиях, используя past simple и present perfect.",
                  "Talk about sightseeing using past simple and present perfect."),
            "v": [("guided tour", "экскурсия с гидом"), ("exhibition", "выставка"),
                  ("to skip the line", "пройти без очереди"), ("opening hours", "часы работы"),
                  ("crowded", "многолюдный"), ("to take photos", "фотографировать"),
                  ("worth", "стоящий (того)")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "We have already visited two museums today.",
                  ["We have visited two museums yesterday.", "We visit two museums already today."]),
            "tr": ("Мы пришли к девяти утра и прошли в собор без очереди.",
                   "We arrived at nine in the morning and skipped the line into the cathedral.",
                   ["did", "arrive", "tomorrow"]),
            "fill": ("The gallery ___ at ten o'clock last Sunday.", "opened",
                     ["has open", "opening"], "Галерея открылась в десять в прошлое воскресенье."),
            "tap": ("She has taken more than two hundred photos today.", ["was", "did"]),
            "sh": ("The old town was less crowded in the evening, and we have finally seen the famous tower without queues.",
                   "Старый город вечером был менее многолюдным, и мы наконец увидели знаменитую башню без очередей."),
            "st": ("The Long Queue", [
                ("Tom", "The queue for the castle is enormous — two hours, the sign says.",
                 "Очередь в замок огромная — на табличке два часа."),
                ("Anna", "Have you checked the online tickets?", "Ты проверил онлайн-билеты?"),
                ("What does Tom say?", [
                    ("Yes, the e-ticket holders have skipped the line all morning.", True),
                    ("Yes, they skipped it yesterday tomorrow.", False),
                    ("The queue is visiting the castle itself.", False)])]),
            "d": ("opening hours", "The times when a place is open to visitors",
                  ["The price of a single entrance ticket", "A tour that happens every hour"]),
            "lw": ("We have ___ the whole old town.", "We have explored the whole old town.",
                   "explored", ["explore", "exploring"]),
            "mw": ("The exhibition was ___ the price.", "worth", "wo"),
            "ch": ([("Guide", "Did you enjoy the walking tour?")], "You",
                   "Very much — it was more interesting than the bus tour we took last year.",
                   ["I enjoyed it yesterday tomorrow.", "The tour is enjoying us."]),
        },
        {
            "t": ("Планы на выходные", "Weekend Plans"),
            "o": ("Спланировать осмотр достопримечательностей и сравнить активности.",
                  "Plan sightseeing and compare activities."),
            "v": [("boat trip", "прогулка на лодке"), ("more relaxing", "расслабляющий (более спокойный)"),
                  ("to climb", "подняться на (возвышенность)"), ("sunset", "закат"),
                  ("to rent", "взять напрокат"), ("local guide", "местный гид"),
                  ("busier", "оживлённее")],
            "q": ("Which sentence compares two activities correctly?",
                  "The boat trip is more relaxing than the mountain hike.",
                  ["The boat trip is relaxingest than the hike.", "The boat trip is more relax than the hike."]),
            "tr": ("В субботу мы собираемся взять напрокат велосипеды и поехать к пляжу.",
                   "On Saturday we are going to rent bikes and ride to the beach.",
                   ["did", "rented", "yesterday"]),
            "fill": ("The square at sunset is ___ than at noon.", "busier",
                     ["busiest", "more busy"], "Площадь на закате оживлённее, чем в полдень."),
            "tap": ("We are going to watch the sunset from the hill.", ["was", "did"]),
            "sh": ("If we book the early boat trip, we will see the caves before the crowds.",
                   "Если забронировать раннюю прогулку на лодке, увидим гроты до наплыва туристов."),
            "st": ("Saturday Morning", [
                ("Anna", "What are we doing on Saturday — the boat trip or the castle?", "Что делаем в субботу — лодку или замок?"),
                ("Tom", "The castle gets busier later, and the boat is more relaxing in the afternoon.",
                 "Замок позже оживлённее, а лодка расслабляет лучше во второй половине дня."),
                ("What do they decide?", [
                    ("Then we are going to the castle first and the boat at four.", True),
                    ("Then we went to the castle yesterday tomorrow.", False),
                    ("Saturday is deciding our trip.", False)])]),
            "d": ("to rent", "To pay to use something for a short time",
                  ["To buy something to keep forever", "To borrow money from a friend"]),
            "lw": ("We are going to ___ bikes for the day.", "We are going to rent bikes for the day.",
                   "rent", ["rented", "renting"]),
            "mw": ("The evening boat is ___ relaxing.", "more", "mo"),
            "ch": ([("Friend", "Is the tower worth the climb?")], "You",
                   "Yes — if the sky is clear, you will see the whole bay from the top.",
                   ["I climbed it yesterday tomorrow.", "The tower is climbing me."]),
        },
        {
            "t": ("Если погода подведёт", "If the Weather Is Bad"),
            "o": ("Обсудить запасные планы, используя should и первое условное.",
                  "Discuss backup plans using should and the first conditional."),
            "v": [("forecast", "прогноз погоды"), ("indoor", "крытый (в помещении)"),
                  ("to check in advance", "проверить заранее"), ("backup plan", "запасной план"),
                  ("museum pass", "музейный абонемент"), ("to change plans", "изменить планы"),
                  ("after all", "в конце концов")],
            "q": ("Which sentence gives correct advice?",
                  "You should check the forecast before planning a boat trip.",
                  ["You should to check it yesterday.", "You must checking it last night."]),
            "tr": ("Если пойдёт дождь, мы проведём день в музеях вместо пляжа.",
                   "If it rains, we will spend the day in the museums instead of the beach.",
                   ["did", "rained", "yesterday"]),
            "fill": ("If the weather ___ worse, the boat trip will be cancelled.",
                     "gets", ["will get", "got"], "Если погода ухудшится, прогулку на лодке отменят."),
            "tap": ("You should always have an indoor plan B.", ["mustn't", "went"]),
            "sh": ("If you buy the museum pass online, you will enter every rainy-day place without queues.",
                   "Если купить музейный абонемент онлайн, в любой дождливый день вход будет без очередей."),
            "st": ("The Rainy Morning", [
                ("Anna", "The forecast says rain all afternoon.", "Прогноз обещает дождь весь день."),
                ("Tom", "Then the beach is off. What should we do instead?", "Тогда пляж отменяется. Чем заняться вместо?"),
                ("What does Anna suggest?", [
                    ("If it rains, we should use the museum pass we bought online.", True),
                    ("If it will rain, we used it yesterday.", False),
                    ("The rain is planning the beach.", False)])]),
            "d": ("forecast", "Information about future weather",
                  ["A description of yesterday's temperature", "A map of city museums and galleries"]),
            "lw": ("If it ___ , we will visit the aquarium.", "If it rains, we will visit the aquarium.",
                   "rains", ["will rain", "rained"]),
            "mw": ("You should check the forecast in ___ .", "advance", "ad"),
            "ch": ([("Friend", "The sky looks grey today.")], "You",
                   "We should take the umbrellas — if it starts on the hill, the walk will be spoiled.",
                   ["I took them yesterday tomorrow.", "The sky is walking us."]),
        },
    ],

    "A2_TRAVEL_TICKETS_BOOKINGS_AND_CHANGES": [
        {
            "t": ("Как мы бронировали", "How We Booked"),
            "o": ("Рассказать о бронированиях, используя past simple и present perfect.",
                  "Talk about bookings using past simple and present perfect."),
            "v": [("to book online", "забронировать онлайн"), ("confirmation email", "письмо-подтверждение"),
                  ("non-refundable", "невозвратный"), ("to reserve", "зарезервировать"),
                  ("seat reservation", "бронь места"), ("booking reference", "код бронирования"),
                  ("straight away", "сразу же")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The hotel has sent the confirmation email already.",
                  ["The hotel has sent it yesterday.", "The hotel send the email already now."]),
            "tr": ("Я забронировал билеты сразу же, потому что цена выросла на следующий день.",
                   "I booked the tickets straight away because the price went up the next day.",
                   ["did", "book", "tomorrow"]),
            "fill": ("We reserved the seats a month ___ .", "ago",
                     ["since", "before"], "Мы забронировали места месяц назад."),
            "tap": ("She has received the booking reference by email.", ["was", "did"]),
            "sh": ("I have printed all the confirmation emails, but the booking reference has not arrived yet.",
                   "Я распечатал все подтверждения, но код бронирования ещё не пришёл."),
            "st": ("The Vanishing Price", [
                ("Anna", "I booked the flight this morning for two hundred euros.", "Я забронировала рейс сегодня утром за двести евро."),
                ("Tom", "The same flight now costs two hundred and sixty. When did the price change?",
                 "Тот же рейс теперь стоит двести шестьдесят. Когда цена изменилась?"),
                ("What does Anna say?", [
                    ("About an hour after my booking — I have saved sixty euros.", True),
                    ("Tomorrow, an hour ago yesterday.", False),
                    ("The price is booking the flight.", False)])]),
            "d": ("non-refundable", "That cannot be cancelled for money back",
                  ["Easy to change to another date for free", "Paid for at the hotel on arrival"]),
            "lw": ("I have ___ two seats for the night train.", "I have reserved two seats for the night train.",
                   "reserved", ["reserve", "reserving"]),
            "mw": ("Have you received the ___ email?", "confirmation", "co"),
            "ch": ([("Agent", "Do you have your booking reference?")], "You",
                   "Yes, here it is — I have also brought the confirmation email, just in case.",
                   ["Yes, I have it tomorrow yesterday.", "The reference is booking me."]),
        },
        {
            "t": ("Меняем бронирование", "Changing a Booking"),
            "o": ("Изменить бронирование и сравнить тарифы.",
                  "Change a booking and compare fares."),
            "v": [("to change a booking", "изменить бронь"), ("flexible fare", "гибкий тариф"),
                  ("change fee", "сбор за изменение"), ("more expensive", "дороже"),
                  ("to upgrade", "улучшить (тариф/класс)"), ("availability", "наличие мест"),
                  ("to rebook", "перебронировать")],
            "q": ("Which sentence compares two fares correctly?",
                  "The flexible fare is more expensive than the basic one.",
                  ["The flexible fare is expensiver than basic.", "The flexible fare is most expensive than basic."]),
            "tr": ("Мы собираемся изменить дату — гибкий тариф стоит дороже, но без сбора за изменение.",
                   "We are going to change the date — the flexible fare is more expensive, but there is no change fee.",
                   ["did", "changed", "yesterday"]),
            "fill": ("The basic fare has a change ___ of thirty euros.", "fee",
                     ["fees", "feeing"], "У базового тарифа сбор за изменение — тридцать евро."),
            "tap": ("They are going to rebook us on the morning flight.", ["was", "did"]),
            "sh": ("If you upgrade to the flexible fare now, any future change will cost you nothing extra.",
                   "Если перейти на гибкий тариф сейчас, любое будущее изменение будет бесплатным."),
            "st": ("The Date Change", [
                ("Customer", "I need to move my ticket from Friday to Sunday.", "Мне нужно перенести билет с пятницы на воскресенье."),
                ("Agent", "There is availability, but the basic fare has a change fee.", "Места есть, но у базового тарифа сбор за изменение."),
                ("What does the customer ask?", [
                    ("How much is the fee, and is the flexible fare still cheaper than a new ticket?", True),
                    ("Is the fee arriving tomorrow yesterday?", False),
                    ("Is the Friday changing the fee?", False)])]),
            "d": ("fare", "The price you pay for a journey by train or plane",
                  ["The food served during a long flight", "A hotel room with breakfast included"]),
            "lw": ("They are going to ___ us on the early train.", "They are going to rebook us on the early train.",
                   "rebook", ["rebooked", "rebooking"]),
            "mw": ("The flexible fare is ___ for changes.", "better", "be"),
            "ch": ([("Agent", "Would you like to keep the same seat?")], "You",
                   "If possible — if the window seat is free on the new flight, I will take it.",
                   ["I kept it yesterday tomorrow.", "The seat is rebooking me."]),
        },
        {
            "t": ("Если планы сорвутся", "If Plans Fall Through"),
            "o": ("Обсудить отмену бронирования, используя should и первое условное.",
                  "Discuss cancelling a booking using should and the first conditional."),
            "v": [("cancellation", "отмена"), ("to cancel", "отменить"),
                  ("refundable", "возвратный"), ("to read the rules", "прочитать правила"),
                  ("before booking", "до бронирования"), ("insurance", "страховка"),
                  ("in case", "на случай")],
            "q": ("Which sentence gives correct advice?",
                  "You should read the cancellation rules before booking.",
                  ["You should to read them yesterday.", "You must reading them last week."]),
            "tr": ("Если планы изменятся, возвратный тариф спасёт деньги.",
                   "If your plans change, a refundable fare will save your money.",
                   ["did", "changed", "yesterday"]),
            "fill": ("If you ___ within twenty-four hours, most airlines will refund the full price.",
                     "cancel", ["will cancel", "cancelled"], "Если отменить в течение суток, большинство авиакомпаний вернёт полную стоимость."),
            "tap": ("You should keep the insurance documents in case of cancellation.", ["mustn't", "went"]),
            "sh": ("If you book refundable rooms, a sudden change of plans will not destroy your budget.",
                   "Если бронировать возвратные номера, внезапная смена планов не разрушит бюджет."),
            "st": ("The Sudden Change", [
                ("Anna", "Our host has just cancelled our flat for next week!", "Хозяин только что отменил нашу квартиру на следующую неделю!"),
                ("Tom", "Did you book the refundable option?", "Ты брала возвратный вариант?"),
                ("What does Anna answer?", [
                    ("Yes, luckily — if I hadn't, we would lose two hundred euros.", True),
                    ("Yes, I will booked it tomorrow yesterday.", False),
                    ("The flat is refunding our plans.", False)])]),
            "d": ("refundable", "Something you can get your money back for",
                  ["A ticket that cannot be used after the date", "A service paid only in cash"]),
            "lw": ("If the airline ___ the flight, you will get a voucher.", "If the airline cancels the flight, you will get a voucher.",
                   "cancels", ["will cancel", "cancelled"]),
            "mw": ("You should buy insurance ___ case of illness.", "in", "in"),
            "ch": ([("Friend", "Should I book the cheaper non-refundable room?")], "You",
                   "Think twice — if your trip changes, the flexible room will be cheaper in the end.",
                   ["I booked it yesterday tomorrow.", "The room is refunding me."]),
        },
    ],

    "A2_TRAVEL_TRAVEL_EXPERIENCES_AND_RETURNING_HOME": [
        {
            "t": ("Лучшие моменты поездки", "Best Moments of the Trip"),
            "o": ("Поделиться впечатлениями, используя past simple и present perfect.",
                  "Share impressions using past simple and present perfect."),
            "v": [("highlight", "лучший момент"), ("unforgettable", "незабываемый"),
                  ("to try local food", "попробовать местную еду"), ("experience", "впечатление / опыт"),
                  ("to come back", "вернуться"), ("already", "уже"),
                  ("abroad", "за границей")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "This is the best meal I have ever tried abroad.",
                  ["This is the best meal I have tried it last year.", "This is the best meal I try already abroad."]),
            "tr": ("Мы попробовали местную уличную еду, и это был лучший вечер поездки.",
                   "We tried the local street food, and it was the best evening of the trip.",
                   ["did", "try", "tomorrow"]),
            "fill": ("The boat trip at sunset was the ___ of our holiday.", "highlight",
                     ["highlights", "highlighting"], "Прогулка на лодке на закате стала лучшим моментом отпуска."),
            "tap": ("She has already planned to come back next spring.", ["was", "did"]),
            "sh": ("We have visited nine places in ten days, and the mountain village has been the most unforgettable one.",
                   "Мы посетили девять мест за десять дней, и горная деревня оказалась самой незабываемой."),
            "st": ("The Last Evening", [
                ("Anna", "So, what was the highlight of the trip for you?", "Итак, какой момент поездки был лучшим для тебя?"),
                ("Tom", "The night market, definitely. Have you ever tasted anything like that grilled fish?",
                 "Ночной рынок, однозначно. Ты когда-нибудь пробовала что-то вроде той рыбы на гриле?"),
                ("What does Anna answer?", [
                    ("Never — and I have already found a recipe to try at home.", True),
                    ("Yes, I try it tomorrow yesterday.", False),
                    ("The market is highlighting the fish.", False)])]),
            "d": ("highlight", "The best or most memorable part of something",
                  ["A problem that spoiled part of the trip", "The hotel where the trip started"]),
            "lw": ("We have ___ so many new dishes.", "We have tried so many new dishes.",
                   "tried", ["try", "trying"]),
            "mw": ("This trip has been ___ .", "unforgettable", "un"),
            "ch": ([("Friend", "How was your holiday?")], "You",
                   "Amazing — it was more authentic than any trip we have done before.",
                   ["It was good yesterday tomorrow.", "The holiday is travelling me."]),
        },
        {
            "t": ("Возвращаемся домой", "Returning Home"),
            "o": ("Рассказать о возвращении, используя формы будущего и сравнения.",
                  "Talk about returning using future forms and comparatives."),
            "v": [("to pack", "собрать (чемодан)"), ("to land", "приземлиться"),
                  ("earlier than planned", "раньше планируемого"), ("jet lag", "смена часовых поясов"),
                  ("to look forward to", "с нетерпением ждать"), ("more tired", "усталее"),
                  ("home sweet home", "дом милый дом")],
            "q": ("Which sentence talks about the future?",
                  "We are landing at six tomorrow morning.",
                  ["We landed at six yesterday morning.", "We has landed tomorrow already."]),
            "tr": ("Завтра мы вылетаем домой, и я уже жду свою собственную кровать.",
                   "We are flying home tomorrow, and I am already looking forward to my own bed.",
                   ["did", "flew", "yesterday"]),
            "fill": ("The return flight is ___ than the flight out.", "shorter",
                     ["shortest", "more short"], "Обратный рейс короче рейса туда."),
            "tap": ("I am going to pack the evening before we leave.", ["was", "did"]),
            "sh": ("If we sleep on the plane, the jet lag will be easier during the first days at home.",
                   "Если поспать в самолёте, смена часовых поясов перенесётся легче в первые дни дома."),
            "st": ("The Last Day", [
                ("Tom", "Our flight is at nine tomorrow. Have you started packing?",
                 "Наш рейс завтра в девять. Ты начала собираться?"),
                ("Anna", "Half of it. The souvenirs take more space than I thought.",
                 "Наполовину. Сувениры занимают больше места, чем я думала."),
                ("What does Tom advise?", [
                    ("You should pack the heavy things in the hand luggage.", True),
                    ("You must packed them yesterday already.", False),
                    ("The suitcase is packing the souvenirs.", False)])]),
            "d": ("jet lag", "The tired feeling after flying across time zones",
                  ["A long queue at the baggage claim", "A delay caused by bad weather"]),
            "lw": ("We are ___ at six in the morning.", "We are landing at six in the morning.",
                   "landing", ["land", "landed"]),
            "mw": ("I am looking forward ___ my own kitchen.", "to", "to"),
            "ch": ([("Friend", "When do you get back?")], "You",
                   "Sunday evening — if the connection goes well, I will be home before midnight.",
                   ["I got back yesterday tomorrow.", "Sunday is getting me back."]),
        },
        {
            "t": ("Рассказываем о поездке", "Telling Others About the Trip"),
            "o": ("Дать советы о рассказах о поездках, используя should и первое условное.",
                  "Give advice about sharing travel stories using should and the first conditional."),
            "v": [("photo album", "фотоальбом"), ("to recommend", "порекомендовать"),
                  ("to exaggerate", "преувеличивать"), ("honest", "честный"),
                  ("tips", "советы"), ("the same route", "тот же маршрут"),
                  ("to share", "поделиться")],
            "q": ("Which sentence gives correct advice?",
                  "You should share practical tips, not just photos.",
                  ["You should to share tips yesterday.", "You must sharing tips last night."]),
            "tr": ("Если ты честно расскажешь о минусах, друзья лучше спланируют поездку.",
                   "If you talk honestly about the downsides, your friends will plan the trip better.",
                   ["did", "told", "yesterday"]),
            "fill": ("If you ___ too much, people will not believe the story.",
                     "exaggerate", ["will exaggerate", "exaggerated"], "Если слишком преувеличивать, люди не поверят рассказу."),
            "tap": ("You should share the route with anyone who asks.", ["mustn't", "went"]),
            "sh": ("If you write down your tips while the trip is fresh, you will remember much more.",
                   "Если записать советы, пока впечатления свежи, запомнится гораздо больше."),
            "st": ("Dinner Stories", [
                ("Anna", "How was the trip? Tell us everything!", "Как прошла поездка? Рассказывай всё!"),
                ("Tom", "It was great. The caves were even bigger than the photos show.",
                 "Было здорово. Гроты оказались даже больше, чем на фото."),
                ("What does Anna ask?", [
                    ("Would you recommend the same route for our autumn trip?", True),
                    ("Did you recommend it tomorrow yesterday?", False),
                    ("Is the route telling the story itself?", False)])]),
            "d": ("to exaggerate", "To make something sound bigger or better than it really was",
                  ["To describe something exactly as it was", "To refuse to talk about a trip at all"]),
            "lw": ("If they ___ our route, they will save a day.", "If they follow our route, they will save a day.",
                   "follow", ["will follow", "followed"]),
            "mw": ("You should share your ___ with other travellers.", "tips", "ti"),
            "ch": ([("Friend", "I am doing the same route next month.")], "You",
                   "Great — if you message me, I will send you our whole list of places.",
                   ["I sent it yesterday tomorrow.", "The route is messaging you."]),
        },
    ],

    "A2_TRAVEL_TRAVEL_PROBLEMS_AND_SOLUTIONS": [
        {
            "t": ("Что пошло не так в поездке", "What Went Wrong on the Trip"),
            "o": ("Рассказать о проблемах в пути, используя past simple и present perfect.",
                  "Talk about travel problems using past simple and present perfect."),
            "v": [("delay", "задержка"), ("lost luggage", "потерянный багаж"),
                  ("to claim", "подать заявление (на компенсацию)"), ("to rebook", "перебронировать"),
                  ("stressful", "стрессовый"), ("customer service", "служба поддержки"),
                  ("eventually", "в итоге")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The airline has found my suitcase this morning.",
                  ["The airline has found it yesterday.", "The airline find it already this morning."]),
            "tr": ("Наш рейс задержали на пять часов, а багаж в итоге потеряли.",
                   "Our flight was delayed by five hours, and the luggage got lost in the end.",
                   ["did", "was", "tomorrow"]),
            "fill": ("They ___ us on the next flight for free.", "rebooked",
                     ["has rebook", "rebooking"], "Нас бесплатно перебронировали на следующий рейс."),
            "tap": ("She has already claimed compensation for the delay.", ["was", "did"]),
            "sh": ("The airline has apologised for the delay, but nobody has explained where our suitcases are.",
                   "Авиакомпания извинилась за задержку, но никто не объяснил, где наши чемоданы."),
            "st": ("The Empty Belt", [
                ("Anna", "Everyone's luggage has arrived, but ours has not.", "Чей хочешь багаж пришёл, а наш — нет."),
                ("Tom", "Did you report it at the lost luggage desk?", "Ты сообщила на стойке потерянного багажа?"),
                ("What does Anna say?", [
                    ("Yes, I have filled in the form and they have given me a tracking number.", True),
                    ("Yes, I fill it in tomorrow yesterday.", False),
                    ("The belt is losing our luggage report.", False)])]),
            "d": ("lost luggage", "Suitcases that did not arrive with your flight",
                  ["A bag you left at home on purpose", "Extra bags you paid for at check-in"]),
            "lw": ("I have ___ a compensation claim online.", "I have submitted a compensation claim online.",
                   "submitted", ["submit", "submitting"]),
            "mw": ("Our flight has been ___ for three hours.", "delayed", "de"),
            "ch": ([("Agent", "How can I help you?")], "You",
                   "Our connecting train has been cancelled — could you rebook us on the night bus?",
                   ["You rebooked us yesterday tomorrow.", "The train is helping you."]),
        },
        {
            "t": ("Что будем делать дальше", "What We Will Do Next"),
            "o": ("Решить проблемы и сравнить варианты действий.",
                  "Solve problems and compare options."),
            "v": [("solution", "решение"), ("alternative", "альтернатива"),
                  ("more sensible", "разумнее"), ("to wait", "ждать"),
                  ("to rent a car", "взять машину напрокат"), ("overnight", "ночной / на ночь"),
                  ("to compensate", "компенсировать")],
            "q": ("Which sentence compares two solutions correctly?",
                  "Renting a car is more sensible than waiting here all night.",
                  ["Renting a car is sensibler than waiting.", "Renting a car is most sensible than waiting."]),
            "tr": ("Мы возьмём машину напрокат — это выйдет дешевле, чем ночь в аэропорту.",
                   "We are going to rent a car — it will work out cheaper than a night at the airport.",
                   ["did", "rented", "yesterday"]),
            "fill": ("The overnight bus is ___ than the morning train.", "slower",
                     ["slowest", "more slow"], "Ночной автобус медленнее утреннего поезда."),
            "tap": ("The company is going to compensate us for the taxi.", ["was", "did"]),
            "sh": ("If the airline pays for the hotel, waiting until tomorrow will be the easiest solution.",
                   "Если авиакомпания оплатит отель, ожидание до завтра будет самым простым решением."),
            "st": ("Stranded at Midnight", [
                ("Tom", "The last bus has gone, and the first train is at six.", "Последний автобус ушёл, а первый поезд в шесть."),
                ("Anna", "So we either sleep here or take a taxi. Which is more sensible?",
                 "Значит, либо спим здесь, либо берём такси. Что разумнее?"),
                ("What does Tom calculate?", [
                    ("The taxi is expensive, but a hotel near the station costs even more.", True),
                    ("The taxi was cheaper yesterday tomorrow.", False),
                    ("The bus is taking us while sleeping.", False)])]),
            "d": ("overnight", "During the night, lasting the whole night",
                  ["Happening early in the morning", "Taking about half an hour"]),
            "lw": ("We are going to ___ a car for two days.", "We are going to rent a car for two days.",
                   "rent", ["rented", "renting"]),
            "mw": ("This solution is ___ than the first one.", "cheaper", "ch"),
            "ch": ([("Agent", "The next available flight is on Friday.")], "You",
                   "That is too late — if you rebook us via Munich, we will be home on Wednesday.",
                   ["You rebooked us yesterday tomorrow.", "Friday is flying us home."]),
        },
        {
            "t": ("Если проблема повторится", "If the Problem Repeats"),
            "o": ("Предложить профилактику проблем, используя should и первое условное.",
                  "Suggest preventing problems using should and the first conditional."),
            "v": [("to prepare", "подготовиться"), ("copy of documents", "копия документов"),
                  ("to take precautions", "принять меры предосторожности"), ("travel insurance", "страховка поездки"),
                  ("in advance", "заранее"), ("emergency number", "номер для чрезвычайных ситуаций"),
                  ("to save (on phone)", "сохранить (в телефоне)")],
            "q": ("Which sentence gives correct advice?",
                  "You should keep copies of your documents in the cloud.",
                  ["You should to keep them yesterday.", "You must keeping them last trip."]),
            "tr": ("Если ты сохранишь копии документов заранее, потеря паспорта будет менее страшной.",
                   "If you save copies of your documents in advance, losing your passport will be less frightening.",
                   ["did", "saved", "yesterday"]),
            "fill": ("If your phone ___ , you will still have paper copies.",
                     "dies", ["will die", "died"], "Если телефон разрядится, бумажные копии всё равно останутся."),
            "tap": ("You should write down the emergency number on paper.", ["mustn't", "went"]),
            "sh": ("If you arrive at the station forty minutes early, a suddenly changed platform will not catch you out.",
                   "Если прийти на вокзал на сорок минут раньше, внезапно изменённая платформа не застанет врасплох."),
            "st": ("Learning From Trouble", [
                ("Anna", "That was a stressful morning — we nearly missed the check-in.",
                 "Утро было стрессовым — мы чуть не опоздали на регистрацию."),
                ("Tom", "Next time we should take more precautions.", "В следующий раз стоит принять больше мер."),
                ("What does Anna suggest?", [
                    ("If we leave one hour earlier, traffic will not be a problem.", True),
                    ("If we will leave earlier, traffic was fine yesterday.", False),
                    ("The check-in is taking precautions against us.", False)])]),
            "d": ("precautions", "Things you do to stop problems before they happen",
                  ["Surprises that appear during a journey", "Tickets you buy at the last moment"]),
            "lw": ("If you ___ copies in advance, you will be calmer.", "If you save copies in advance, you will be calmer.",
                   "save", ["will save", "saved"]),
            "mw": ("You should prepare ___ advance.", "in", "in"),
            "ch": ([("Friend", "I always panic when plans break down.")], "You",
                   "Make a small checklist — if you follow it, even a cancelled train will not spoil the trip.",
                   ["I made it yesterday tomorrow.", "The panic is planning me."]),
        },
    ],
}
