#!/usr/bin/env python3
"""A2 regenerated content: EXAM PREPARATION (10 tracks x 3 lessons).

Grammar arc per topic: L1 past simple + present perfect,
L2 future forms + comparatives, L3 modals / first conditional.
"""

TRACKS = {
    "A2_EXAM_A2_EXAM_PRACTICE": [
        {
            "t": ("Разбор пробника", "Analysing the Mock Exam"),
            "o": ("Разобрать результаты пробного экзамена, используя past simple и present perfect.",
                  "Analyse mock exam results using past simple and present perfect."),
            "v": [("exam paper", "экзаменационный вариант"), ("to score", "набрать (баллы)"),
                  ("to review mistakes", "разобрать ошибки"), ("section", "раздел (экзамена)"),
                  ("to improve", "улучшить результат"), ("time management", "тайм-менеджмент"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have reviewed all my mistakes from the mock exam.",
                  ["I have reviewed them last week.", "I review my mistakes already so far."]),
            "tr": ("Я набрал 65 баллов в пробнике, но раздел на аудирование провалил.",
                   "I scored 65 points in the mock exam, but I failed the listening section.",
                   ["did", "score", "tomorrow"]),
            "fill": ("She spent forty minutes on the reading ___ last time.", "section",
                     ["sections", "sectional"], "В прошлый раз она потратила сорок минут на раздел чтения."),
            "tap": ("We have practised the writing task twice this week.", ["was", "did"]),
            "sh": ("The mock showed one clear problem: my time management — I have spent half the exam on the first paper.",
                   "Пробник показал одну явную проблему: тайм-менеджмент — я потратил половину экзамена на первый вариант."),
            "st": ("Getting the Results", [
                ("Voice 1", "The mock results are out. How did you do?", "Результаты пробника вышли. Как ты справился?"),
                ("Voice 2", "Better than expected — 72! But I have not seen the listening part yet.",
                 "Лучше ожидаемого — 72! Но раздел аудирования я ещё не видел."),
                ("What does Voice 1 ask?", [
                    ("Which section has caused the most problems?", True),
                    ("Which section caused them tomorrow yesterday?", False),
                    ("Is 72 listening to your problems?", False)])]),
            "d": ("mock exam", "A full practice exam before the real one",
                  ["A short quiz at the end of a lesson", "The final exam itself"]),
            "lw": ("I have ___ 80 out of 100 in the last mock.", "I have scored 80 out of 100 in the last mock.",
                   "scored", ["score", "scoring"]),
            "mw": ("Let's ___ your mistakes together.", "review", "re"),
            "ch": ([("Friend", "How was your mock?")], "You",
                   "Revealing — I have learned that I always lose points on prepositions.",
                   ["I learned it yesterday tomorrow.", "The mock is friending me."]),
        },
        {
            "t": ("Стратегия на настоящий экзамен", "Strategy for the Real Exam"),
            "o": ("Сравнить стратегии сдачи и спланировать подготовку.",
                  "Compare exam strategies and plan your preparation."),
            "v": [("to skip a question", "пропустить вопрос"), ("more efficient", "эффективнее"),
                  ("easy questions first", "лёгкие вопросы первыми"), ("to allocate", "распределить (время)"),
                  ("guess", "догадка / угадать"), ("answer sheet", "бланк ответов"),
                  ("checklist", "чек-лист")],
            "q": ("Which sentence compares two strategies correctly?",
                  "Doing easy questions first is more efficient than a strict order.",
                  ["Easy first is efficienсter than order.", "Easy questions are most efficient than order."]),
            "tr": ("На экзамене я собираюсь сначала отвечать на лёгкие вопросы.",
                   "In the exam I am going to answer the easy questions first.",
                   ["did", "answered", "yesterday"]),
            "fill": ("Leaving a hard question for later is ___ than guessing at once.", "smarter",
                     ["smartest", "more smart"], "Оставить сложный вопрос на потом умнее, чем сразу угадывать."),
            "tap": ("I am going to fill the answer sheet at the end.", ["was", "did"]),
            "sh": ("If you allocate fixed minutes to each section, you will never run out of time on the last page.",
                   "Если распределить фиксированные минуты на каждый раздел, времени на последней странице не закончится."),
            "st": ("Exam Tactics", [
                ("Voice 1", "What is your tactic for the multiple-choice part?", "Какая у тебя тактика для тестовой части?"),
                ("Voice 2", "Two passes: easy ones first, then the hard ones with the time left.",
                 "Два прохода: сначала лёгкие, потом сложные с оставшимся временем."),
                ("What does Voice 1 decide?", [
                    ("I am going to try exactly that in the next mock.", True),
                    ("I tried it yesterday tomorrow already.", False),
                    ("The tactic is multipassing my choices.", False)])]),
            "d": ("answer sheet", "The form where you write your final answers",
                  ["The question paper you read from", "A certificate you get after the exam"]),
            "lw": ("I am going to ___ ten minutes for checking.", "I am going to allocate ten minutes for checking.",
                   "allocate", ["allocated", "allocating"]),
            "mw": ("A planned guess is ___ than a panic guess.", "better", "be"),
            "ch": ([("Friend", "Should I answer every question?")], "You",
                   "No penalty means yes — if you mark every answer, you will gain a few free points.",
                   ["I answered them yesterday tomorrow.", "The questions are penaltying me."]),
        },
        {
            "t": ("Если завалишь раздел", "If You Fail a Section"),
            "o": ("Обсудить пересдачи и страховку, используя should и первое условное.",
                  "Discuss retakes and safety nets using should and the first conditional."),
            "v": [("to retake", "пересдать"), ("to pass", "сдать"),
                  ("required score", "проходной балл"), ("to book", "забронировать (дату)"),
                  ("in case", "на случай"), ("back-up date", "запасная дата"),
                  ("nervous", "нервный")],
            "q": ("Which sentence gives correct advice?",
                  "You should book a back-up date in case you need a retake.",
                  ["You should to book it yesterday.", "You must booking dates last exam."]),
            "tr": ("Если наберёшь проходной балл с первого раза, пересдача не понадобится.",
                   "If you reach the required score first time, you will not need a retake.",
                   ["did", "reached", "yesterday"]),
            "fill": ("If you feel too nervous, your score ___ lower.", "will be",
                     ["be", "is"], "Если слишком нервничать, балл будет ниже."),
            "tap": ("You should register for the earliest available date.", ["mustn't", "went"]),
            "sh": ("If you prepare a back-up plan for a retake, you will walk into the exam calmer — strange but true.",
                   "Если подготовить запасной план на пересдачу, войдёшь на экзамен спокойнее — странно, но факт."),
            "st": ("After a Bad Section", [
                ("Voice 1", "The listening was a disaster. I think I have failed the whole exam.",
                 "Аудирование было катастрофой. Кажется, я завалил весь экзамен."),
                ("Voice 2", "Wait for the results — sections are scored separately.",
                 "Дождись результатов — разделы оцениваются отдельно."),
                ("What does Voice 2 advise?", [
                    ("If you fail only one part, you can retake just that part.", True),
                    ("You retaked it yesterday tomorrow.", False),
                    ("The disaster is listening your exam.", False)])]),
            "d": ("to retake", "To take an exam again after failing",
                  ["To check your answers before submitting", "To leave the exam room early"]),
            "lw": ("If I ___ , I will book a new date in May.", "If I fail, I will book a new date in May.",
                   "fail", ["will fail", "failed"]),
            "mw": ("The ___ score is 60 points.", "required", "req"),
            "ch": ([("Friend", "What if I do not pass this time?")], "You",
                   "Then you retake in June — if you keep practising, the second attempt is usually easier.",
                   ["I passed it yesterday tomorrow.", "The exam is passing time."]),
        },
    ],

    "A2_EXAM_FUTURE_FORMS_AND_COMPARISONS": [
        {
            "t": ("Прошлое и настоящее в задачах", "Past and Present in Exam Tasks"),
            "o": ("Потренировать past simple и present perfect в экзаменационных заданиях.",
                  "Practise past simple and present perfect in exam tasks."),
            "v": [("tense", "время (глагола)"), ("signal word", "слово-маркер"),
                  ("already / yet", "уже / ещё"), ("since / for", "с / в течение"),
                  ("irregular verb", "неправильный глагол"), ("to complete the sentence", "завершить предложение"),
                  ("gap fill", "задание на пропуски")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "She has lived here since 2019.",
                  ["She has lived here in 2019.", "She lives here since already 2019."]),
            "tr": ("Я живу здесь с 2019 года и ещё не поменял работу.",
                   "I have lived here since 2019 and have not changed my job yet.",
                   ["did", "live", "tomorrow"]),
            "fill": ("We ___ to London three years ago.", "moved",
                     ["have moved", "are moving"], "Мы переехали в Лондон три года назад."),
            "tap": ("He has already finished the gap-fill task.", ["was", "did"]),
            "sh": ("Signal words are your friends: 'yesterday' means past simple, and 'since' points to the present perfect.",
                   "Слова-маркеры — твои друзья: «yesterday» означает past simple, а «since» указывает на present perfect."),
            "st": ("The Grammar Section", [
                ("Voice 1", "I never remember when to use 'since' and 'for'.", "Я никак не запомню, когда 'since', а когда 'for'."),
                ("Voice 2", "Point in time — since; period of time — for. Since Monday, for three days.",
                 "Точка во времени — since; период — for. Since Monday, for three days."),
                ("What does Voice 1 say?", [
                    ("Got it — 'for two years' but 'since 2020'.", True),
                    ("Got it — 'since two years' and 'for 2020'.", False),
                    ("The words are pointing my time.", False)])]),
            "d": ("irregular verb", "A verb with special past forms, like go-went",
                  ["A verb that ends in -ed in the past", "A verb used only in questions"]),
            "lw": ("They have ___ the project since March.", "They have worked on the project since March.",
                   "worked", ["work", "working"]),
            "mw": ("I have ___ sent the form.", "already", "al"),
            "ch": ([("Examiner", "Have you ever taken this exam before?")], "You",
                   "Yes, once last year — and I have practised a lot since then.",
                   ["I take it yesterday tomorrow.", "The exam is taking me once."]),
        },
        {
            "t": ("Будущее в заданиях", "The Future in Exam Tasks"),
            "o": ("Потренировать формы будущего и сравнительные степени.",
                  "Practise future forms and comparatives."),
            "v": [("will / going to", "will / going to"), ("arrangement", "договорённость"),
                  ("prediction", "предсказание"), ("comparative", "сравнительная степень"),
                  ("superlative", "превосходная степень"), ("than", "чем"),
                  ("the ...est", "самый ...")],
            "q": ("Which sentence uses going to for a plan?",
                  "We are going to visit the museum on Saturday.",
                  ["We will visited the museum yesterday.", "We visit museum going to Saturday."]),
            "tr": ("Этот вариант проще, а тот — самый сложный за весь год.",
                   "This option is easier, and that one is the most difficult of the whole year.",
                   ["did", "was", "yesterday"]),
            "fill": ("Look at those clouds — it ___ rain.", "is going to",
                     ["will be", "goes to"], "Посмотри на тучи — сейчас пойдёт дождь."),
            "tap": ("My exam is going to be in June.", ["was", "did"]),
            "sh": ("A plan takes going to; an arrangement takes the present continuous; a prediction takes will.",
                   "План требует going to; договорённость — present continuous; предсказание — will."),
            "st": ("Choosing the Future Form", [
                ("Voice 1", "This question has both 'will' and 'going to' as options...", "В этом вопросе и 'will', и 'going to' в вариантах..."),
                ("Voice 2", "Read the context: is it a plan decided before, or a decision right now?",
                 "Читай контекст: это заранее принятое решение или решение прямо сейчас?"),
                ("What does Voice 1 answer?", [
                    ("It says 'we decided last week' — so going to.", True),
                    ("It decided yesterday tomorrow — will.", False),
                    ("The question is going to the context.", False)])]),
            "d": ("superlative", "The form like 'the biggest' or 'the best'",
                  ["The form like 'bigger' or 'better'", "The form like 'as big as'"]),
            "lw": ("She is ___ to retake the exam in May.", "She is going to retake the exam in May.",
                   "going", ["went", "gone"]),
            "mw": ("This task is ___ than the last one.", "easier", "ea"),
            "ch": ([("Friend", "Will vs going to — one more time?")], "You",
                   "Evidence in the sentence: 'I promise' → will; 'we planned' → going to.",
                   ["You explained it yesterday tomorrow.", "The forms are willing me."]),
        },
        {
            "t": ("Если сомневаешься во времени", "If You Doubt the Tense"),
            "o": ("Разобрать типичные ошибки, используя should и первое условное.",
                  "Analyse typical mistakes using should and the first conditional."),
            "v": [("common mistake", "типичная ошибка"), ("to mark the signal", "отметить маркер"),
                  ("to translate literally", "переводить дословно"), ("reliable", "надёжный"),
                  ("to eliminate options", "отсеять варианты"), ("guessing", "угадывание"),
                  ("clue", "ключ / подсказка")],
            "q": ("Which sentence gives correct exam advice?",
                  "You should underline the time signal before choosing a tense.",
                  ["You should to underline it yesterday.", "You must underlining signals last exam."]),
            "tr": ("Если дословно переводить с русского, часто выбираешь неправильное время.",
                   "If you translate literally from Russian, you will often choose the wrong tense.",
                   ["did", "translated", "yesterday"]),
            "fill": ("If you eliminate two options, your ___ becomes much safer.",
                     "guess", ["will guess", "guessed"], "Если отсеять два варианта, догадка станет гораздо безопаснее."),
            "tap": ("You should check the time markers twice.", ["mustn't", "went"]),
            "sh": ("If a sentence contains 'ago', the present perfect is impossible — this clue alone solves half the questions.",
                   "Если в предложении есть 'ago', present perfect невозможен — одна эта подсказка решает половину вопросов."),
            "st": ("The Repeated Mistake", [
                ("Voice 1", "I always write 'I have seen him yesterday' — why is it wrong?", "Я всё время пишу 'I have seen him yesterday' — почему это неверно?"),
                ("Voice 2", "'Yesterday' is a finished time, so the present perfect cannot take it.", "'Yesterday' — завершённое время, present perfect его не принимает."),
                ("What does Voice 1 learn?", [
                    ("So with 'yesterday' I should use past simple — saw.", True),
                    ("So I should using it yesterday again.", False),
                    ("The mistake is seeing my yesterday.", False)])]),
            "d": ("to eliminate", "To remove wrong options one by one",
                  ["To choose the first option you like", "To translate the task into Russian first"]),
            "lw": ("If you see 'ago', ___ the perfect option.", "If you see 'ago', eliminate the perfect option.",
                   "eliminate", ["will eliminate", "eliminated"]),
            "mw": ("Never translate ___ from Russian.", "literally", "li"),
            "ch": ([("Friend", "Two options look identical to me.")], "You",
                   "Look for the signal word — if you mark it, the difference will appear.",
                   ["I marked it yesterday tomorrow.", "The options are doubling me."]),
        },
    ],

    "A2_EXAM_LISTENING_FOR_MAIN_IDEAS_AND_DETAILS": [
        {
            "t": ("Аудирование: что было в записи", "Listening: What Was in the Recording"),
            "o": ("Понимать аудиотексты, используя past simple и present perfect.",
                  "Understand audio texts using past simple and present perfect."),
            "v": [("recording", "запись"), ("to catch", "уловить (на слух)"),
                  ("the main idea", "главная мысль"), ("detail", "деталь"),
                  ("to note down", "записать (на ходу)"), ("twice", "дважды"),
                  ("noise", "шум")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have listened to the recording twice already.",
                  ["I have listened to it yesterday twice.", "I listen the recording already twice now."]),
            "tr": ("Я уловил главную мысль, но пропустил две детали.",
                   "I caught the main idea but missed two details.",
                   ["did", "catch", "tomorrow"]),
            "fill": ("The speaker mentioned the price only ___ .", "once",
                     ["ones", "one"], "Спикер упомянул цену только один раз."),
            "tap": ("She has noted down all the numbers from the talk.", ["was", "did"]),
            "sh": ("The recording has mentioned three deadlines, but only the second one is about the exam.",
                   "В записи упомянуты три срока, но только второй касается экзамена."),
            "st": ("After the Listening", [
                ("Voice 1", "What was the talk mainly about — transport or hotels?", "О чём в основном был доклад — о транспорте или отелях?"),
                ("Voice 2", "Hotels — the transport part was just one detail at the start.",
                 "Об отелях — транспорт был лишь деталью в начале."),
                ("What does Voice 1 realise?", [
                    ("Ah, so answer B was the main idea, not A.", True),
                    ("So answer A was the detail of B tomorrow.", False),
                    ("Is the talk listening to answers?", False)])]),
            "d": ("to catch", "To hear and understand something difficult",
                  ["To hold an object with your hands", "To be late for a recording session"]),
            "lw": ("I have ___ every date in the talk.", "I have noted down every date in the talk.",
                   "noted down", ["note down", "noting down"]),
            "mw": ("Listen for the numbers — they are often the ___ .", "details", "de"),
            "ch": ([("Friend", "Did you catch the address at the end?")], "You",
                   "No — the noise covered it. I have put a guess and marked the question for review.",
                   ["I caught it yesterday tomorrow.", "The address is ending me."]),
        },
        {
            "t": ("Аудирование на следующей неделе", "Listening Next Week"),
            "o": ("Планировать тренировку аудирования и сравнивать материалы.",
                  "Plan listening practice and compare materials."),
            "v": [("twice as fast", "вдвое быстрее"), ("more natural", "естественнее"),
                  ("podcast", "подкаст"), ("transcript", "расшифровка"),
                  ("to slow down the audio", "замедлить аудио"), ("accent", "акцент"),
                  ("background noise", "фоновый шум")],
            "q": ("Which sentence compares two listening sources correctly?",
                  "Podcasts are more natural than exam recordings.",
                  ["Podcasts are naturaler than exams.", "Podcasts are most natural than recordings."]),
            "tr": ("Я собираюсь слушать по одному подкасту в день с расшифровкой.",
                   "I am going to listen to one podcast a day with the transcript.",
                   ["did", "listened", "yesterday"]),
            "fill": ("Audio with background noise is ___ than studio audio.", "harder",
                     ["hardest", "more hard"], "Аудио с фоновым шумом сложнее студийного."),
            "tap": ("We are going to practise with two accents this month.", ["was", "did"]),
            "sh": ("If you listen at normal speed first and then check the transcript, your ear will improve twice as fast.",
                   "Если слушать сначала на нормальной скорости, а потом проверять по расшифровке, слух улучшится вдвое быстрее."),
            "st": ("Choosing Practice Material", [
                ("Voice 1", "Exam recordings are so slow and clean — is that bad?", "Экзаменационные записи такие медленные и чистые — это плохо?"),
                ("Voice 2", "For the exam, no. But real speech is faster and noisier.",
                 "Для экзамена нет. Но реальная речь быстрее и шумнее."),
                ("What does Voice 1 plan?", [
                    ("Then I am going to add one noisy podcast a day.", True),
                    ("Then I added it yesterday tomorrow.", False),
                    ("The exam is podcasting my speech.", False)])]),
            "d": ("transcript", "The written text of an audio recording",
                  ["A translation of the task into Russian", "A list of new words with translations"]),
            "lw": ("I am going to ___ the audio first.", "I am going to play the audio first.",
                   "play", ["played", "playing"]),
            "mw": ("Podcasts with transcripts are ___ for learners.", "better", "be"),
            "ch": ([("Friend", "British or American audio for practice?")], "You",
                   "Both — if you know two accents, any exam voice will sound familiar.",
                   ["I practised it yesterday tomorrow.", "The accents are Britishing me."]),
        },
        {
            "t": ("Если не успел за записью", "If You Cannot Keep Up with the Recording"),
            "o": ("Разобрать стратегии аудирования, используя should и первое условное.",
                  "Analyse listening strategies using should and the first conditional."),
            "v": [("to fall behind", "отставать"), ("to panic", "паниковать"),
                  ("keyword", "ключевое слово"), ("to skip", "пропустить"),
                  ("for now", "пока (что)"), ("to move on", "двигаться дальше"),
                  ("lost", "потерявшийся (потерявший нить)")],
            "q": ("Which sentence gives correct listening advice?",
                  "You should move to the next question instead of panicking.",
                  ["You should to move on yesterday.", "You must moving on last listening."]),
            "tr": ("Если застрянешь на одном вопросе, потеряешь ещё два следующих.",
                   "If you get stuck on one question, you will lose the next two as well.",
                   ["did", "got stuck", "yesterday"]),
            "fill": ("If you miss a keyword, ___ on to the next task.",
                     "move", ["will move", "moved"], "Если пропустил ключевое слово, переходи к следующему заданию."),
            "tap": ("You should read the questions before the audio starts.", ["mustn't", "went"]),
            "sh": ("If you read the questions in advance, you will know which keywords to wait for.",
                   "Если прочитать вопросы заранее, будешь знать, каких ключевых слов ждать."),
            "st": ("The Lost Minute", [
                ("Voice 1", "I lost the thread in the middle of part two and missed everything after it.", "Я потерял нить в середине второй части и пропустил всё после."),
                ("Voice 2", "Classic. What do the tips say about that moment?", "Классика. Что говорят советы про такой момент?"),
                ("What is the rule?", [
                    ("Let it go and catch the next question — the recording waits for nobody.", True),
                    ("I let it go yesterday tomorrow.", False),
                    ("The thread is recording my questions.", False)])]),
            "d": ("keyword", "The important word that carries the answer",
                  ["Any word you hear clearly", "The first word of every question"]),
            "lw": ("If you ___ a question, skip it.", "If you miss a question, skip it.",
                   "miss", ["will miss", "missed"]),
            "mw": ("Do not ___ — breathe and refocus.", "panic", "pa"),
            "ch": ([("Friend", "The speakers talk so fast!")], "You",
                   "Hunt keywords, not words — if you catch three key ones, the answer will come.",
                   ["I caught them yesterday tomorrow.", "The speakers are wording me."]),
        },
    ],

    "A2_EXAM_PRESENT_AND_PAST_TENSES": [
        {
            "t": ("Времена в контексте", "Tenses in Context"),
            "o": ("Тренировать времена в экзаменационных текстах, используя past simple и present perfect.",
                  "Practise tenses in exam texts using past simple and present perfect."),
            "v": [("past simple", "прошедшее простое"), ("present perfect", "настоящее совершённое"),
                  ("while / when", "пока / когда"), ("ago", "тому назад"),
                  ("state verb", "глагол состояния"), ("continuous", "длительное время"),
                  ("context", "контекст")],
            "q": ("Which sentence uses the past continuous correctly?",
                  "I was reading when she called.",
                  ["I read when she was calling yesterday.", "I was read when she has called."]),
            "tr": ("Я писал эссе, когда отключился свет.",
                   "I was writing the essay when the power went off.",
                   ["did", "was", "yesterday"]),
            "fill": ("They have known each other ___ ten years.", "for",
                     ["since", "ago"], "Они знакомы десять лет."),
            "tap": ("We were waiting for the results the whole evening.", ["was", "did"]),
            "sh": ("The context decides: 'while' pairs two continuous actions, and 'when' interrupts them with a short one.",
                   "Контекст решает: 'while' объединяет два длительных действия, а 'when' прерывает их коротким."),
            "st": ("The Story Task", [
                ("Voice 1", "The text begins 'Yesterday I ___ (walk) home when...'", "Текст начинается 'Yesterday I ___ (walk) home when...'"),
                ("Voice 2", "Two actions — a long one and a short interrupting one.", "Два действия — длительное и короткое, прерывающее."),
                ("What is the answer?", [
                    ("was walking — the long background action.", True),
                    ("walked — yesterday asks for past simple only.", False),
                    ("have walked — it is a life experience.", False)])]),
            "d": ("state verb", "A verb like know or love, rarely used in continuous",
                  ["A verb of movement like run or jump", "A verb used only in the past tense"]),
            "lw": ("She ___ dinner when I arrived.", "She was cooking dinner when I arrived.",
                   "was cooking", ["cooked", "has cooked"]),
            "mw": ("I met him three years ___ .", "ago", "ag"),
            "ch": ([("Friend", "How do you spot the continuous gap?")], "You",
                   "Look for 'while' or a longer action around it — if you see them, the continuous will fit.",
                   ["I saw it yesterday tomorrow.", "The gap is continuing me."]),
        },
        {
            "t": ("Рассказ о прошлом в заданиях", "Telling the Past in Tasks"),
            "o": ("Сравнить употребление времён и спланировать практику.",
                  "Compare tense usage and plan practice."),
            "v": [("storytelling", "рассказывание историй"), ("more natural", "естественнее"),
                  ("sequence of events", "последовательность событий"), ("background", "фон"),
                  ("to link events", "связать события"), ("vivid", "яркий"),
                  ("then / after that", "затем / после этого")],
            "q": ("Which sentence compares two ways of telling a story correctly?",
                  "Continuous for background makes a story more natural.",
                  ["Continuous is naturaler for stories.", "The continuous is most natural than simple."]),
            "tr": ("На этой неделе я собираюсь написать три истории по картинкам.",
                   "This week I am going to write three picture-based stories.",
                   ["did", "wrote", "yesterday"]),
            "fill": ("First he arrived, ___ he opened the letter, and after that everything changed.",
                     "then", ["than", "when"], "Сначала он пришёл, затем открыл письмо, и после этого всё изменилось."),
            "tap": ("The past simple moves the events; the continuous paints the background.", ["was", "did"]),
            "sh": ("If you set the background in the continuous first, the short past actions will feel more vivid.",
                   "Если сначала задать фон длительным временем, короткие действия в past simple будут звучать ярче."),
            "st": ("The Picture Story", [
                ("Voice 1", "For this picture, which tense for 'the sun shine'?", "Для этой картинки какое время для 'sun shine'?"),
                ("Voice 2", "Continuous — it is the background, not an event.", "Длительное — это фон, а не событие."),
                ("What does Voice 1 write?", [
                    ("The sun was shining while they were carrying the boat.", True),
                    ("The sun shone while they carried the boat out.", False),
                    ("The sun has shone since they carry boats.", False)])]),
            "d": ("background", "The longer situation around the main events",
                  ["The most important event of the story", "The final sentence of a story"]),
            "lw": ("I am going to ___ the events with 'after that'.", "I am going to link the events with 'after that'.",
                   "link", ["linked", "linking"]),
            "mw": ("A story with background feels ___ .", "more natural", "mo"),
            "ch": ([("Friend", "All past simple sounds flat in my story.")], "You",
                   "Add one continuous sentence at the start — if the background is there, the events will pop.",
                   ["I added it yesterday tomorrow.", "The story is simplifying me."]),
        },
        {
            "t": ("Если время выбрано неверно", "If the Tense Is Chosen Wrong"),
            "o": ("Разобрать ошибки во временах, используя should и первое условное.",
                  "Analyse tense mistakes using should and the first conditional."),
            "v": [("error log", "журнал ошибок"), ("to repeat a mistake", "повторить ошибку"),
                  ("pattern", "паттерн"), ("to drill", "дриллить (прорабатывать)"),
                  ("carefully", "внимательно"), ("correction", "исправление"),
                  ("rule", "правило")],
            "q": ("Which sentence gives correct advice about mistakes?",
                  "You should keep an error log and review it weekly.",
                  ["You should to keep it yesterday.", "You must keeping logs last month."]),
            "tr": ("Если ты ведёшь журнал ошибок, паттерны видны за неделю.",
                   "If you keep an error log, you will see the patterns within a week.",
                   ["did", "kept", "yesterday"]),
            "fill": ("If you drill one rule a day, it ___ yours.", "becomes",
                     ["will become", "became"], "Если прорабатывать одно правило в день, оно станет твоим."),
            "tap": ("You should read the correction aloud.", ["mustn't", "went"]),
            "sh": ("If you write the correct version three times, your hand will remember it even under exam stress.",
                   "Если написать правильный вариант три раза, рука запомнит его даже в экзаменационном стрессе."),
            "st": ("The Same Mistake", [
                ("Voice 1", "I have made the same tense mistake in every mock this month.", "Я допускал одну и ту же ошибку во времени в каждом пробнике за месяц."),
                ("Voice 2", "Every single one? That is a pattern, not bad luck.", "В каждом? Это паттерн, а не невезение."),
                ("What does Voice 2 advise?", [
                    ("You should drill that one rule until it is automatic.", True),
                    ("You must drilled it yesterday already.", False),
                    ("The mistake is mocking your month.", False)])]),
            "d": ("error log", "A notebook where you collect your own mistakes",
                  ["A list of rules from the textbook", "A diary about your exam feelings"]),
            "lw": ("If you ___ the mistake again, log it.", "If you repeat the mistake again, log it.",
                   "repeat", ["will repeat", "repeated"]),
            "mw": ("Read your ___ log before the exam.", "error", "er"),
            "ch": ([("Friend", "I always confuse these two tenses.")], "You",
                   "Drill five sentences daily — if you do it for a week, the choice will become automatic.",
                   ["I drilled them yesterday tomorrow.", "The tenses are confusing my week."]),
        },
    ],

    "A2_EXAM_QUESTION_FORMS_AND_SHORT_ANSWERS": [
        {
            "t": ("Вопросы и короткие ответы", "Questions and Short Answers"),
            "o": ("Тренировать формы вопросов, используя past simple и present perfect.",
                  "Practise question forms using past simple and present perfect."),
            "v": [("auxiliary verb", "вспомогательный глагол"), ("subject", "подлежащее"),
                  ("word order", "порядок слов"), ("short answer", "короткий ответ"),
                  ("tag question", "разделительный вопрос"), ("Wh-question", "специальный вопрос"),
                  ("to invert", "инвертировать")],
            "q": ("Which question is built correctly?",
                  "Where did you buy this dictionary?",
                  ["Where you did bought this dictionary?", "Where did you bought this dictionary?"]),
            "tr": ("Ты когда-нибудь сдавал этот экзамен раньше?",
                   "Have you ever taken this exam before?",
                   ["did", "have", "tomorrow"]),
            "fill": ("___ she called you yesterday?", "Did",
                     ["Has", "Was"], "Она звонила тебе вчера?"),
            "tap": ("You have met him before, haven't you?", ["was", "did"]),
            "sh": ("In questions the auxiliary jumps before the subject — do, does, did, have or has.",
                   "В вопросах вспомогательный глагол встаёт перед подлежащим — do, does, did, have или has."),
            "st": ("The Interview Task", [
                ("Voice 1", "The task says 'Ask your partner about last weekend'.", "В задании: 'Расспроси партнёра о прошлых выходных'."),
                ("Voice 2", "So past simple questions — did you go, did you see...", "Значит, вопросы в past simple — did you go, did you see..."),
                ("What does Voice 1 form?", [
                    ("Did you do anything interesting on Saturday?", True),
                    ("Have you did anything interesting tomorrow?", False),
                    ("Did you anything interesting on Saturday?", False)])]),
            "d": ("auxiliary verb", "A helping verb like do, does or have",
                  ["The main action verb of a sentence", "A word that shows politeness in requests"]),
            "lw": ("___ you finished the task yet?", "Have you finished the task yet?",
                   "Have", ["Did", "Are"]),
            "mw": ("Short answer: Yes, I ___ .", "have", "ha"),
            "ch": ([("Examiner", "Do you live near the exam centre?")], "You",
                   "Yes, I do — ten minutes by metro, and I have walked it before.",
                   ["Yes, I live it yesterday tomorrow.", "The centre is examinating me."]),
        },
        {
            "t": ("Вопросы к будущим задачам", "Questions for Future Tasks"),
            "o": ("Сравнить типы вопросов и потренировать порядок слов.",
                  "Compare question types and practise word order."),
            "v": [("subject question", "вопрос к подлежащему"), ("more polite", "вежливее (более)"),
                  ("indirect question", "косвенный вопрос"), ("Could you tell me...?", "Не могли бы вы сказать...?"),
                  ("rising intonation", "восходящая интонация"), ("to stress", "выделить ударением"),
                  ("clarify", "уточнить")],
            "q": ("Which question is more polite?",
                  "Could you tell me where the room is?",
                  ["Where is the room? Tell fast.", "You tell me where the room is being?"]),
            "tr": ("Не могли бы вы сказать, когда начинаются результаты?",
                   "Could you tell me when the results come out?",
                   ["did", "can", "yesterday"]),
            "fill": ("Who ___ you at the exam centre? — My teacher did.", "met",
                     ["did meet", "meets"], "Кто встретил тебя в экзаменационном центре? — Мой преподаватель."),
            "tap": ("Indirect questions keep the statement word order.", ["was", "did"]),
            "sh": ("In indirect questions there is no inversion — 'Could you tell me where the room is', not 'where is the room'.",
                   "В косвенных вопросах нет инверсии — 'Could you tell me where the room is', а не 'where is the room'."),
            "st": ("Asking the Examiner", [
                ("Voice 1", "How do I ask about the start time politely?", "Как вежливо спросить о времени начала?"),
                ("Voice 2", "Use an indirect question — 'Could you tell me what time we start?'",
                 "Используй косвенный вопрос — 'Could you tell me what time we start?'"),
                ("What does Voice 1 notice?", [
                    ("Interesting — 'we start', not 'do we start'.", True),
                    ("Interesting — 'what time do we start' inside it.", False),
                    ("The time is questioning my politeness.", False)])]),
            "d": ("indirect question", "A question inside a polite phrase",
                  ["A question with a question tag at the end", "A question answered only with yes or no"]),
            "lw": ("Could you ___ me where the exit is?", "Could you tell me where the exit is?",
                   "tell", ["told", "telling"]),
            "mw": ("Indirect questions sound ___ .", "more polite", "mo"),
            "ch": ([("Friend", "'Who did call you?' — is this right?")], "You",
                   "No — a who-question needs no did: 'Who called you?'",
                   ["It was right yesterday tomorrow.", "The who is doing my calls."]),
        },
        {
            "t": ("Если вопрос составлен неверно", "If the Question Is Built Wrong"),
            "o": ("Разобрать ошибки в вопросах, используя should и первое условное.",
                  "Analyse question mistakes using should and the first conditional."),
            "v": [("inversion", "инверсия"), ("to double the verb", "удвоить глагол"),
                  ("typical error", "типичная ошибка"), ("to self-check", "проверить себя"),
                  ("pattern", "шаблон"), ("slowly", "медленно"),
                  ("word by word", "слово за словом")],
            "q": ("Which sentence gives correct advice?",
                  "You should check the auxiliary before writing the question.",
                  ["You should to check it yesterday.", "You must checking auxiliaries last test."]),
            "tr": ("Если забудешь инверсию, вопрос станет утверждением.",
                   "If you forget the inversion, the question will become a statement.",
                   ["did", "forgot", "yesterday"]),
            "fill": ("If you write 'did', the main verb stays in the ___ form.",
                     "base", ["will base", "based"], "Если написал 'did', основной глагол остаётся в начальной форме."),
            "tap": ("You should read your question word by word.", ["mustn't", "went"]),
            "sh": ("If you translate the question from Russian word by word, the word order will break — build it from the pattern instead.",
                   "Если переводить вопрос с русского слово за словом, порядок слов сломается — строй его по шаблону."),
            "st": ("The Doubled Verb", [
                ("Voice 1", "I wrote 'Where did you went?' again...", "Я снова написал 'Where did you went?'..."),
                ("Voice 2", "Did — the classic doubled past. What does the rule say?", "Did — классическое удвоение прошедшего. Что говорит правило?"),
                ("What is the correction?", [
                    ("After 'did', use 'go', not 'went'.", True),
                    ("After 'did', use 'went' twice.", False),
                    ("The question is going where I did.", False)])]),
            "d": ("inversion", "Swapping the subject and the auxiliary in questions",
                  ["Adding a tag like 'isn't it' to any sentence", "Rising your voice at the end"]),
            "lw": ("If you see 'did', ___ the second past verb.", "If you see 'did', remove the second past verb.",
                   "remove", ["will remove", "removed"]),
            "mw": ("Check the auxiliary ___ writing.", "before", "be"),
            "ch": ([("Friend", "My questions lose points every time.")], "You",
                   "Self-check with the pattern: auxiliary + subject + verb — if you run it slowly, errors will show.",
                   ["I checked them yesterday tomorrow.", "The questions are losing me."]),
        },
    ],

    "A2_EXAM_READING_FOR_MAIN_IDEAS": [
        {
            "t": ("Главное в тексте", "The Gist of the Text"),
            "o": ("Находить главную мысль, используя past simple и present perfect.",
                  "Find main ideas using past simple and present perfect."),
            "v": [("gist", "суть"), ("to skim", "просмотреть бегло"),
                  ("heading", "заголовок"), ("first paragraph", "первый абзац"),
                  ("to summarise", "резюмировать"), ("distractor", "отвлекающий вариант"),
                  ("to match headings", "сопоставить заголовки")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The author has written three books on the topic so far.",
                  ["The author has written three books last year.", "The author writes three books already so far."]),
            "tr": ("В тексте говорилось, что город отремонтировал набережную.",
                   "The text said that the city had renovated the embankment.",
                   ["did", "said", "tomorrow"]),
            "fill": ("The ___ paragraph usually contains the main idea.", "first",
                     ["one", "firstly"], "Первый абзац обычно содержит главную мысль."),
            "tap": ("I have matched five of the seven headings already.", ["was", "did"]),
            "sh": ("A distractor repeats the words of the text, but the correct heading summarises the whole paragraph.",
                   "Отвлекающий вариант повторяет слова текста, а верный заголовок резюмирует весь абзац."),
            "st": ("The Matching Task", [
                ("Voice 1", "Two headings fit paragraph three equally well...", "К абзацу три одинаково подходят два заголовка..."),
                ("Voice 2", "One of them just repeats a word. Which one summarises the whole idea?", "Один просто повторяет слово. Какой резюмирует всю мысль?"),
                ("What is the strategy?", [
                    ("Choose the one that covers everything, not just one sentence.", True),
                    ("Choose the one with more words from the text.", False),
                    ("The paragraph is heading two fit.", False)])]),
            "d": ("distractor", "A wrong option that looks almost right",
                  ["The correct answer that is easy to miss", "A question you have skipped"]),
            "lw": ("I have ___ the text in three minutes.", "I have skimmed the text in three minutes.",
                   "skimmed", ["skim", "skimming"]),
            "mw": ("Find the ___ of each paragraph.", "gist", "gi"),
            "ch": ([("Friend", "I chose the option with the same words as the text.")], "You",
                   "That is the trap — if words match exactly, it is usually a distractor.",
                   ["I trapped it yesterday tomorrow.", "The words are distractoring me."]),
        },
        {
            "t": ("Читаем быстрее к экзамену", "Reading Faster for the Exam"),
            "o": ("Сравнить техники чтения и спланировать практику.",
                  "Compare reading techniques and plan practice."),
            "v": [("reading speed", "скорость чтения"), ("faster", "быстрее"),
                  ("to scan for", "искать (сканированием)"), ("key information", "ключевая информация"),
                  ("to time yourself", "засечь время"), ("gradually", "постепенно"),
                  ("more texts", "больше текстов")],
            "q": ("Which sentence compares two reading speeds correctly?",
                  "My reading is faster than it was in September.",
                  ["My reading is more fast than September.", "My reading is fastest than it was."]),
            "tr": ("Я собираюсь засекать время на каждом тексте этой недели.",
                   "I am going to time myself on every text this week.",
                   ["did", "timed", "yesterday"]),
            "fill": ("Scanning for names and numbers is ___ than reading everything.", "quicker",
                     ["quickest", "more quick"], "Искать имена и цифры быстрее, чем читать всё."),
            "tap": ("We are going to do more texts per week.", ["was", "did"]),
            "sh": ("If you time yourself on every practice text, your reading speed will grow gradually but noticeably.",
                   "Если засекать время на каждом тренировочном тексте, скорость чтения будет расти постепенно, но заметно."),
            "st": ("The Timed Practice", [
                ("Voice 1", "Nine hundred words in the exam, and only twenty minutes!", "Девятьсот слов на экзамене, а времени всего двадцать минут!"),
                ("Voice 2", "Do not read everything — scan for the questions' key information.", "Не читай всё — ищи ключевую информацию по вопросам."),
                ("What does Voice 1 plan?", [
                    ("I am going to practise timed scanning every evening.", True),
                    ("I practised it yesterday tomorrow already.", False),
                    ("The words are scanning my minutes.", False)])]),
            "d": ("to time yourself", "To measure how long you take to do something",
                  ["To plan your day with a timetable", "To arrive at the exam centre early"]),
            "lw": ("I am going to ___ myself with a timer.", "I am going to time myself with a timer.",
                   "time", ["timed", "timing"]),
            "mw": ("Practice makes reading ___ .", "faster", "fa"),
            "ch": ([("Friend", "I never finish the reading section.")], "You",
                   "Start with the questions, not the text — if you know what to look for, you will skip half the words.",
                   ["I finished it yesterday tomorrow.", "The section is reading me."]),
        },
        {
            "t": ("Если текст сложный", "If the Text Is Difficult"),
            "o": ("Разобрать стратегии сложных текстов, используя should и первое условное.",
                  "Analyse difficult-text strategies using should and the first conditional."),
            "v": [("unknown word", "незнакомое слово"), ("to skip it", "пропустить его"),
                  ("context clue", "контекстуальная подсказка"), ("to slow down", "замедлиться"),
                  ("key sentence", "ключевое предложение"), ("topic sentence", "тематическое предложение"),
                  ("calm", "спокойный")],
            "q": ("Which sentence gives correct reading advice?",
                  "You should skip unknown words that are not in the questions.",
                  ["You should to skip them yesterday.", "You must skipping words last text."]),
            "tr": ("Если незнакомое слово не в вопросах, его можно пропустить без потерь.",
                   "If an unknown word is not in the questions, you can skip it without loss.",
                   ["did", "was", "yesterday"]),
            "fill": ("If the first sentence is hard, read the ___ one for support.",
                     "second", ["will second", "seconded"], "Если первое предложение сложное, прочитай второе для опоры."),
            "tap": ("You should stay calm with hard texts.", ["mustn't", "went"]),
            "sh": ("If the topic sentence is unclear, the examples after it will usually explain the idea in simpler words.",
                   "Если тематическое предложение неясно, примеры после него обычно объясняют мысль более простыми словами."),
            "st": ("The Scary Article", [
                ("Voice 1", "The first text is full of words I have never seen.", "Первый текст полон слов, которых я никогда не видел."),
                ("Voice 2", "Are those words in the questions?", "Эти слова есть в вопросах?"),
                ("What does Voice 1 realise?", [
                    ("No... so I can skip them and hunt for the topic sentences instead.", True),
                    ("No, so I must learning them tonight.", False),
                    ("The questions are full of my words.", False)])]),
            "d": ("context clue", "Information around a word that helps guess its meaning",
                  ["A dictionary entry for the word", "The translation printed under the text"]),
            "lw": ("If a word is not in the questions, ___ it.", "If a word is not in the questions, skip it.",
                   "skip", ["will skip", "skipped"]),
            "mw": ("Find the ___ sentence of the paragraph.", "topic", "to"),
            "ch": ([("Friend", "This text looks impossible.")], "You",
                   "Stay calm — if you find the topic sentences, half the answers will come from them alone.",
                   ["I calmed yesterday tomorrow.", "The text is impossibling me."]),
        },
    ],

    "A2_EXAM_READING_FOR_SPECIFIC_INFORMATION": [
        {
            "t": ("Поиск деталей в тексте", "Hunting for Details"),
            "o": ("Находить конкретную информацию, используя past simple и present perfect.",
                  "Find specific information using past simple and present perfect."),
            "v": [("specific detail", "конкретная деталь"), ("date / figure", "дата / цифра"),
                  ("to locate", "локализовать"), ("proper noun", "имя собственное"),
                  ("to underline", "подчеркнуть"), ("true / false / not stated", "верно / неверно / не указано"),
                  ("line", "строка")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The writer has mentioned the price only once.",
                  ["The writer has mentioned it yesterday once.", "The writer mention the price already once."]),
            "tr": ("Автор упомянул дедлайн в третьей строке.",
                   "The writer mentioned the deadline in the third line.",
                   ["did", "mention", "tomorrow"]),
            "fill": ("Names of people are ___ nouns — they are easy to find.", "proper",
                     ["properly", "propers"], "Имена людей — имена собственные, их легко найти."),
            "tap": ("I have underlined all the figures in the text.", ["was", "did"]),
            "sh": ("For true-or-false tasks, the answer is 'not stated' when the text simply does not mention the fact.",
                   "В заданиях верно/неверно ответ «не указано», если текст просто не упоминает факт."),
            "st": ("The True/False Task", [
                ("Voice 1", "Statement five says the museum is free. Where is that?", "В утверждении пять сказано, что музей бесплатный. Где это?"),
                ("Voice 2", "I have scanned the text — free entry is mentioned, but for students only.",
                 "Я просмотрел текст — бесплатный вход упомянут, но только для студентов."),
                ("What is the verdict?", [
                    ("Then the statement is false in general.", True),
                    ("Then it is true for everyone.", False),
                    ("Then the museum is stating the students.", False)])]),
            "d": ("proper noun", "A name of a person, place or organisation",
                  ["An action word in the past tense", "A number written in figures"]),
            "lw": ("I have ___ the key dates in blue.", "I have underlined the key dates in blue.",
                   "underlined", ["underline", "underlining"]),
            "mw": ("The price is in ___ four.", "line", "li"),
            "ch": ([("Friend", "'Not stated' or 'false' — I never know.")], "You",
                   "Ask: does the text say the opposite? If not, and it is silent — if the text is silent, it is not stated.",
                   ["I knew it yesterday tomorrow.", "The statements are falsing me."]),
        },
        {
            "t": ("Быстрый поиск к следующей части", "Fast Search for the Next Part"),
            "o": ("Сравнивать стратегии поиска и планировать тренировку.",
                  "Compare search strategies and plan practice."),
            "v": [("keyword from the question", "ключевое слово из вопроса"), ("more focused", "сфокусированнее"),
                  ("synonym", "синоним"), ("to paraphrase", "перефразировать"),
                  ("to scan the lines", "просканировать строки"), ("question order", "порядок вопросов"),
                  ("usually", "обычно")],
            "q": ("Which sentence compares two search ways correctly?",
                  "Reading with a question in mind is more focused than reading first.",
                  ["Reading with questions is focusser than first.", "Questions are most focused than reading."]),
            "tr": ("Я собираюсь искать синонимы, а не точные слова.",
                   "I am going to look for synonyms rather than exact words.",
                   ["did", "looked", "yesterday"]),
            "fill": ("The questions ___ follow the order of the text.", "usually",
                     ["usual", "usuallys"], "Вопросы обычно следуют порядку текста."),
            "tap": ("The exam paraphrases the text in the questions.", ["was", "did"]),
            "sh": ("If you take a keyword from the question and hunt its synonyms, your eyes will land on the answer line immediately.",
                   "Если взять ключевое слово из вопроса и искать его синонимы, взгляд сразу попадёт на строку с ответом."),
            "st": ("The Paraphrased Answer", [
                ("Voice 1", "The question says 'affordable', but this word is not in the text at all!", "В вопросе 'affordable', но этого слова в тексте вообще нет!"),
                ("Voice 2", "The text paraphrases it — look for 'cheap' or 'low prices'.", "Текст перефразирует — ищи 'cheap' или 'low prices'."),
                ("What does Voice 1 find?", [
                    ("Yes! Line six says 'lower prices than anywhere else'.", True),
                    ("No, line six says 'affordable' twice.", False),
                    ("The question is affording the text.", False)])]),
            "d": ("synonym", "A word with a similar meaning to another",
                  ["A word spelled the same but different", "The opposite word in meaning"]),
            "lw": ("I am going to ___ every keyword before scanning.", "I am going to underline every keyword before scanning.",
                   "underline", ["underlined", "underlining"]),
            "mw": ("Question-first reading is ___ .", "more focused", "mo"),
            "ch": ([("Friend", "How do you find answers so fast?")], "You",
                   "Keywords and their synonyms — if you hunt both, the answer line will appear in seconds.",
                   ["I hunted it yesterday tomorrow.", "The answers are keying me."]),
        },
        {
            "t": ("Если детали путаются", "If the Details Get Mixed Up"),
            "o": ("Разобрать ошибки поиска, используя should и первое условное.",
                  "Analyse search mistakes using should and the first conditional."),
            "v": [("to mix up", "перепутать"), ("similar option", "похожий вариант"),
                  ("careless mistake", "невнимательная ошибка"), ("to verify", "проверить"),
                  ("evidence line", "строка-доказательство"), ("to mark", "отметить"),
                  ("rush", "спешка")],
            "q": ("Which sentence gives correct advice?",
                  "You should mark the line that proves your answer.",
                  ["You should to mark it yesterday.", "You must marking lines last task."]),
            "tr": ("Если перепутаешь похожие варианты, потеряешь верные баллы.",
                   "If you mix up similar options, you will lose easy points.",
                   ["did", "mixed", "yesterday"]),
            "fill": ("If you choose an option, ___ it in the text.",
                     "verify", ["will verify", "verified"], "Если выбрал вариант, проверь его по тексту."),
            "tap": ("Rush is the main enemy in part two.", ["mustn't", "went"]),
            "sh": ("If you write the evidence line number next to each answer, checking will take one minute at the end.",
                   "Если записывать номер строки-доказательства у каждого ответа, проверка займёт одну минуту в конце."),
            "st": ("The Careless Point", [
                ("Voice 1", "I have lost two points because the options were almost identical.", "Я потерял два балла, потому что варианты были почти одинаковыми."),
                ("Voice 2", "Almost — so one word differs. Did you compare them word by word?", "Почти — значит, различается одно слово. Ты сравнил их слово за словом?"),
                ("What is the lesson?", [
                    ("No — next time I will find the word that differs.", True),
                    ("No, I will compared them yesterday.", False),
                    ("The options are losing my points themselves.", False)])]),
            "d": ("careless mistake", "An error made by rushing, not by not knowing",
                  ["A mistake caused by an unknown grammar rule", "A question you left unanswered"]),
            "lw": ("If two options look the same, ___ them word by word.", "If two options look the same, compare them word by word.",
                   "compare", ["will compare", "compared"]),
            "mw": ("Do not ___ — reread the line.", "rush", "ru"),
            "ch": ([("Friend", "I keep confusing dates in the text.")], "You",
                   "Circle them — if every date has a mark, you will stop mixing them up.",
                   ["I circled them yesterday tomorrow.", "The dates are confusing my circles."]),
        },
    ],

    "A2_EXAM_SPEAKING_ABOUT_FAMILIAR_TOPICS": [
        {
            "t": ("Рассказываю о себе", "Talking About Myself"),
            "o": ("Готовить монолог о себе, используя past simple и present perfect.",
                  "Prepare a monologue about yourself using past simple and present perfect."),
            "v": [("to introduce oneself", "представиться"), ("hometown", "родной город"),
                  ("to major in", "учиться по специальности"), ("leisure", "досуг"),
                  ("for ... years", "в течение ... лет"), ("to give reasons", "привести причины"),
                  ("fluently", "бегло")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have studied English for six years.",
                  ["I have studied English six years ago.", "I study English for six years already."]),
            "tr": ("Я занимаюсь фотографией пять лет и уже выиграл два конкурса.",
                   "I have done photography for five years and have already won two contests.",
                   ["did", "do", "tomorrow"]),
            "fill": ("Two years ago I ___ my studies and moved to the capital.", "started",
                     ["has start", "starting"], "Два года назад я начал учёбу и переехал в столицу."),
            "tap": ("She has spoken about her hometown twice already.", ["was", "did"]),
            "sh": ("I grew up in a small town, I have lived in the capital for three years, and I am going to become a designer.",
                   "Я вырос в маленьком городе, три года живу в столице и собираюсь стать дизайнером."),
            "st": ("The Speaking Card", [
                ("Examiner", "Tell me about your hobbies and how long you have done them.", "Расскажите о хобби и как долго вы ими занимаетесь."),
                ("Candidate", "I started climbing at university and have done it for four years now.",
                 "Я начал скалолазание в университете и занимаюсь им уже четыре года."),
                ("What does the examiner ask next?", [
                    ("Why do you enjoy it so much?", True),
                    ("Why did you enjoying it tomorrow?", False),
                    ("Is the climbing speaking about you?", False)])]),
            "d": ("to major in", "To study a main subject at university",
                  ["To work in several jobs at once", "To teach younger students"]),
            "lw": ("I have ___ English since childhood.", "I have learned English since childhood.",
                   "learned", ["learn", "learning"]),
            "mw": ("I have lived here ___ five years.", "for", "fo"),
            "ch": ([("Examiner", "Where are you from?")], "You",
                   "A small town in the south — I moved to the city for university and have stayed since.",
                   ["I am from it yesterday tomorrow.", "The town is being me."]),
        },
        {
            "t": ("Вопросы и ответы по темам", "Topic Questions and Answers"),
            "o": ("Отвечать на вопросы по знакомым темам, сравнивая варианты ответов.",
                  "Answer familiar-topic questions, comparing answer options."),
            "v": [("to give an example", "привести пример"), ("longer answer", "более развёрнутый ответ"),
                  ("reason + example", "причина + пример"), ("to stick to the point", "не отходить от темы"),
                  ("more confident", "увереннее"), ("to hesitate", "запинаться"),
                  ("linking phrases", "связующие фразы")],
            "q": ("Which answer is better in a speaking exam?",
                  "Yes, I do — because it helps me relax. For example, I walk every evening.",
                  ["Yes.", "Yes, I do walk, yes, walking, yes."]),
            "tr": ("Я собираюсь давать развёрнутые ответы: причина плюс пример.",
                   "I am going to give longer answers: reason plus example.",
                   ["did", "gave", "yesterday"]),
            "fill": ("A short 'yes' sounds ___ than a developed answer.", "weaker",
                     ["weakest", "more weak"], "Короткое «да» звучит слабее развёрнутого ответа."),
            "tap": ("Linking phrases make the speech smoother.", ["was", "did"]),
            "sh": ("If you add a reason and one example to every answer, your minute of speaking will feel too short.",
                   "Если добавлять причину и один пример к каждому ответу, минуты речи покажется слишком мало."),
            "st": ("The One-Word Answer", [
                ("Examiner", "Do you like cooking?", "Вы любите готовить?"),
                ("Candidate", "Yes... a little.", "Да... немного."),
                ("What should the candidate add?", [
                    ("A reason and an example — 'because it relaxes me; last weekend I made borscht'.", True),
                    ("Only 'yes' repeated more confidently.", False),
                    ("A question back to the examiner about cooking.", False)])]),
            "d": ("to hesitate", "To pause often because you are not sure",
                  ["To speak without any stops", "To answer before the question ends"]),
            "lw": ("I am going to ___ an example to each answer.", "I am going to add an example to each answer.",
                   "add", ["added", "adding"]),
            "mw": ("Reason plus example makes answers ___ .", "longer", "lo"),
            "ch": ([("Friend", "I run out of things to say quickly.")], "You",
                   "Use reason-plus-example — if you build answers this way, forty seconds will fill themselves.",
                   ["I used it yesterday tomorrow.", "The seconds are running out of me."]),
        },
        {
            "t": ("Если забыл слово", "If You Forget a Word"),
            "o": ("Справляться с паузами, используя should и первое условное.",
                  "Handle pauses using should and the first conditional."),
            "v": [("to paraphrase around", "объяснить по-другому"), ("to describe the function", "описать функцию"),
                  ("filler phrase", "фраза-заполнитель"), ("silence", "молчание"),
                  ("to keep talking", "продолжать говорить"), ("calm", "спокойный"),
                  ("to come back to mind", "вспомниться")],
            "q": ("Which sentence gives correct speaking advice?",
                  "You should paraphrase the word instead of going silent.",
                  ["You should to paraphrase it yesterday.", "You must paraphrasing words last exam."]),
            "tr": ("Если замолчишь, это хуже, чем неидеальный ответ.",
                   "If you go silent, it is worse than an imperfect answer.",
                   ["did", "went", "yesterday"]),
            "fill": ("If a word does not come, ___ its function: 'a thing for opening bottles'.",
                     "describe", ["will describe", "described"], "Если слово не приходит, опиши его функцию: «штука для открывания бутылок»."),
            "tap": ("You should keep talking — never stop.", ["mustn't", "went"]),
            "sh": ("If you use fillers like 'well, let me think', the examiner will hear fluency instead of silence.",
                   "Если использовать фразы-заполнители вроде 'well, let me think', экзаменатор услышит беглость вместо молчания."),
            "st": ("The Missing Word", [
                ("Voice 1", "I forgot the word 'wallet' in the practice exam and just stopped.", "Я забыл слово 'wallet' на тренировочном экзамене и просто замолчал."),
                ("Voice 2", "What did the teacher say to do in such moments?", "Что преподаватель советует в такие моменты?"),
                ("What is the technique?", [
                    ("Describe it — 'the small thing where I keep money and cards'.", True),
                    ("Say the Russian word louder and continue.", False),
                    ("Wait silently until the word returns.", False)])]),
            "d": ("filler phrase", "A phrase like 'you know' that fills a pause",
                  ["A long academic definition", "The final sentence of your monologue"]),
            "lw": ("If you forget a word, ___ around it.", "If you forget a word, talk around it.",
                   "talk", ["will talk", "talked"]),
            "mw": ("Keep ___ , even without the perfect word.", "talking", "ta"),
            "ch": ([("Friend", "I panic when words disappear.")], "You",
                   "Train paraphrasing daily — if it becomes a habit, a lost word will not break your flow.",
                   ["I trained it yesterday tomorrow.", "The words are panicking me."]),
        },
    ],

    "A2_EXAM_VOCABULARY_IN_CONTEXT": [
        {
            "t": ("Слова в текстах", "Words in Texts"),
            "o": ("Работать со значением слов, используя past simple и present perfect.",
                  "Work with word meanings using past simple and present perfect."),
            "v": [("meaning in context", "значение в контексте"), ("to guess", "догадаться"),
                  ("part of speech", "часть речи"), ("collocation", "словосочетание"),
                  ("prefix", "приставка"), ("synonym substitution", "подбор синонима"),
                  ("surrounding", "окружающий (контекст)")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "This word has appeared in every text this week.",
                  ["This word has appeared yesterday.", "This word appear in texts already now."]),
            "tr": ("Из контекста я догадался, что это слово означает «наоборот».",
                   "From the context I guessed that the word means 'on the contrary'.",
                   ["did", "guess", "tomorrow"]),
            "fill": ("The word 'unfair' has a negative ___ 'un-'.", "prefix",
                     ["prefixes", "prefixion"], "У слова 'unfair' отрицательная приставка 'un-'."),
            "tap": ("She has learned fifty collocations this month.", ["was", "did"]),
            "sh": ("The same verb changes its meaning in different collocations: make coffee, make a mistake, make a decision.",
                   "Один и тот же глагол меняет значение в разных словосочетаниях: make coffee, make a mistake, make a decision."),
            "st": ("The Meaning Task", [
                ("Voice 1", "What does 'sharp' mean in 'a sharp increase'?", "Что значит 'sharp' во фразе 'a sharp increase'?"),
                ("Voice 2", "Not about knives — in this context it means 'fast and sudden'.", "Не про ножи — в этом контексте это значит «быстрый и резкий»."),
                ("What does Voice 1 learn?", [
                    ("So the noun decides the meaning of the adjective here.", True),
                    ("So 'sharp' always means knives in every text.", False),
                    ("So the increase is cutting the context.", False)])]),
            "d": ("collocation", "Words that naturally go together, like make a decision",
                  ["Two words with opposite meanings", "A word that came from another language"]),
            "lw": ("I have ___ the meaning from the context.", "I have guessed the meaning from the context.",
                   "guessed", ["guess", "guessing"]),
            "mw": ("Check the part of ___ first.", "speech", "sp"),
            "ch": ([("Friend", "'Run a company' — can you run a company?")], "You",
                   "Yes — run has many collocations: run a company, run late, run out of money.",
                   ["I ran it yesterday tomorrow.", "The company is running me."]),
        },
        {
            "t": ("Расширяем словарь к экзамену", "Expanding Vocabulary for the Exam"),
            "o": ("Сравнить способы учить слова и спланировать словарную работу.",
                  "Compare ways of learning words and plan vocabulary work."),
            "v": [("word family", "словообразовательное гнездо"), ("more efficient", "эффективнее"),
                  ("topic lists", "тематические списки"), ("spaced repetition", "интервальное повторение"),
                  ("to recycle words", "повторять (пущ. в оборот) слова"), ("active vocabulary", "активный словарь"),
                  ("in chunks", "блоками / кусочками")],
            "q": ("Which sentence compares two learning ways correctly?",
                  "Learning word families is more efficient than single words.",
                  ["Word families are efficienсter than words.", "Families are most efficient than single words."]),
            "tr": ("Я собираюсь учить слова блоками, а не по одному.",
                   "I am going to learn words in chunks, not one by one.",
                   ["did", "learned", "yesterday"]),
            "fill": ("Topic lists are ___ than alphabetical ones for the exam.", "better",
                     ["best", "more good"], "Тематические списки лучше алфавитных для экзамена."),
            "tap": ("We are going to recycle last month's words weekly.", ["was", "did"]),
            "sh": ("If you recycle old words in new sentences, they will move into your active vocabulary.",
                   "Если использовать старые слова в новых предложениях, они перейдут в активный словарь."),
            "st": ("The Word List", [
                ("Voice 1", "I have learned two hundred words this month, but I forget them in texts.", "Я выучил двести слов за месяц, но в текстах их забываю."),
                ("Voice 2", "Single words or chunks with examples?", "Отдельные слова или блоками с примерами?"),
                ("What does Voice 1 admit?", [
                    ("Single words... I should switch to chunks and word families.", True),
                    ("Chunks — I have always learned them in families already.", False),
                    ("The texts are forgetting my two hundred words.", False)])]),
            "d": ("word family", "A group of words from one root: decide, decision, decisive",
                  ["Words that rhyme with each other", "Words listed together in one topic"]),
            "lw": ("I am going to learn phrasal verbs in ___ .", "I am going to learn phrasal verbs in chunks.",
                   "chunks", ["chunk", "chunking"]),
            "mw": ("Spaced repetition is ___ than one-night learning.", "more efficient", "mo"),
            "ch": ([("Friend", "How many words a day?")], "You",
                   "Ten in chunks — if you recycle them weekly, they will stay for the exam.",
                   ["I learned them yesterday tomorrow.", "The words are chunking me."]),
        },
        {
            "t": ("Если слово не вспоминается", "If the Word Does Not Come"),
            "o": ("Разобрать словарные ошибки, используя should и первое условное.",
                  "Analyse vocabulary mistakes using should and the first conditional."),
            "v": [("to confuse", "путать"), ("similar-looking word", "похожее по написанию слово"),
                  ("false friend", "ложный друг переводчика"), ("to double the meaning", "проверить значение дважды"),
                  ("to note down", "записать"), ("review", "повторение"),
                  ("context sentence", "предложение с контекстом")],
            "q": ("Which sentence gives correct vocabulary advice?",
                  "You should learn false friends with context sentences.",
                  ["You should to learn them yesterday.", "You must learning friends last week."]),
            "tr": ("Если выучить слово без контекста, легко перепутать его с похожим.",
                   "If you learn a word without context, you will easily confuse it with a similar one.",
                   ["did", "learned", "yesterday"]),
            "fill": ("If you confuse two words, ___ them together in one notebook entry.",
                     "write", ["will write", "wrote"], "Если путаешь два слова, запиши их вместе в одной записи."),
            "tap": ("You should review new words within a day.", ["mustn't", "went"]),
            "sh": ("If you note down the context sentence, not just the translation, the word will return to you in the exam.",
                   "Если записать предложение с контекстом, а не только перевод, слово вернётся к тебе на экзамене."),
            "st": ("The False Friend", [
                ("Voice 1", "I wrote 'magazine' in the essay — but I meant a shop!", "Я написал 'magazine' в эссе — а имел в виду магазин!"),
                ("Voice 2", "A classic false friend. What is the correct English word?", "Классический ложный друг. Какое правильное английское слово?"),
                ("What does Voice 1 learn?", [
                    ("'Shop' — and I have noted the pair down with an example sentence.", True),
                    ("'Magasin' — the same word in English spelling.", False),
                    ("The magazine is shopping my essay.", False)])]),
            "d": ("false friend", "A word that looks the same in two languages but means something different",
                  ["A word that is easy to translate exactly", "A synonym pair in one language"]),
            "lw": ("If you ___ similar words, study them side by side.", "If you confuse similar words, study them side by side.",
                   "confuse", ["will confuse", "confused"]),
            "mw": ("Note the ___ sentence, not only the translation.", "context", "co"),
            "ch": ([("Friend", "I mix up 'receipt' and 'recipe' all the time.")], "You",
                   "Write them together with examples — if you see the pair, the difference will stick.",
                   ["I wrote them yesterday tomorrow.", "The words are recipeting me."]),
        },
    ],

    "A2_EXAM_WRITING_MESSAGES_AND_EMAILS": [
        {
            "t": ("Письмо, которое я написал", "The Email I Wrote"),
            "o": ("Написать письмо по образцу, используя past simple и present perfect.",
                  "Write a model email using past simple and present perfect."),
            "v": [("salutation", "обращение"), ("reason for writing", "причина письма"),
                  ("to attach", "приложить"), ("sign-off", "заключительная формула"),
                  ("word count", "количество слов"), ("formal register", "официальный стиль"),
                  ("to proofread", "вычитать")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have attached the form to this email.",
                  ["I have attached it yesterday.", "I attach the form already now."]),
            "tr": ("Я написал письмо, приложил форму и вычитал текст дважды.",
                   "I wrote the email, attached the form and proofread the text twice.",
                   ["did", "write", "tomorrow"]),
            "fill": ("The task asked for a ___ register, so I wrote 'Dear Mr Brown'.", "formal",
                     ["formally", "formals"], "В задании требовался официальный стиль, поэтому я написал 'Dear Mr Brown'."),
            "tap": ("She has checked the word count twice.", ["was", "did"]),
            "sh": ("The task usually gives three points — if you cover all of them, the structure of the email writes itself.",
                   "Задание обычно даёт три пункта — если покрыть все, структура письма напишется сама."),
            "st": ("The Task Check", [
                ("Voice 1", "The task says: explain the problem, suggest a date, ask about equipment.", "В задании: объяснить проблему, предложить дату, спросить про оборудование."),
                ("Voice 2", "Three paragraphs, one point each. Have you covered all three?", "Три абзаца, по пункту на каждый. Ты покрыл все три?"),
                ("What does Voice 1 say?", [
                    ("Two... I have missed the question about equipment. Fixing it now.", True),
                    ("All three — I covered them tomorrow yesterday.", False),
                    ("The paragraphs are tasking my points.", False)])]),
            "d": ("sign-off", "The closing phrase like 'Kind regards'",
                  ["The first line with the recipient's name", "The subject line of the email"]),
            "lw": ("I have ___ the documents to the reply.", "I have attached the documents to the reply.",
                   "attached", ["attach", "attaching"]),
            "mw": ("State your ___ for writing in line one.", "reason", "re"),
            "ch": ([("Friend", "'Hi Sir' — is that a good salutation?")], "You",
                   "No — either 'Dear Sir' or 'Hi Mr Brown'; a mix is too informal for the exam.",
                   ["I mixed it yesterday tomorrow.", "The sir is salutating me."]),
        },
        {
            "t": ("Пишем письмо на следующей неделе", "Writing Next Week's Email"),
            "o": ("Сравнить письма и спланировать письменную практику.",
                  "Compare emails and plan writing practice."),
            "v": [("informal email", "неофициальное письмо"), ("formal email", "официальное письмо"),
                  ("shorter", "короче"), ("contractions", "сокращения (don't, I'm)"),
                  ("to organise into paragraphs", "разбить на абзацы"), ("flow", "связность (текста)"),
                  ("to keep to the limit", "уложиться в лимит")],
            "q": ("Which sentence compares two email styles correctly?",
                  "An informal email is shorter than a formal one.",
                  ["Informal emails is shorterest than formal.", "An informal email is most short than formal."]),
            "tr": ("На следующей неделе я собираюсь писать по одному письму в день.",
                   "Next week I am going to write one email a day.",
                   ["did", "wrote", "yesterday"]),
            "fill": ("Contractions like 'I'm' suit ___ emails.", "informal",
                     ["informals", "informally"], "Сокращения вроде 'I'm' уместны в неофициальных письмах."),
            "tap": ("We are going to organise answers into clear paragraphs.", ["was", "did"]),
            "sh": ("If you organise the email into short paragraphs, the examiner will see your structure in five seconds.",
                   "Если разбить письмо на короткие абзацы, экзаменатор увидит структуру за пять секунд."),
            "st": ("Formal or Informal?", [
                ("Voice 1", "The task says 'write to your friend about the trip'.", "В задании: 'напиши другу о поездке'."),
                ("Voice 2", "Then informal — contractions, short sentences, a friendly sign-off.",
                 "Значит неофициальное — сокращения, короткие предложения, дружеское завершение."),
                ("What does Voice 1 write?", [
                    ("'Hi Sam, great news — I've booked the tickets!'", True),
                    ("'Dear Sir, I am writing to inform you about my trip.'", False),
                    ("'To whom it may concern, my friend Sam...'", False)])]),
            "d": ("contractions", "Short forms like 'don't' or 'I'm'",
                  ["Long full forms like 'do not'", "Formal titles before names"]),
            "lw": ("I am going to ___ the letter into three paragraphs.", "I am going to divide the letter into three paragraphs.",
                   "divide", ["divided", "dividing"]),
            "mw": ("A good flow makes the text ___ to read.", "easier", "ea"),
            "ch": ([("Friend", "I always write more words than needed.")], "You",
                   "Cut the weakest sentence — if you keep to the limit, you will not lose points for length.",
                   ["I cut it yesterday tomorrow.", "The words are limiting me."]),
        },
        {
            "t": ("Если письмо выходит за лимит", "If the Email Exceeds the Limit"),
            "o": ("Редактировать письмо, используя should и первое условное.",
                  "Edit an email using should and the first conditional."),
            "v": [("word limit", "лимит слов"), ("to cut out", "вырезать"),
                  ("redundant", "избыточный"), ("to prioritise", "расставить приоритеты"),
                  ("checking stage", "этап проверки"), ("spelling", "орфография"),
                  ("punctuation", "пунктуация")],
            "q": ("Which sentence gives correct writing advice?",
                  "You should leave two minutes for a final check.",
                  ["You should to leave it yesterday.", "You must leaving minutes last email."]),
            "tr": ("Если не оставить время на проверку, орфография пострадает.",
                   "If you do not leave time for checking, your spelling will suffer.",
                   ["did", "left", "yesterday"]),
            "fill": ("If the text is too long, ___ the redundant sentences.",
                     "cut out", ["will cut out", "cutted out"], "Если текст слишком длинный, вырежь избыточные предложения."),
            "tap": ("You should check punctuation before submitting.", ["mustn't", "went"]),
            "sh": ("If you spend the last two minutes on spelling and punctuation, your email will look a grade higher.",
                   "Если потратить последние две минуты на орфографию и пунктуацию, письмо будет выглядеть на балл выше."),
            "st": ("The Overlong Draft", [
                ("Voice 1", "My draft has 160 words, and the limit is 120.", "В черновике 160 слов, а лимит 120."),
                ("Voice 2", "Which sentences repeat the same idea?", "Какие предложения повторяют одну мысль?"),
                ("What does Voice 1 do?", [
                    ("I have found two redundant ones — cutting them out.", True),
                    ("I have counted the words more times.", False),
                    ("The limit is drafting my 160 words.", False)])]),
            "d": ("redundant", "Not needed, repeating other words",
                  ["Necessary for covering the task points", "The first sentence of the email"]),
            "lw": ("If you ___ two minutes, you will catch the typos.", "If you leave two minutes, you will catch the typos.",
                   "leave", ["will leave", "left"]),
            "mw": ("Spelling and ___ are checked last.", "punctuation", "pu"),
            "ch": ([("Friend", "I never have time to check my writing.")], "You",
                   "Write shorter — if the draft is tight, the checking stage will fit in two minutes.",
                   ["I checked it yesterday tomorrow.", "The writing is timing me."]),
        },
    ],
}
