#!/usr/bin/env python3
"""A2 regenerated content: WORK AND CAREER (10 tracks x 3 lessons).

Grammar arc per topic: L1 past simple + present perfect,
L2 future forms + comparatives, L3 modals / first conditional.
"""

TRACKS = {
    "A2_WORK_BREAKS_AND_TEAM_SMALL_TALK": [
        {
            "t": ("Новости с прошлой недели", "News From Last Week"),
            "o": ("Обсудить в перерыве прошедшие события, используя past simple и present perfect.",
                  "Discuss recent events during a break using past simple and present perfect."),
            "v": [("to catch up", "обменяться новостями"), ("team lunch", "обед с командой"),
                  ("already", "уже"), ("yet", "ещё"), ("to join", "присоединиться"),
                  ("stressful", "напряжённый"), ("weekend", "выходные")],
            "q": ("Which sentence is in the present perfect?",
                  "I have already told the team about the change.",
                  ["I told the team about the change yesterday.", "I will tell the team about the change."]),
            "tr": ("Мы уже обсудили новый график, но ещё не сказали об этом менеджеру.",
                   "We have already discussed the new schedule, but we have not told the manager yet.",
                   ["did", "yesterday", "will"]),
            "fill": ("We had a team lunch ___ Friday.", "last", ["next", "since"],
                     "Мы обедали всей командой в прошлую пятницу."),
            "tap": ("She joined our team two months ago.", ["will", "never"]),
            "sh": ("Have you finished the report yet? We discussed it last week.",
                   "Ты уже закончил отчёт? Мы обсуждали его на прошлой неделе."),
            "st": ("Monday Morning", [
                ("Maya", "Did you have a good weekend?", "Как прошли твои выходные?"),
                ("Ben", "Yes, I visited my parents. Have you seen the new coffee machine yet?",
                 "Да, я навестил родителей. Ты уже видел новую кофемашину?"),
                ("What does Maya answer?", [
                    ("Not yet, but I have already made tea.", True),
                    ("Yes, I see it tomorrow.", False),
                    ("The coffee machine is on holiday.", False)])]),
            "d": ("stressful", "Making you feel worried and tired",
                  ["Making you feel happy and relaxed", "Very cheap to buy"]),
            "lw": ("I have ___ joined the new project team.", "I have just joined the new project team.",
                   "just", ["yet", "last week"]),
            "mw": ("She has worked here ___ 2021.", "since", "si"),
            "ch": ([("Colleague", "Have you had lunch yet?")], "You",
                   "Not yet, I have just finished a call.",
                   ["Yes, I eat lunch yesterday.", "Lunch is a meeting room."]),
        },
        {
            "t": ("Планы на пятницу", "Friday Plans"),
            "o": ("Рассказать о планах и сравнить варианты, используя going to и сравнительные степени.",
                  "Talk about plans and compare options using going to and comparatives."),
            "v": [("to be going to", "собираться (что-то сделать)"), ("day off", "выходной день"),
                  ("to invite", "пригласить"), ("birthday", "день рождения"), ("cake", "торт"),
                  ("to order", "заказать"), ("than", "чем")],
            "q": ("Which sentence talks about a future plan?",
                  "We are going to order pizza for the team lunch.",
                  ["We ordered pizza for the team lunch.", "We have ordered pizza for the team lunch."]),
            "tr": ("Мы собираемся устроить обед побольше, чем в прошлый раз, потому что у Аны день рождения.",
                   "We are going to have a bigger lunch than last time because it is Ana's birthday.",
                   ["did", "had", "will"]),
            "fill": ("This Monday is ___ stressful than last Monday.", "less", ["most", "the"],
                     "Этот понедельник менее напряжённый, чем прошлый."),
            "tap": ("I am going to invite the whole team to my birthday party.", ["was", "did"]),
            "sh": ("Are you going to join us for coffee? This cafe is quieter than the one downstairs.",
                   "Ты пойдёшь с нами за кофе? Это кафе тише, чем то, что на первом этаже."),
            "st": ("Friday Plans", [
                ("Ben", "Are you going to join the team lunch on Friday?",
                 "Ты присоединишься к обеду команды в пятницу?"),
                ("Maya", "Yes, I am. Is it going to be at the Italian place again?",
                 "Да. Он снова будет в том итальянском месте?"),
                ("What does Ben say?", [
                    ("No, we are going to try the new cafe this time.", True),
                    ("Yes, it is going to yesterday.", False),
                    ("The lunch is eating a pizza.", False)])]),
            "d": ("to invite", "To ask someone to come to an event",
                  ["To tell someone to leave a place", "To pay for someone's meal"]),
            "lw": ("We are ___ to order a cake for Friday.", "We are going to order a cake for Friday.",
                   "going", ["went", "gone"]),
            "mw": ("Friday is ___ than Monday for meetings.", "better", "be"),
            "ch": ([("Colleague", "Do you want to join our coffee break?")], "You",
                   "I can't now, but I am going to join you in ten minutes.",
                   ["I will joined you yesterday.", "Coffee is drinking me."]),
        },
        {
            "t": ("Хороший совет", "Good Advice"),
            "o": ("Дать совет коллеге, используя should, must и первое условное наклонение.",
                  "Give a colleague advice using should, must and the first conditional."),
            "v": [("should", "следует"), ("must", "должен (обязан)"), ("to relax", "расслабиться"),
                  ("break", "перерыв"), ("to suggest", "предложить"), ("fresh air", "свежий воздух"),
                  ("to feel tired", "чувствовать усталость")],
            "q": ("Which sentence gives advice about breaks?",
                  "You should take a short break every hour.",
                  ["You must take a break yesterday.", "You are taking a break every hour."]),
            "tr": ("Если ты будешь работать без перерывов, ты устанешь к обеду.",
                   "If you work without breaks, you will feel tired by lunchtime.",
                   ["did", "worked", "yesterday"]),
            "fill": ("You ___ turn off your phone during the meeting — it is the rule.",
                     "must", ["might", "would"], "Ты обязан выключить телефон на встрече — это правило."),
            "tap": ("We should go for a walk in the park during the lunch break.", ["mustn't", "went"]),
            "sh": ("If the weather is nice, we should have our coffee break outside.",
                   "Если погода будет хорошей, нам стоит выпить кофе на улице."),
            "st": ("A Good Idea", [
                ("Maya", "You look tired today. Have you taken a break?",
                 "Ты выглядишь уставшим. Ты сегодня делал перерыв?"),
                ("Ben", "No, I have been at my desk since nine.", "Нет, я за столом с девяти."),
                ("What should Maya suggest?", [
                    ("You should take a short walk and get some fresh air.", True),
                    ("You must work faster and finish everything.", False),
                    ("You should to sleep in the office.", False)])]),
            "d": ("to suggest", "To offer an idea for other people to think about",
                  ["To say no to an idea politely", "To finish work earlier than usual"]),
            "lw": ("If you ___ a break, you will feel better.", "If you take a break, you will feel better.",
                   "take", ["will take", "took"]),
            "mw": ("You ___ not use your phone in the meeting room.", "must", "mu"),
            "ch": ([("Colleague", "I always feel tired in the afternoon.")], "You",
                   "You should take a short walk after lunch.",
                   ["You must to drink coffee all day.", "You should worked less yesterday."]),
        },
    ],

    "A2_WORK_EQUIPMENT_AND_SUPPLIES": [
        {
            "t": ("Что случилось с принтером", "What Happened to the Printer"),
            "o": ("Сообщить о поломке и заказе техники, используя past simple и present perfect.",
                  "Report a breakdown and an order using past simple and present perfect."),
            "v": [("to break down", "сломаться"), ("printer", "принтер"), ("to report", "сообщить"),
                  ("to replace", "заменить"), ("supply", "канцтовары / расходники"),
                  ("to order", "заказать"), ("out of order", "не работает")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The printer has broken down twice this week.",
                  ["The printer has broken down yesterday.", "The printer break down twice this week."]),
            "tr": ("Принтер сломался в понедельник, и мы уже заказали новый.",
                   "The printer broke down on Monday, and we have already ordered a new one.",
                   ["did", "yesterday", "will"]),
            "fill": ("I ___ the problem to the office manager an hour ago.", "reported",
                     ["have report", "will reported"], "Я сообщил о проблеме офис-менеджеру час назад."),
            "tap": ("We have run out of paper and ink for the printer.", ["was", "did"]),
            "sh": ("The scanner has stopped working, so I reported it to the IT department.",
                   "Сканер перестал работать, поэтому я сообщил об этом в IT-отдел."),
            "st": ("The Broken Printer", [
                ("Tom", "Why is the printer out of order?", "Почему принтер не работает?"),
                ("Anna", "It broke down this morning. I have already called the service company.",
                 "Он сломался сегодня утром. Я уже позвонила в сервисную компанию."),
                ("What does Tom ask next?", [
                    ("Have they said when they will come?", True),
                    ("Did they will come tomorrow?", False),
                    ("Is the printer feeling better?", False)])]),
            "d": ("to replace", "To put something new in place of something old",
                  ["To turn a machine on and off", "To borrow something for a short time"]),
            "lw": ("We have ___ out of sticky notes.", "We have run out of sticky notes.",
                   "run", ["ran", "running"]),
            "mw": ("The lift has been ___ of order since Monday.", "out", "ou"),
            "ch": ([("Colleague", "The coffee machine is not working again.")], "You",
                   "I know. I have already reported it to the facilities team.",
                   ["Yes, I will reported it yesterday.", "The coffee is drinking the machine."]),
        },
        {
            "t": ("Что закажем в этом месяце", "What We Will Order This Month"),
            "o": ("Сравнить товары и поставщиков и рассказать о будущих заказах.",
                  "Compare products and suppliers and talk about future orders."),
            "v": [("cheaper", "дешевле"), ("more reliable", "надёжнее"),
                  ("supplier", "поставщик"), ("to order in advance", "заказывать заранее"),
                  ("delivery", "доставка"), ("budget", "бюджет"), ("laptop", "ноутбук")],
            "q": ("Which sentence compares two things correctly?",
                  "This supplier is cheaper than the old one.",
                  ["This supplier is more cheap than the old one.", "This supplier is cheapest than the old one."]),
            "tr": ("Новый ноутбук дороже, но он прослужит дольше, чем старый.",
                   "The new laptop is more expensive, but it will last longer than the old one.",
                   ["did", "was", "most"]),
            "fill": ("These chairs are ___ comfortable than the old ones.", "more",
                     ["most", "much"], "Эти кресла удобнее старых."),
            "tap": ("We are going to order the supplies from a cheaper supplier.", ["was", "did"]),
            "sh": ("If we order in advance, the delivery will be faster and the price will be lower.",
                   "Если мы закажем заранее, доставка будет быстрее, а цена ниже."),
            "st": ("Choosing a Supplier", [
                ("Anna", "Which supplier are we going to choose?", "Какого поставщика мы выберем?"),
                ("Tom", "Company A is cheaper, but Company B is more reliable.",
                 "Компания A дешевле, но компания B надёжнее."),
                ("What does Anna say?", [
                    ("Then we should choose Company B for important orders.", True),
                    ("Then we must to choose the expensive one yesterday.", False),
                    ("The supplier is choosing us next week.", False)])]),
            "d": ("supplier", "A company that sells goods or services to other companies",
                  ["A person who buys goods in a shop", "A machine that makes paper"]),
            "lw": ("This model is ___ expensive than that one.", "This model is less expensive than that one.",
                   "less", ["least", "little"]),
            "mw": ("The delivery will arrive ___ Tuesday than planned.", "earlier", "ea"),
            "ch": ([("Colleague", "Should we order the new monitors now?")], "You",
                   "Yes, if we order today, they will arrive before the deadline.",
                   ["No, we will ordered them yesterday.", "The monitors are ordering themselves."]),
        },
        {
            "t": ("Правила безопасности с техникой", "Equipment Safety Rules"),
            "o": ("Объяснить обязательные правила и последствия, используя must и первое условное.",
                  "Explain obligatory rules and consequences using must and the first conditional."),
            "v": [("to unplug", "отключить от сети"), ("cable", "кабель"), ("dangerous", "опасный"),
                  ("to follow the rules", "соблюдать правила"), ("instruction", "инструкция"),
                  ("to damage", "повредить"), ("carefully", "осторожно")],
            "q": ("Which sentence expresses an obligation?",
                  "You must unplug the machine before cleaning it.",
                  ["You should unplugging the machine yesterday.", "You can unplugged the machine last week."]),
            "tr": ("Если ты не будешь следовать инструкции, ты можешь повредить оборудование.",
                   "If you do not follow the instructions, you may damage the equipment.",
                   ["did", "followed", "yesterday"]),
            "fill": ("You ___ not use damaged cables — it is dangerous.", "must",
                     ["should to", "don't have"], "Нельзя пользоваться повреждёнными кабелями — это опасно."),
            "tap": ("You must read the instruction manual before using the new machine.", ["may", "went"]),
            "sh": ("If the cable feels hot, you must unplug it immediately and call the technician.",
                   "Если кабель горячий на ощупь, нужно сразу отключить его и вызвать техника."),
            "st": ("A Damaged Cable", [
                ("Tom", "Look, this cable is damaged. Can we still use it?",
                 "Смотри, этот кабель повреждён. Можно им всё ещё пользоваться?"),
                ("Anna", "No, we can't. We must replace it today.", "Нет. Мы должны заменить его сегодня."),
                ("What does Tom say?", [
                    ("If we use it, the computer may break.", True),
                    ("If we will use it, the computer breaks yesterday.", False),
                    ("The cable must to fix itself.", False)])]),
            "d": ("to damage", "To break something or make it worse",
                  ["To make something look newer", "To buy something for the office"]),
            "lw": ("If you ___ the printer, it will not work.", "If you overload the printer, it will not work.",
                   "overload", ["will overload", "overloaded"]),
            "mw": ("You must turn ___ the machine before leaving.", "off", "of"),
            "ch": ([("Colleague", "Can I keep my heater under the desk?")], "You",
                   "No, you mustn't — if it overheats, it can start a fire.",
                   ["Yes, heaters are working yesterday.", "The heater must to sleep under the desk."]),
        },
    ],

    "A2_WORK_JOBS_AND_RESPONSIBILITIES": [
        {
            "t": ("Кто что сделал в этом квартале", "Who Did What This Quarter"),
            "o": ("Рассказать о результатах коллег, используя past simple и present perfect.",
                  "Talk about colleagues' results using past simple and present perfect."),
            "v": [("responsibility", "обязанность"), ("to promote", "повысить в должности"),
                  ("department", "отдел"), ("to achieve", "достичь"), ("target", "цель / план"),
                  ("employee", "сотрудник"), ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect with 'so far'?",
                  "Our team has achieved three targets so far this year.",
                  ["Our team has achieved three targets last year.", "Our team achieved three targets so far yet."]),
            "tr": ("Мария руководила проектом с марта и уже повысила продажи на десять процентов.",
                   "Maria has led the project since March and has already increased sales by ten percent.",
                   ["did", "led", "yesterday"]),
            "fill": ("Last year he ___ in the sales department.", "worked",
                     ["has work", "working"], "В прошлом году он работал в отделе продаж."),
            "tap": ("She has trained five new employees since September.", ["was", "did"]),
            "sh": ("Who prepared the quarterly report? I think Anna did it, and she has done it very well.",
                   "Кто подготовил квартальный отчёт? Думаю, это сделала Аня, и она сделала это очень хорошо."),
            "st": ("A Promotion", [
                ("Manager", "I have good news. We have promoted Daniel to team leader.",
                 "У меня хорошая новость. Мы повысили Даниэля до тимлида."),
                ("Daniel", "Thank you! I have worked hard for this opportunity.",
                 "Спасибо! Я усердно работал ради этой возможности."),
                ("What does the manager add?", [
                    ("You have led the project very well since March.", True),
                    ("You have lead the project yesterday.", False),
                    ("The project is promoting you next year.", False)])]),
            "d": ("to promote", "To move someone to a higher, more important position at work",
                  ["To send someone to another office", "To give someone less work to do"]),
            "lw": ("He has ___ in three departments so far.", "He has worked in three departments so far.",
                   "worked", ["work", "working"]),
            "mw": ("She has been responsible ___ the project since May.", "for", "fo"),
            "ch": ([("Colleague", "Has the new employee started yet?")], "You",
                   "Yes, he joined last Monday and has already finished the training.",
                   ["Yes, he has start yesterday.", "The employee is starting himself."]),
        },
        {
            "t": ("Карьерные планы", "Career Plans"),
            "o": ("Рассказать о карьерных планах и сравнить должности.",
                  "Talk about career plans and compare positions."),
            "v": [("position", "должность"), ("salary", "зарплата"), ("experience", "опыт"),
                  ("to apply for", "подать заявку на"), ("promotion", "повышение"),
                  ("more interesting", "интереснее"), ("skills", "навыки")],
            "q": ("Which sentence talks about a future career plan?",
                  "I am going to apply for the project manager position.",
                  ["I applied for the project manager position last month.", "I have applied for the position yesterday."]),
            "tr": ("Эта должность интереснее моей текущей, но требует большего опыта.",
                   "This position is more interesting than my current one, but it requires more experience.",
                   ["did", "was", "most"]),
            "fill": ("A manager's salary is ___ than an assistant's.", "higher",
                     ["highest", "more high"], "Зарплата менеджера выше, чем у ассистента."),
            "tap": ("I am going to improve my presentation skills this year.", ["was", "did"]),
            "sh": ("If I get this promotion, I will have more responsibility but a better salary.",
                   "Если я получу это повышение, у меня будет больше ответственности, но лучше зарплата."),
            "st": ("The Internal Vacancy", [
                ("Anna", "Have you seen the new vacancy on the company website?",
                 "Ты видел новую вакансию на сайте компании?"),
                ("Tom", "Yes, the position is more senior than my current role.",
                 "Да, эта должность выше моей текущей."),
                ("What does Anna say?", [
                    ("You should apply — you have great experience.", True),
                    ("You must to apply yesterday immediately.", False),
                    ("The vacancy is applying for you.", False)])]),
            "d": ("to apply for", "To formally ask for a job or a position",
                  ["To refuse a job politely", "To leave a job to travel"]),
            "lw": ("I am going to ___ for a new position.", "I am going to apply for a new position.",
                   "apply", ["applied", "applying"]),
            "mw": ("This job is ___ demanding than my old one.", "more", "mo"),
            "ch": ([("Colleague", "Are you going to apply for the team leader role?")], "You",
                   "Yes, I am going to apply before Friday.",
                   ["Yes, I applied it tomorrow.", "The role is applying me."]),
        },
        {
            "t": ("Советы по развитию карьеры", "Career Advice"),
            "o": ("Дать совет о развитии карьеры, используя should и первое условное.",
                  "Give career development advice using should and the first conditional."),
            "v": [("to improve", "улучшить"), ("advice", "совет"), ("opportunity", "возможность"),
                  ("to take on", "взять на себя (задачи)"), ("regularly", "регулярно"),
                  ("confident", "уверенный"), ("career development", "развитие карьеры")],
            "q": ("Which sentence gives correct advice?",
                  "You should take on more responsibility if you want a promotion.",
                  ["You should to take more responsibility yesterday.", "You must taking responsibility last year."]),
            "tr": ("Если ты хочешь развивать карьеру, тебе следует регулярно учиться новому.",
                   "If you want to develop your career, you should learn something new regularly.",
                   ["did", "wanted", "yesterday"]),
            "fill": ("You ___ discuss your career plan with your manager every year.",
                     "should", ["must to", "shoulds"], "Тебе стоит обсуждать карьерный план с менеджером каждый год."),
            "tap": ("You should speak more confidently during the team meetings.", ["mustn't", "went"]),
            "sh": ("If you take on this project, you will get valuable experience and new skills.",
                   "Если ты возьмёшь на себя этот проект, ты получишь ценный опыт и новые навыки."),
            "st": ("After the Review", [
                ("Manager", "Your technical skills are strong, but you should improve your communication.",
                 "Твои технические навыки сильны, но тебе стоит улучшить коммуникацию."),
                ("Tom", "I agree. What should I do first?", "Согласен. Что мне сделать сначала?"),
                ("What does the manager say?", [
                    ("You should present at the next team meeting.", True),
                    ("You must to present at yesterday meeting.", False),
                    ("The communication is improving you.", False)])]),
            "d": ("opportunity", "A chance to do something good or useful",
                  ["A problem that is difficult to solve", "A rule that stops people from working"]),
            "lw": ("If you ___ this course, you will get a certificate.", "If you take this course, you will get a certificate.",
                   "take", ["will take", "took"]),
            "mw": ("You ___ ask for feedback more often.", "should", "sh"),
            "ch": ([("Colleague", "I want to become a senior specialist.")], "You",
                   "You should take on more complex tasks and ask for feedback.",
                   ["You must to become senior yesterday.", "The specialist is becoming you."]),
        },
    ],

    "A2_WORK_PROCEDURES_AND_SAFETY": [
        {
            "t": ("Инцидент на складе", "The Warehouse Incident"),
            "o": ("Сообщить о происшествии, используя past simple и present perfect.",
                  "Report an incident using past simple and present perfect."),
            "v": [("incident", "происшествие"), ("to injure", "травмировать"),
                  ("first aid kit", "аптечка"), ("to fill in a form", "заполнить форму"),
                  ("safety officer", "инспектор по охране труда"), ("immediately", "немедленно"),
                  ("floor", "пол / этаж")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The safety officer has already written the report.",
                  ["The safety officer has written the report yesterday.", "The safety officer write the report already."]),
            "tr": ("Вчера на складе произошёл небольшой инцидент, но никто не пострадал.",
                   "A small incident happened at the warehouse yesterday, but nobody has been injured.",
                   ["did", "happens", "tomorrow"]),
            "fill": ("He ___ his hand while moving the boxes last Friday.", "hurt",
                     ["has hurt yet", "hurting"], "Он поранил руку, когда переносил коробки в прошлую пятницу."),
            "tap": ("Someone has already called the safety officer about the incident.", ["was", "did"]),
            "sh": ("The floor was wet this morning, and one colleague slipped near the entrance.",
                   "Пол был мокрым сегодня утром, и один коллега поскользнулся у входа."),
            "st": ("Reporting an Incident", [
                ("Anna", "What happened to your arm?", "Что случилось с твоей рукой?"),
                ("Tom", "I slipped on the wet floor near the loading dock this morning.",
                 "Я поскользнулся на мокром полу у зоны погрузки сегодня утром."),
                ("What should Anna ask?", [
                    ("Have you reported it to the safety officer?", True),
                    ("Did you reported it yesterday already?", False),
                    ("Is your arm working in the office?", False)])]),
            "d": ("incident", "Something unusual and often dangerous that happens",
                  ["A regular meeting that happens every week", "A long holiday from work"]),
            "lw": ("We have ___ in the incident report form.", "We have filled in the incident report form.",
                   "filled", ["fill", "filling"]),
            "mw": ("Nobody has used the first aid ___ this year.", "kit", "ki"),
            "ch": ([("Colleague", "Did you fill in the incident form?")], "You",
                   "Yes, I filled it in and sent it to the safety officer.",
                   ["Yes, I have fill it yesterday.", "The form is filling itself."]),
        },
        {
            "t": ("Обучение по безопасности", "Safety Training"),
            "o": ("Рассказать о будущих тренировках по безопасности и сравнить риски.",
                  "Talk about future safety training and compare risks."),
            "v": [("training session", "тренировочное занятие"), ("fire drill", "учебная эвакуация"),
                  ("to attend", "посетить"), ("protective equipment", "средства защиты"),
                  ("exit", "выход"), ("more dangerous", "опаснее"), ("to practise", "практиковать")],
            "q": ("Which sentence is about the future?",
                  "The fire drill is going to take place on Thursday.",
                  ["The fire drill took place on Thursday last week.", "The fire drill has take place yesterday."]),
            "tr": ("Послезавтра мы будем практиковать эвакуацию — она пройдёт быстрее, чем в прошлый раз.",
                   "The day after tomorrow we are going to practise the fire drill — it will go faster than last time.",
                   ["did", "went", "yesterday"]),
            "fill": ("Working at heights is ___ dangerous than working in the office.", "more",
                     ["most", "much"], "Работа на высоте опаснее работы в офисе."),
            "tap": ("All employees are going to attend the safety training next month.", ["was", "did"]),
            "sh": ("If the alarm sounds, you should leave the building through the nearest exit immediately.",
                   "Если сработает сигнализация, следует немедленно покинуть здание через ближайший выход."),
            "st": ("The Fire Drill", [
                ("Manager", "Our fire drill is going to start at ten o'clock.", "Наша учебная эвакуация начнётся в десять."),
                ("Anna", "Is it going to be like the one last year?", "Она будет такой же, как в прошлом году?"),
                ("What does the manager say?", [
                    ("No, this time the route is going to be shorter.", True),
                    ("Yes, it is going to yesterday again.", False),
                    ("The drill is attending the employees.", False)])]),
            "d": ("fire drill", "A practice of leaving a building safely in case of fire",
                  ["A tool for putting out small fires", "A meeting about safety rules once a year"]),
            "lw": ("The training will ___ two hours.", "The training will last two hours.",
                   "last", ["lasted", "lasting"]),
            "mw": ("The new exit is ___ to find than the old one.", "easier", "ea"),
            "ch": ([("Colleague", "Do I have to attend the safety training?")], "You",
                   "Yes, everyone must attend — if you miss it, you will repeat the course online.",
                   ["No, I attended it tomorrow already.", "The training is musting everyone."]),
        },
        {
            "t": ("Правила, которые нельзя нарушать", "Rules You Must Not Break"),
            "o": ("Объяснить строгие правила безопасности с must и первым условным.",
                  "Explain strict safety rules with must and the first conditional."),
            "v": [("to require", "требовать"), ("without permission", "без разрешения"),
                  ("to lock", "закрыть на замок"), ("warning sign", "предупреждающий знак"),
                  ("to ignore", "игнорировать"), ("strict", "строгий"), ("in case of", "в случае")],
            "q": ("Which sentence expresses a strict rule?",
                  "You must not open this door without permission.",
                  ["You should not opening this door yesterday.", "You don't must open this door last week."]),
            "tr": ("Если ты будешь игнорировать предупреждающие знаки, ты нарушишь правила безопасности.",
                   "If you ignore the warning signs, you will break the safety rules.",
                   ["did", "ignored", "yesterday"]),
            "fill": ("In case of fire, you ___ use the lift.", "mustn't",
                     ["should to", "musts"], "В случае пожара нельзя пользоваться лифтом."),
            "tap": ("Every employee must wear protective equipment in this area.", ["may", "went"]),
            "sh": ("If you see a warning sign, you must stop and read it carefully before you continue.",
                   "Если ты видишь предупреждающий знак, нужно остановиться и внимательно прочитать его, прежде чем идти дальше."),
            "st": ("The Warning Sign", [
                ("Tom", "There is a new warning sign near the machine.", "У станка появился новый знак."),
                ("Anna", "What does it say?", "Что на нём написано?"),
                ("How does Tom explain the rule?", [
                    ("You must not touch the machine without permission.", True),
                    ("You must to not touch the machine yesterday.", False),
                    ("The sign is touching the employees.", False)])]),
            "d": ("to ignore", "To pretend you did not see or hear something",
                  ["To look at something very carefully", "To ask questions about a new rule"]),
            "lw": ("If the machine ___ a strange noise, stop it at once.",
                   "If the machine makes a strange noise, stop it at once.", "makes", ["will make", "made"]),
            "mw": ("You must ___ the door at the end of the day.", "lock", "lo"),
            "ch": ([("Colleague", "Can I repair this machine myself?")], "You",
                   "No, you mustn't — only certified technicians can open it.",
                   ["Yes, I repaired it myself yesterday always.", "The machine must to repair you."]),
        },
    ],

    "A2_WORK_REQUESTS_AND_CLARIFICATION": [
        {
            "t": ("Просьбы на этой неделе", "Requests This Week"),
            "o": ("Рассказать о просьбах и уточнениях, используя past simple и present perfect.",
                  "Talk about requests and clarifications using past simple and present perfect."),
            "v": [("to ask for", "попросить (что-то)"), ("to explain", "объяснить"),
                  ("to clarify", "уточнить"), ("detail", "деталь / подробность"),
                  ("request", "просьба / запрос"), ("by email", "по электронной почте"),
                  ("to double-check", "перепроверить")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have already asked him for the details twice.",
                  ["I have asked him for the details yesterday.", "I ask him for the details already twice."]),
            "tr": ("Я попросил её объяснить детали, и она уже прислала ответ по почте.",
                   "I asked her to explain the details, and she has already sent the reply by email.",
                   ["did", "asks", "tomorrow"]),
            "fill": ("Yesterday he ___ me for help with the presentation.", "asked",
                     ["has ask", "asking"], "Вчера он попросил меня помочь с презентацией."),
            "tap": ("She has clarified all the details of our request.", ["was", "did"]),
            "sh": ("I asked for the exact numbers, and the client has just sent them by email.",
                   "Я попросил точные цифры, и клиент только что прислал их по почте."),
            "st": ("A Vague Email", [
                ("Anna", "Did you understand what the client wants?", "Ты понял, чего хочет клиент?"),
                ("Tom", "Not really. His email was not very clear about the deadline.",
                 "Не совсем. Его письмо не очень ясно описывало сроки."),
                ("What should Tom do?", [
                    ("He should ask the client to clarify the deadline.", True),
                    ("He must to guess the deadline yesterday.", False),
                    ("The email is asking Tom for more details itself.", False)])]),
            "d": ("to clarify", "To make something easier to understand",
                  ["To close a request without an answer", "To send a document without checking it"]),
            "lw": ("Could you ___ the question, please?", "Could you repeat the question, please?",
                   "repeat", ["repeated", "repeating"]),
            "mw": ("I have double-___ the numbers in the report.", "checked", "ch"),
            "ch": ([("Colleague", "Did you get my email about the venue?")], "You",
                   "Yes, I got it, but could you clarify the date? The email says two different days.",
                   ["Yes, I have get it yesterday.", "The venue is emailing me the date."]),
        },
        {
            "t": ("Вежливые просьбы на будущее", "Polite Requests for the Future"),
            "o": ("Вежливо просить о будущем и сравнивать способы общения.",
                  "Make polite future requests and compare ways of communicating."),
            "v": [("Could you...?", "Не могли бы вы...?"), ("as soon as possible", "как можно скорее"),
                  ("to send a reminder", "отправить напоминание"), ("urgent", "срочный"),
                  ("more convenient", "удобнее"), ("to respond", "ответить"),
                  ("attachment", "вложение")],
            "q": ("Which request is the most polite?",
                  "Could you send the report as soon as possible, please?",
                  ["Send the report now.", "You will send the report today."]),
            "tr": ("Не могли бы вы проверить вложение и ответить до конца дня?",
                   "Could you check the attachment and respond before the end of the day?",
                   ["did", "can", "yesterday"]),
            "fill": ("A phone call is ___ convenient than a long email chain.", "more",
                     ["most", "much"], "Телефонный звонок удобнее длинной переписки."),
            "tap": ("Could you send me a reminder about tomorrow's meeting?", ["was", "did"]),
            "sh": ("If the request is urgent, a phone call is faster than an email, but an email is clearer.",
                   "Если просьба срочная, звонок быстрее письма, но письмо понятнее."),
            "st": ("The Urgent Request", [
                ("Client", "Could you send us the updated prices this week?", "Не могли бы вы прислать обновлённые цены на этой неделе?"),
                ("Anna", "Of course. Is Friday soon enough?", "Конечно. Пятницы будет достаточно?"),
                ("What does the client answer?", [
                    ("Friday is fine, but could you also include the delivery costs?", True),
                    ("Yes, you will sent them last Monday.", False),
                    ("The prices are sending themselves.", False)])]),
            "d": ("urgent", "Needing attention very quickly",
                  ["Planned for a later time", "Not important at all"]),
            "lw": ("Could you ___ the attachment, please?", "Could you open the attachment, please?",
                   "open", ["opened", "opening"]),
            "mw": ("Could you reply ___ Friday, please?", "by", "by"),
            "ch": ([("Colleague", "I need those figures for the meeting.")], "You",
                   "Sure. Could you tell me which figures you need exactly?",
                   ["Yes, I will sended them yesterday.", "The figures are meeting me tomorrow."]),
        },
        {
            "t": ("Уточняем правильно", "Clarifying the Right Way"),
            "o": ("Уточнять информацию с should и первым условным.",
                  "Clarify information using should and the first conditional."),
            "v": [("to make sure", "убедиться"), ("to misunderstand", "неправильно понять"),
                  ("exact", "точный"), ("to confirm", "подтвердить"),
                  ("in writing", "в письменном виде"), ("to avoid", "избежать"),
                  ("confusion", "путаница")],
            "q": ("Which sentence gives correct advice?",
                  "You should confirm important requests in writing.",
                  ["You should to confirm the request yesterday.", "You must confirming requests last week."]),
            "tr": ("Если ты не уточнишь детали сейчас, потом возникнет путаница.",
                   "If you do not clarify the details now, there will be confusion later.",
                   ["did", "clarified", "yesterday"]),
            "fill": ("You ___ make sure you have the exact numbers before the call.",
                     "should", ["must to", "shoulds"], "Стоит убедиться, что у тебя точные цифры, перед звонком."),
            "tap": ("You should confirm the time of the meeting in writing.", ["mustn't", "went"]),
            "sh": ("If you repeat the request in your own words, you will avoid many misunderstandings.",
                   "Если ты повторишь просьбу своими словами, ты избежишь многих недопониманий."),
            "st": ("Avoiding Confusion", [
                ("Manager", "The client was not happy yesterday. He misunderstood our offer.",
                 "Клиент был недоволен вчера. Он неправильно понял наше предложение."),
                ("Anna", "What should we do differently next time?", "Что нам делать иначе в следующий раз?"),
                ("What does the manager say?", [
                    ("We should confirm every detail in writing to avoid confusion.", True),
                    ("We must to confirm details yesterday again.", False),
                    ("The confusion is avoiding us next time.", False)])]),
            "d": ("to avoid", "To stop something bad from happening",
                  ["To create a new problem at work", "To answer a question very slowly"]),
            "lw": ("If you ___ the details, you will avoid mistakes.", "If you double-check the details, you will avoid mistakes.",
                   "double-check", ["will double-check", "double-checked"]),
            "mw": ("You should confirm the order ___ writing.", "in", "in"),
            "ch": ([("Colleague", "The client changed the quantity again.")], "You",
                   "You should ask him to confirm the new number by email.",
                   ["You must to ask him yesterday.", "The quantity is confirming the client."]),
        },
    ],

    "A2_WORK_SCHEDULES_SHIFTS_AND_DEADLINES": [
        {
            "t": ("Что изменилось на этой неделе", "What Changed This Week"),
            "o": ("Сообщить об изменениях в графике, используя past simple и present perfect.",
                  "Report schedule changes using past simple and present perfect."),
            "v": [("shift", "смена"), ("deadline", "срок"), ("to move", "перенести"),
                  ("to extend", "продлить"), ("night shift", "ночная смена"),
                  ("to swap", "обменяться (сменами)"), ("schedule", "график")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The deadline has moved to the end of the month.",
                  ["The deadline has moved yesterday.", "The deadline move already to Friday."]),
            "tr": ("Мы перенесли дедлайн на пятницу, и клиент уже подтвердил новую дату.",
                   "We have moved the deadline to Friday, and the client has already confirmed the new date.",
                   ["did", "move", "yesterday"]),
            "fill": ("Last month she worked the ___ shift every week.", "night",
                     ["nights", "nightly"], "В прошлом месяце она каждую неделю работала в ночную смену."),
            "tap": ("He has swapped shifts with a colleague from the morning team.", ["was", "did"]),
            "sh": ("The deadline has changed again, so we have more time than we planned last week.",
                   "Срок снова изменился, поэтому у нас больше времени, чем мы планировали на прошлой неделе."),
            "st": ("The Moved Deadline", [
                ("Tom", "Why is everyone working late today?", "Почему сегодня все работают допоздна?"),
                ("Anna", "The client moved the deadline, and we have only three days left now.",
                 "Клиент перенёс срок, и у нас осталось всего три дня."),
                ("What does Tom ask?", [
                    ("Has the manager approved the new plan?", True),
                    ("Did the manager has approved it yesterday?", False),
                    ("Is the deadline working late too?", False)])]),
            "d": ("deadline", "The time or date by which something must be finished",
                  ["The day when a project starts", "A meeting about next year's plan"]),
            "lw": ("We have ___ the deadline by two days.", "We have extended the deadline by two days.",
                   "extended", ["extend", "extending"]),
            "mw": ("She has worked the night ___ since June.", "shift", "sh"),
            "ch": ([("Colleague", "Are you working the morning shift tomorrow?")], "You",
                   "I was, but I have swapped it for the evening shift.",
                   ["Yes, I work it yesterday.", "The shift is swapping me."]),
        },
        {
            "t": ("График на следующий месяц", "Next Month's Schedule"),
            "o": ("Обсудить будущие смены и сравнить варианты времени.",
                  "Discuss future shifts and compare time options."),
            "v": [("rota", "график смен"), ("early shift", "ранняя смена"),
                  ("later", "позже"), ("to cover", "подменить / закрыть (смену)"),
                  ("overtime", "сверхурочные"), ("flexible hours", "гибкий график"),
                  ("to prefer", "предпочитать")],
            "q": ("Which sentence talks about the future?",
                  "I am going to cover Anna's shift on Saturday.",
                  ["I covered Anna's shift last Saturday.", "I have cover Anna's shift yesterday."]),
            "tr": ("Ранняя смена начинается раньше, но зато я свободен весь вечер.",
                   "The early shift starts earlier, but I am free all evening.",
                   ["did", "starts", "yesterday"]),
            "fill": ("Flexible hours are ___ convenient for parents than fixed shifts.", "more",
                     ["most", "much"], "Гибкий график удобнее для родителей, чем фиксированные смены."),
            "tap": ("We are going to publish the new rota at the end of the week.", ["was", "did"]),
            "sh": ("If you prefer later starts, you should tell the manager before the rota is final.",
                   "Если ты предпочитаешь начинать позже, стоит сказать менеджеру до того, как график станет окончательным."),
            "st": ("Choosing Shifts", [
                ("Manager", "The new rota starts next month. Do you have any preferences?",
                 "Новый график начинается со следующего месяца. Есть предпочтения?"),
                ("Tom", "Yes. Could I work the early shift on Mondays?", "Да. Можно мне раннюю смену по понедельникам?"),
                ("What does the manager answer?", [
                    ("That is fine — Mondays are quieter in the morning.", True),
                    ("Yes, you worked it last month already.", False),
                    ("The early shift is preferring you.", False)])]),
            "d": ("overtime", "Extra working hours beyond your normal schedule",
                  ["A short break during the working day", "A day off that you take every week"]),
            "lw": ("The meeting is going to start ___ than usual.", "The meeting is going to start later than usual.",
                   "later", ["late", "latest"]),
            "mw": ("I am going to ___ the Saturday shift for a colleague.", "cover", "co"),
            "ch": ([("Colleague", "Can you work on Sunday?")], "You",
                   "I'd rather not, but if you find nobody else, I will do it.",
                   ["Yes, I will worked it last Sunday.", "Sunday is working me this week."]),
        },
        {
            "t": ("Если не успеем к сроку", "If We Miss the Deadline"),
            "o": ("Обсудить последствия и обязательства с must и первым условным.",
                  "Discuss consequences and obligations with must and the first conditional."),
            "v": [("on time", "вовремя"), ("to delay", "задержать"),
                  ("to prioritise", "расставить приоритеты"), ("consequence", "последствие"),
                  ("to rush", "спешить (делать наспех)"), ("carefully", "внимательно"),
                  ("as agreed", "как договорились")],
            "q": ("Which sentence expresses a strong obligation?",
                  "We must finish the order as agreed.",
                  ["We must to finish the order yesterday.", "We finishing the order must now."]),
            "tr": ("Если мы не расставим приоритеты сегодня, мы не успеем к сроку.",
                   "If we do not prioritise today, we will not meet the deadline.",
                   ["did", "prioritised", "yesterday"]),
            "fill": ("If we ___ the delivery, the client will complain.", "delay",
                     ["will delay", "delayed"], "Если мы задержим доставку, клиент будет недоволен."),
            "tap": ("We must send the confirmation as agreed in the contract.", ["may", "went"]),
            "sh": ("If we rush the work, we will make more mistakes, so we should plan the time carefully.",
                   "Если мы будем делать работу наспех, мы допустим больше ошибок, поэтому стоит внимательно спланировать время."),
            "st": ("The Risky Week", [
                ("Anna", "We have too many tasks and only one week.", "У нас слишком много задач и всего одна неделя."),
                ("Tom", "What happens if we do not finish everything on time?",
                 "Что будет, если мы не закончим всё вовремя?"),
                ("How does Anna explain the consequence?", [
                    ("If we miss the deadline, the client will choose another supplier.", True),
                    ("If we will miss the deadline, the client chose another supplier.", False),
                    ("The deadline is finishing us instead.", False)])]),
            "d": ("to prioritise", "To decide which tasks are the most important and do them first",
                  ["To do all tasks at the same time", "To stop working when you feel tired"]),
            "lw": ("If we ___ the tasks, we will finish faster.", "If we prioritise the tasks, we will finish faster.",
                   "prioritise", ["will prioritise", "prioritised"]),
            "mw": ("We must finish the report ___ Friday.", "by", "by"),
            "ch": ([("Colleague", "The deadline is on Friday. Are we ready?")], "You",
                   "Almost. If we prioritise the main sections, we will make it.",
                   ["Yes, we are ready yesterday.", "Friday is finishing the report for us."]),
        },
    ],

    "A2_WORK_TASKS_AND_PROGRESS_UPDATES": [
        {
            "t": ("Статус задач", "Task Status"),
            "o": ("Сообщить о прогрессе задач, используя past simple и present perfect.",
                  "Give task progress updates using past simple and present perfect."),
            "v": [("in progress", "в процессе"), ("completed", "завершённый"),
                  ("to update", "обновить / сообщить новости"), ("status", "статус"),
                  ("task list", "список задач"), ("so far", "до сих пор"),
                  ("to finish", "закончить")],
            "q": ("Which sentence reports progress correctly?",
                  "We have completed two tasks and started the third one.",
                  ["We have completed two tasks yesterday.", "We completes two tasks so far already."]),
            "tr": ("Мы закончили дизайн на прошлой неделе, а тестирование уже началось.",
                   "We finished the design last week, and the testing has already started.",
                   ["did", "finish", "yesterday"]),
            "fill": ("I ___ the task list before the meeting yesterday.", "updated",
                     ["have update", "updating"], "Я обновил список задач перед вчерашней встречей."),
            "tap": ("The marketing team has already updated the project status.", ["was", "did"]),
            "sh": ("Here is a quick update: we have finished the first stage, and the second stage is in progress.",
                   "Короткий апдейт: мы закончили первый этап, а второй уже в процессе."),
            "st": ("The Monday Update", [
                ("Manager", "What is the status of the website tasks?", "Как статус задач по сайту?"),
                ("Anna", "The design is completed, and the texts are in progress.",
                 "Дизайн завершён, тексты в процессе."),
                ("What does the manager ask next?", [
                    ("Have you updated the task list in the system?", True),
                    ("Did you has updated it yesterday?", False),
                    ("Is the status updating the tasks itself?", False)])]),
            "d": ("in progress", "Happening now but not finished yet",
                  ["Finished successfully some time ago", "Cancelled by the manager last week"]),
            "lw": ("We have ___ the first task on the list.", "We have completed the first task on the list.",
                   "completed", ["complete", "completing"]),
            "mw": ("The report is ___ progress at the moment.", "in", "in"),
            "ch": ([("Colleague", "Where are we with the presentation?")], "You",
                   "I have finished the slides, and Ben has already checked the numbers.",
                   ["I finished them tomorrow already.", "The slides are presenting us."]),
        },
        {
            "t": ("Что дальше по плану", "What Comes Next"),
            "o": ("Рассказать о следующих задачах и сравнить их приоритет.",
                  "Talk about upcoming tasks and compare their priority."),
            "v": [("next step", "следующий шаг"), ("priority", "приоритет"),
                  ("more important", "важнее"), ("to focus on", "сосредоточиться на"),
                  ("first of all", "прежде всего"), ("to expect", "ожидать"),
                  ("estimate", "оценка (сроков)")],
            "q": ("Which sentence compares priorities correctly?",
                  "Fixing the bug is more important than adding new colours.",
                  ["Fixing the bug is importanter than adding colours.", "Fixing the bug is most important than colours."]),
            "tr": ("На следующей неделе мы сначала сосредоточимся на самых важных задачах.",
                   "Next week we are going to focus on the most important tasks first of all.",
                   ["did", "focused", "yesterday"]),
            "fill": ("This task is ___ important than the weekly report.", "less",
                     ["least", "little"], "Эта задача менее важная, чем еженедельный отчёт."),
            "tap": ("The team is going to focus on quality first of all.", ["was", "did"]),
            "sh": ("If we finish the priority tasks early, we will start the next stage sooner than expected.",
                   "Если мы рано закончим приоритетные задачи, то начнём следующий этап раньше ожидаемого."),
            "st": ("Planning the Sprint", [
                ("Anna", "We have two days left. What is the priority?", "У нас осталось два дня. Что в приоритете?"),
                ("Tom", "The client demo is more important than the internal report.",
                 "Демо для клиента важнее внутреннего отчёта."),
                ("What does Anna decide?", [
                    ("Then we should focus on the demo first of all.", True),
                    ("Then we must to focus on the report yesterday.", False),
                    ("The priority is focusing the team tomorrow.", False)])]),
            "d": ("priority", "Something that is more important and must be done first",
                  ["A task that you can skip every week", "A meeting without an agenda"]),
            "lw": ("We are going to ___ on the main task.", "We are going to focus on the main task.",
                   "focus", ["focused", "focusing"]),
            "mw": ("The demo is ___ important than the slides.", "more", "mo"),
            "ch": ([("Colleague", "What is the next step after testing?")], "You",
                   "We are going to fix the small bugs and then release the update.",
                   ["We fixed them tomorrow already.", "The step is going us next."]),
        },
        {
            "t": ("Если задача буксует", "When a Task Is Stuck"),
            "o": ("Обсудить проблемы с задачами, используя should и первое условное.",
                  "Discuss task problems using should and the first conditional."),
            "v": [("stuck", "застрявший (о задаче)"), ("blocker", "блокер / препятствие"),
                  ("to escalate", "передать вопрос выше"), ("to wait", "ждать"),
                  ("to inform", "проинформировать"), ("as early as possible", "как можно раньше"),
                  ("solution", "решение")],
            "q": ("Which sentence gives correct advice?",
                  "You should tell your manager about the blocker as early as possible.",
                  ["You should to tell the manager yesterday.", "You must telling the manager last week."]),
            "tr": ("Если задача застряла, стоит сообщить об этом как можно раньше.",
                   "If a task is stuck, you should inform your manager as early as possible.",
                   ["did", "stucked", "yesterday"]),
            "fill": ("If you ___ for an answer too long, you will lose a day.",
                     "wait", ["will wait", "waited"], "Если будешь слишком долго ждать ответа, потеряешь день."),
            "tap": ("You should escalate the problem if there is no solution.", ["mustn't", "went"]),
            "sh": ("If we do not find a solution today, we will ask the senior engineer for help tomorrow.",
                   "Если мы не найдём решение сегодня, завтра попросим помощи у старшего инженера."),
            "st": ("The Blocker", [
                ("Tom", "The integration task has been stuck since Tuesday.", "Задача по интеграции застряла со вторника."),
                ("Anna", "What is blocking it?", "Что её блокирует?"),
                ("What does Tom explain?", [
                    ("If the other team does not reply, we will escalate it.", True),
                    ("If the team will not reply, we escalated it yesterday.", False),
                    ("The blocker is tasking the team.", False)])]),
            "d": ("to escalate", "To pass a problem to a more senior person",
                  ["To solve a problem completely alone", "To forget about a problem for a week"]),
            "lw": ("If the task ___ stuck, ask for help.", "If the task gets stuck, ask for help.",
                   "gets", ["will get", "got"]),
            "mw": ("You should inform the team ___ early as possible.", "as", "as"),
            "ch": ([("Colleague", "I have been waiting for the data for two days.")], "You",
                   "You should escalate it — if you wait longer, we will miss the deadline.",
                   ["You must to wait more yesterday.", "The data is waiting for you."]),
        },
    ],

    "A2_WORK_WORKDAY_ROUTINES_AND_PRIORITIES": [
        {
            "t": ("Мой обычный рабочий день", "My Usual Workday"),
            "o": ("Описать рабочий день и изменения в нём, используя past simple и present perfect.",
                  "Describe a workday and its changes using past simple and present perfect."),
            "v": [("routine", "порядок дня"), ("to plan the day", "планировать день"),
                  ("most important task", "самая важная задача"), ("before lunch", "до обеда"),
                  ("to check emails", "проверить почту"), ("focus time", "время для концентрации"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have checked my emails twice so far today.",
                  ["I have checked my emails yesterday twice.", "I check my emails already so far."]),
            "tr": ("Раньше я проверял почту первым делом, но теперь я начинаю с самой важной задачи.",
                   "I used to check my emails first, but now I have started with the most important task.",
                   ["did", "use", "yesterday"]),
            "fill": ("Last year my working day ___ at eight o'clock.", "started",
                     ["has start", "starting"], "В прошлом году мой рабочий день начинался в восемь."),
            "tap": ("This morning I have already planned the whole day.", ["was", "did"]),
            "sh": ("I have already answered the most important emails, and it is only ten o'clock.",
                   "Я уже ответил на самые важные письма, а сейчас только десять часов."),
            "st": ("A New Routine", [
                ("Anna", "You look much more organised this month. What has changed?",
                 "Ты выглядишь гораздо организованнее в этом месяце. Что изменилось?"),
                ("Tom", "I have started to plan my day the evening before.",
                 "Я начал планировать день накануне вечером."),
                ("What does Anna ask?", [
                    ("And what do you do first in the morning now?", True),
                    ("And what did you did first tomorrow?", False),
                    ("Is the routine planning you now?", False)])]),
            "d": ("routine", "Things you regularly do in the same order",
                  ["Something you do only once a year", "A surprise meeting without a plan"]),
            "lw": ("I have ___ my day before lunch today.", "I have planned my day before lunch today.",
                   "planned", ["plan", "planning"]),
            "mw": ("She has answered ten emails ___ far.", "so", "so"),
            "ch": ([("Colleague", "When do you check your emails?")], "You",
                   "I used to check them all morning, but now I do it twice a day.",
                   ["Yes, I check them yesterday.", "The emails are checking me."]),
        },
        {
            "t": ("Завтра по плану", "Tomorrow's Plan"),
            "o": ("Рассказать о планах на день и сравнить задачи по важности.",
                  "Talk about tomorrow's plans and compare tasks by importance."),
            "v": [("first thing", "первым делом"), ("to-do list", "список дел"),
                  ("urgent task", "срочная задача"), ("later", "позже"),
                  ("as early as possible", "как можно раньше"), ("to schedule", "запланировать"),
                  ("quieter", "тише (спокойнее)")],
            "q": ("Which sentence talks about tomorrow's plan?",
                  "I am going to write the report first thing tomorrow.",
                  ["I wrote the report first thing yesterday.", "I have write the report first thing already."]),
            "tr": ("Завтра я собираюсь прийти пораньше, потому что утром в офисе тише.",
                   "I am going to arrive earlier tomorrow because the office is quieter in the morning.",
                   ["did", "arrives", "yesterday"]),
            "fill": ("The morning is ___ for focused work than the afternoon.", "better",
                     ["best", "more good"], "Утро лучше подходит для концентрированной работы, чем день."),
            "tap": ("I am going to schedule all my meetings for the afternoon.", ["was", "did"]),
            "sh": ("If I finish the urgent task in the morning, I will have a quieter afternoon tomorrow.",
                   "Если я закончу срочную задачу утром, завтра во второй половине дня будет спокойнее."),
            "st": ("The Evening Plan", [
                ("Tom", "What are you going to do first thing tomorrow?", "Что ты сделаешь первым делом завтра?"),
                ("Anna", "The quarterly report — it is more urgent than the emails.",
                 "Квартальный отчёт — он срочнее почты."),
                ("What does Tom advise?", [
                    ("Good idea — you should schedule it before lunch.", True),
                    ("You must to schedule it yesterday evening.", False),
                    ("The report is going you first tomorrow.", False)])]),
            "d": ("to-do list", "A list of tasks that you need to do",
                  ["A list of people invited to a party", "A report about finished work only"]),
            "lw": ("I am going to write the to-do ___ this evening.", "I am going to write the to-do list this evening.",
                   "list", ["listed", "listing"]),
            "mw": ("The urgent task is ___ important than the rest.", "more", "mo"),
            "ch": ([("Colleague", "Are you free for a call tomorrow at eight?")], "You",
                   "Eight is a bit early — could we schedule it after ten instead?",
                   ["Yes, I called you tomorrow already.", "The call is scheduling me at eight."]),
        },
        {
            "t": ("Как правильно расставить приоритеты", "How to Prioritise Well"),
            "o": ("Дать советы о приоритетах, используя should и первое условное.",
                  "Give prioritisation advice using should and the first conditional."),
            "v": [("to manage time", "управлять временем"), ("distraction", "отвлекающий фактор"),
                  ("to turn off notifications", "выключить уведомления"),
                  ("one task at a time", "одна задача за раз"), ("to be worth", "стоить того"),
                  ("regularly", "регулярно"), ("habit", "привычка")],
            "q": ("Which sentence gives correct advice?",
                  "You should turn off notifications when you do focused work.",
                  ["You should to turn off notifications yesterday.", "You must turning off notifications last week."]),
            "tr": ("Если ты будешь делать одну задачу за раз, ты закончишь работу быстрее.",
                   "If you do one task at a time, you will finish your work faster.",
                   ["did", "does", "yesterday"]),
            "fill": ("If a distraction ___ you every five minutes, you will lose your focus.",
                     "interrupts", ["will interrupt", "interrupted"],
                     "Если отвлекающий фактор мешает тебе каждые пять минут, ты потеряешь концентрацию."),
            "tap": ("You should check your emails at fixed times of the day.", ["mustn't", "went"]),
            "sh": ("If you plan your day regularly, prioritising will become a habit very quickly.",
                   "Если ты будешь регулярно планировать день, расстановка приоритетов быстро станет привычкой."),
            "st": ("Time Management Tips", [
                ("Anna", "I never finish my to-do list. What should I do?",
                 "Я никогда не заканчиваю список дел. Что мне делать?"),
                ("Tom", "How many tasks do you put on it?", "Сколько задач ты в него записываешь?"),
                ("What does Anna say?", [
                    ("About fifteen — maybe that is too many.", True),
                    ("About fifteen, and I finished them all yesterday.", False),
                    ("The list is doing itself the tasks.", False)])]),
            "d": ("distraction", "Something that takes your attention away from work",
                  ["A quiet room where nobody interrupts you", "A short break between two meetings"]),
            "lw": ("If you ___ notifications, you will focus better.", "If you turn off notifications, you will focus better.",
                   "turn off", ["will turn off", "turned off"]),
            "mw": ("You should do ___ task at a time.", "one", "on"),
            "ch": ([("Colleague", "I start many tasks but finish few.")], "You",
                   "You should try one task at a time — it is worth building the habit.",
                   ["You must to try it yesterday.", "The tasks are starting you."]),
        },
    ],

    "A2_WORK_WORKPLACE_CONVERSATIONS": [
        {
            "t": ("Разговоры у кулера", "Conversations by the Coffee Machine"),
            "o": ("Обменяться новостями с коллегами, используя past simple и present perfect.",
                  "Exchange news with colleagues using past simple and present perfect."),
            "v": [("small talk", "светская беседа"), ("news", "новости"),
                  ("to hear about", "услышать о"), ("to move offices", "переехать в другой офис"),
                  ("to congratulate", "поздравить"), ("team", "команда"),
                  ("lately", "в последнее время")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "Have you heard about the new project lately?",
                  ["Did you have heard about it yesterday?", "Have you hearing about it last week?"]),
            "tr": ("Я слышал, что отдел маркетинга переехал на третий этаж на прошлой неделе.",
                   "I heard that the marketing team moved to the third floor last week.",
                   ["did", "hears", "tomorrow"]),
            "fill": ("She ___ her colleague on the promotion this morning.", "congratulated",
                     ["has congratulate", "congratulating"], "Она поздравила коллегу с повышением сегодня утром."),
            "tap": ("Our team has grown a lot lately.", ["was", "did"]),
            "sh": ("Have you spoken to Daniel lately? He has moved to the Berlin office.",
                   "Ты в последнее время разговаривал с Даниэлем? Он переехал в берлинский офис."),
            "st": ("Good News", [
                ("Ben", "Have you heard the news? Anna has joined our project team!",
                 "Слышал новость? Аня вошла в нашу проектную команду!"),
                ("Maya", "That's great! When did she start?", "Здорово! Когда она начала?"),
                ("What does Ben answer?", [
                    ("Last Monday, and she has already shared some good ideas.", True),
                    ("Tomorrow, and she shared ideas yesterday.", False),
                    ("The project team has start her.", False)])]),
            "d": ("to congratulate", "To tell someone you are happy about their success",
                  ["To tell someone about a problem", "To ask someone to leave the room"]),
            "lw": ("Have you ___ about the reorganisation?", "Have you heard about the reorganisation?",
                   "heard", ["hear", "hearing"]),
            "mw": ("We have moved to the new office ___ March.", "since", "si"),
            "ch": ([("Colleague", "Did you hear about the new office?")], "You",
                   "Yes, I heard about it last week. Have you seen the plans yet?",
                   ["Yes, I have hear it yesterday.", "The office is hearing us."]),
        },
        {
            "t": ("Договариваемся о встрече", "Arranging to Meet"),
            "o": ("Договориться о встрече, используя формы будущего и сравнения.",
                  "Arrange a meeting using future forms and comparatives."),
            "v": [("to arrange", "договориться (о встрече)"), ("to suit", "подходить (о времени)"),
                  ("instead", "вместо этого"), ("to postpone", "перенести"),
                  ("video call", "видеозвонок"), ("in person", "лично"),
                  ("easier", "проще")],
            "q": ("Which sentence uses the present continuous for a future arrangement?",
                  "We are meeting the client at three o'clock tomorrow.",
                  ["We meet the client at three yesterday.", "We has met the client at three tomorrow."]),
            "tr": ("Завтра в десять мы обсуждаем бюджет — лично это проще, чем по видеосвязи.",
                   "We are discussing the budget at ten tomorrow — in person is easier than a video call.",
                   ["did", "discuss", "yesterday"]),
            "fill": ("A short video call is ___ than a long email thread.", "quicker",
                     ["quickest", "more quick"], "Короткий видеозвонок быстрее длинной переписки."),
            "tap": ("I am meeting the suppliers on Thursday morning.", ["was", "did"]),
            "sh": ("I am going to postpone our call because the client is visiting us at the same time.",
                   "Я перенесу наш звонок, потому что клиент приедет к нам в то же время."),
            "st": ("Rescheduling", [
                ("Anna", "I'm afraid I can't meet on Thursday. Could we meet on Friday instead?",
                 "Боюсь, не смогу в четверг. Можем встретиться в пятницу?"),
                ("Tom", "Friday morning is busy, but the afternoon is free.", "Утро пятницы занято, но вторая половина свободна."),
                ("What does Anna suggest?", [
                    ("Then we are meeting at two o'clock on Friday.", True),
                    ("Then we met at two yesterday.", False),
                    ("Friday is meeting us instead.", False)])]),
            "d": ("to postpone", "To move an event to a later time",
                  ["To cancel an event completely", "To start a meeting earlier than planned"]),
            "lw": ("We are ___ the client at three.", "We are meeting the client at three.",
                   "meeting", ["meet", "met"]),
            "mw": ("A video call is ___ than travelling.", "cheaper", "ch"),
            "ch": ([("Colleague", "Does Monday at ten suit you?")], "You",
                   "Monday suits me fine — I am seeing the dentist in the afternoon.",
                   ["Yes, I suited it yesterday.", "Monday is suiting the dentist."]),
        },
        {
            "t": ("Если возникнет недопонимание", "If There Is a Misunderstanding"),
            "o": ("Обсудить недопонимания, используя should и первое условное.",
                  "Discuss misunderstandings using should and the first conditional."),
            "v": [("misunderstanding", "недопонимание"), ("to apologise", "извиниться"),
                  ("to listen carefully", "внимательно слушать"), ("to interrupt", "перебивать"),
                  ("tone", "тон"), ("directly", "прямо"), ("to sort out", "уладить")],
            "q": ("Which sentence gives correct advice?",
                  "You should listen carefully before you answer.",
                  ["You should to listen carefully yesterday.", "You must listening carefully last week."]),
            "tr": ("Если возникнет недопонимание, лучше обсудить его напрямую и спокойно.",
                   "If there is a misunderstanding, you should discuss it directly and calmly.",
                   ["did", "was", "yesterday"]),
            "fill": ("If you ___ people all the time, they will stop listening to you.",
                     "interrupt", ["will interrupt", "interrupted"], "Если ты всё время перебиваешь, тебя перестанут слушать."),
            "tap": ("You should apologise if the tone of your email sounded rude.", ["mustn't", "went"]),
            "sh": ("If you explain the problem calmly, you will sort it out quickly and keep a good relationship.",
                   "Если ты спокойно объяснишь проблему, то быстро уладишь её и сохранишь хорошие отношения."),
            "st": ("After the Argument", [
                ("Manager", "I heard raised voices in the meeting room. What happened?",
                 "Я слышал повышенные голоса в переговорке. Что случилось?"),
                ("Tom", "We had a misunderstanding about the budget numbers.",
                 "У нас было недопонимание по цифрам бюджета."),
                ("What should Tom do next?", [
                    ("I should apologise and explain the numbers calmly.", True),
                    ("I must to apologise yesterday afternoon.", False),
                    ("The numbers are apologising for me.", False)])]),
            "d": ("to interrupt", "To start speaking while someone else is speaking",
                  ["To wait quietly until someone finishes", "To write down what someone says"]),
            "lw": ("If you ___ to both sides, you will understand the problem.",
                   "If you listen to both sides, you will understand the problem.", "listen", ["will listen", "listened"]),
            "mw": ("You should sort out the problem ___ soon as possible.", "as", "as"),
            "ch": ([("Colleague", "I think Maya misunderstood my email.")], "You",
                   "You should speak to her directly — if you wait, it will get worse.",
                   ["You must to speak yesterday.", "The email is misunderstanding her."]),
        },
    ],

    "A2_WORK_WORKPLACE_PROBLEMS_AND_SOLUTIONS": [
        {
            "t": ("Что пошло не так", "What Went Wrong"),
            "o": ("Описать рабочую проблему, используя past simple и present perfect.",
                  "Describe a workplace problem using past simple and present perfect."),
            "v": [("to go wrong", "пойти не так"), ("to complain", "жаловаться"),
                  ("to lose data", "потерять данные"), ("to fix", "починить"),
                  ("issue", "проблема / вопрос"), ("twice", "дважды"),
                  ("to contact support", "обратиться в поддержку")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The system has crashed twice this week.",
                  ["The system has crashed yesterday twice.", "The system crash twice already this week."]),
            "tr": ("Сервер упал вчера утром, и мы потеряли два часа работы.",
                   "The server crashed yesterday morning, and we have lost two hours of work.",
                   ["did", "crashes", "tomorrow"]),
            "fill": ("The client ___ about the delay last Tuesday.", "complained",
                     ["has complain", "complaining"], "Клиент пожаловался на задержку в прошлый вторник."),
            "tap": ("We have already contacted support about this issue.", ["was", "did"]),
            "sh": ("The payment system went down this morning, and three customers have already called to complain.",
                   "Платёжная система упала сегодня утром, и три клиента уже позвонили с жалобами."),
            "st": ("The System Crash", [
                ("Anna", "Why is everyone standing near the coffee machine?", "Почему все стоят у кофемашины?"),
                ("Tom", "The order system went down an hour ago.", "Система заказов упала час назад."),
                ("What does Anna ask?", [
                    ("Has anyone contacted support yet?", True),
                    ("Did anyone has contacted them yesterday?", False),
                    ("Is the system drinking coffee too?", False)])]),
            "d": ("to complain", "To say that you are not happy about something",
                  ["To say thank you for good service", "To ask a question about prices"]),
            "lw": ("We have ___ support twice today.", "We have contacted support twice today.",
                   "contacted", ["contact", "contacting"]),
            "mw": ("The issue has ___ worse since Monday.", "got", "go"),
            "ch": ([("Colleague", "The printer is broken again.")], "You",
                   "I know — it has already broken down twice this month.",
                   ["Yes, it broke tomorrow morning.", "The printer is fixing itself."]),
        },
        {
            "t": ("Как мы это решим", "How We Will Solve It"),
            "o": ("Предложить решения и сравнить варианты.",
                  "Offer solutions and compare options."),
            "v": [("solution", "решение"), ("backup", "резервная копия"),
                  ("temporary", "временный"), ("to test", "протестировать"),
                  ("more efficient", "эффективнее"), ("to implement", "внедрить"),
                  ("step by step", "шаг за шагом")],
            "q": ("Which sentence compares two solutions correctly?",
                  "The new process is more efficient than the old one.",
                  ["The new process is efficienter than the old one.", "The new process is most efficient than old."]),
            "tr": ("Мы собираемся внедрить временное решение, а потом протестировать его шаг за шагом.",
                   "We are going to implement a temporary solution and then test it step by step.",
                   ["did", "implemented", "yesterday"]),
            "fill": ("A backup process is ___ than having no process at all.", "better",
                     ["best", "more good"], "Резервный процесс лучше, чем его отсутствие."),
            "tap": ("The team is going to test the solution tomorrow morning.", ["was", "did"]),
            "sh": ("If we implement the backup system now, the next crash will cause fewer problems.",
                   "Если мы внедрим резервную систему сейчас, следующий сбой вызовет меньше проблем."),
            "st": ("Two Options", [
                ("Manager", "We have two options: a quick temporary fix or a full system update.",
                 "У нас два варианта: быстрый временный фикс или полное обновление системы."),
                ("Anna", "The temporary fix is faster, but the update is more reliable.",
                 "Временный фикс быстрее, но обновление надёжнее."),
                ("What does the manager decide?", [
                    ("We are going to do the fix now and the update next month.", True),
                    ("We did the fix yesterday and the update tomorrow.", False),
                    ("The options are deciding about us.", False)])]),
            "d": ("backup", "A copy of information that you keep in case of a problem",
                  ["A meeting about future plans", "A person who repairs computers every day"]),
            "lw": ("We are going to ___ the new process.", "We are going to test the new process.",
                   "test", ["tested", "testing"]),
            "mw": ("The temporary solution is ___ reliable.", "less", "le"),
            "ch": ([("Colleague", "Which solution should we choose?")], "You",
                   "The second one — it is more expensive but much more reliable.",
                   ["We chose it yesterday tomorrow.", "The solution is choosing us."]),
        },
        {
            "t": ("Чтобы проблема не повторилась", "Stopping the Problem From Repeating"),
            "o": ("Предложить меры профилактики, используя should и первое условное.",
                  "Suggest preventive measures using should and the first conditional."),
            "v": [("to prevent", "предотвратить"), ("root cause", "первопричина"),
                  ("to repeat", "повториться"), ("checklist", "контрольный список"),
                  ("to train", "обучить"), ("regularly", "регулярно"),
                  ("to document", "задокументировать")],
            "q": ("Which sentence gives correct advice?",
                  "We should find the root cause before we change anything.",
                  ["We should to find the root cause yesterday.", "We must finding the cause last week."]),
            "tr": ("Если мы задокументируем проблему сейчас, то сможем предотвратить её повторение.",
                   "If we document the problem now, we will be able to prevent it from repeating.",
                   ["did", "documented", "yesterday"]),
            "fill": ("If staff ___ the checklist, mistakes will happen less often.",
                     "follow", ["will follow", "followed"], "Если сотрудники будут следовать чек-листу, ошибок станет меньше."),
            "tap": ("You should document every step of the process.", ["mustn't", "went"]),
            "sh": ("If we train the team regularly, the same problem will not repeat next quarter.",
                   "Если мы будем регулярно обучать команду, та же проблема не повторится в следующем квартале."),
            "st": ("Prevention", [
                ("Tom", "The same issue has repeated three times this month.", "Эта проблема повторилась трижды за месяц."),
                ("Anna", "Then we should look for the root cause.", "Тогда стоит искать первопричину."),
                ("What does Tom suggest?", [
                    ("If we document the steps, we will find the cause faster.", True),
                    ("If we will document the steps, we found it yesterday.", False),
                    ("The root cause is documenting us.", False)])]),
            "d": ("checklist", "A list of steps to check so you do not forget anything",
                  ["A list of employees on holiday", "A letter from a client about a problem"]),
            "lw": ("If we ___ the team, the problem will not repeat.", "If we train the team, the problem will not repeat.",
                   "train", ["will train", "trained"]),
            "mw": ("We should prevent it ___ happening again.", "from", "fr"),
            "ch": ([("Colleague", "The same mistake happened again today.")], "You",
                   "We should create a checklist — if we follow it, the mistake will not repeat.",
                   ["We must to create it yesterday.", "The mistake is creating checklists."]),
        },
    ],
}
