#!/usr/bin/env python3
"""A2 regenerated content: BUSINESS ENGLISH (10 tracks x 3 lessons).

Grammar arc per topic: L1 past simple + present perfect,
L2 future forms + comparatives, L3 modals / first conditional.
"""

TRACKS = {
    "A2_BUSINESS_ENGLISH_APPOINTMENTS_SCHEDULES_AND_CHANGES": [
        {
            "t": ("Переносим встречу", "Moving a Meeting"),
            "o": ("Сообщить об изменениях во встречах, используя past simple и present perfect.",
                  "Report changes to appointments using past simple and present perfect."),
            "v": [("appointment", "встреча / договорённость"), ("to reschedule", "перенести (на другое время)"),
                  ("available", "свободный (о времени)"), ("calendar", "календарь"),
                  ("to cancel", "отменить"), ("confirmation", "подтверждение"),
                  ("in advance", "заранее")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The client has rescheduled the appointment twice this week.",
                  ["The client has reschedule it yesterday.", "The client reschedule it already twice."]),
            "tr": ("Клиент перенёс встречу на четверг, и мы уже подтвердили новое время.",
                   "The client has moved the appointment to Thursday, and we have already confirmed the new time.",
                   ["did", "move", "yesterday"]),
            "fill": ("She ___ the Monday meeting because of the flight delay.", "cancelled",
                     ["has cancel", "cancelling"], "Она отменила понедельничную встречу из-за задержки рейса."),
            "tap": ("I have updated the calendar with the new appointment time.", ["was", "did"]),
            "sh": ("The Tuesday appointment has been cancelled, so I have offered two new slots instead.",
                   "Встреча во вторник отменена, поэтому я предложил два новых времени."),
            "st": ("The Full Calendar", [
                ("Assistant", "Mr Weber has moved his appointment to Friday at eleven.",
                 "Господин Вебер перенёс встречу на пятницу на одиннадцать."),
                ("Anna", "That's fine. Have you sent him the confirmation yet?",
                 "Хорошо. Ты уже отправил ему подтверждение?"),
                ("What does the assistant answer?", [
                    ("Yes, I sent it an hour ago and he has already replied.", True),
                    ("Yes, I have send it tomorrow morning.", False),
                    ("The confirmation is sending itself.", False)])]),
            "d": ("to reschedule", "To change a planned time to another time",
                  ["To finish a meeting earlier than planned", "To arrive at a meeting very early"]),
            "lw": ("I have ___ the call to three o'clock.", "I have moved the call to three o'clock.",
                   "moved", ["move", "moving"]),
            "mw": ("We have received the ___ for Friday.", "confirmation", "co"),
            "ch": ([("Colleague", "Has the client confirmed the new time?")], "You",
                   "Yes, he confirmed it this morning and has added it to his calendar.",
                   ["Yes, he confirm it yesterday now.", "The time is confirming the client."]),
        },
        {
            "t": ("Планируем встречи на месяц", "Planning Meetings for the Month"),
            "o": ("Договориться о будущих встречах и сравнить варианты времени.",
                  "Arrange future meetings and compare time options."),
            "v": [("slot", "окно в расписании"), ("to book", "забронировать"),
                  ("earlier", "раньше"), ("conflict", "конфликт (в расписании)"),
                  ("agenda", "повестка дня"), ("to offer", "предложить"),
                  ("convenient", "удобный")],
            "q": ("Which sentence talks about a future arrangement?",
                  "We are meeting the suppliers on Tuesday at ten.",
                  ["We met the suppliers on Tuesday at ten.", "We has meet them tomorrow already."]),
            "tr": ("Я собираюсь забронировать зал на два часа, потому что он больше, чем переговорка.",
                   "I am going to book the main room for two hours because it is bigger than the small one.",
                   ["did", "booked", "yesterday"]),
            "fill": ("The morning slots are ___ popular than the afternoon ones.", "more",
                     ["most", "much"], "Утренние окна пользуются большей популярностью, чем дневные."),
            "tap": ("We are going to send the agenda a day before the meeting.", ["was", "did"]),
            "sh": ("If you send me two convenient slots, I will book the room and invite the team.",
                   "Если пришлёте два удобных времени, я забронирую зал и приглашу команду."),
            "st": ("Finding a Slot", [
                ("Client", "Could we meet next week to discuss the contract?", "Можем встретиться на следующей неделе обсудить контракт?"),
                ("Anna", "Of course. Tuesday at ten or Thursday at two — which is more convenient?",
                 "Конечно. Вторник в десять или четверг в два — что удобнее?"),
                ("What does the client choose?", [
                    ("Thursday is better for me because I am travelling on Tuesday.", True),
                    ("Thursday was better yesterday when I travel.", False),
                    ("The contract is meeting me on Tuesday.", False)])]),
            "d": ("agenda", "A list of topics for a meeting",
                  ["A room where people have meetings", "A document that confirms a booking"]),
            "lw": ("I am going to ___ the conference room.", "I am going to book the conference room.",
                   "book", ["booked", "booking"]),
            "mw": ("The afternoon slot is ___ convenient for the client.", "less", "le"),
            "ch": ([("Colleague", "When should we send the agenda?")], "You",
                   "We are going to send it tomorrow — a day before the meeting.",
                   ["We sent it yesterday tomorrow.", "The agenda is sending us."]),
        },
        {
            "t": ("Если планы меняются", "When Plans Change"),
            "o": ("Объяснить изменения планов, используя should и первое условное.",
                  "Explain changing plans using should and the first conditional."),
            "v": [("to inform", "известить"), ("as soon as", "как только"),
                  ("change", "изменение"), ("to avoid confusion", "избежать путаницы"),
                  ("polite", "вежливый"), ("to appreciate", "быть благодарным"),
                  ("flexible", "гибкий")],
            "q": ("Which sentence gives correct advice?",
                  "You should inform everyone as soon as plans change.",
                  ["You should to inform everyone yesterday.", "You must informing everyone last week."]),
            "tr": ("Если встреча изменится, сообщите всем участникам как можно скорее.",
                   "If the appointment changes, you should inform all the participants as soon as possible.",
                   ["did", "changed", "yesterday"]),
            "fill": ("If you ___ the time in two places, people will miss the update.",
                     "change", ["will change", "changed"], "Если поменять время только в двух местах, люди пропустят обновление."),
            "tap": ("You should be flexible when clients change their plans.", ["mustn't", "went"]),
            "sh": ("If a client cancels, you should offer a new slot politely — they will appreciate it.",
                   "Если клиент отменяет встречу, стоит вежливо предложить новое время — это оценят."),
            "st": ("The Late Change", [
                ("Tom", "The client has just cancelled tomorrow's call.", "Клиент только что отменил завтрашний звонок."),
                ("Anna", "Have you told the whole team yet?", "Ты уже сказал всей команде?"),
                ("What does Tom say?", [
                    ("No, but I should inform them now to avoid confusion.", True),
                    ("No, I must informing them yesterday.", False),
                    ("The cancellation is telling the team.", False)])]),
            "d": ("flexible", "Able to change plans easily when it is necessary",
                  ["Doing everything exactly as planned every time", "Refusing all changes to a schedule"]),
            "lw": ("If the client ___, we will offer a new slot.", "If the client cancels, we will offer a new slot.",
                   "cancels", ["will cancel", "cancelled"]),
            "mw": ("You should inform the team as ___ as possible.", "soon", "so"),
            "ch": ([("Colleague", "The supplier wants to move Friday's call.")], "You",
                   "That's fine — if he sends two new slots, I will inform everyone today.",
                   ["He moved it yesterday tomorrow.", "Friday is moving the supplier."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_BUSINESS_CALLS_AND_MESSAGES": [
        {
            "t": ("Звонки на этой неделе", "Calls This Week"),
            "o": ("Рассказать о звонках и сообщениях, используя past simple и present perfect.",
                  "Talk about calls and messages using past simple and present perfect."),
            "v": [("to call back", "перезвонить"), ("voicemail", "голосовая почта"),
                  ("to leave a message", "оставить сообщение"), ("line", "линия"),
                  ("to reach", "дозвониться до"), ("missed call", "пропущенный звонок"),
                  ("twice", "дважды")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have left two voicemails since this morning.",
                  ["I have left a voicemail yesterday.", "I left two voicemails already since morning."]),
            "tr": ("Я позвонил ему в десять, но не дозвонился и оставил сообщение.",
                   "I called him at ten, but I did not reach him and left a message instead.",
                   ["did", "call", "tomorrow"]),
            "fill": ("She ___ me back within an hour yesterday.", "called",
                     ["has call", "calling"], "Она перезвонила мне в течение часа вчера."),
            "tap": ("He has already returned three missed calls this morning.", ["was", "did"]),
            "sh": ("I have called the office twice today, but the line has been busy both times.",
                   "Я звонил в офис дважды сегодня, но линия оба раза была занята."),
            "st": ("The Missed Call", [
                ("Anna", "You have three missed calls from the same number.", "У тебя три пропущенных с одного номера."),
                ("Tom", "Really? When did they call?", "Серьёзно? Когда звонили?"),
                ("What does Anna say?", [
                    ("Twice this morning and once after lunch — you should call back soon.", True),
                    ("Yesterday twice, and they has called again tomorrow.", False),
                    ("The number is calling the missed calls.", False)])]),
            "d": ("voicemail", "A recorded message you leave when someone does not answer",
                  ["A written message you send by email", "A meeting room booking system"]),
            "lw": ("Could you ask him to ___ me back?", "Could you ask him to call me back?",
                   "call", ["called", "calling"]),
            "mw": ("I have left a message ___ his voicemail.", "on", "on"),
            "ch": ([("Colleague", "Did you get my voicemail?")], "You",
                   "Yes, I listened to it this morning and have already replied by email.",
                   ["Yes, I listen it tomorrow.", "The voicemail is replying to me."]),
        },
        {
            "t": ("Важный звонок завтра", "An Important Call Tomorrow"),
            "o": ("Подготовиться к будущим звонкам и сравнить способы связи.",
                  "Prepare for future calls and compare ways of contacting people."),
            "v": [("conference call", "конференц-звонок"), ("to dial in", "подключиться к звонку"),
                  ("clearly", "чётко / ясно"), ("to take notes", "делать записи"),
                  ("in advance", "заранее"), ("more useful", "полезнее"),
                  ("to prepare questions", "подготовить вопросы")],
            "q": ("Which sentence talks about tomorrow?",
                  "We are going to have a conference call with the Berlin office.",
                  ["We had a conference call with Berlin yesterday.", "We has a call tomorrow already."]),
            "tr": ("Завтра у нас конференц-звонок, поэтому я подготовлю вопросы заранее.",
                   "We are having a conference call tomorrow, so I am going to prepare the questions in advance.",
                   ["did", "had", "yesterday"]),
            "fill": ("A short agenda is ___ useful than a long silence.", "more",
                     ["most", "much"], "Короткая повестка полезнее долгого молчания."),
            "tap": ("I am going to take notes during the call and send them after.", ["was", "did"]),
            "sh": ("If you dial in five minutes early, you will have time to test your microphone.",
                   "Если подключишься на пять минут раньше, успеешь проверить микрофон."),
            "st": ("Before the Call", [
                ("Manager", "The client call starts at nine tomorrow. Are you ready?",
                 "Звонок с клиентом завтра в девять. Ты готов?"),
                ("Anna", "Almost. I have prepared the questions but not the slides.",
                 "Почти. Я подготовил вопросы, но не слайды."),
                ("What does the manager advise?", [
                    ("You should finish the slides tonight — they matter more.", True),
                    ("You must finishing them yesterday evening.", False),
                    ("The slides are preparing you tonight.", False)])]),
            "d": ("to dial in", "To join a phone or video call by entering a code",
                  ["To hang up at the end of a conversation", "To write down a phone number on paper"]),
            "lw": ("We are ___ the supplier at ten.", "We are calling the supplier at ten.",
                   "calling", ["call", "called"]),
            "mw": ("You should prepare ___ in advance.", "questions", "qu"),
            "ch": ([("Colleague", "Should I join the call with the client?")], "You",
                   "Yes, dial in at nine — if you take notes, the summary will be ready by noon.",
                   ["I dialled in yesterday tomorrow.", "The call is joining me."]),
        },
        {
            "t": ("Правила хороших звонков", "Rules for Good Calls"),
            "o": ("Дать советы о деловых звонках, используя should и первое условное.",
                  "Give advice about business calls using should and the first conditional."),
            "v": [("to disturb", "беспокоить"), ("brief", "краткий"),
                  ("to summarise", "подытожить"), ("at the end", "в конце"),
                  ("to confirm", "подтвердить"), ("polite", "вежливый"),
                  ("to hang up", "положить трубку")],
            "q": ("Which sentence gives correct advice about calls?",
                  "You should summarise the main points at the end of the call.",
                  ["You should to summarise the points yesterday.", "You must summarising the call last week."]),
            "tr": ("Если ты подытожишь договорённости в конце, вы избежите недопонимания.",
                   "If you summarise the agreements at the end, you will avoid misunderstandings.",
                   ["did", "summarised", "yesterday"]),
            "fill": ("If you speak too fast, the client ___ understand you.", "will not",
                     ["not will", "don't"], "Если говорить слишком быстро, клиент вас не поймёт."),
            "tap": ("You should confirm the next steps before you hang up.", ["mustn't", "went"]),
            "sh": ("If the client sounds busy, you should keep the call brief and offer to email the details.",
                   "Если клиент звучит занятым, стоит говорить кратко и предложить прислать детали письмом."),
            "st": ("After the Call", [
                ("Anna", "The call went well, but did we confirm who sends the offer?",
                 "Звонок прошёл хорошо, но мы подтвердили, кто отправляет предложение?"),
                ("Tom", "I'm not sure — we talked about so many things.", "Не уверен — мы обсудили столько всего."),
                ("What should they do?", [
                    ("You should send a short summary email to confirm.", True),
                    ("You must sending it yesterday afternoon.", False),
                    ("The offer is confirming itself by email.", False)])]),
            "d": ("brief", "Short and using few words",
                  ["Very long and detailed", "Loud and difficult to hear"]),
            "lw": ("If you ___ the steps in writing, nothing will be lost.",
                   "If you confirm the steps in writing, nothing will be lost.", "confirm", ["will confirm", "confirmed"]),
            "mw": ("You should summarise the call ___ the end.", "at", "at"),
            "ch": ([("Colleague", "The client asked so many questions on the call.")], "You",
                   "You should send a brief follow-up email — if you write the answers down, they will trust us more.",
                   ["I sent it yesterday tomorrow.", "The questions are emailing the client."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_COMPANIES_DEPARTMENTS_AND_ROLES": [
        {
            "t": ("Как устроена компания", "How the Company Is Organised"),
            "o": ("Описать структуру компании, используя past simple и present perfect.",
                  "Describe a company structure using past simple and present perfect."),
            "v": [("head office", "главный офис"), ("subsidiary", "дочерняя компания"),
                  ("to be responsible for", "отвечать за"), ("to expand", "расшириться"),
                  ("staff", "персонал"), ("to found", "основать"),
                  ("abroad", "за границей")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The company has opened three new offices since January.",
                  ["The company has opened a new office last year.", "The company open three offices already."]),
            "tr": ("Компания основала главный офис в 2010 году и с тех пор открыла филиалы за границей.",
                   "The company founded its head office in 2010 and has opened branches abroad since then.",
                   ["did", "found", "yesterday"]),
            "fill": ("Last year the sales department ___ to a bigger floor.", "moved",
                     ["has move", "moving"], "В прошлом году отдел продаж переехал на больший этаж."),
            "tap": ("Our HR team has grown from two to ten people.", ["was", "did"]),
            "sh": ("The finance department has just published the annual report, and the CEO has commented on it already.",
                   "Финансовый отдел только что опубликовал годовой отчёт, и CEO уже прокомментировал его."),
            "st": ("The New Subsidiary", [
                ("Ben", "Have you heard? The company has opened a subsidiary in Poland.",
                 "Слышал? Компания открыла дочернюю компанию в Польше."),
                ("Maya", "When did it happen?", "Когда это произошло?"),
                ("What does Ben answer?", [
                    ("Last month. The Warsaw team has already hired twenty people.", True),
                    ("Tomorrow. They hired twenty people last year already.", False),
                    ("The subsidiary is opening the company.", False)])]),
            "d": ("subsidiary", "A company that belongs to a larger company",
                  ["A small shop that sells one product", "A department inside one office building"]),
            "lw": ("The company has ___ to South America.", "The company has expanded to South America.",
                   "expanded", ["expand", "expanding"]),
            "mw": ("She is responsible ___ the marketing team.", "for", "fo"),
            "ch": ([("Colleague", "Who is responsible for the new project?")], "You",
                   "Anna is. She has led similar projects since 2019.",
                   ["Anna was it tomorrow.", "The project is responsible for Anna."]),
        },
        {
            "t": ("Роли и рост команды", "Roles and Team Growth"),
            "o": ("Сравнить роли и рассказать о планах роста команды.",
                  "Compare roles and talk about team growth plans."),
            "v": [("team leader", "тимлид"), ("more senior", "старше по должности"),
                  ("to report to", "подотчётен (кому-то)"), ("to hire", "найять (сотрудника)"),
                  ("position", "должность"), ("junior", "младший (сотрудник)"),
                  ("to grow", "расти")],
            "q": ("Which sentence compares roles correctly?",
                  "A team leader is more senior than a junior specialist.",
                  ["A team leader is seniorer than a junior.", "A team leader is most senior than a junior."]),
            "tr": ("Мы собираемся нанять двух младших специалистов, потому что команда выросла вдвое.",
                   "We are going to hire two junior specialists because the team has doubled in size.",
                   ["did", "hired", "yesterday"]),
            "fill": ("In our structure, assistants ___ directly to the office manager.", "report",
                     ["reports", "reporting"], "В нашей структуре ассистенты подотчётны напрямую офис-менеджеру."),
            "tap": ("The logistics team is going to grow next quarter.", ["was", "did"]),
            "sh": ("If the company wins the tender, the department will create fifteen new positions.",
                   "Если компания выиграет тендер, отдел создаст пятнадцать новых должностей."),
            "st": ("The New Role", [
                ("Manager", "We are going to create a new position: customer success manager.",
                 "Мы собираемся ввести новую должность: менеджер по удержанию клиентов."),
                ("Anna", "Who will the new manager report to?", "Кому будет подотчётен новый менеджер?"),
                ("What does the manager say?", [
                    ("To me — and the role is more senior than the support team roles.", True),
                    ("To me, and it was seniorer yesterday.", False),
                    ("The position is reporting to itself.", False)])]),
            "d": ("to report to", "To be managed by a particular person at work",
                  ["To write a report about a colleague", "To finish work before the deadline"]),
            "lw": ("They are going to ___ five engineers.", "They are going to hire five engineers.",
                   "hire", ["hired", "hiring"]),
            "mw": ("This role is ___ senior than my old one.", "more", "mo"),
            "ch": ([("Colleague", "Is the new position junior or senior?")], "You",
                   "More senior — it reports directly to the head of department.",
                   ["It was seniorer yesterday.", "The position is reporting me."]),
        },
        {
            "t": ("К кому обратиться", "Who to Contact"),
            "o": ("Объяснить, к кому идти с вопросами, используя should и первое условное.",
                  "Explain who to contact using should and the first conditional."),
            "v": [("to contact", "обратиться к"), ("in charge of", "ответственный за"),
                  ("to solve", "решить (вопрос)"), ("colleague", "коллега"),
                  ("department", "отдел"), ("faster", "быстрее"),
                  ("internal request", "внутренний запрос")],
            "q": ("Which sentence gives correct advice?",
                  "You should contact HR about holiday requests.",
                  ["You should to contact HR yesterday.", "You must contacting HR last week."]),
            "tr": ("Если вопрос касается зарплаты, обратитесь в отдел кадров.",
                   "If the question is about salaries, you should contact the HR department.",
                   ["did", "concerned", "yesterday"]),
            "fill": ("If you ___ the right department, you will get an answer faster.",
                     "contact", ["will contact", "contacted"], "Если обратишься в нужный отдел, получишь ответ быстрее."),
            "tap": ("You should ask the person in charge of the budget.", ["mustn't", "went"]),
            "sh": ("If you are not sure who to ask, the office manager will point you to the right department.",
                   "Если не знаешь, кого спросить, офис-менеджер подскажет нужный отдел."),
            "st": ("The Wrong Department", [
                ("Tom", "I sent my request to finance, but they returned it.", "Я отправил запрос в финансовый отдел, но его вернули."),
                ("Anna", "Equipment requests go to the office manager, not finance.",
                 "Запросы на технику идут офис-менеджеру, а не в финансы."),
                ("What did Tom do wrong?", [
                    ("He contacted the wrong department, so he should resend it.", True),
                    ("He contacted finance tomorrow instead.", False),
                    ("The request is sending itself back.", False)])]),
            "d": ("in charge of", "Having control or responsibility for something",
                  ["Being new in a company", "Being on holiday this week"]),
            "lw": ("If you ___ the office manager, she will help today.",
                   "If you contact the office manager, she will help today.", "contact", ["will contact", "contacted"]),
            "mw": ("You should contact the person ___ charge of IT.", "in", "in"),
            "ch": ([("Colleague", "Who should I ask about the parking pass?")], "You",
                   "Ask the office manager — if she cannot help, she will forward you to facilities.",
                   ["I asked her yesterday tomorrow.", "The pass is parking the office."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_CUSTOMER_REQUESTS_AND_COMPLAINTS": [
        {
            "t": ("Жалоба клиента", "A Customer Complaint"),
            "o": ("Описать жалобу и действия, используя past simple и present perfect.",
                  "Describe a complaint and the actions taken using past simple and present perfect."),
            "v": [("complaint", "жалоба"), ("refund", "возврат средств"),
                  ("faulty", "неисправный"), ("to replace", "заменить"),
                  ("to apologise", "извиниться"), ("within", "в течение"),
                  ("to investigate", "расследовать")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "We have received three complaints about the same product this month.",
                  ["We have received a complaint yesterday.", "We receive three complaints already this month."]),
            "tr": ("Клиент получил неисправный товар, и мы уже отправили ему замену.",
                   "The customer received a faulty product, and we have already sent him a replacement.",
                   ["did", "receive", "yesterday"]),
            "fill": ("The support team ___ to the customer within an hour.", "apologised",
                     ["has apologise", "apologising"], "Команда поддержки извинилась перед клиентом в течение часа."),
            "tap": ("We have investigated the problem and found the cause.", ["was", "did"]),
            "sh": ("The customer has complained twice this week, so the manager has called her personally.",
                   "Клиент жаловался дважды за неделю, поэтому менеджер позвонил ей лично."),
            "st": ("The Faulty Printer", [
                ("Client", "The printer you delivered last week does not work.", "Принтер, который вы доставили на прошлой неделе, не работает."),
                ("Anna", "I'm sorry about that. Have you checked the power cable?", "Сожалею. Вы проверили кабель питания?"),
                ("What does the client say?", [
                    ("Yes, the machine itself is faulty — I would like a replacement.", True),
                    ("Yes, I check it tomorrow morning.", False),
                    ("The printer is complaining about the cable.", False)])]),
            "d": ("faulty", "Not working correctly; having a fault",
                  ["Brand new and never used", "Very expensive but popular"]),
            "lw": ("We have ___ the complaint already.", "We have investigated the complaint already.",
                   "investigated", ["investigate", "investigating"]),
            "mw": ("She has asked for a ___ of the payment.", "refund", "re"),
            "ch": ([("Colleague", "Did the customer accept the replacement?")], "You",
                   "Yes, she accepted it and has already thanked the support team.",
                   ["Yes, she accepts it tomorrow.", "The replacement is accepting her."]),
        },
        {
            "t": ("Как мы ответим", "How We Will Respond"),
            "o": ("Предложить решения по жалобе и сравнить варианты.",
                  "Offer solutions to a complaint and compare options."),
            "v": [("solution", "решение"), ("compensation", "компенсация"),
                  ("faster", "быстрее"), ("to offer a discount", "предложить скидку"),
                  ("loyal", "лояльный"), ("to satisfy", "удовлетворить (клиента)"),
                  ("more generous", "щедрее")],
            "q": ("Which sentence compares two offers correctly?",
                  "A discount is more generous than a simple apology.",
                  ["A discount is generousest than an apology.", "A discount is more generous of the two most."]),
            "tr": ("Мы предложим скидку десять процентов — это лучше, чем просто извинение.",
                   "We are going to offer a ten percent discount — it is better than a simple apology.",
                   ["did", "offered", "yesterday"]),
            "fill": ("A quick answer is ___ important than a perfect answer.", "more",
                     ["most", "much"], "Быстрый ответ важнее идеального ответа."),
            "tap": ("The manager is going to call the client personally tomorrow.", ["was", "did"]),
            "sh": ("If we respond faster than the competition, the customer will stay with us.",
                   "Если мы отвечаем быстрее конкурентов, клиент останется с нами."),
            "st": ("Choosing Compensation", [
                ("Manager", "The client is angry. What can we offer?", "Клиент недоволен. Что мы можем предложить?"),
                ("Anna", "A refund or a twenty percent discount on the next order.",
                 "Возврат средств или скидку двадцать процентов на следующий заказ."),
                ("What does the manager decide?", [
                    ("The discount is better — it keeps the customer loyal.", True),
                    ("The refund was better yesterday tomorrow.", False),
                    ("The anger is offering a discount.", False)])]),
            "d": ("compensation", "Something given to make up for a problem",
                  ["A price list sent before the order", "A thank-you letter without any offer"]),
            "lw": ("We are going to ___ a full refund.", "We are going to offer a full refund.",
                   "offer", ["offered", "offering"]),
            "mw": ("This solution is ___ generous than the first one.", "more", "mo"),
            "ch": ([("Colleague", "The client wants a discount this time.")], "You",
                   "I agree — if we offer ten percent now, we will keep the order.",
                   ["We offered it yesterday tomorrow.", "The discount is wanting the client."]),
        },
        {
            "t": ("Профилактика жалоб", "Preventing Complaints"),
            "o": ("Предложить меры против жалоб, используя should и первое условное.",
                  "Suggest measures against complaints using should and the first conditional."),
            "v": [("to prevent", "предотвратить"), ("to check quality", "проверять качество"),
                  ("before delivery", "до доставки"), ("feedback", "обратная связь"),
                  ("to repeat", "повториться"), ("to improve service", "улучшить сервис"),
                  ("to promise", "обещать")],
            "q": ("Which sentence gives correct advice?",
                  "We should check the quality before every delivery.",
                  ["We should to check the quality yesterday.", "We must checking quality last week."]),
            "tr": ("Если мы будем проверять качество до отправки, жалоб станет меньше.",
                   "If we check the quality before delivery, there will be fewer complaints.",
                   ["did", "checked", "yesterday"]),
            "fill": ("If we ___ only what we can deliver, clients will trust us.",
                     "promise", ["will promise", "promised"], "Если обещать только то, что можем выполнить, клиенты будут нам доверять."),
            "tap": ("You should ask for feedback after every order.", ["mustn't", "went"]),
            "sh": ("If we call customers after delivery, we will solve small problems before they grow.",
                   "Если звонить клиентам после доставки, мы решим мелкие проблемы до того, как они вырастут."),
            "st": ("After the Incident", [
                ("Director", "This is the second complaint about packaging this month.",
                 "Это вторая жалоба на упаковку за месяц."),
                ("Anna", "What should we change?", "Что нам изменить?"),
                ("What does the director suggest?", [
                    ("If we use stronger boxes, the damage will not repeat.", True),
                    ("If we will use stronger boxes, the damage repeated yesterday.", False),
                    ("The packaging is complaining about itself.", False)])]),
            "d": ("feedback", "Opinions about how well something is done",
                  ["A list of products for the next order", "A signed contract with a client"]),
            "lw": ("If we ___ quality twice, faults will not reach clients.",
                   "If we check quality twice, faults will not reach clients.", "check", ["will check", "checked"]),
            "mw": ("We should call clients ___ every delivery.", "after", "af"),
            "ch": ([("Colleague", "The same client has complained again.")], "You",
                   "We should offer a call — if he explains the problem, we will fix it for good.",
                   ["We must to call him yesterday.", "The problem is complaining again."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_EVERYDAY_BUSINESS_EMAILS": [
        {
            "t": ("Письма на этой неделе", "Emails This Week"),
            "o": ("Рассказать о переписке, используя past simple и present perfect.",
                  "Talk about email exchanges using past simple and present perfect."),
            "v": [("inbox", "входящие"), ("to reply", "ответить"),
                  ("attachment", "вложение"), ("to forward", "переслать"),
                  ("subject line", "тема письма"), ("to attach", "приложить"),
                  ("so far", "до сих пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "I have answered twenty emails so far today.",
                  ["I have answered twenty emails yesterday.", "I answer twenty emails so far already."]),
            "tr": ("Я переслал письмо бухгалтерии и приложил счёт-фактуру.",
                   "I forwarded the email to the accounting department and attached the invoice.",
                   ["did", "forwards", "tomorrow"]),
            "fill": ("She forgot to ___ the attachment last Friday.", "add",
                     ["has add", "adding"], "В прошлую пятницу она забыла приложить вложение."),
            "tap": ("He has already replied to the most important message.", ["was", "did"]),
            "sh": ("I have checked my inbox twice this morning, and the contract has not arrived yet.",
                   "Я проверял входящие дважды сегодня утром, а контракт всё ещё не пришёл."),
            "st": ("The Missing Attachment", [
                ("Client", "Your email arrived, but there is no attachment.", "Ваше письмо пришло, но вложения нет."),
                ("Anna", "You are right — I forgot it. I'm very sorry.", "Вы правы — я забыла его. Очень извиняюсь."),
                ("What does Anna do next?", [
                    ("She has just sent the file again with an apology.", True),
                    ("She sends it yesterday again tomorrow.", False),
                    ("The attachment is emailing itself.", False)])]),
            "d": ("to forward", "To send an email you received to another person",
                  ["To delete an email from the inbox", "To print an email on paper"]),
            "lw": ("I have ___ the invoice to the email.", "I have attached the invoice to the email.",
                   "attached", ["attach", "attaching"]),
            "mw": ("Please write a clear subject ___ .", "line", "li"),
            "ch": ([("Colleague", "Did you see the client's email?")], "You",
                   "Yes, I replied this morning and have forwarded it to the manager.",
                   ["Yes, I reply it tomorrow.", "The email is seeing me."]),
        },
        {
            "t": ("Пишем письмо-запрос", "Writing a Request Email"),
            "o": ("Составить вежливый запрос и сравнить формулировки.",
                  "Write a polite request and compare wording options."),
            "v": [("polite", "вежливый"), ("formal", "официальный"),
                  ("more direct", "прямее"), ("to request", "запросить"),
                  ("regarding", "касательно"), ("to follow up", "напомнить о себе письмом"),
                  ("short", "короткий")],
            "q": ("Which subject line is the clearest?",
                  "Request: new price list for 2026",
                  ["Hello!", "Very important, open now!!!"]),
            "tr": ("Не могли бы вы прислать обновлённый прайс-лист касательно нашего контракта?",
                   "Could you please send the updated price list regarding our contract?",
                   ["did", "can", "yesterday"]),
            "fill": ("A formal email is ___ appropriate for a first contact than a short chat message.", "more",
                     ["most", "much"], "Официальное письмо уместнее для первого контакта, чем короткое сообщение в чате."),
            "tap": ("I am going to write a short email with one clear question.", ["was", "did"]),
            "sh": ("If you put the main question in the first line, the reader will answer faster.",
                   "Если поставить главный вопрос в первую строку, читатель ответит быстрее."),
            "st": ("The Rushed Email", [
                ("Tom", "I sent the request five minutes ago and got an answer already!",
                 "Я отправил запрос пять минут назад и уже получил ответ!"),
                ("Anna", "That's unusually fast. What did you write in the subject line?",
                 "Это необычно быстро. Что ты написал в теме письма?"),
                ("What does Tom say?", [
                    ("I wrote one clear question: 'Invoice number for order 415?'", True),
                    ("I wrote 'Hello' and attached three documents.", False),
                    ("The subject line answered me itself.", False)])]),
            "d": ("regarding", "About or connected with a subject",
                  ["Before a deadline", "Instead of an attachment"]),
            "lw": ("Could you ___ the form by Friday?", "Could you complete the form by Friday?",
                   "complete", ["completed", "completing"]),
            "mw": ("A short email is ___ effective than a long one.", "more", "mo"),
            "ch": ([("Colleague", "How should I start the email to the new client?")], "You",
                   "Start formally — 'Dear Mr Brown' is safer than 'Hi' for a first contact.",
                   ["I started it yesterday tomorrow.", "The email is starting the client."]),
        },
        {
            "t": ("Если письмо не понятно", "When an Email Is Unclear"),
            "o": ("Уточнить письмо, используя should и первое условное.",
                  "Clarify an email using should and the first conditional."),
            "v": [("unclear", "неясный"), ("to rewrite", "переписать"),
                  ("shorter", "короче"), ("bulleted list", "маркированный список"),
                  ("to misunderstand", "неверно понять"), ("simple", "простой"),
                  ("to proofread", "вычитать")],
            "q": ("Which sentence gives correct advice?",
                  "You should proofread the email before you send it.",
                  ["You should to proofread it yesterday.", "You must proofreading it last night."]),
            "tr": ("Если письмо непонятное, читатель потратит вдвое больше времени.",
                   "If an email is unclear, the reader will spend twice as much time.",
                   ["did", "was", "yesterday"]),
            "fill": ("If you ___ the email into short paragraphs, it will be easier to read.",
                     "divide", ["will divide", "divided"], "Если разбить письмо на короткие абзацы, его будет легче читать."),
            "tap": ("You should use a bulleted list for three or more items.", ["mustn't", "went"]),
            "sh": ("If you rewrite the message in simpler words, the client will not misunderstand you.",
                   "Если переписать сообщение более простыми словами, клиент вас не поймёт неверно."),
            "st": ("The Confusing Reply", [
                ("Anna", "I have read the client's reply three times, and it is still unclear.",
                 "Я трижды прочитала ответ клиента, и он всё ещё неясен."),
                ("Tom", "What should we do — guess or ask?", "Что делать — догадаться или спросить?"),
                ("What is the better decision?", [
                    ("We should ask one short clarifying question today.", True),
                    ("We should guessing until tomorrow.", False),
                    ("The reply is reading us three times.", False)])]),
            "d": ("to proofread", "To read a text again to find mistakes",
                  ["To translate an email into another language", "To send an email to a big group"]),
            "lw": ("If you ___ the email, you will find the typo.",
                   "If you proofread the email, you will find the typo.", "proofread", ["will proofread", "proofreaded"]),
            "mw": ("Shorter sentences are ___ to understand.", "easier", "ea"),
            "ch": ([("Colleague", "The client misunderstood my last email.")], "You",
                   "Next time you should use a bulleted list — if the points are numbered, nothing will be lost.",
                   ["I used it yesterday tomorrow.", "The email is misunderstanding the client."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_OFFICE_SERVICES_AND_ADMINISTRATION": [
        {
            "t": ("Заявки в администрацию", "Requests to the Administration"),
            "o": ("Сообщить о заявках и услугах офиса, используя past simple и present perfect.",
                  "Report office service requests using past simple and present perfect."),
            "v": [("facilities", "хозяйственная служба"), ("to submit a request", "подать заявку"),
                  ("maintenance", "техобслуживание"), ("access card", "пропуск"),
                  ("to repair", "отремонтировать"), ("work order", "наряд на работы"),
                  ("within a week", "в течение недели")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "The facilities team has fixed the heating already.",
                  ["The facilities team has fixed it yesterday.", "The team fix the heating already now."]),
            "tr": ("Я подал заявку на ремонт в понедельник, и её уже выполнили.",
                   "I submitted the repair request on Monday, and they have already completed it.",
                   ["did", "submit", "yesterday"]),
            "fill": ("My access card ___ working last Tuesday.", "stopped",
                     ["has stop", "stopping"], "Мой пропуск перестал работать в прошлый вторник."),
            "tap": ("They have replaced all the lights on our floor.", ["was", "did"]),
            "sh": ("The air conditioning broke down again, so I have submitted a new work order.",
                   "Кондиционер снова сломался, поэтому я подал новый наряд на работы."),
            "st": ("The Access Card", [
                ("Tom", "I can't get into the meeting room — my card doesn't work.",
                 "Не могу попасть в переговорку — мой пропуск не работает."),
                ("Anna", "When did it stop working?", "Когда он перестал работать?"),
                ("What does Tom say?", [
                    ("This morning. I have already submitted a request to facilities.", True),
                    ("Tomorrow morning. I submitted it yesterday already.", False),
                    ("The card is getting into the room itself.", False)])]),
            "d": ("maintenance", "Work done to keep equipment or buildings in good condition",
                  ["A meeting about next year's budget", "A welcome party for new employees"]),
            "lw": ("I have ___ a work order for the door.", "I have submitted a work order for the door.",
                   "submitted", ["submit", "submitting"]),
            "mw": ("The heating has been ___ since October.", "broken", "br"),
            "ch": ([("Colleague", "Did facilities reply to your ticket?")], "You",
                   "Yes, they replied this morning and have already scheduled the repair.",
                   ["Yes, they reply tomorrow.", "The ticket is replying to them."]),
        },
        {
            "t": ("Улучшения в офисе", "Office Improvements"),
            "o": ("Рассказать о будущих улучшениях и сравнить варианты.",
                  "Talk about future improvements and compare options."),
            "v": [("renovation", "ремонт"), ("more comfortable", "комфортнее"),
                  ("to install", "установить"), ("meeting room booking", "бронирование переговорок"),
                  ("quieter", "тише"), ("to upgrade", "модернизировать"),
                  ("by the end of", "к концу")],
            "q": ("Which sentence talks about the future?",
                  "They are going to install new desks by the end of the month.",
                  ["They installed new desks by the end of last month.", "They has installed desks tomorrow already."]),
            "tr": ("Администрация собирается отремонтировать кухню — она будет просторнее.",
                   "The administration is going to renovate the kitchen — it will be more spacious.",
                   ["did", "renovated", "yesterday"]),
            "fill": ("The new meeting rooms are ___ than the old ones.", "quieter",
                     ["quietest", "more quiet"], "Новые переговорки тише старых."),
            "tap": ("We are going to upgrade the booking system next quarter.", ["was", "did"]),
            "sh": ("If we install the screens this week, the training room will be ready before the visit.",
                   "Если мы установим экраны на этой неделе, учебная комната будет готова до визита."),
            "st": ("Two Renovation Plans", [
                ("Office manager", "We can renovate either the kitchen or the lounge this year.",
                 "В этом году мы можем отремонтировать либо кухню, либо зону отдыха."),
                ("Anna", "The kitchen is more useful — everyone eats there every day.",
                 "Кухня полезнее — там каждый день обедают все."),
                ("What does the office manager decide?", [
                    ("Then we are going to start with the kitchen in May.", True),
                    ("Then we started with it yesterday tomorrow.", False),
                    ("The kitchen is renovating itself.", False)])]),
            "d": ("to upgrade", "To improve something or replace it with a better version",
                  ["To move furniture from one room to another", "To book a room for a meeting"]),
            "lw": ("They are going to ___ new lamps.", "They are going to install new lamps.",
                   "install", ["installed", "installing"]),
            "mw": ("The lounge will be ___ comfortable after the renovation.", "more", "mo"),
            "ch": ([("Colleague", "When will the new booking system be ready?")], "You",
                   "They are going to launch it by the end of the quarter.",
                   ["It was ready yesterday tomorrow.", "The system is launching us."]),
        },
        {
            "t": ("Правила использования услуг", "Rules for Using Services"),
            "o": ("Объяснить правила офисных услуг, используя should и первое условное.",
                  "Explain office service rules using should and the first conditional."),
            "v": [("to keep clean", "содержать в чистоте"), ("shared", "общий"),
                  ("to book in advance", "бронировать заранее"), ("cleaning schedule", "график уборки"),
                  ("to follow", "соблюдать"), ("fair", "справедливый"),
                  ("label", "надпись / маркировать")],
            "q": ("Which sentence expresses a rule for shared spaces?",
                  "You should book the meeting rooms in advance.",
                  ["You should to book them yesterday.", "You must booking them last week."]),
            "tr": ("Если каждый будет убирать за собой, кухня останется чистой.",
                   "If everyone cleans up after themselves, the kitchen will stay clean.",
                   ["did", "cleaned", "yesterday"]),
            "fill": ("If you ___ your food in the fridge, nobody will throw it away.",
                     "label", ["will label", "labelled"], "Если подписать еду в холодильнике, её никто не выбросит."),
            "tap": ("You should follow the cleaning schedule in shared kitchens.", ["mustn't", "went"]),
            "sh": ("If you cancel a booking you do not need, another team will be able to use the room.",
                   "Если отменить ненужное бронирование, другая команда сможет воспользоваться комнатой."),
            "st": ("The Shared Fridge", [
                ("Anna", "Someone has thrown away my lunch box again!", "Кто-то снова выбросил мой ланчбокс!"),
                ("Tom", "Did it have your name on it?", "На нём было твоё имя?"),
                ("What is the fair solution?", [
                    ("From now on, everyone should label their food clearly.", True),
                    ("From now on, everyone must labelling it yesterday.", False),
                    ("The fridge is eating the lunches itself.", False)])]),
            "d": ("shared", "Used by several people, not only one person",
                  ["Kept locked in a personal office", "Bought by one employee yesterday"]),
            "lw": ("If you ___ the room, others can use it.", "If you cancel the room, others can use it.",
                   "cancel", ["will cancel", "cancelled"]),
            "mw": ("You should book the room ___ advance.", "in", "in"),
            "ch": ([("Colleague", "The meeting room is always busy at noon.")], "You",
                   "That's why you should book it in advance — if you book at nine, you will get it.",
                   ["I booked it yesterday tomorrow.", "Noon is booking the room."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_ORDERS_DELIVERIES_AND_FOLLOW_UP": [
        {
            "t": ("Что случилось с заказом", "What Happened to the Order"),
            "o": ("Сообщить о статусе заказа, используя past simple и present perfect.",
                  "Report an order status using past simple and present perfect."),
            "v": [("purchase order", "заказ на закупку"), ("to dispatch", "отправить (товар)"),
                  ("tracking number", "трек-номер"), ("out of stock", "нет на складе"),
                  ("partial delivery", "частичная доставка"), ("to arrive", "прибыть"),
                  ("invoice", "счёт")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "Half of the order has already arrived at the warehouse.",
                  ["Half of the order has arrived yesterday.", "Half of the order arrive already now."]),
            "tr": ("Мы отправили заказ в пятницу, но половина позиций была не на складе.",
                   "We dispatched the order on Friday, but half of the items were out of stock.",
                   ["did", "dispatch", "yesterday"]),
            "fill": ("The supplier ___ us the tracking number two days ago.", "sent",
                     ["has send", "sending"], "Поставщик прислал трек-номер два дня назад."),
            "tap": ("The remaining items have left the warehouse this morning.", ["was", "did"]),
            "sh": ("The first delivery has arrived, but the invoice has not come yet, so accounting cannot close the month.",
                   "Первая поставка пришла, но счёт ещё не пришёл, поэтому бухгалтерия не может закрыть месяц."),
            "st": ("The Partial Delivery", [
                ("Client", "We ordered fifty chairs, but only twenty arrived.", "Мы заказали пятьдесят стульев, а пришло только двадцать."),
                ("Anna", "You are right. The rest were out of stock at that moment.",
                 "Вы правы. Остальных не было на складе в тот момент."),
                ("What does the client ask?", [
                    ("When are the other thirty going to arrive?", True),
                    ("When did the other thirty arrived tomorrow?", False),
                    ("Are the chairs ordering themselves?", False)])]),
            "d": ("out of stock", "Not available to buy or order at the moment",
                  ["Ready to send from the warehouse today", "Delivered last week without problems"]),
            "lw": ("The rest of the order has ___ the warehouse.", "The rest of the order has left the warehouse.",
                   "left", ["leave", "leaving"]),
            "mw": ("Have you received the ___ for order 512?", "invoice", "in"),
            "ch": ([("Colleague", "Did the replacement items arrive?")], "You",
                   "Yes, they arrived today, and I have already checked them against the invoice.",
                   ["Yes, they arrive tomorrow morning.", "The items are checking themselves."]),
        },
        {
            "t": ("Следующий заказ", "The Next Order"),
            "o": ("Спланировать будущие заказы и сравнить условия доставки.",
                  "Plan future orders and compare delivery terms."),
            "v": [("to place an order", "разместить заказ"), ("delivery time", "срок доставки"),
                  ("faster", "быстрее"), ("cheaper", "дешевле"),
                  ("minimum order", "минимальный заказ"), ("to expect", "ожидать"),
                  ("in total", "всего")],
            "q": ("Which sentence compares delivery options correctly?",
                  "Express delivery is faster but more expensive.",
                  ["Express delivery is more fast but expensiver.", "Express delivery is fastest but most cheap."]),
            "tr": ("Мы собираемся разместить более крупный заказ, потому что так доставка выходит дешевле.",
                   "We are going to place a larger order because the delivery works out cheaper that way.",
                   ["did", "placed", "yesterday"]),
            "fill": ("The minimum order is fifty units ___ total.", "in",
                     ["at", "on"], "Минимальный заказ — пятьдесят единиц в сумме."),
            "tap": ("We are going to order twice a month instead of every week.", ["was", "did"]),
            "sh": ("If we place the order before noon, the goods will leave the warehouse today.",
                   "Если разместить заказ до полудня, товар покинет склад сегодня же."),
            "st": ("Two Delivery Options", [
                ("Supplier", "We can offer standard delivery in five days or express in two.",
                 "Мы можем предложить стандартную доставку за пять дней или экспресс за два."),
                ("Tom", "How much more expensive is the express option?", "Насколько экспресс дороже?"),
                ("What does the supplier say?", [
                    ("It costs thirty percent more, but it is three days faster.", True),
                    ("It costs thirty percent more yesterday.", False),
                    ("The delivery is ordering itself faster.", False)])]),
            "d": ("to place an order", "To officially ask a company to send goods",
                  ["To cancel an order that has not arrived", "To return goods to the shop"]),
            "lw": ("We are going to ___ a bigger order.", "We are going to place a bigger order.",
                   "place", ["placed", "placing"]),
            "mw": ("Express delivery is ___ than standard.", "quicker", "qu"),
            "ch": ([("Colleague", "Should we order the smaller pack?")], "You",
                   "No — if we order the large one, the price per unit will be ten percent lower.",
                   ["We ordered it yesterday tomorrow.", "The pack is ordering us."]),
        },
        {
            "t": ("Если поставка задержится", "If the Delivery Is Late"),
            "o": ("Обсудить задержки поставки, используя should и первое условное.",
                  "Discuss delivery delays using should and the first conditional."),
            "v": [("delay", "задержка"), ("to notify", "уведомить"),
                  ("immediately", "немедленно"), ("to run out of", "закончиться (о запасах)"),
                  ("stock level", "уровень запасов"), ("to plan ahead", "планировать заранее"),
                  ("alternative supplier", "альтернативный поставщик")],
            "q": ("Which sentence gives correct advice?",
                  "The supplier should notify us about delays immediately.",
                  ["The supplier should to notify us yesterday.", "The supplier must notifying us last week."]),
            "tr": ("Если поставщик задержит доставку, мы закончим запасы к пятнице.",
                   "If the supplier delays the delivery, we will run out of stock by Friday.",
                   ["did", "delayed", "yesterday"]),
            "fill": ("If stock ___ too low, we will lose orders.", "gets",
                     ["will get", "got"], "Если запасов станет слишком мало, мы потеряем заказы."),
            "tap": ("You should keep stock levels higher in the busy season.", ["mustn't", "went"]),
            "sh": ("If the main supplier is late again, we should contact the alternative supplier the same day.",
                   "Если основной поставщик снова задержит, стоит в тот же день связаться с запасным."),
            "st": ("The Monday Delay", [
                ("Anna", "The delivery has not arrived, and it was due yesterday.",
                 "Поставка не пришла, хотя её ждали ещё вчера."),
                ("Tom", "Have they told us why?", "Они сказали почему?"),
                ("What is the risk?", [
                    ("If it does not come today, the production line will stop tomorrow.", True),
                    ("If it will not come, the line stopped yesterday.", False),
                    ("The delivery is stopping itself.", False)])]),
            "d": ("to run out of", "To have no more of something left",
                  ["To order a large quantity of goods", "To check the quality of a delivery"]),
            "lw": ("If we ___ of packaging, orders will stop.", "If we run out of packaging, orders will stop.",
                   "run out", ["will run out", "ran out"]),
            "mw": ("The supplier should notify us ___ advance.", "in", "in"),
            "ch": ([("Colleague", "The supplier is late again.")], "You",
                   "We should plan ahead — if we keep a buffer stock, a delay will not stop us.",
                   ["We planned it yesterday tomorrow.", "The delay is stocking us."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_PARTICIPATING_IN_MEETINGS": [
        {
            "t": ("Что решили на встрече", "What We Decided"),
            "o": ("Сообщить о решениях встречи, используя past simple и present perfect.",
                  "Report meeting decisions using past simple and present perfect."),
            "v": [("decision", "решение"), ("to agree on", "договориться о"),
                  ("action item", "пункт действий"), ("minutes", "протокол встречи"),
                  ("to vote", "голосовать"), ("next steps", "следующие шаги"),
                  ("to chair", "вести (встречу)")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "We have agreed on the budget for the next quarter.",
                  ["We have agreed on the budget yesterday.", "We agree on the budget already now."]),
            "tr": ("На встрече мы договорились о сроках и распределили задачи.",
                   "At the meeting we agreed on the deadlines and shared out the tasks.",
                   ["did", "agrees", "tomorrow"]),
            "fill": ("Who ___ the meeting last Thursday?", "chaired",
                     ["has chair", "chairing"], "Кто вёл встречу в прошлый четверг?"),
            "tap": ("She has already sent the minutes to all participants.", ["was", "did"]),
            "sh": ("The team has made three decisions, and every action item now has an owner and a deadline.",
                   "Команда приняла три решения, и у каждого пункта действий теперь есть владелец и срок."),
            "st": ("After the Meeting", [
                ("Tom", "I missed the planning meeting. What did they decide?", "Я пропустил планёрку. Что решили?"),
                ("Anna", "They have chosen May for the launch and agreed on the new budget.",
                 "Выбрали май для запуска и согласовали новый бюджет."),
                ("What does Tom ask?", [
                    ("Has anyone published the minutes yet?", True),
                    ("Did anyone has published them tomorrow?", False),
                    ("Is the launch deciding the budget?", False)])]),
            "d": ("minutes", "The written record of what was said and decided at a meeting",
                  ["Sixty seconds of waiting before a call starts", "A short break in the middle of a meeting"]),
            "lw": ("We have ___ on the final date.", "We have agreed on the final date.",
                   "agreed", ["agree", "agreeing"]),
            "mw": ("Every action ___ has an owner.", "item", "it"),
            "ch": ([("Colleague", "Did you send the minutes?")], "You",
                   "Yes, I sent them an hour ago, and the director has already replied.",
                   ["Yes, I send them tomorrow.", "The minutes are sending themselves."]),
        },
        {
            "t": ("Встреча на следующей неделе", "The Meeting Next Week"),
            "o": ("Подготовиться к будущей встрече и сравнить форматы.",
                  "Prepare for a future meeting and compare formats."),
            "v": [("to invite", "пригласить"), ("shorter", "короче"),
                  ("to prepare", "подготовиться"), ("online", "онлайн"),
                  ("in person", "лично"), ("more productive", "продуктивнее"),
                  ("timebox", "лимит времени")],
            "q": ("Which sentence talks about a future meeting?",
                  "We are going to invite the design team to the next call.",
                  ["We invited the design team to yesterday's call.", "We has invited them tomorrow already."]),
            "tr": ("Следующая встреча будет короче — всего тридцать минут с лимитом на каждый вопрос.",
                   "The next meeting is going to be shorter — only thirty minutes with a timebox for each question.",
                   ["did", "was", "yesterday"]),
            "fill": ("A meeting with an agenda is ___ productive than a chat without a plan.", "more",
                     ["most", "much"], "Встреча с повесткой продуктивнее болтовни без плана."),
            "tap": ("I am going to prepare two slides for the budget part.", ["was", "did"]),
            "sh": ("If everyone reads the documents in advance, the meeting will be ten minutes shorter.",
                   "Если все прочитают документы заранее, встреча будет на десять минут короче."),
            "st": ("Online or in Person?", [
                ("Manager", "Should we do the quarterly review online or in person?",
                 "Проводить квартальный обзор онлайн или лично?"),
                ("Anna", "In person is more productive for long discussions.",
                 "Лично продуктивнее для долгих обсуждений."),
                ("What does the manager decide?", [
                    ("Then we are going to book a room for the whole morning.", True),
                    ("Then we booked it yesterday tomorrow.", False),
                    ("The review is meeting us online.", False)])]),
            "d": ("timebox", "A fixed maximum time for one topic or task",
                  ["A calendar invitation sent by email", "A list of people at a meeting"]),
            "lw": ("We are going to ___ the suppliers too.", "We are going to invite the suppliers too.",
                   "invite", ["invited", "inviting"]),
            "mw": ("Online calls are ___ for short check-ins.", "better", "be"),
            "ch": ([("Colleague", "How long should the demo meeting be?")], "You",
                   "Thirty minutes — if we timebox the questions, we will finish on time.",
                   ["It was thirty minutes yesterday tomorrow.", "The demo is timing us."]),
        },
        {
            "t": ("Как вести себя на встрече", "How to Behave in a Meeting"),
            "o": ("Дать советы об участии во встречах, используя should и первое условное.",
                  "Give meeting participation advice using should and the first conditional."),
            "v": [("to interrupt politely", "вежливо перебить"), ("to stay on topic", "не отходить от темы"),
                  ("to listen first", "сначала выслушать"), ("late", "поздний"),
                  ("to contribute", "внести вклад"), ("respect", "уважение"),
                  ("to mute", "выключить микрофон")],
            "q": ("Which sentence gives correct meeting advice?",
                  "You should mute your microphone when you are not speaking.",
                  ["You should to mute it yesterday.", "You must muting it last meeting."]),
            "tr": ("Если ты выслушаешь коллегу до конца, твой ответ будет точнее.",
                   "If you listen to your colleague to the end, your answer will be more precise.",
                   ["did", "listened", "yesterday"]),
            "fill": ("If you arrive late, the meeting ___ start without you.", "will",
                     ["wills", "is"], "Если опоздаешь, встреча начнётся без тебя."),
            "tap": ("You should stay on topic during short meetings.", ["mustn't", "went"]),
            "sh": ("If you contribute one clear idea instead of five vague ones, people will remember it.",
                   "Если внести одну чёткую идею вместо пяти расплывчатых, её запомнят."),
            "st": ("The Long Monologue", [
                ("Anna", "Tom spoke for fifteen minutes about his holiday during the budget meeting.",
                 "Том говорил пятнадцать минут об отпуске во время встречи по бюджету."),
                ("Manager", "What should we do about it?", "Что нам с этим делать?"),
                ("What does Anna suggest?", [
                    ("You should remind him politely to stay on topic.", True),
                    ("You must to remind him yesterday.", False),
                    ("The holiday is speaking about Tom.", False)])]),
            "d": ("to contribute", "To give your ideas or effort to a discussion",
                  ["To stay completely silent during a call", "To leave a meeting before it ends"]),
            "lw": ("If you ___ first, you will understand better.", "If you listen first, you will understand better.",
                   "listen", ["will listen", "listened"]),
            "mw": ("You should keep your answers ___ and clear.", "short", "sh"),
            "ch": ([("Colleague", "People keep interrupting each other on our calls.")], "You",
                   "The chair should set a speaking order — if we follow it, the call will be calmer.",
                   ["The chair set it yesterday tomorrow.", "The calls are interrupting us."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_PRICES_FIGURES_AND_SIMPLE_BUDGETS": [
        {
            "t": ("Цифры за квартал", "The Quarterly Figures"),
            "o": ("Сообщить финансовые результаты, используя past simple и present perfect.",
                  "Report financial results using past simple and present perfect."),
            "v": [("revenue", "выручка"), ("costs", "расходы"),
                  ("to increase by", "вырасти на"), ("to decrease", "снизиться"),
                  ("profit", "прибыль"), ("per cent", "процент"),
                  ("compared to", "по сравнению с")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "Revenue has increased by eight per cent this year.",
                  ["Revenue has increased by eight per cent last year.", "Revenue increase eight per cent already."]),
            "tr": ("Расходы выросли на пять процентов по сравнению с прошлым кварталом.",
                   "Costs have increased by five per cent compared to the last quarter.",
                   ["did", "increase", "yesterday"]),
            "fill": ("Profit ___ by two thousand euros last month.", "fell",
                     ["has fall", "falling"], "Прибыль упала на две тысячи евро в прошлом месяце."),
            "tap": ("The finance team has just published the annual report.", ["was", "did"]),
            "sh": ("Costs have decreased slightly, but revenue has grown faster, so the profit is higher than last year.",
                   "Расходы немного снизились, но выручка выросла быстрее, поэтому прибыль выше, чем в прошлом году."),
            "st": ("The Budget Review", [
                ("Director", "How are the numbers compared to last year?", "Каковы цифры по сравнению с прошлым годом?"),
                ("Anna", "Revenue has grown by twelve per cent, and costs have fallen by three.",
                 "Выручка выросла на двенадцать процентов, а расходы упали на три."),
                ("What does the director ask?", [
                    ("And what has happened to the marketing budget?", True),
                    ("And what did happened to it tomorrow?", False),
                    ("Is the budget growing the numbers itself?", False)])]),
            "d": ("revenue", "The money a company receives from its business",
                  ["The money a company pays to employees", "The number of clients per year"]),
            "lw": ("Costs have ___ by three per cent.", "Costs have decreased by three per cent.",
                   "decreased", ["decrease", "decreasing"]),
            "mw": ("Revenue has grown ___ ten per cent.", "by", "by"),
            "ch": ([("Colleague", "Did you see the half-year figures?")], "You",
                   "Yes — profit has increased, and the team has already updated the forecast.",
                   ["Yes, I see them tomorrow.", "The figures are seeing us."]),
        },
        {
            "t": ("Бюджет на следующий год", "The Budget for Next Year"),
            "o": ("Спланировать бюджет и сравнить статьи расходов.",
                  "Plan a budget and compare spending items."),
            "v": [("budget", "бюджет"), ("to allocate", "распределить (средства)"),
                  ("to save", "сэкономить"), ("more important", "важнее"),
                  ("to cut", "сократить (расходы)"), ("estimate", "оценка"),
                  ("to spend", "тратить")],
            "q": ("Which sentence compares budget items correctly?",
                  "Training is more important than new furniture this year.",
                  ["Training is importanter than furniture.", "Training is most important than furniture."]),
            "tr": ("Мы собираемся выделить больше средств на обучение и сократить расходы на поездки.",
                   "We are going to allocate more money to training and cut the travel budget.",
                   ["did", "allocated", "yesterday"]),
            "fill": ("If we buy in bulk, we ___ up to twenty per cent.", "will save",
                     ["saves", "saving"], "Если покупать оптом, сэкономим до двадцати процентов."),
            "tap": ("The marketing budget is going to grow next year.", ["was", "did"]),
            "sh": ("If we cut the software budget, the team will work more slowly, so we should cut travel instead.",
                   "Если сократить бюджет на софт, команда будет работать медленнее, поэтому лучше сократить поездки."),
            "st": ("The Budget Discussion", [
                ("Director", "We can increase only one budget line. Which one?",
                 "Мы можем увеличить только одну статью бюджета. Какую?"),
                ("Tom", "Salaries are fixed, so it is between marketing and equipment.",
                 "Зарплаты фиксированы, значит выбор между маркетингом и техникой."),
                ("What does the director decide?", [
                    ("We are going to spend more on marketing — it brings new clients.", True),
                    ("We spent more on it yesterday tomorrow.", False),
                    ("The budget is deciding between itself.", False)])]),
            "d": ("to allocate", "To officially give money for a particular purpose",
                  ["To borrow money from a bank", "To return unused money to the client"]),
            "lw": ("We are going to ___ more to training.", "We are going to allocate more to training.",
                   "allocate", ["allocated", "allocating"]),
            "mw": ("Travel costs are ___ important this year.", "less", "le"),
            "ch": ([("Colleague", "How much can we spend on the event?")], "You",
                   "About two thousand — if we spend more, the training budget will be too small.",
                   ["We spent it yesterday tomorrow.", "The event is spending us."]),
        },
        {
            "t": ("Если превысим бюджет", "If We Go Over Budget"),
            "o": ("Обсудить перерасход бюджета, используя should и первое условное.",
                  "Discuss going over budget using should and the first conditional."),
            "v": [("overspend", "перерасход"), ("to approve", "одобрить"),
                  ("in advance", "заранее"), ("necessary", "необходимый"),
                  ("to track", "отслеживать"), ("warning", "предупреждение"),
                  ("monthly", "ежемесячно")],
            "q": ("Which sentence gives correct advice?",
                  "You should get approval before any extra spending.",
                  ["You should to get approval yesterday.", "You must getting approval last week."]),
            "tr": ("Если мы будем отслеживать расходы ежемесячно, перерасход не станет сюрпризом.",
                   "If we track the costs monthly, overspending will not be a surprise.",
                   ["did", "tracked", "yesterday"]),
            "fill": ("If the project ___ over budget, the director will hear about it immediately.",
                     "goes", ["will go", "went"], "Если проект выйдет за бюджет, директор узнает об этом немедленно."),
            "tap": ("You should warn the manager about extra costs in advance.", ["mustn't", "went"]),
            "sh": ("If we get a warning at seventy per cent of the budget, we will still have time to react.",
                   "Если предупреждение срабатывает на семидесяти процентах бюджета, у нас ещё будет время отреагировать."),
            "st": ("The Surprise Overspend", [
                ("Anna", "The event costs are already above the plan, and it is only October.",
                 "Расходы на мероприятие уже выше плана, а ведь только октябрь."),
                ("Tom", "Why did nobody warn us earlier?", "Почему никто не предупредил раньше?"),
                ("What is the lesson?", [
                    ("We should track the costs monthly and give early warnings.", True),
                    ("We must tracking them yesterday already.", False),
                    ("The costs are warning the plan.", False)])]),
            "d": ("overspend", "To spend more money than was planned",
                  ["To save part of the budget for later", "To ask for a bigger budget politely"]),
            "lw": ("If you ___ extra costs early, we can react.", "If you report extra costs early, we can react.",
                   "report", ["will report", "reported"]),
            "mw": ("All spending above five hundred euros needs ___.", "approval", "ap"),
            "ch": ([("Colleague", "The travel costs look high this month.")], "You",
                   "We should check them today — if we wait for the report, it will be too late to fix.",
                   ["We checked it yesterday tomorrow.", "The costs are travelling to us."]),
        },
    ],

    "A2_BUSINESS_ENGLISH_PROFESSIONAL_INTRODUCTIONS_AND_NETWORKING": [
        {
            "t": ("Знакомство на конференции", "Meeting at a Conference"),
            "o": ("Рассказать о знакомствах, используя past simple и present perfect.",
                  "Talk about new contacts using past simple and present perfect."),
            "v": [("to introduce", "представить (кого-то)"), ("business card", "визитка"),
                  ("to exchange", "обменяться"), ("common interests", "общие интересы"),
                  ("to keep in touch", "оставаться на связи"), ("network", "сеть контактов"),
                  ("since then", "с тех пор")],
            "q": ("Which sentence uses the present perfect correctly?",
                  "We have kept in touch since the conference.",
                  ["We have kept in touch last year.", "We keep in touch since yesterday already."]),
            "tr": ("Я познакомился с ней на конференции, и с тех пор мы сотрудничаем.",
                   "I met her at the conference, and we have cooperated since then.",
                   ["did", "meets", "tomorrow"]),
            "fill": ("He ___ me to the sales director at the dinner.", "introduced",
                     ["has introduce", "introducing"], "Он представил меня директору по продажам на ужине."),
            "tap": ("We have exchanged contacts with three potential partners.", ["was", "did"]),
            "sh": ("I have just met the founder of a logistics startup, and we have agreed to call next week.",
                   "Я только что познакомился с основателем логистического стартапа, и мы договорились созвониться на следующей неделе."),
            "st": ("After the Panel", [
                ("Stranger", "Excuse me, I enjoyed your presentation. I'm Lena from SoftLine.",
                 "Извините, мне понравилась ваша презентация. Я Лена из SoftLine."),
                ("Anna", "Thank you! Nice to meet you, Lena. Have you been to this conference before?",
                 "Спасибо! Приятно познакомиться, Лена. Вы раньше были на этой конференции?"),
                ("What does Lena answer?", [
                    ("Yes, I came last year too, and it has grown a lot.", True),
                    ("Yes, I come tomorrow also last year.", False),
                    ("The conference is meeting me before.", False)])]),
            "d": ("to keep in touch", "To continue to communicate with someone",
                  ["To forget a contact after one meeting", "To send one invoice per year"]),
            "lw": ("We have ___ business cards.", "We have exchanged business cards.",
                   "exchanged", ["exchange", "exchanging"]),
            "mw": ("Nice to ___ you at last!", "meet", "me"),
            "ch": ([("Colleague", "Did you talk to the speaker after the session?")], "You",
                   "Yes, we exchanged contacts and have already emailed twice.",
                   ["Yes, I talk to him tomorrow.", "The speaker is emailing me."]),
        },
        {
            "t": ("Нетворкинг на завтра", "Networking Tomorrow"),
            "o": ("Рассказать о планах на нетворкинг и сравнить мероприятия.",
                  "Talk about networking plans and compare events."),
            "v": [("trade fair", "отраслевая выставка"), ("more useful", "полезнее"),
                  ("to attend", "посетить"), ("to register", "зарегистрироваться"),
                  ("in advance", "заранее"), ("bigger", "больше"),
                  ("follow-up", "последующее письмо /跟进")],
            "q": ("Which sentence talks about the future?",
                  "I am going to attend two networking events this month.",
                  ["I attended two events last month.", "I has attended two events yesterday already."]),
            "tr": ("Выставка в этом году больше, и я собираюсь посетить оба дня.",
                   "The trade fair is bigger this year, and I am going to attend both days.",
                   ["did", "was", "yesterday"]),
            "fill": ("Small events are ___ useful for real contacts than huge ones.", "more",
                     ["most", "much"], "Небольшие мероприятия полезнее для реальных контактов, чем огромные."),
            "tap": ("I am going to register for the conference in advance.", ["was", "did"]),
            "sh": ("If you send a short follow-up email the day after the event, people will remember you.",
                   "Если на следующий день после мероприятия отправить короткое письмо, вас запомнят."),
            "st": ("Which Event?", [
                ("Tom", "There are two events in May: a big expo and a small business breakfast.",
                 "В мае два мероприятия: большая выставка и небольшой бизнес-завтрак."),
                ("Anna", "The breakfast is smaller, but the contacts are more relevant.",
                 "Завтрак меньше, но контакты более релевантные."),
                ("What do they decide?", [
                    ("I am going to attend the breakfast, and you should visit the expo.", True),
                    ("I attended the breakfast yesterday tomorrow.", False),
                    ("The events are attending us in May.", False)])]),
            "d": ("trade fair", "A big event where companies show their products",
                  ["A small meeting of two colleagues", "An online course about sales"]),
            "lw": ("I am going to ___ for the dinner.", "I am going to register for the dinner.",
                   "register", ["registered", "registering"]),
            "mw": ("A follow-up email is ___ than silence.", "better", "be"),
            "ch": ([("Colleague", "Are you going to the expo on Wednesday?")], "You",
                   "Yes — if I collect twenty contacts, the trip will be worth the price.",
                   ["I went there yesterday tomorrow.", "The expo is collecting me."]),
        },
        {
            "t": ("Как поддерживать связи", "How to Maintain Contacts"),
            "o": ("Дать советы о поддержании связей, используя should и первое условное.",
                  "Give advice on maintaining contacts using should and the first conditional."),
            "v": [("regularly", "регулярно"), ("congratulations", "поздравления"),
                  ("to mention", "упомянуть"), ("mutual contact", "общий контакт"),
                  ("to recommend", "порекомендовать"), ("genuine", "искренний"),
                  ("to add on LinkedIn", "добавить в LinkedIn")],
            "q": ("Which sentence gives correct advice?",
                  "You should congratulate contacts on their promotions.",
                  ["You should to congratulate them yesterday.", "You must congratulating them last year."]),
            "tr": ("Если ты упомянешь общего знакомого, разговор начнётся легче.",
                   "If you mention a mutual contact, the conversation will start more easily.",
                   ["did", "mentioned", "yesterday"]),
            "fill": ("If you only write when you ___ something, people will notice.",
                     "need", ["will need", "needed"], "Если писать только когда что-то нужно, люди это заметят."),
            "tap": ("You should add new contacts on LinkedIn within a day.", ["mustn't", "went"]),
            "sh": ("If you recommend a contact to a client, both of them will trust you more in the future.",
                   "Если порекомендовать контакт клиенту, в будущем оба будут больше вам доверять."),
            "st": ("The One-Sided Contact", [
                ("Anna", "This supplier only calls when he wants to sell something.",
                 "Этот поставщик звонит только когда хочет что-то продать."),
                ("Tom", "That's not real networking. What should we do?",
                 "Это не настоящий нетворкинг. Что нам делать?"),
                ("What does Anna advise?", [
                    ("We should also share useful news, not only requests.", True),
                    ("We must to share news yesterday already.", False),
                    ("The supplier is networking us calls.", False)])]),
            "d": ("genuine", "Real and honest, not pretended",
                  ["Very formal and cold", "Only about business numbers"]),
            "lw": ("If you ___ them to a client, they will thank you.", "If you recommend them to a client, they will thank you.",
                   "recommend", ["will recommend", "recommended"]),
            "mw": ("You should keep in touch ___ often.", "more", "mo"),
            "ch": ([("Colleague", "Should I message the new contact today?")], "You",
                   "Yes — if you write while the conversation is fresh, they will remember you.",
                   ["I messaged them yesterday tomorrow.", "The contact is messaging me."]),
        },
    ],
}
