// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Profile представляет профиль пользователя
type Profile struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	NativeLang    *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=native_lang,json=nativeLang,proto3" json:"native_lang,omitempty"`
	TargetLang    *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	Bio           *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	DateOfBirth   *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Timezone      *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetFirstName() *wrapperspb.StringValue {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *Profile) GetLastName() *wrapperspb.StringValue {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *Profile) GetNativeLang() *wrapperspb.StringValue {
	if x != nil {
		return x.NativeLang
	}
	return nil
}

func (x *Profile) GetTargetLang() *wrapperspb.StringValue {
	if x != nil {
		return x.TargetLang
	}
	return nil
}

func (x *Profile) GetBio() *wrapperspb.StringValue {
	if x != nil {
		return x.Bio
	}
	return nil
}

func (x *Profile) GetAvatarUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.AvatarUrl
	}
	return nil
}

func (x *Profile) GetDateOfBirth() *wrapperspb.StringValue {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *Profile) GetTimezone() *wrapperspb.StringValue {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *Profile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetProfileRequest содержит ID пользователя
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetProfileResponse содержит профиль пользователя
type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// UpdateProfileRequest содержит данные для обновления профиля
type UpdateProfileRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserId        string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	NativeLang    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=native_lang,json=nativeLang,proto3" json:"native_lang,omitempty"`
	TargetLang    *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	Bio           *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	DateOfBirth   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Timezone      *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetFirstName() *wrapperspb.StringValue {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *UpdateProfileRequest) GetLastName() *wrapperspb.StringValue {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *UpdateProfileRequest) GetNativeLang() *wrapperspb.StringValue {
	if x != nil {
		return x.NativeLang
	}
	return nil
}

func (x *UpdateProfileRequest) GetTargetLang() *wrapperspb.StringValue {
	if x != nil {
		return x.TargetLang
	}
	return nil
}

func (x *UpdateProfileRequest) GetBio() *wrapperspb.StringValue {
	if x != nil {
		return x.Bio
	}
	return nil
}

func (x *UpdateProfileRequest) GetAvatarUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.AvatarUrl
	}
	return nil
}

func (x *UpdateProfileRequest) GetDateOfBirth() *wrapperspb.StringValue {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateProfileRequest) GetTimezone() *wrapperspb.StringValue {
	if x != nil {
		return x.Timezone
	}
	return nil
}

// UpdateProfileResponse содержит обновленный профиль
type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetUserLanguagesRequest содержит ID пользователя
type GetUserLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLanguagesRequest) Reset() {
	*x = GetUserLanguagesRequest{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLanguagesRequest) ProtoMessage() {}

func (x *GetUserLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLanguagesRequest.ProtoReflect.Descriptor instead.
func (*GetUserLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserLanguagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserLanguagesResponse содержит языковые настройки
type GetUserLanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NativeLang    string                 `protobuf:"bytes,1,opt,name=native_lang,json=nativeLang,proto3" json:"native_lang,omitempty"`
	TargetLang    string                 `protobuf:"bytes,2,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLanguagesResponse) Reset() {
	*x = GetUserLanguagesResponse{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLanguagesResponse) ProtoMessage() {}

func (x *GetUserLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLanguagesResponse.ProtoReflect.Descriptor instead.
func (*GetUserLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserLanguagesResponse) GetNativeLang() string {
	if x != nil {
		return x.NativeLang
	}
	return ""
}

func (x *GetUserLanguagesResponse) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

// BatchGetProfilesRequest — список user_id для enrichment.
type BatchGetProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetProfilesRequest) Reset() {
	*x = BatchGetProfilesRequest{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetProfilesRequest) ProtoMessage() {}

func (x *BatchGetProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetProfilesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetProfilesRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetProfilesRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// BatchGetProfilesResponse — карта user_id → Profile.
// Не-существующие user_id опускаются (без ошибки).
type BatchGetProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      map[string]*Profile    `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetProfilesResponse) Reset() {
	*x = BatchGetProfilesResponse{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetProfilesResponse) ProtoMessage() {}

func (x *BatchGetProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetProfilesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetProfilesResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetProfilesResponse) GetProfiles() map[string]*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// User представляет пользователя системы
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ListUsersRequest запрос на получение списка пользователей
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

// ListUsersResponse ответ со списком пользователей
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// GetUserRequest запрос на получение пользователя
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserResponse ответ с информацией о пользователе
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// UpdateUserRequest запрос на обновление пользователя
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// UpdateUserResponse ответ с обновленным пользователем
type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// DeleteUserRequest запрос на удаление пользователя
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeleteUserResponse ответ на удаление пользователя
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// OnboardingState — combined state онбординга юзера, читается из profiles.
type OnboardingState struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	UserId           string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NativeLanguage   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=native_language,json=nativeLanguage,proto3" json:"native_language,omitempty"` // 'ru' | 'en' | ...
	TargetLanguage   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"`
	ProficiencyLevel *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=proficiency_level,json=proficiencyLevel,proto3" json:"proficiency_level,omitempty"` // 'beginner'..'b2'|'just_for_fun'
	DailyGoalXp      *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=daily_goal_xp,json=dailyGoalXp,proto3" json:"daily_goal_xp,omitempty"`              // 10/20/30/50
	Motivation       []string                `protobuf:"bytes,6,rep,name=motivation,proto3" json:"motivation,omitempty"`                                     // ['travel','work',...]
	SignupSource     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=signup_source,json=signupSource,proto3" json:"signup_source,omitempty"`             // 'tiktok'|'friend'|...
	PlacementScore   *wrapperspb.Int32Value  `protobuf:"bytes,8,opt,name=placement_score,json=placementScore,proto3" json:"placement_score,omitempty"`       // 0..5
	DateOfBirth      *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`              // ISO date
	OnboardedAt      *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=onboarded_at,json=onboardedAt,proto3" json:"onboarded_at,omitempty"`
	Completed        bool                    `protobuf:"varint,11,opt,name=completed,proto3" json:"completed,omitempty"` // == onboarded_at != null
	// === Onboarding v3 (Oki-style) ===
	// См. docs/tasks/mob/onboarding-v3-oki-style.md §2.1.
	AgeBracket         *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=age_bracket,json=ageBracket,proto3" json:"age_bracket,omitempty"`                           // '7-12'|'13-17'|...|'55+'
	DailyCommitMinutes *wrapperspb.Int32Value  `protobuf:"bytes,13,opt,name=daily_commit_minutes,json=dailyCommitMinutes,proto3" json:"daily_commit_minutes,omitempty"` // 5|10|15|25
	PainPoint          *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=pain_point,json=painPoint,proto3" json:"pain_point,omitempty"`                              // 'fear_speaking'|'lack_vocab'|...
	SpeakingSituation  *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=speaking_situation,json=speakingSituation,proto3" json:"speaking_situation,omitempty"`      // 'freeze'|'translate_in_head'|...
	PastBlocker        *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=past_blocker,json=pastBlocker,proto3" json:"past_blocker,omitempty"`                        // 'boring'|'too_hard'|...
	FutureRegret       *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=future_regret,json=futureRegret,proto3" json:"future_regret,omitempty"`                     // 'stay_same'|'limit_self'|...
	EmotionalReaction  *wrapperspb.StringValue `protobuf:"bytes,18,opt,name=emotional_reaction,json=emotionalReaction,proto3" json:"emotional_reaction,omitempty"`      // 'lose_confidence'|'upset'|...
	ReminderSlot       *wrapperspb.StringValue `protobuf:"bytes,19,opt,name=reminder_slot,json=reminderSlot,proto3" json:"reminder_slot,omitempty"`                     // 'morning'|'day'|'evening'|'flex'
	PaywallSeenAt      *timestamppb.Timestamp  `protobuf:"bytes,20,opt,name=paywall_seen_at,json=paywallSeenAt,proto3" json:"paywall_seen_at,omitempty"`
	PaywallChoice      *wrapperspb.StringValue `protobuf:"bytes,21,opt,name=paywall_choice,json=paywallChoice,proto3" json:"paywall_choice,omitempty"` // 'annual'|'monthly'|'dismissed'|'special_offer'
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OnboardingState) Reset() {
	*x = OnboardingState{}
	mi := &file_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardingState) ProtoMessage() {}

func (x *OnboardingState) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardingState.ProtoReflect.Descriptor instead.
func (*OnboardingState) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *OnboardingState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OnboardingState) GetNativeLanguage() *wrapperspb.StringValue {
	if x != nil {
		return x.NativeLanguage
	}
	return nil
}

func (x *OnboardingState) GetTargetLanguage() *wrapperspb.StringValue {
	if x != nil {
		return x.TargetLanguage
	}
	return nil
}

func (x *OnboardingState) GetProficiencyLevel() *wrapperspb.StringValue {
	if x != nil {
		return x.ProficiencyLevel
	}
	return nil
}

func (x *OnboardingState) GetDailyGoalXp() *wrapperspb.Int32Value {
	if x != nil {
		return x.DailyGoalXp
	}
	return nil
}

func (x *OnboardingState) GetMotivation() []string {
	if x != nil {
		return x.Motivation
	}
	return nil
}

func (x *OnboardingState) GetSignupSource() *wrapperspb.StringValue {
	if x != nil {
		return x.SignupSource
	}
	return nil
}

func (x *OnboardingState) GetPlacementScore() *wrapperspb.Int32Value {
	if x != nil {
		return x.PlacementScore
	}
	return nil
}

func (x *OnboardingState) GetDateOfBirth() *wrapperspb.StringValue {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *OnboardingState) GetOnboardedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OnboardedAt
	}
	return nil
}

func (x *OnboardingState) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *OnboardingState) GetAgeBracket() *wrapperspb.StringValue {
	if x != nil {
		return x.AgeBracket
	}
	return nil
}

func (x *OnboardingState) GetDailyCommitMinutes() *wrapperspb.Int32Value {
	if x != nil {
		return x.DailyCommitMinutes
	}
	return nil
}

func (x *OnboardingState) GetPainPoint() *wrapperspb.StringValue {
	if x != nil {
		return x.PainPoint
	}
	return nil
}

func (x *OnboardingState) GetSpeakingSituation() *wrapperspb.StringValue {
	if x != nil {
		return x.SpeakingSituation
	}
	return nil
}

func (x *OnboardingState) GetPastBlocker() *wrapperspb.StringValue {
	if x != nil {
		return x.PastBlocker
	}
	return nil
}

func (x *OnboardingState) GetFutureRegret() *wrapperspb.StringValue {
	if x != nil {
		return x.FutureRegret
	}
	return nil
}

func (x *OnboardingState) GetEmotionalReaction() *wrapperspb.StringValue {
	if x != nil {
		return x.EmotionalReaction
	}
	return nil
}

func (x *OnboardingState) GetReminderSlot() *wrapperspb.StringValue {
	if x != nil {
		return x.ReminderSlot
	}
	return nil
}

func (x *OnboardingState) GetPaywallSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaywallSeenAt
	}
	return nil
}

func (x *OnboardingState) GetPaywallChoice() *wrapperspb.StringValue {
	if x != nil {
		return x.PaywallChoice
	}
	return nil
}

// GetOnboardingStateRequest — юзер из контекста.
type GetOnboardingStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnboardingStateRequest) Reset() {
	*x = GetOnboardingStateRequest{}
	mi := &file_user_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnboardingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnboardingStateRequest) ProtoMessage() {}

func (x *GetOnboardingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnboardingStateRequest.ProtoReflect.Descriptor instead.
func (*GetOnboardingStateRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetOnboardingStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetOnboardingStateResponse — current state.
type GetOnboardingStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *OnboardingState       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnboardingStateResponse) Reset() {
	*x = GetOnboardingStateResponse{}
	mi := &file_user_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnboardingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnboardingStateResponse) ProtoMessage() {}

func (x *GetOnboardingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnboardingStateResponse.ProtoReflect.Descriptor instead.
func (*GetOnboardingStateResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetOnboardingStateResponse) GetState() *OnboardingState {
	if x != nil {
		return x.State
	}
	return nil
}

// PatchOnboardingStateRequest — partial update.
// Любое не-nil поле перезаписывает текущее значение в БД. nil — оставляет
// как есть. Поле motivation особое — используется motivation_set, чтобы
// отличить «не передавали» от «явно очистили в []».
type PatchOnboardingStateRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	UserId           string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NativeLanguage   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=native_language,json=nativeLanguage,proto3" json:"native_language,omitempty"`
	TargetLanguage   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"`
	ProficiencyLevel *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=proficiency_level,json=proficiencyLevel,proto3" json:"proficiency_level,omitempty"`
	DailyGoalXp      *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=daily_goal_xp,json=dailyGoalXp,proto3" json:"daily_goal_xp,omitempty"`
	// motivation: repeated → replace целиком (не append).
	// motivation_set=false → не трогаем колонку.
	// motivation_set=true  → пишем motivation (даже если пусто).
	Motivation     []string                `protobuf:"bytes,6,rep,name=motivation,proto3" json:"motivation,omitempty"`
	MotivationSet  bool                    `protobuf:"varint,7,opt,name=motivation_set,json=motivationSet,proto3" json:"motivation_set,omitempty"`
	SignupSource   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=signup_source,json=signupSource,proto3" json:"signup_source,omitempty"`
	PlacementScore *wrapperspb.Int32Value  `protobuf:"bytes,9,opt,name=placement_score,json=placementScore,proto3" json:"placement_score,omitempty"`
	DateOfBirth    *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	// === Onboarding v3 (Oki-style) — все nullable для partial-update ===
	AgeBracket         *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=age_bracket,json=ageBracket,proto3" json:"age_bracket,omitempty"`
	DailyCommitMinutes *wrapperspb.Int32Value  `protobuf:"bytes,12,opt,name=daily_commit_minutes,json=dailyCommitMinutes,proto3" json:"daily_commit_minutes,omitempty"`
	PainPoint          *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=pain_point,json=painPoint,proto3" json:"pain_point,omitempty"`
	SpeakingSituation  *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=speaking_situation,json=speakingSituation,proto3" json:"speaking_situation,omitempty"`
	PastBlocker        *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=past_blocker,json=pastBlocker,proto3" json:"past_blocker,omitempty"`
	FutureRegret       *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=future_regret,json=futureRegret,proto3" json:"future_regret,omitempty"`
	EmotionalReaction  *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=emotional_reaction,json=emotionalReaction,proto3" json:"emotional_reaction,omitempty"`
	ReminderSlot       *wrapperspb.StringValue `protobuf:"bytes,18,opt,name=reminder_slot,json=reminderSlot,proto3" json:"reminder_slot,omitempty"`
	PaywallSeenAt      *timestamppb.Timestamp  `protobuf:"bytes,19,opt,name=paywall_seen_at,json=paywallSeenAt,proto3" json:"paywall_seen_at,omitempty"`
	PaywallChoice      *wrapperspb.StringValue `protobuf:"bytes,20,opt,name=paywall_choice,json=paywallChoice,proto3" json:"paywall_choice,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PatchOnboardingStateRequest) Reset() {
	*x = PatchOnboardingStateRequest{}
	mi := &file_user_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchOnboardingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchOnboardingStateRequest) ProtoMessage() {}

func (x *PatchOnboardingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchOnboardingStateRequest.ProtoReflect.Descriptor instead.
func (*PatchOnboardingStateRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *PatchOnboardingStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PatchOnboardingStateRequest) GetNativeLanguage() *wrapperspb.StringValue {
	if x != nil {
		return x.NativeLanguage
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetTargetLanguage() *wrapperspb.StringValue {
	if x != nil {
		return x.TargetLanguage
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetProficiencyLevel() *wrapperspb.StringValue {
	if x != nil {
		return x.ProficiencyLevel
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetDailyGoalXp() *wrapperspb.Int32Value {
	if x != nil {
		return x.DailyGoalXp
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetMotivation() []string {
	if x != nil {
		return x.Motivation
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetMotivationSet() bool {
	if x != nil {
		return x.MotivationSet
	}
	return false
}

func (x *PatchOnboardingStateRequest) GetSignupSource() *wrapperspb.StringValue {
	if x != nil {
		return x.SignupSource
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetPlacementScore() *wrapperspb.Int32Value {
	if x != nil {
		return x.PlacementScore
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetDateOfBirth() *wrapperspb.StringValue {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetAgeBracket() *wrapperspb.StringValue {
	if x != nil {
		return x.AgeBracket
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetDailyCommitMinutes() *wrapperspb.Int32Value {
	if x != nil {
		return x.DailyCommitMinutes
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetPainPoint() *wrapperspb.StringValue {
	if x != nil {
		return x.PainPoint
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetSpeakingSituation() *wrapperspb.StringValue {
	if x != nil {
		return x.SpeakingSituation
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetPastBlocker() *wrapperspb.StringValue {
	if x != nil {
		return x.PastBlocker
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetFutureRegret() *wrapperspb.StringValue {
	if x != nil {
		return x.FutureRegret
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetEmotionalReaction() *wrapperspb.StringValue {
	if x != nil {
		return x.EmotionalReaction
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetReminderSlot() *wrapperspb.StringValue {
	if x != nil {
		return x.ReminderSlot
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetPaywallSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaywallSeenAt
	}
	return nil
}

func (x *PatchOnboardingStateRequest) GetPaywallChoice() *wrapperspb.StringValue {
	if x != nil {
		return x.PaywallChoice
	}
	return nil
}

// PatchOnboardingStateResponse — обновлённый state.
type PatchOnboardingStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *OnboardingState       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchOnboardingStateResponse) Reset() {
	*x = PatchOnboardingStateResponse{}
	mi := &file_user_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchOnboardingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchOnboardingStateResponse) ProtoMessage() {}

func (x *PatchOnboardingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchOnboardingStateResponse.ProtoReflect.Descriptor instead.
func (*PatchOnboardingStateResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *PatchOnboardingStateResponse) GetState() *OnboardingState {
	if x != nil {
		return x.State
	}
	return nil
}

// CompleteOnboardingRequest — финальный шаг.
type CompleteOnboardingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingRequest) Reset() {
	*x = CompleteOnboardingRequest{}
	mi := &file_user_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingRequest) ProtoMessage() {}

func (x *CompleteOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{23}
}

func (x *CompleteOnboardingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CompleteOnboardingResponse — обновлённый state с onboarded_at.
type CompleteOnboardingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *OnboardingState       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingResponse) Reset() {
	*x = CompleteOnboardingResponse{}
	mi := &file_user_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingResponse) ProtoMessage() {}

func (x *CompleteOnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingResponse.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *CompleteOnboardingResponse) GetState() *OnboardingState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x87\x05\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12;\n" +
	"\n" +
	"first_name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\tfirstName\x129\n" +
	"\tlast_name\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\blastName\x12=\n" +
	"\vnative_lang\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"nativeLang\x12=\n" +
	"\vtarget_lang\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"targetLang\x12.\n" +
	"\x03bio\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x03bio\x12;\n" +
	"\n" +
	"avatar_url\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\tavatarUrl\x12@\n" +
	"\rdate_of_birth\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\vdateOfBirth\x128\n" +
	"\btimezone\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\btimezone\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x12GetProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.user.v1.ProfileR\aprofile\"\x8e\x04\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12;\n" +
	"\n" +
	"first_name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\tfirstName\x129\n" +
	"\tlast_name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\blastName\x12=\n" +
	"\vnative_lang\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"nativeLang\x12=\n" +
	"\vtarget_lang\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"targetLang\x12.\n" +
	"\x03bio\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x03bio\x12;\n" +
	"\n" +
	"avatar_url\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\tavatarUrl\x12@\n" +
	"\rdate_of_birth\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\vdateOfBirth\x128\n" +
	"\btimezone\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\btimezone\"C\n" +
	"\x15UpdateProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.user.v1.ProfileR\aprofile\"2\n" +
	"\x17GetUserLanguagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\\\n" +
	"\x18GetUserLanguagesResponse\x12\x1f\n" +
	"\vnative_lang\x18\x01 \x01(\tR\n" +
	"nativeLang\x12\x1f\n" +
	"\vtarget_lang\x18\x02 \x01(\tR\n" +
	"targetLang\"4\n" +
	"\x17BatchGetProfilesRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xb6\x01\n" +
	"\x18BatchGetProfilesResponse\x12K\n" +
	"\bprofiles\x18\x01 \x03(\v2/.user.v1.BatchGetProfilesResponse.ProfilesEntryR\bprofiles\x1aM\n" +
	"\rProfilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.user.v1.ProfileR\x05value:\x028\x01\"\xd3\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x12\n" +
	"\x10ListUsersRequest\"8\n" +
	"\x11ListUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.user.v1.UserR\x05users\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x0fGetUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"]\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"7\n" +
	"\x12UpdateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc1\n" +
	"\n" +
	"\x0fOnboardingState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12E\n" +
	"\x0fnative_language\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x0enativeLanguage\x12E\n" +
	"\x0ftarget_language\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x0etargetLanguage\x12I\n" +
	"\x11proficiency_level\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x10proficiencyLevel\x12?\n" +
	"\rdaily_goal_xp\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\vdailyGoalXp\x12\x1e\n" +
	"\n" +
	"motivation\x18\x06 \x03(\tR\n" +
	"motivation\x12A\n" +
	"\rsignup_source\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\fsignupSource\x12D\n" +
	"\x0fplacement_score\x18\b \x01(\v2\x1b.google.protobuf.Int32ValueR\x0eplacementScore\x12@\n" +
	"\rdate_of_birth\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\vdateOfBirth\x12=\n" +
	"\fonboarded_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vonboardedAt\x12\x1c\n" +
	"\tcompleted\x18\v \x01(\bR\tcompleted\x12=\n" +
	"\vage_bracket\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"ageBracket\x12M\n" +
	"\x14daily_commit_minutes\x18\r \x01(\v2\x1b.google.protobuf.Int32ValueR\x12dailyCommitMinutes\x12;\n" +
	"\n" +
	"pain_point\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\tpainPoint\x12K\n" +
	"\x12speaking_situation\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\x11speakingSituation\x12?\n" +
	"\fpast_blocker\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\vpastBlocker\x12A\n" +
	"\rfuture_regret\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\ffutureRegret\x12K\n" +
	"\x12emotional_reaction\x18\x12 \x01(\v2\x1c.google.protobuf.StringValueR\x11emotionalReaction\x12A\n" +
	"\rreminder_slot\x18\x13 \x01(\v2\x1c.google.protobuf.StringValueR\freminderSlot\x12B\n" +
	"\x0fpaywall_seen_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\rpaywallSeenAt\x12C\n" +
	"\x0epaywall_choice\x18\x15 \x01(\v2\x1c.google.protobuf.StringValueR\rpaywallChoice\"4\n" +
	"\x19GetOnboardingStateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x1aGetOnboardingStateResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.user.v1.OnboardingStateR\x05state\"\x97\n" +
	"\n" +
	"\x1bPatchOnboardingStateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12E\n" +
	"\x0fnative_language\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x0enativeLanguage\x12E\n" +
	"\x0ftarget_language\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x0etargetLanguage\x12I\n" +
	"\x11proficiency_level\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x10proficiencyLevel\x12?\n" +
	"\rdaily_goal_xp\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\vdailyGoalXp\x12\x1e\n" +
	"\n" +
	"motivation\x18\x06 \x03(\tR\n" +
	"motivation\x12%\n" +
	"\x0emotivation_set\x18\a \x01(\bR\rmotivationSet\x12A\n" +
	"\rsignup_source\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\fsignupSource\x12D\n" +
	"\x0fplacement_score\x18\t \x01(\v2\x1b.google.protobuf.Int32ValueR\x0eplacementScore\x12@\n" +
	"\rdate_of_birth\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\vdateOfBirth\x12=\n" +
	"\vage_bracket\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"ageBracket\x12M\n" +
	"\x14daily_commit_minutes\x18\f \x01(\v2\x1b.google.protobuf.Int32ValueR\x12dailyCommitMinutes\x12;\n" +
	"\n" +
	"pain_point\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\tpainPoint\x12K\n" +
	"\x12speaking_situation\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\x11speakingSituation\x12?\n" +
	"\fpast_blocker\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\vpastBlocker\x12A\n" +
	"\rfuture_regret\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\ffutureRegret\x12K\n" +
	"\x12emotional_reaction\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\x11emotionalReaction\x12A\n" +
	"\rreminder_slot\x18\x12 \x01(\v2\x1c.google.protobuf.StringValueR\freminderSlot\x12B\n" +
	"\x0fpaywall_seen_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\rpaywallSeenAt\x12C\n" +
	"\x0epaywall_choice\x18\x14 \x01(\v2\x1c.google.protobuf.StringValueR\rpaywallChoice\"N\n" +
	"\x1cPatchOnboardingStateResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.user.v1.OnboardingStateR\x05state\"4\n" +
	"\x19CompleteOnboardingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x1aCompleteOnboardingResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.user.v1.OnboardingStateR\x05state2\x89\a\n" +
	"\vUserService\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.user.v1.GetProfileRequest\x1a\x1b.user.v1.GetProfileResponse\x12N\n" +
	"\rUpdateProfile\x12\x1d.user.v1.UpdateProfileRequest\x1a\x1e.user.v1.UpdateProfileResponse\x12W\n" +
	"\x10GetUserLanguages\x12 .user.v1.GetUserLanguagesRequest\x1a!.user.v1.GetUserLanguagesResponse\x12W\n" +
	"\x10BatchGetProfiles\x12 .user.v1.BatchGetProfilesRequest\x1a!.user.v1.BatchGetProfilesResponse\x12B\n" +
	"\tListUsers\x12\x19.user.v1.ListUsersRequest\x1a\x1a.user.v1.ListUsersResponse\x12<\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\x12E\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x1b.user.v1.UpdateUserResponse\x12E\n" +
	"\n" +
	"DeleteUser\x12\x1a.user.v1.DeleteUserRequest\x1a\x1b.user.v1.DeleteUserResponse\x12]\n" +
	"\x12GetOnboardingState\x12\".user.v1.GetOnboardingStateRequest\x1a#.user.v1.GetOnboardingStateResponse\x12c\n" +
	"\x14PatchOnboardingState\x12$.user.v1.PatchOnboardingStateRequest\x1a%.user.v1.PatchOnboardingStateResponse\x12]\n" +
	"\x12CompleteOnboarding\x12\".user.v1.CompleteOnboardingRequest\x1a#.user.v1.CompleteOnboardingResponseB\x8b\x01\n" +
	"\vcom.user.v1B\tUserProtoP\x01Z4github.com/elearning/shared/pkg/proto/user/v1;userv1\xa2\x02\x03UXX\xaa\x02\aUser.V1\xca\x02\aUser\\V1\xe2\x02\x13User\\V1\\GPBMetadata\xea\x02\bUser::V1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_user_v1_user_proto_goTypes = []any{
	(*Profile)(nil),                      // 0: user.v1.Profile
	(*GetProfileRequest)(nil),            // 1: user.v1.GetProfileRequest
	(*GetProfileResponse)(nil),           // 2: user.v1.GetProfileResponse
	(*UpdateProfileRequest)(nil),         // 3: user.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),        // 4: user.v1.UpdateProfileResponse
	(*GetUserLanguagesRequest)(nil),      // 5: user.v1.GetUserLanguagesRequest
	(*GetUserLanguagesResponse)(nil),     // 6: user.v1.GetUserLanguagesResponse
	(*BatchGetProfilesRequest)(nil),      // 7: user.v1.BatchGetProfilesRequest
	(*BatchGetProfilesResponse)(nil),     // 8: user.v1.BatchGetProfilesResponse
	(*User)(nil),                         // 9: user.v1.User
	(*ListUsersRequest)(nil),             // 10: user.v1.ListUsersRequest
	(*ListUsersResponse)(nil),            // 11: user.v1.ListUsersResponse
	(*GetUserRequest)(nil),               // 12: user.v1.GetUserRequest
	(*GetUserResponse)(nil),              // 13: user.v1.GetUserResponse
	(*UpdateUserRequest)(nil),            // 14: user.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),           // 15: user.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),            // 16: user.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),           // 17: user.v1.DeleteUserResponse
	(*OnboardingState)(nil),              // 18: user.v1.OnboardingState
	(*GetOnboardingStateRequest)(nil),    // 19: user.v1.GetOnboardingStateRequest
	(*GetOnboardingStateResponse)(nil),   // 20: user.v1.GetOnboardingStateResponse
	(*PatchOnboardingStateRequest)(nil),  // 21: user.v1.PatchOnboardingStateRequest
	(*PatchOnboardingStateResponse)(nil), // 22: user.v1.PatchOnboardingStateResponse
	(*CompleteOnboardingRequest)(nil),    // 23: user.v1.CompleteOnboardingRequest
	(*CompleteOnboardingResponse)(nil),   // 24: user.v1.CompleteOnboardingResponse
	nil,                                  // 25: user.v1.BatchGetProfilesResponse.ProfilesEntry
	(*wrapperspb.StringValue)(nil),       // 26: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),        // 27: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil),        // 28: google.protobuf.Int32Value
}
var file_user_v1_user_proto_depIdxs = []int32{
	26, // 0: user.v1.Profile.first_name:type_name -> google.protobuf.StringValue
	26, // 1: user.v1.Profile.last_name:type_name -> google.protobuf.StringValue
	26, // 2: user.v1.Profile.native_lang:type_name -> google.protobuf.StringValue
	26, // 3: user.v1.Profile.target_lang:type_name -> google.protobuf.StringValue
	26, // 4: user.v1.Profile.bio:type_name -> google.protobuf.StringValue
	26, // 5: user.v1.Profile.avatar_url:type_name -> google.protobuf.StringValue
	26, // 6: user.v1.Profile.date_of_birth:type_name -> google.protobuf.StringValue
	26, // 7: user.v1.Profile.timezone:type_name -> google.protobuf.StringValue
	27, // 8: user.v1.Profile.created_at:type_name -> google.protobuf.Timestamp
	27, // 9: user.v1.Profile.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: user.v1.GetProfileResponse.profile:type_name -> user.v1.Profile
	26, // 11: user.v1.UpdateProfileRequest.first_name:type_name -> google.protobuf.StringValue
	26, // 12: user.v1.UpdateProfileRequest.last_name:type_name -> google.protobuf.StringValue
	26, // 13: user.v1.UpdateProfileRequest.native_lang:type_name -> google.protobuf.StringValue
	26, // 14: user.v1.UpdateProfileRequest.target_lang:type_name -> google.protobuf.StringValue
	26, // 15: user.v1.UpdateProfileRequest.bio:type_name -> google.protobuf.StringValue
	26, // 16: user.v1.UpdateProfileRequest.avatar_url:type_name -> google.protobuf.StringValue
	26, // 17: user.v1.UpdateProfileRequest.date_of_birth:type_name -> google.protobuf.StringValue
	26, // 18: user.v1.UpdateProfileRequest.timezone:type_name -> google.protobuf.StringValue
	0,  // 19: user.v1.UpdateProfileResponse.profile:type_name -> user.v1.Profile
	25, // 20: user.v1.BatchGetProfilesResponse.profiles:type_name -> user.v1.BatchGetProfilesResponse.ProfilesEntry
	27, // 21: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	27, // 22: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 23: user.v1.ListUsersResponse.users:type_name -> user.v1.User
	9,  // 24: user.v1.GetUserResponse.user:type_name -> user.v1.User
	9,  // 25: user.v1.UpdateUserResponse.user:type_name -> user.v1.User
	26, // 26: user.v1.OnboardingState.native_language:type_name -> google.protobuf.StringValue
	26, // 27: user.v1.OnboardingState.target_language:type_name -> google.protobuf.StringValue
	26, // 28: user.v1.OnboardingState.proficiency_level:type_name -> google.protobuf.StringValue
	28, // 29: user.v1.OnboardingState.daily_goal_xp:type_name -> google.protobuf.Int32Value
	26, // 30: user.v1.OnboardingState.signup_source:type_name -> google.protobuf.StringValue
	28, // 31: user.v1.OnboardingState.placement_score:type_name -> google.protobuf.Int32Value
	26, // 32: user.v1.OnboardingState.date_of_birth:type_name -> google.protobuf.StringValue
	27, // 33: user.v1.OnboardingState.onboarded_at:type_name -> google.protobuf.Timestamp
	26, // 34: user.v1.OnboardingState.age_bracket:type_name -> google.protobuf.StringValue
	28, // 35: user.v1.OnboardingState.daily_commit_minutes:type_name -> google.protobuf.Int32Value
	26, // 36: user.v1.OnboardingState.pain_point:type_name -> google.protobuf.StringValue
	26, // 37: user.v1.OnboardingState.speaking_situation:type_name -> google.protobuf.StringValue
	26, // 38: user.v1.OnboardingState.past_blocker:type_name -> google.protobuf.StringValue
	26, // 39: user.v1.OnboardingState.future_regret:type_name -> google.protobuf.StringValue
	26, // 40: user.v1.OnboardingState.emotional_reaction:type_name -> google.protobuf.StringValue
	26, // 41: user.v1.OnboardingState.reminder_slot:type_name -> google.protobuf.StringValue
	27, // 42: user.v1.OnboardingState.paywall_seen_at:type_name -> google.protobuf.Timestamp
	26, // 43: user.v1.OnboardingState.paywall_choice:type_name -> google.protobuf.StringValue
	18, // 44: user.v1.GetOnboardingStateResponse.state:type_name -> user.v1.OnboardingState
	26, // 45: user.v1.PatchOnboardingStateRequest.native_language:type_name -> google.protobuf.StringValue
	26, // 46: user.v1.PatchOnboardingStateRequest.target_language:type_name -> google.protobuf.StringValue
	26, // 47: user.v1.PatchOnboardingStateRequest.proficiency_level:type_name -> google.protobuf.StringValue
	28, // 48: user.v1.PatchOnboardingStateRequest.daily_goal_xp:type_name -> google.protobuf.Int32Value
	26, // 49: user.v1.PatchOnboardingStateRequest.signup_source:type_name -> google.protobuf.StringValue
	28, // 50: user.v1.PatchOnboardingStateRequest.placement_score:type_name -> google.protobuf.Int32Value
	26, // 51: user.v1.PatchOnboardingStateRequest.date_of_birth:type_name -> google.protobuf.StringValue
	26, // 52: user.v1.PatchOnboardingStateRequest.age_bracket:type_name -> google.protobuf.StringValue
	28, // 53: user.v1.PatchOnboardingStateRequest.daily_commit_minutes:type_name -> google.protobuf.Int32Value
	26, // 54: user.v1.PatchOnboardingStateRequest.pain_point:type_name -> google.protobuf.StringValue
	26, // 55: user.v1.PatchOnboardingStateRequest.speaking_situation:type_name -> google.protobuf.StringValue
	26, // 56: user.v1.PatchOnboardingStateRequest.past_blocker:type_name -> google.protobuf.StringValue
	26, // 57: user.v1.PatchOnboardingStateRequest.future_regret:type_name -> google.protobuf.StringValue
	26, // 58: user.v1.PatchOnboardingStateRequest.emotional_reaction:type_name -> google.protobuf.StringValue
	26, // 59: user.v1.PatchOnboardingStateRequest.reminder_slot:type_name -> google.protobuf.StringValue
	27, // 60: user.v1.PatchOnboardingStateRequest.paywall_seen_at:type_name -> google.protobuf.Timestamp
	26, // 61: user.v1.PatchOnboardingStateRequest.paywall_choice:type_name -> google.protobuf.StringValue
	18, // 62: user.v1.PatchOnboardingStateResponse.state:type_name -> user.v1.OnboardingState
	18, // 63: user.v1.CompleteOnboardingResponse.state:type_name -> user.v1.OnboardingState
	0,  // 64: user.v1.BatchGetProfilesResponse.ProfilesEntry.value:type_name -> user.v1.Profile
	1,  // 65: user.v1.UserService.GetProfile:input_type -> user.v1.GetProfileRequest
	3,  // 66: user.v1.UserService.UpdateProfile:input_type -> user.v1.UpdateProfileRequest
	5,  // 67: user.v1.UserService.GetUserLanguages:input_type -> user.v1.GetUserLanguagesRequest
	7,  // 68: user.v1.UserService.BatchGetProfiles:input_type -> user.v1.BatchGetProfilesRequest
	10, // 69: user.v1.UserService.ListUsers:input_type -> user.v1.ListUsersRequest
	12, // 70: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	14, // 71: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	16, // 72: user.v1.UserService.DeleteUser:input_type -> user.v1.DeleteUserRequest
	19, // 73: user.v1.UserService.GetOnboardingState:input_type -> user.v1.GetOnboardingStateRequest
	21, // 74: user.v1.UserService.PatchOnboardingState:input_type -> user.v1.PatchOnboardingStateRequest
	23, // 75: user.v1.UserService.CompleteOnboarding:input_type -> user.v1.CompleteOnboardingRequest
	2,  // 76: user.v1.UserService.GetProfile:output_type -> user.v1.GetProfileResponse
	4,  // 77: user.v1.UserService.UpdateProfile:output_type -> user.v1.UpdateProfileResponse
	6,  // 78: user.v1.UserService.GetUserLanguages:output_type -> user.v1.GetUserLanguagesResponse
	8,  // 79: user.v1.UserService.BatchGetProfiles:output_type -> user.v1.BatchGetProfilesResponse
	11, // 80: user.v1.UserService.ListUsers:output_type -> user.v1.ListUsersResponse
	13, // 81: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	15, // 82: user.v1.UserService.UpdateUser:output_type -> user.v1.UpdateUserResponse
	17, // 83: user.v1.UserService.DeleteUser:output_type -> user.v1.DeleteUserResponse
	20, // 84: user.v1.UserService.GetOnboardingState:output_type -> user.v1.GetOnboardingStateResponse
	22, // 85: user.v1.UserService.PatchOnboardingState:output_type -> user.v1.PatchOnboardingStateResponse
	24, // 86: user.v1.UserService.CompleteOnboarding:output_type -> user.v1.CompleteOnboardingResponse
	76, // [76:87] is the sub-list for method output_type
	65, // [65:76] is the sub-list for method input_type
	65, // [65:65] is the sub-list for extension type_name
	65, // [65:65] is the sub-list for extension extendee
	0,  // [0:65] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
