// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: srs/v1/srs.proto

package srsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SRSService_EnsureItem_FullMethodName              = "/srs.v1.SRSService/EnsureItem"
	SRSService_RecordReview_FullMethodName            = "/srs.v1.SRSService/RecordReview"
	SRSService_GetDueItems_FullMethodName             = "/srs.v1.SRSService/GetDueItems"
	SRSService_GetWeakItems_FullMethodName            = "/srs.v1.SRSService/GetWeakItems"
	SRSService_GetStats_FullMethodName                = "/srs.v1.SRSService/GetStats"
	SRSService_RecordMistake_FullMethodName           = "/srs.v1.SRSService/RecordMistake"
	SRSService_ResolveMistakesForStep_FullMethodName  = "/srs.v1.SRSService/ResolveMistakesForStep"
	SRSService_ListMistakes_FullMethodName            = "/srs.v1.SRSService/ListMistakes"
	SRSService_GeneratePracticeSession_FullMethodName = "/srs.v1.SRSService/GeneratePracticeSession"
	SRSService_InitSkill_FullMethodName               = "/srs.v1.SRSService/InitSkill"
	SRSService_StrengthenSkill_FullMethodName         = "/srs.v1.SRSService/StrengthenSkill"
	SRSService_GetSkillStrengths_FullMethodName       = "/srs.v1.SRSService/GetSkillStrengths"
	SRSService_GetWeakSkills_FullMethodName           = "/srs.v1.SRSService/GetWeakSkills"
	SRSService_RunDailyDecay_FullMethodName           = "/srs.v1.SRSService/RunDailyDecay"
)

// SRSServiceClient is the client API for SRSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SRSService — Phase 3 (Adaptive learning).
//
// Хранит карточки повторения по алгоритму SM-2 (SuperMemo 2). Каждая
// "карточка" — это связка (user_id, item_type, item_id), где item_type
// — `vocabulary` / `step` / `phrase`. На каждое прохождение шага из
// step-validation-service вызывается RecordReview(quality), где
// quality (0..5) рассчитывается из is_correct + time_spent + retry.
//
// Sibling-stream — Mistakes: накапливают неправильные ответы для
// последующего повторения. resolved=true ставится, когда юзер
// исправляется на том же шаге.
type SRSServiceClient interface {
	// EnsureItem — создаёт карточку (user_id, item_type, item_id) если
	// её нет. Idempotent. Используется при первой встрече материала.
	EnsureItem(ctx context.Context, in *EnsureItemRequest, opts ...grpc.CallOption) (*EnsureItemResponse, error)
	// RecordReview — записывает попытку повторения и обновляет SM-2
	// параметры (EF / interval / repetitions / next_review_at).
	// Создаёт SRS-item лениво если его ещё не было.
	RecordReview(ctx context.Context, in *RecordReviewRequest, opts ...grpc.CallOption) (*RecordReviewResponse, error)
	// GetDueItems — карточки с next_review_at <= now (отсортированы по
	// приоритету: сильнее просрочена → раньше).
	GetDueItems(ctx context.Context, in *GetDueItemsRequest, opts ...grpc.CallOption) (*GetDueItemsResponse, error)
	// GetWeakItems — карточки с самым низким strength (для
	// дополнительной практики).
	GetWeakItems(ctx context.Context, in *GetWeakItemsRequest, opts ...grpc.CallOption) (*GetWeakItemsResponse, error)
	// GetStats — счётчики по статусам (total / due / mastered / new).
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// RecordMistake — фиксирует неправильный ответ. Если такая ошибка
	// уже была (user_id+step_id+answer-сигнатура) — инкрементируется
	// times_made.
	RecordMistake(ctx context.Context, in *RecordMistakeRequest, opts ...grpc.CallOption) (*RecordMistakeResponse, error)
	// ResolveMistakesForStep — помечает все неразрешённые ошибки юзера
	// на данном шаге как resolved=true. Вызывается из step-validation
	// при первом корректном ответе после ошибки.
	ResolveMistakesForStep(ctx context.Context, in *ResolveMistakesForStepRequest, opts ...grpc.CallOption) (*ResolveMistakesForStepResponse, error)
	// ListMistakes — список ошибок юзера (фильтр по resolved).
	ListMistakes(ctx context.Context, in *ListMistakesRequest, opts ...grpc.CallOption) (*ListMistakesResponse, error)
	// GeneratePracticeSession — собирает microservice-side список items
	// для практики: микс overdue / mistakes / weak (по умолчанию 50/30/20).
	// Pure read-only, не создаёт ни Session, ни attempts — лайфцикл
	// практики делается фронтом через обычный /steps/:id/submit.
	GeneratePracticeSession(ctx context.Context, in *GeneratePracticeSessionRequest, opts ...grpc.CallOption) (*GeneratePracticeSessionResponse, error)
	// InitSkill — создать запись decay'я для (user, skill). Idempotent.
	// Вызывается course-service.OnLessonCompleted при первом завершении
	// урока / модуля (initial_strength = 1.0).
	InitSkill(ctx context.Context, in *InitSkillRequest, opts ...grpc.CallOption) (*InitSkillResponse, error)
	// StrengthenSkill — практика → подпинка current_strength + reset
	// last_practiced_at. Используется на практике/в правильных ответах.
	StrengthenSkill(ctx context.Context, in *StrengthenSkillRequest, opts ...grpc.CallOption) (*StrengthenSkillResponse, error)
	// GetSkillStrengths — все навыки юзера, отсортированы по
	// current_strength ASC (слабые первыми).
	GetSkillStrengths(ctx context.Context, in *GetSkillStrengthsRequest, opts ...grpc.CallOption) (*GetSkillStrengthsResponse, error)
	// GetWeakSkills — top-N слабых.
	GetWeakSkills(ctx context.Context, in *GetWeakSkillsRequest, opts ...grpc.CallOption) (*GetWeakSkillsResponse, error)
	// RunDailyDecay — административный endpoint (cron его сам вызывает,
	// но можно вручную для тестов / fix-up). Возвращает кол-во затронутых строк.
	RunDailyDecay(ctx context.Context, in *RunDailyDecayRequest, opts ...grpc.CallOption) (*RunDailyDecayResponse, error)
}

type sRSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSRSServiceClient(cc grpc.ClientConnInterface) SRSServiceClient {
	return &sRSServiceClient{cc}
}

func (c *sRSServiceClient) EnsureItem(ctx context.Context, in *EnsureItemRequest, opts ...grpc.CallOption) (*EnsureItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureItemResponse)
	err := c.cc.Invoke(ctx, SRSService_EnsureItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) RecordReview(ctx context.Context, in *RecordReviewRequest, opts ...grpc.CallOption) (*RecordReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordReviewResponse)
	err := c.cc.Invoke(ctx, SRSService_RecordReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) GetDueItems(ctx context.Context, in *GetDueItemsRequest, opts ...grpc.CallOption) (*GetDueItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDueItemsResponse)
	err := c.cc.Invoke(ctx, SRSService_GetDueItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) GetWeakItems(ctx context.Context, in *GetWeakItemsRequest, opts ...grpc.CallOption) (*GetWeakItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeakItemsResponse)
	err := c.cc.Invoke(ctx, SRSService_GetWeakItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, SRSService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) RecordMistake(ctx context.Context, in *RecordMistakeRequest, opts ...grpc.CallOption) (*RecordMistakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordMistakeResponse)
	err := c.cc.Invoke(ctx, SRSService_RecordMistake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) ResolveMistakesForStep(ctx context.Context, in *ResolveMistakesForStepRequest, opts ...grpc.CallOption) (*ResolveMistakesForStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveMistakesForStepResponse)
	err := c.cc.Invoke(ctx, SRSService_ResolveMistakesForStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) ListMistakes(ctx context.Context, in *ListMistakesRequest, opts ...grpc.CallOption) (*ListMistakesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMistakesResponse)
	err := c.cc.Invoke(ctx, SRSService_ListMistakes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) GeneratePracticeSession(ctx context.Context, in *GeneratePracticeSessionRequest, opts ...grpc.CallOption) (*GeneratePracticeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePracticeSessionResponse)
	err := c.cc.Invoke(ctx, SRSService_GeneratePracticeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) InitSkill(ctx context.Context, in *InitSkillRequest, opts ...grpc.CallOption) (*InitSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitSkillResponse)
	err := c.cc.Invoke(ctx, SRSService_InitSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) StrengthenSkill(ctx context.Context, in *StrengthenSkillRequest, opts ...grpc.CallOption) (*StrengthenSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrengthenSkillResponse)
	err := c.cc.Invoke(ctx, SRSService_StrengthenSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) GetSkillStrengths(ctx context.Context, in *GetSkillStrengthsRequest, opts ...grpc.CallOption) (*GetSkillStrengthsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillStrengthsResponse)
	err := c.cc.Invoke(ctx, SRSService_GetSkillStrengths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) GetWeakSkills(ctx context.Context, in *GetWeakSkillsRequest, opts ...grpc.CallOption) (*GetWeakSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeakSkillsResponse)
	err := c.cc.Invoke(ctx, SRSService_GetWeakSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) RunDailyDecay(ctx context.Context, in *RunDailyDecayRequest, opts ...grpc.CallOption) (*RunDailyDecayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunDailyDecayResponse)
	err := c.cc.Invoke(ctx, SRSService_RunDailyDecay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SRSServiceServer is the server API for SRSService service.
// All implementations must embed UnimplementedSRSServiceServer
// for forward compatibility.
//
// SRSService — Phase 3 (Adaptive learning).
//
// Хранит карточки повторения по алгоритму SM-2 (SuperMemo 2). Каждая
// "карточка" — это связка (user_id, item_type, item_id), где item_type
// — `vocabulary` / `step` / `phrase`. На каждое прохождение шага из
// step-validation-service вызывается RecordReview(quality), где
// quality (0..5) рассчитывается из is_correct + time_spent + retry.
//
// Sibling-stream — Mistakes: накапливают неправильные ответы для
// последующего повторения. resolved=true ставится, когда юзер
// исправляется на том же шаге.
type SRSServiceServer interface {
	// EnsureItem — создаёт карточку (user_id, item_type, item_id) если
	// её нет. Idempotent. Используется при первой встрече материала.
	EnsureItem(context.Context, *EnsureItemRequest) (*EnsureItemResponse, error)
	// RecordReview — записывает попытку повторения и обновляет SM-2
	// параметры (EF / interval / repetitions / next_review_at).
	// Создаёт SRS-item лениво если его ещё не было.
	RecordReview(context.Context, *RecordReviewRequest) (*RecordReviewResponse, error)
	// GetDueItems — карточки с next_review_at <= now (отсортированы по
	// приоритету: сильнее просрочена → раньше).
	GetDueItems(context.Context, *GetDueItemsRequest) (*GetDueItemsResponse, error)
	// GetWeakItems — карточки с самым низким strength (для
	// дополнительной практики).
	GetWeakItems(context.Context, *GetWeakItemsRequest) (*GetWeakItemsResponse, error)
	// GetStats — счётчики по статусам (total / due / mastered / new).
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// RecordMistake — фиксирует неправильный ответ. Если такая ошибка
	// уже была (user_id+step_id+answer-сигнатура) — инкрементируется
	// times_made.
	RecordMistake(context.Context, *RecordMistakeRequest) (*RecordMistakeResponse, error)
	// ResolveMistakesForStep — помечает все неразрешённые ошибки юзера
	// на данном шаге как resolved=true. Вызывается из step-validation
	// при первом корректном ответе после ошибки.
	ResolveMistakesForStep(context.Context, *ResolveMistakesForStepRequest) (*ResolveMistakesForStepResponse, error)
	// ListMistakes — список ошибок юзера (фильтр по resolved).
	ListMistakes(context.Context, *ListMistakesRequest) (*ListMistakesResponse, error)
	// GeneratePracticeSession — собирает microservice-side список items
	// для практики: микс overdue / mistakes / weak (по умолчанию 50/30/20).
	// Pure read-only, не создаёт ни Session, ни attempts — лайфцикл
	// практики делается фронтом через обычный /steps/:id/submit.
	GeneratePracticeSession(context.Context, *GeneratePracticeSessionRequest) (*GeneratePracticeSessionResponse, error)
	// InitSkill — создать запись decay'я для (user, skill). Idempotent.
	// Вызывается course-service.OnLessonCompleted при первом завершении
	// урока / модуля (initial_strength = 1.0).
	InitSkill(context.Context, *InitSkillRequest) (*InitSkillResponse, error)
	// StrengthenSkill — практика → подпинка current_strength + reset
	// last_practiced_at. Используется на практике/в правильных ответах.
	StrengthenSkill(context.Context, *StrengthenSkillRequest) (*StrengthenSkillResponse, error)
	// GetSkillStrengths — все навыки юзера, отсортированы по
	// current_strength ASC (слабые первыми).
	GetSkillStrengths(context.Context, *GetSkillStrengthsRequest) (*GetSkillStrengthsResponse, error)
	// GetWeakSkills — top-N слабых.
	GetWeakSkills(context.Context, *GetWeakSkillsRequest) (*GetWeakSkillsResponse, error)
	// RunDailyDecay — административный endpoint (cron его сам вызывает,
	// но можно вручную для тестов / fix-up). Возвращает кол-во затронутых строк.
	RunDailyDecay(context.Context, *RunDailyDecayRequest) (*RunDailyDecayResponse, error)
	mustEmbedUnimplementedSRSServiceServer()
}

// UnimplementedSRSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSRSServiceServer struct{}

func (UnimplementedSRSServiceServer) EnsureItem(context.Context, *EnsureItemRequest) (*EnsureItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureItem not implemented")
}
func (UnimplementedSRSServiceServer) RecordReview(context.Context, *RecordReviewRequest) (*RecordReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordReview not implemented")
}
func (UnimplementedSRSServiceServer) GetDueItems(context.Context, *GetDueItemsRequest) (*GetDueItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDueItems not implemented")
}
func (UnimplementedSRSServiceServer) GetWeakItems(context.Context, *GetWeakItemsRequest) (*GetWeakItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeakItems not implemented")
}
func (UnimplementedSRSServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedSRSServiceServer) RecordMistake(context.Context, *RecordMistakeRequest) (*RecordMistakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordMistake not implemented")
}
func (UnimplementedSRSServiceServer) ResolveMistakesForStep(context.Context, *ResolveMistakesForStepRequest) (*ResolveMistakesForStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveMistakesForStep not implemented")
}
func (UnimplementedSRSServiceServer) ListMistakes(context.Context, *ListMistakesRequest) (*ListMistakesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMistakes not implemented")
}
func (UnimplementedSRSServiceServer) GeneratePracticeSession(context.Context, *GeneratePracticeSessionRequest) (*GeneratePracticeSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePracticeSession not implemented")
}
func (UnimplementedSRSServiceServer) InitSkill(context.Context, *InitSkillRequest) (*InitSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitSkill not implemented")
}
func (UnimplementedSRSServiceServer) StrengthenSkill(context.Context, *StrengthenSkillRequest) (*StrengthenSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StrengthenSkill not implemented")
}
func (UnimplementedSRSServiceServer) GetSkillStrengths(context.Context, *GetSkillStrengthsRequest) (*GetSkillStrengthsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkillStrengths not implemented")
}
func (UnimplementedSRSServiceServer) GetWeakSkills(context.Context, *GetWeakSkillsRequest) (*GetWeakSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeakSkills not implemented")
}
func (UnimplementedSRSServiceServer) RunDailyDecay(context.Context, *RunDailyDecayRequest) (*RunDailyDecayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunDailyDecay not implemented")
}
func (UnimplementedSRSServiceServer) mustEmbedUnimplementedSRSServiceServer() {}
func (UnimplementedSRSServiceServer) testEmbeddedByValue()                    {}

// UnsafeSRSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SRSServiceServer will
// result in compilation errors.
type UnsafeSRSServiceServer interface {
	mustEmbedUnimplementedSRSServiceServer()
}

func RegisterSRSServiceServer(s grpc.ServiceRegistrar, srv SRSServiceServer) {
	// If the following call panics, it indicates UnimplementedSRSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SRSService_ServiceDesc, srv)
}

func _SRSService_EnsureItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).EnsureItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_EnsureItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).EnsureItem(ctx, req.(*EnsureItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_RecordReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).RecordReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_RecordReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).RecordReview(ctx, req.(*RecordReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_GetDueItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDueItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).GetDueItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_GetDueItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).GetDueItems(ctx, req.(*GetDueItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_GetWeakItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeakItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).GetWeakItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_GetWeakItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).GetWeakItems(ctx, req.(*GetWeakItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_RecordMistake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordMistakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).RecordMistake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_RecordMistake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).RecordMistake(ctx, req.(*RecordMistakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_ResolveMistakesForStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveMistakesForStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).ResolveMistakesForStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_ResolveMistakesForStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).ResolveMistakesForStep(ctx, req.(*ResolveMistakesForStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_ListMistakes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMistakesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).ListMistakes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_ListMistakes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).ListMistakes(ctx, req.(*ListMistakesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_GeneratePracticeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePracticeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).GeneratePracticeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_GeneratePracticeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).GeneratePracticeSession(ctx, req.(*GeneratePracticeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_InitSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).InitSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_InitSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).InitSkill(ctx, req.(*InitSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_StrengthenSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrengthenSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).StrengthenSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_StrengthenSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).StrengthenSkill(ctx, req.(*StrengthenSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_GetSkillStrengths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillStrengthsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).GetSkillStrengths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_GetSkillStrengths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).GetSkillStrengths(ctx, req.(*GetSkillStrengthsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_GetWeakSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeakSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).GetWeakSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_GetWeakSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).GetWeakSkills(ctx, req.(*GetWeakSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_RunDailyDecay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunDailyDecayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).RunDailyDecay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_RunDailyDecay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).RunDailyDecay(ctx, req.(*RunDailyDecayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SRSService_ServiceDesc is the grpc.ServiceDesc for SRSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SRSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "srs.v1.SRSService",
	HandlerType: (*SRSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureItem",
			Handler:    _SRSService_EnsureItem_Handler,
		},
		{
			MethodName: "RecordReview",
			Handler:    _SRSService_RecordReview_Handler,
		},
		{
			MethodName: "GetDueItems",
			Handler:    _SRSService_GetDueItems_Handler,
		},
		{
			MethodName: "GetWeakItems",
			Handler:    _SRSService_GetWeakItems_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _SRSService_GetStats_Handler,
		},
		{
			MethodName: "RecordMistake",
			Handler:    _SRSService_RecordMistake_Handler,
		},
		{
			MethodName: "ResolveMistakesForStep",
			Handler:    _SRSService_ResolveMistakesForStep_Handler,
		},
		{
			MethodName: "ListMistakes",
			Handler:    _SRSService_ListMistakes_Handler,
		},
		{
			MethodName: "GeneratePracticeSession",
			Handler:    _SRSService_GeneratePracticeSession_Handler,
		},
		{
			MethodName: "InitSkill",
			Handler:    _SRSService_InitSkill_Handler,
		},
		{
			MethodName: "StrengthenSkill",
			Handler:    _SRSService_StrengthenSkill_Handler,
		},
		{
			MethodName: "GetSkillStrengths",
			Handler:    _SRSService_GetSkillStrengths_Handler,
		},
		{
			MethodName: "GetWeakSkills",
			Handler:    _SRSService_GetWeakSkills_Handler,
		},
		{
			MethodName: "RunDailyDecay",
			Handler:    _SRSService_RunDailyDecay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srs/v1/srs.proto",
}
